### ISSUE TITLE
Spell-checker button for the editor bar 

### ISSUE THREAD

**Issue by internettips** [GetPublii/Publii#100]
I'm getting addicted to your superb Publii. :-)

Though I'm also realising my limitations. That's why a spelling-checker button would be nice. However, I appreciate that given the rich variety of languages out there, it's an option that's not always so straightforward.

You probably expected this at some point. I'm amazed it hasn't been mentioned before now. Can you add a spell-checker button as an option to the superb editor Publii is?

For me, that would be English - any variety is fine: I can work out the differences :-)

Thanks for the consideration. Anything you can do that takes us closer to a spell-checker is much appreciated.

**Comment by bobmitro** [comment]
Hey Brian,
Thank you for your "superb opinion" about our app.  I really appreciate that. 
I can not promise you when but we will try to add this functionality soon.

**Comment by internettips** [comment]
At a glance, sounds good for a half-way solution. Great to skim and scan. Not sure how easy this is for Publii to do though. Plus of course, how to deal with a range of different languages can create more fun :-)

**Comment by cwmke** [comment]
Just a little bit longer and it looks like Electron will be adding native spell-checking support. Looks like it might already be in the latest Electron releases. electron/electron#20692

**Comment by dziudek** [comment]
@cwmke - https://github.com/GetPublii/Publii/issues/569 :)
