### ISSUE TITLE
SVGZ and SVG support, is partially supported

### ISSUE THREAD

**Issue by nordseo** [GetPublii/Publii#1000]
I just thought I would post this since I do not see a request for SVG and SVGZ.

I've had some great luck so far using SVGZ with Publii. Most of my images are down under 10KB, making my website blazing fast. However, there are some areas where SVGZ is not fully supported yet. 

1. TinyMCE currently doesn't allow upoading or displaying them in the post editor.
2. SVGZ Post Featured Image doesn't display in Publii
3. SVGZ Featured Image doesn't display on website theme (possibly this is the theme, but seems it is due to no SVGZ support for Publii Featured Images)

**Workarounds:**
Upload SVGZ to Publii media files. This actually works, then using HTML in the post editor to target it gets around it. But, it would be nice to have SVGZ support in the post editor and featured image field.

**Comment by dziudek** [comment]
Hi,

Do you think that there is a sense to add support for SVGZ? AFAIK - if you are using GZIP compression on your hosting, then in fact all SVG images turns automagically into SVGZ during send to the user browser. If I am missing something - please let me know :)

**Comment by nordseo** [comment]
Thanks! Sorry I forgot all about this.
