### ISSUE TITLE
Publii hangs on Sync Website after changing Post slugs and or saving drafts

### ISSUE THREAD

**Issue by nordseo** [GetPublii/Publii#1004]
I'm getting a few errors after saving some posts as drafts and also updating slugs on a few posts. The deployment hangs.

`ERROR REMOVE FILE`

`Error: delete: No such file`

I tried to clone the site, and re-sync again to our servers, but this also fails.

I tried to manually place the old missing folders and index.html files, and while it does seem to get a little further in the sync, it still fails, then deletes all of the folders and index files again, and I'm back to where I started. 

Any known issues with this bug? Is there a possibility of some JS parsing error in my post entry content?

**Comment by dziudek** [comment]
Hi,

I suppose that you have something seriously messed up with your website according to your previous issues with tags :) 

Could you share with me your problematic website backup? You can share it to my email: dziudek@gmail.com

**Comment by nordseo** [comment]
Sure. 

I'll send you a backup copy. I ended up just deleting the site from the server, and re-uploading everything again, and got around the errors. 


I will test this other issue as well again, and send you a copy of my Publii site if it occurs again. #999
