### ISSUE TITLE
Porting a theme

### ISSUE THREAD

**Issue by MaluNoPeleke** [GetPublii/Publii#1007]
How easy or hard is it to port a theme for Ghost CMS (also using Handlebars) to Publii?
For example this great open source theme would be a nice addition to Publii: [Mapache theme](https://github.com/godofredoninja/Mapache)

**Comment by internettips** [comment]
Try checking out: https://forum.getpublii.com/topic/importing-a-ghost-site-into-publii/

**Comment by MaluNoPeleke** [comment]
Thanks for the quick response but that doesn't help much.

**Comment by internettips** [comment]
Maybe try asking on the forum. Though at first glance: (1) export your Ghost site to WordPress format, (2) Import your exported Wordpress site into Publii using the built-in Wordpress importer tool / WXR file importer.

**Comment by MaluNoPeleke** [comment]
Thanks for the suggestion but I was more interested in porting the mentioned theme than migrating the content.

**Comment by internettips** [comment]
Porting a theme like Mapache to Publii is quite an undertaking. Have you checked out [Splitian theme](https://marketplace.getpublii.com/product/splitian/) from Publii?

**Comment by MaluNoPeleke** [comment]
No, it doesn't look similar or describes how to port it.

**Comment by internettips** [comment]
Perhaps you could try asking at: [https://forum.getpublii.com](url). Plus, you can learn more about how Publii themes work at: [https://getpublii.com/dev/](url).

**Comment by MaluNoPeleke** [comment]
Done: https://forum.getpublii.com/topic/porting-a-ghost-cms-theme-based-on-handlebars/

**Comment by dziudek** [comment]
I am closing this issue due inactivity and also due fact that it is not strictly connected with Publii core functionality. I think that such issues can be continued on official forum.
