### ISSUE TITLE
search.html gets generated even though Search is off in theme settings

### ISSUE THREAD

**Issue by stefan-scholl** [GetPublii/Publii#1009]
Fresh install of Publii v.0.38.2 (build 14204), default theme Simple v.2.3.1.0. In theme settings "Search" not turned on. 
Syncing website (manual) generates a file `search.html`

**Comment by stefan-scholl** [comment]
Tried in v.0.38.3 (build 14238). Same result.

**Comment by bobmitro** [comment]
If it really bothers you, you can disable the search completely by editing the config.json file in the rendered section by changing the "createSearchPage" value to false.

**Comment by stefan-scholl** [comment]
Thank you, setting `createSearchPage` to `false` helps.

It bothers me because it could have  *potential* legal problems with European privacy laws. Not likely but possible. Better not to include anything against the users intentions.

**Comment by bobmitro** [comment]
> It bothers me because it could have _potential_ legal problems with European privacy laws.

You can now use the new privacy-friendly [Static Search](https://marketplace.getpublii.com/plugins/static-search/) plugin.
