### ISSUE TITLE
Donations through PayPal

### ISSUE THREAD

**Issue by internettips** [GetPublii/Publii#101]
I'm really grateful for what you folks at Publii are doing. 

I think you completely on target with static websites, trends, etc., and what needs to happen for websites for many people. 

So thank you for the work that you're doing. Much appreciated.

Naturally, while I've already sent some funds your way, hopefully, to keep the coffee supply on tap, I also wanted to donate a regular amount of money to help add to the pool of folks that are already doing that. 

However, your link for the OpenCollective.com / https://opencollective.com/publii/ may not accept contributions sent via PayPal.com from the UK - and I prefer to use PayPal for now instead of credit card.

So, rather than use OpenCollective.com, I can send set up a subscription contribution stream directly from my PayPal.com account. That way, I also know it's going straight to the people who are making such a difference. Please let me know your PayPal.com ID to use for that.

Thank you.

**Comment by bobmitro** [comment]
Thanks again you for kind words. Thank you also for your previous grants and for the support of our project. 
You can still use Paypal via OpenCollective: https://opencollective.com/publii/donate or send your donation directly to our Paypal account by clicking this [link](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FKUUHBN9BTT56).
