### ISSUE TITLE
Json-LD, LazyLoad and Webp

### ISSUE THREAD

**Issue by rodrigophpweb** [GetPublii/Publii#1024]
Hello how are you?  Hope everything is great!  I'm about to migrate from WordPress and definitely go to Público, I would like to know 3 items that for me are fundamental and I use a lot in my WordPress projects.  With Plubii my posts and my pages can I work with structured data using JSON-LD?  The other two questions are related to images when inserting image into content, when rendered does it use LazyLoad?  and If I uploaded a jpeg it convert to webp?  Can you answer these questions for me?

**Comment by bobmitro** [comment]
I think a forum is a more appropriate place to ask such questions https://forum.getpublii.com/
Nevertheless, to answer your questions:
1. Publii generates JSON-LD data automatically, for the homepage, it is an Organization @type, for the posts an Article @type.
2. Publii themes use a native lazy loading that lazy loads images, videos,  iframes, also responsive images.
3. Publii supports WEBP but does not convert any other to this one.
