### ISSUE TITLE
recovering website from github

### ISSUE THREAD

**Issue by utilitieslit1t** [GetPublii/Publii#1028]
I have lost my data i.e. the data of the publii application on my windows machine, i also have not created the backup from the publii application. I want to recover my website, i have used github-pages  as the server is there a way i can recover the site ?

**Comment by dziudek** [comment]
Due lack of backups it is impossible to easily recreate website from github or any other hosting, because it is only output of the source website files. The only way is manually recreate website according to the existing HTML version, but it requires usually a lot of manual work.
