### ISSUE TITLE
Custom fields and custom content types

### ISSUE THREAD

**Issue by Zyles** [GetPublii/Publii#1032]
Is there a plan to add custom fields and custom content types like in Wordpress? I did not see this mentioned anywhere.

For now this project seems great but very simple.

When we can have different page templates with custom fields then it can really go places.

**Comment by erikobox** [comment]
I have same question. We need to make database like websites. Custom fields, filters and couple of premium themes for making shops, file downloading portals, movie websites.

**Comment by bobmitro** [comment]
> When we can have different page templates with custom fields then it can really go places.

This feature has been implemented some time ago. You can have a different post, tag or and author templates https://getpublii.com/dev/how-to-create-custom-templates/#how-to-create-custom-templates

You can also define custom fields using the post config option https://getpublii.com/dev/post-config-options/#post-config-options

**Comment by bobmitro** [comment]
Closed due to inactivity for a long time.
