### ISSUE TITLE
Are the themes still maintained?

### ISSUE THREAD

**Issue by kasperireland** [GetPublii/Publii#1040]
Howdy,
I was just curious if the Publii themes on the marketplace are still maintained (https://marketplace.getpublii.com/). Mostly talking about "Portfolio" which displayed a bunch of errors when using. I'm currently using "Taste" and am hoping it continues to be maintained & doesn't lose support. 
Thanks.

**Comment by bobmitro** [comment]
> I'm currently using "Taste" and am hoping it continues to be maintained & doesn't lose support.
Yeap, they are still supported and updated. Today, almost all free themes have been updated.

**Comment by kasperireland** [comment]
Alright, thank you for the response!
