### ISSUE TITLE
[Feature Request] Tiny MCE Editor for Tag Description

### ISSUE THREAD

**Issue by iamadlx** [GetPublii/Publii#1041]
Hello,

I did not find the possibility to do this but is it possible to add more option for editing the description of the tags?

I would like to suggest to add a "Tiny MCE" editor for the tag description as for the description of the home page in the "Taste" theme for example.

Thank you,

**Comment by Andy-Node** [comment]
![image](https://user-images.githubusercontent.com/60820173/158995763-9f81ac4e-bc85-49b7-8aad-ef19771b6365.png)
Come back on this :) I wish I had more option to write the description. A WYSIWYG editor or Tiny MCE ?

**Comment by dziudek** [comment]
WYSIWYG editor will be added in v.0.42 for tag and author descriptions :)
