### ISSUE TITLE
Can you add custom Social Icons on Footer?

### ISSUE THREAD

**Issue by fajarsiddiqfs** [GetPublii/Publii#1044]
Can we upload our own icon and links, example tiktok, our own store icon marketplace and etc?

**Comment by candideu** [comment]
Have you been able to figure this out? The only option I can think of anything easier than editing the svg map and footer partial.

**Comment by fajarsiddiqfs** [comment]
That is helpful, thanks for sharing me the link of the forum. Will try soon
