### ISSUE TITLE
Submenu items disappear on hover?

### ISSUE THREAD

**Issue by TheBruinStory** [GetPublii/Publii#1046]
Hello, I am having an issue with my menu/submenus. I have a submenu called "Timeline" and additional submenus within this submenu named "Creation of UCLA...", "UCLA during the McCarthy Era...", etc. **When the website is full screen, the submenu items under "Timeline" disappear.** However, when the window is minimized, I can access the submenu items under Timeline by clicking the three horizontal lines, opening "Timeline", and navigating to each submenu. Does anyone know how to bypass the issue of the submenu items disappearing when the window is fullscreen? Thank you! 

https://oliviatruong.github.io/FinalProject/

**Comment by dziudek** [comment]
Seems to be a problem with theme not with Publii - please use the official support forum for such cases: https://forum.getpublii.com
