### ISSUE TITLE
Button on "Taste" theme has wrong text

### ISSUE THREAD

**Issue by kasperireland** [GetPublii/Publii#1048]
On the "Taste" theme for Publii, when you scroll down on the homepage to the bottom until it is the end of all of the posts, the button that goes to the next page of posts says "Previous" while it should say "Next". "Previous" indicates that it is not on the first page, while it really is. This can be seen on the Taste Demo -> https://demo.getpublii.com/themes/taste/

**Comment by bobmitro** [comment]
If you need help with anything not related to the Publii app, please submit the request to our community forum. https://forum.getpublii.com/
