### ISSUE TITLE
Bug with Paragraphs

### ISSUE THREAD

**Issue by Feriman22** [GetPublii/Publii#1049]
Hi,

I found a bug in Publii (v.0.38.3 (build 14238)). You cannot select anyting the left paragraph menu if you already chose something from the right one.

**Steps to reproduce:**

1., Open a new post with WYSIWYG editor
2., Type something in text field
3., Select anything from the right paragraph menu, for example the "Heading 3"
4., After that you cannot select anything from the left paragraph menu.

![deny](https://user-images.githubusercontent.com/22872515/144847093-d106e9a1-fe36-4ba5-88a5-1fc2db0700f3.png)

The strange thing is if you select first something from the left menu, you can select anything from the right one.

![allow](https://user-images.githubusercontent.com/22872515/144847133-85f8f451-60b8-4d94-8c7c-fc7a91f41263.png)

Please fix this bug by enabling both way of edit the text.

Thank you!
Feriman

**Comment by bobmitro** [comment]
This is not a bug, the first drop-down menu contains content styling elements that are associated only with the selected HTML elements. 

For example: the info, highlight, success elements are related to paragraphs only and will not affect others like headings (h1-h2), blockquote, etc. this is why they are not available in the drop-down list.
Fortunately, you can manage these items with the config.json file in the "customElements" section. 

More details about that can be found in our documentation https://getpublii.com/dev/post-editor-api/#customformats
