### ISSUE TITLE
Links and Edits to HTML are broken by Publii

### ISSUE THREAD

**Issue by Linus-007** [GetPublii/Publii#1050]
Is anyone having an issue where manual HTML edits in the WISIWIG editor are being broken after _apply changes_ is pressed?

Ampersand (&) symbols in links are being destroyed by the editor

Example:  `. . . server&qid= . . .`

is being replaced with: `. . . server&amp;qid . . .`

The above code sample is part of an href image link.

The same thing happens when you insert an image. If the link contains an &, it is changed to the HTML code `&amp;`.

**Comment by wuniversales** [comment]
It happens to me too, it's quite annoying.

**Comment by dziudek** [comment]
It seems that this behaviour is valid: https://stackoverflow.com/questions/50069810/tinymce-converting-ampersand-in-querystring-to-html-entity

**Comment by Linus-007** [comment]
Thanks for validation. No one in the Publii site believes this is an issue. Is there a fix?

**Comment by Linus-007** [comment]
0.39 version is no better. Others have confirmed the issue. Any updates?

**Comment by dziudek** [comment]
@Linus-007 - I still do not understand one thing - what do you mean by "broken"? These links for me are working correctly when they are clicked.

**Comment by Linus-007** [comment]
For Broken Description:
Example: ` . . . server&qid= . . .`
is being replaced with: ` . . . server&amp;qid . . .`
The above code sample is part of an href image link.

Users who click the link that is modified by Publii get a 404 not found error.

**Comment by Linus-007** [comment]
Any updates?

**Comment by dziudek** [comment]
@Linus-007 - there is no update, because I do not see any issue there. Replacing `&` to `&amp;` is absolutely correct https://stackoverflow.com/questions/50069810/tinymce-converting-ampersand-in-querystring-to-html-entity
