### ISSUE TITLE
AWS S3 Synchronization

### ISSUE THREAD

**Issue by Linus-007** [GetPublii/Publii#1051]
Does Publii synchronize files on S3 that changed or overwrite everything? I ask because a simple change to one page causes an extended upload of 200+ items. To save time on responses, I do not have versioned storage turned on in AWS S3.

I made one change, and looked at my S3 bucket after pushing that change. Every item in the bucket has a new date and time. Why upload everything rather than maintain a list of what has changed and only upload the changes? This can increase egress charges and put request charges. In five days, I have over 20,000 put requests for simple edits.

To save time on responses, I do not have versioned storage turned on in AWS S3.

**Comment by bobmitro** [comment]
In general, Publii only syncs files that have changed or are new. But it all depends on the changes made. 
For example, changing the post title, date, etc... changes the content of e.g. related posts. So, a small change must be reflected in most of the posts (files).

**Comment by Linus-007** [comment]
It looks like this is the same as issue #377. `files.publii.json` is not being uploaded by Publii despite the fact that the IAM user has AmazonS3FullAccess.
In the log viewer, `deployment-process.log`, I can see that the last file with checksums is not uploaded.

```
[Tue, 07 Dec 2021 06:46:21 GMT] UPL 404.html -> 404.html
[Tue, 07 Dec 2021 06:46:22 GMT] -> files.publii.json
[Tue, 07 Dec 2021 06:46:22 GMT] S3 ERROR: Access Denied
```

**Comment by bobmitro** [comment]
Oh yes, if the `files.publii.json` file is not uploaded, all files are uploaded again to the server.

**Comment by Linus-007** [comment]
I do not think that #377 satisfactorily resolved the issue. I read the entire thread, examines the other issues. I think "authenticated-read" #62 contributes to the issue. If I set Publii to use ACL authenticated read, for a test, the result is 100% failure. Why this one file is set that way does not make sense.

**Comment by Linus-007** [comment]
I can see the issue in the s3.js. Why not honor user ALC the setting in Publii rather than hard coding it in the code?

**Comment by dziudek** [comment]
The problem will be probably solved in v.0.41 (planned for mid-October) - since this version Publii will use the same ACL for all files, without predefined ACLs for publii.files.json file. Most probably the current issues are caused by fact that the used ACL are non-compatible with some buckets policies.
