### ISSUE TITLE
[Feature Request] Add Follow Buttons for Fediverse Services like Mastodon, PeerTube etc.

### ISSUE THREAD

**Issue by tigexplorer** [GetPublii/Publii#1053]
It would be nice to have the ability to add follow buttons for 
* Mastodon
* PeerTube
* FunkWhale
* Freindica
* PixelFed
* Mobilizon

and other services that are using the AcitivityPup protokoll.

**Comment by bobmitro** [comment]
I think the forum is a more appropriate place to ask questions like this https://forum.getpublii.com/ as it is about theme options, not the app.
