### ISSUE TITLE
"You cannot save a post with empty title" for a title-existing post

### ISSUE THREAD

**Issue by Leon0824** [GetPublii/Publii#1055]
https://user-images.githubusercontent.com/1922026/147573585-24826aab-e646-4baa-ac0a-e7b39f2165b7.mp4

**Comment by dziudek** [comment]
Hi,

Unfortunately I am unable to reproduce this issue on my instance. Are you always able to reproduce this problem in the same way or it is a random issue?

**Comment by Leon0824** [comment]
It is a random issue.

**Comment by dziudek** [comment]
Today during work with #1080 I have changed a method of detecting title changes - I suppose that it will solve also your issue. If this issue will come back after update to v.0.39 planned for beginning of march - feel free to reopen this issue :)
