### ISSUE TITLE
Scrollbar is missing in Editor view

### ISSUE THREAD

**Issue by Feriman22** [GetPublii/Publii#1056]
Hi,

I cannot see/use the scrollbar in Editor view in the latest Publii (v.0.38.3). I can see that while viewing the "Posts" or any other menu, but it doesn't appear when I open an article in Editor mode (simply click on the article in Posts menu).

It's hard to edit an article if my scroll is broken on my mouse or I'm working from laptop (there is no scroll function).

I use Windows 10 21H2 LTSC.

**Comment by dziudek** [comment]
Hi,

Did you tried to use wide scrollbars option under app settings?

**Comment by Feriman22** [comment]
Yes, it's already enabled.

**Comment by dziudek** [comment]
I cannot reproduce this issue, and also it is a first report of such issue - maybe it is related to your Windows configuration. At this moment I am unable to help :(

**Comment by Feriman22** [comment]
Okay, no problem. I close this ticket. I'll try to reproduce this issue on another machine.
