### ISSUE TITLE
Missing Data For "Author" in JsonLD

### ISSUE THREAD

**Issue by reachandy** [GetPublii/Publii#1057]
Hello,

=> app/back-end/modules/render-html/handlebars/helpers/json-ld.js
For all posts, the author's url is missing :

"author": {
        "@type": "Person",
        "name": "John Doe",
=>    "url": "http://example.com/profile/johndoe123"

We then have an error in the rich results of google.
Thank you in advance,

**Comment by dziudek** [comment]
Thank you for this report - it will be fixed in v.0.39
