### ISSUE TITLE
Hidden tags are not linkable by menu items

### ISSUE THREAD

**Issue by s3nnet** [GetPublii/Publii#1061]
Use case: Offer different languages via header menu, but do not overcrowd tags list with several language tags.
If tags are hidden, the menu items linked to these tags point to nowhere.
An "Exclude from tags list" option would be outstanding imho.

**Comment by dziudek** [comment]
@s3nnet - we have excluded hidden tags from UI where links are created (editors, menu item editor) as hidden tags are not rendered at all.
