### ISSUE TITLE
Feature Request: Add &nbsp support

### ISSUE THREAD

**Issue by s3nnet** [GetPublii/Publii#1062]
Non-breaking spaces may in some cases be essential for the layout of a headline / text line.
However, even manually adding the &nbsc entity in HTML mode does not work.

**Comment by internettips** [comment]
Try using &nbsp;

**Comment by internettips** [comment]
Try using `&nbsp;`

**Comment by s3nnet** [comment]
The HTML entity &nbsp; doesn't work, hence the feature request.

**Comment by internettips** [comment]
On my version, it works just fine. Perhaps go to: https://forum.getpublii.com and ask for help.

**Comment by s3nnet** [comment]
Thank you, I found this topic:
https://forum.getpublii.com/topic/non-breaking-space-in-html-block/#post-6837
And I did some testing (Publii 0.38.3 / Manjaro / Plasma).
Indeed both & # 160; and & nbsp; work. Kind of.
However, these entities do not show up when I once again hit the HTML mode button, they are gone, invisible or something. Yet nbsp's keep working until I further edit the paragraph. Adding a single space after the nbsp’ed text is enough to revert the nbsp’s, no matter which method you used.

**Comment by internettips** [comment]
Great news! Maybe at some point a programmable Editor bar -- to allow users to add their own preferred HTML buttons for example -- might become possible. Fingers crossed.

**Comment by bobmitro** [comment]
There is an option to put the custom button, more about it can be found here: https://getpublii.com/dev/how-to-add-custom-config-or-js-for-post-editor/
Also, the good news is that Tiny editor comes with the [nonbreaking](https://www.tiny.cloud/docs/plugins/opensource/nonbreaking/) plugin. 

So, to add an **nbsp** button follow only one step :)

1. Create the **tinymce.override.json** file in the _(Documents ▸ ⁨Publii⁩ ▸ ⁨config)_ location with the following content: 
```
{
   "toolbar2": "nonbreaking styleselect formatselect searchreplace hr readmore removeformat undo redo restoredraft sourcecode ",
   "plugins": "nonbreaking advlist autolink autosave link image lists hr pagebreak searchreplace media table paste autoresize emoticons textpattern toc"
  }
```
a result:
![screen](https://user-images.githubusercontent.com/1391007/151662305-fd787395-769c-48a5-bbac-3160e82159e6.png)

**Comment by internettips** [comment]
Superb Bob! How cool is that? 👍

**Comment by s3nnet** [comment]
Thank you, Bob!
I just tried your solution and I can confirm it works as expected.
In particular, after clicking the nbsp button the nbsp is then permanently represented in HTML mode by "<span class="mce-nbsp-wrap" contenteditable="false"> </span>".
Also, adding text afterwards no longer reverts the nbsp :+1: 
It keeps striking me on a regular basis how simple Publii is by default, and how powerful it is when needed :100:

**Comment by candideu** [comment]
Is the same applicable for the block_formats / formatselect dropdown?

![image](https://user-images.githubusercontent.com/55474996/183921075-ce015def-37b8-4141-874c-483f4d3a5d3c.png)
