### ISSUE TITLE
JS error on sync/export

### ISSUE THREAD

**Issue by boneblack** [GetPublii/Publii#1065]
Week-old Publii installation on Win 10. (Will provide more OS details if necessary.)

Site files "imported" via copy and pasting as importing backup data didn't work. Publii opened the site fine, previews generated fine. However, when attempting to sync the site to .zip output, I get this error:

> Uncaught Execption:
>
>Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
>     at ChildProcess.target.send (internal/child_process.js:679:16)
>     at IpcMainImpl.<anonymous>
>C:\Users\USERNAME\AppData\Local\Programs\Publii\resources\app.asar\back-end\events\de...:44)
>     at IpcMainImpl.emit (events.js:315:20)
>     at IpcMainImpl.EventEmitter.emit (domain.js:483:12)
>     at Object.<anonymous> (electron/js2c/browser_init.js:157:9051)
>     at Object.emit (events.js:315:20)
>     at Object.EventEmitter.emit (domain.js:483:12)

**Comment by dziudek** [comment]
Hi,

Do you have any errors in the Tools -> log viewer?

**Comment by boneblack** [comment]
I am unable to replicate the issue now, unfortunately.

**Comment by dziudek** [comment]
Closing issue due inactivity
