### ISSUE TITLE
Allow search page to be a 'pretty URL' 

### ISSUE THREAD

**Issue by Stretch96** [GetPublii/Publii#1066]
Currently, if we enable 'pretty URLs', all posts are created as a directory containing `index.html`

This requires some server configuration (eg. htaccess files, CloudFront function) to handle the requests

The search URL can currently only be created as a .html file in the root, meaning that an exception needs to be created within the server configuration to exclude it from the normal rewrite rules

One solution would be to enforce the use of the `.html` extension in the `Search page` setting, so that the `Use pretty URLs` could do the right thing (eg. create it as an `index.html` file within a `search` directory) - Which should also make it compatible with `@website.searchUrl` in the hbs templates

**Comment by GetPublii** [comment]
Try to use our new [Static Seach](https://marketplace.getpublii.com/plugins/static-search/) plugin, it does not generate an additional results page.
