### ISSUE TITLE
Very long author names are reverse-indented in the sidebar's authors section

### ISSUE THREAD

**Issue by s3nnet** [GetPublii/Publii#1074]
That is to say they are slightly left to the other entries

**Comment by s3nnet** [comment]
![Publii_LongAuthor_ReverseIndent](https://user-images.githubusercontent.com/88955021/153721428-0c4dc6d3-2cf3-482a-a8c7-fac2a4febf1c.png)

**Comment by bobmitro** [comment]
For questions about Publii functionality, themes, plugins, or other general queries, please contact our development team via the [community forum](https://forum.getpublii.com/).
