### ISSUE TITLE
Fix GPDR / DSGVO / TTDSG Compliance by binding video embeds and comments to an un-preselected functions cookie

### ISSUE THREAD

**Issue by s3nnet** [GetPublii/Publii#1077]
European courts and authorities are dropping rulings like mad, Google Analytics (used by Odysee and probably Youtube, too) needs permission, Disqus probably as well.
https://www.wired.com/story/google-analytics-europe-austria-privacy-shield/

**Comment by bobmitro** [comment]
Publii has a built-in tool to handle this kind of things https://getpublii.com/docs/website-settings.html#gdpr

**Comment by s3nnet** [comment]
Sure, but the idea was to make it default to protect Publii beginners from certain business cases based on copyright or law infringements. Privacy and legal certainty by Design™ of sorts.

**Comment by s3nnet** [comment]
I see. I read the docs about how to do the trick with the disqus script, but I coundn't find documentation on how to bind video embeds to cookie groups. Maybe that should be added.
Btw, I'm a good documentation writer ;-)

**Comment by dziudek** [comment]
For videos it is impossible now to get consent for videos via cookie banner - it will be possible with v.0.39, as cookie banner in this version will emit consent custom events which can be handled via custom scripts which will replace video src attributes. Maybe I will even prepare small plugin which will replace specific iframes src with data-src and will integrate with our cookie banner

**Comment by s3nnet** [comment]
That's great!
Count me in if you need translation, documentation or testing.
