### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by wuniversales** [GetPublii/Publii#1080]
### Operating system

Manjaro Linux Latest Version

### Publii version

v.0.38.3 (build 14238)

### Post editor

WYSIWYG editor

### Bug description

https://imgur.com/ICWENN3
As shown in the gif, the information is not saved when using the corrector in the title of the post.

**Comment by dziudek** [comment]
This issue will be fixed in v.0.39 as I will change a method of detecting changes in the post title
