### ISSUE TITLE
[Bug]: Issue with Prism.js code highlighting, Line Breaks, Copy Code (WYSIWYG Editor)

### ISSUE THREAD

**Issue by candideu** [GetPublii/Publii#1084]
### Operating system

Windows 10

### Publii version

v.0.38.3 (build 14238)

### Post editor

WYSIWYG editor

### Bug description

I just spent the last hour trying to get the Prism Code highlight to work on the Mercury theme and Documentation theme, and was stuck on the code displaying as one long line with a horizontal scroll, as opposed to including the line breaks from the copied code. I had no issues with the Block Editor, but the WYSIWYG Editor had the horizontal scroll issue.

### Steps to reproduce

I then tried the following steps:
1. Paste your code as is in the editor
2. Highlight the code and select “Pre” from the 2nd dropdown on the 2nd row of the Post Editor.
3. With the code still highlighted, select “Line numbers < pre >” from the 1st dropdown on the 2nd row of the Post Editor.
4. With the code still highlighted, select “Code” from the 2nd dropdown on the 2nd row of the Post Editor.
5. With the code still highlighted, select “Code-[LANGUAGE]” from the 1st dropdown on the 2nd row of the Post Editor.

This helped with eliminating the horizontal scroll, but clicking on “Copy” only copied the first line of code…

It appears that when a code reference is added to the WYSIWYG Editor, it creates separate < code > elements for each line inside the < pre >, and when you try to place all the code in the same < code > element, the line breaks aren’t generated properly (even if you manually add < br > elements).

**Comment by bobmitro** [comment]
It's not an app issue. For questions about Publii functionality, themes, plugins, or other general queries, please contact our development team via the community forum.

**Comment by candideu** [comment]
> It's not an app issue. This is how the Tiny Editor works. I propose to dress your code with appropriate tags in HTML mode. The best way is to use the Block editor.
> 
> For questions about Publii functionality, themes, plugins, or other general queries, please contact our development team via the community forum.

I've tried all kinds of variations, HTML-wise, for the code snippets, but it still didn't look right. Either all the code was on one line with a horizontal scroll (ignored line break), or it displayed correctly but only copied the first line. I've turned off the "Copy Code" feature for now, and I guess I'll just use the Code Block Editor for posts that have code snippets

**Comment by LochanLoch** [comment]
Still copy only first line ...

**Comment by LochanLoch** [comment]
Found a Workaround ... HTML Code if someone still interested.

**Comment by candideu** [comment]
> Found a Workaround ... HTML Code if someone still interested.

Yes, please share. My question was closed on both GitHub and [the forum](https://forum.getpublii.com/topic/issue-with-prism-js-code-highlighting-line-breaks-copy-code-wysiwyg-editor/) (even though I was told to use the forum).

**Comment by candideu** [comment]
@LochanLoch 

> Found a Workaround ... HTML Code if someone still interested.

Yes, please share.

Does it look something like this? I just remembered that I had found a workaround a while back:

Create a draft post with the Block Editor and add a Code Block. Paste your code and preview the page. Inspect the code block and copy the `<pre>` inside the `<div class="code toolbar">`.

https://user-images.githubusercontent.com/55474996/211183137-6e9a380c-819c-484f-8b73-73a38e41ef79.mp4

Open your WYSIWYG Post, and open the Source code editor. Paste the pre-code from the previous step in the desired location. Apply changes and preview.

https://user-images.githubusercontent.com/55474996/211183369-30c4750f-84fd-461b-a25c-70925d28ed34.mp4

To make any changes to the code, you'll have to run these steps again from the Block Editor.


It would be great to get this fixed for the WYSIWYG Editor to make this more efficient @bobmitro

**Comment by candideu** [comment]
For comparison purposes:

## Here's what the WYSIWYG Editor generates on its own if you try to format code:

```html
<pre class="language-css" tabindex="0">
  <code class="language-css"><span class="token selector">pre</span> <span class="token punctuation">{</span>
  </code>
    <br>
    <code class="language-css">  <span class="token property">background-color</span><span class="token punctuation">:</span> $dark<span class="token punctuation">;</span>
  </code>
  <br>
  <code class="language-css">  <span class="token property">white-space</span><span class="token punctuation">:</span> pre-wrap<span class="token punctuation">;</span>
  </code>
  <br>
  <code class="language-css"><span class="token punctuation">}</span>
  </code>
</pre>
```

In this case, only the first line is copied:

![](https://i.imgur.com/HaoLvIB.gif)

## Here's what the pasted `<pre>` from the Block Editor looks like:

```html
<pre class="line-numbers language-css" tabindex="0">
  <code class="language-css"><span class="token selector">pre</span> <span class="token punctuation">{</span>  
    <span class="token property">background-color</span><span class="token punctuation">:</span> $dark<span class="token punctuation">;</span>
    <span class="token property">white-space</span><span class="token punctuation">:</span> pre-wrap<span class="token punctuation">;</span>
    <span class="token punctuation">}</span><span aria-hidden="true" class="line-numbers-rows"><span style="height: 34.4333px;"></span><span style="height: 34.4333px;"></span><span style="height: 34.4333px;"></span><span style="height: 34.4333px;"></span></span><span class="line-numbers-sizer" style="display: none;"></span>
  </code>
</pre>
```

With this, the entire code is copied:

![](https://i.imgur.com/bpyd13j.gif)

**Comment by LochanLoch** [comment]
OK for Publii I noticed that the COPY Button not in all Themes is Implemented - when it is than this worked:
<pre tabindex="0"><code class="language-MirDochEgal"><span class="token">..	A ..</span>
<span class="token">..	B ..</span>
<span class="token">..	C ..</span>
</code></pre>

```
<pre tabindex="0"><code class="language-MirDochEgal"><span class="token">..	A ..</span>
<span class="token">..	B ..</span>
<span class="token">..	C ..</span>
</code></pre>
```
MirDochEgal can but must not a Code language :-)
The pre and code is than the main bracket for the code - Look Test A and the CODE ;-)
On my [Publii Test Page - Theme: ProDoc](https://zudrosdatius.de/test.html#eintestzulualatex) all other sides I test this time don't have that Copy Button ... maybe its easy xD

**Comment by candideu** [comment]
@LochanLoch the "Copy" button is a Prism.js functionality. You just have to add Prism.js to themes that don't have it: https://getpublii.com/docs/highlight-your-code-syntax-with-prism-js.html

**Comment by LochanLoch** [comment]
> @LochanLoch the "Copy" button is a Prism.js functionality. You just have to add Prism.js to themes that don't have it: https://getpublii.com/docs/highlight-your-code-syntax-with-prism-js.html

Yeah one thing I still don't do @ all Sites ;-) Thanks for it @candideu.
