### ISSUE TITLE
Sync Gitlab existing site

### ISSUE THREAD

**Issue by javiergradiche** [GetPublii/Publii#1086]
I have a site configured and working fine with Gitlab.

When I want to share the project with other Gitlab user and it fails the sync, looks like it's only uploading the local version (empty for the 2nd user).

Is the Gitlab sync working in 2 ways (upload+ download/merge)?.

**Comment by dziudek** [comment]
Hi,

GitLab sync is working in one way - from Publii to Gitlab. Please remember that you deploy only final files to Gitlab, so there is no way to receive applied changes from other users.

**Comment by javiergradiche** [comment]
Hi @dziudek thanks for your prompt response. 

Is there any other type of server integration that supports sync in both ways?

**Comment by dziudek** [comment]
Hi,

Unfortunately there are no server integration which supports sync in both ways. All deployment methods syncs only output site data. For two ways sync it is necessary to sync also input site data and it will require a lot of core changes in the app, so at this moment we have no plans for such integration - sorry.
