### ISSUE TITLE
[Bug]: Publii does not copy files from the File manager into destination directory

### ISSUE THREAD

**Issue by anonymousbugreporter2602** [GetPublii/Publii#1087]
### Operating system

Windows 10

### Publii version

v.0.38.3 (build 14239)

### Post editor

Block editor

### Bug description

When site is deployed into local filesystem - Publii does not copy files from the File manager into destination directory.

### Steps to reproduce

1. Install the app
2. Create a site with default theme and a couple of posts
3. Got to Server section, and choose output type - "non compressed catalog", choose any folder for destination. Enter site URL.
4. Go to Tools - File manager, and create or upload the ".htaccess" file
5. Press "Sync your website"

Expected behaviour: the ".htaccess" file should be copied into destination directory. 
In fact it's not.

### Relevant log output

```shell
(No errors in logs)
```

**Comment by dziudek** [comment]
Hi,

Thank you for your feedback - yes, this bug occurs under manual deployment. It will be fixed in the upcoming v.0.39 release :)
