### ISSUE TITLE
[Feature Request]: Add extensions to the store

### ISSUE THREAD

**Issue by wuniversales** [GetPublii/Publii#1088]
### Feature Description

I would like to add a plugin but I don't see a way to register.
Thanks greetings

**Comment by bobmitro** [comment]
Hi @wuniversales 
We must reflect carefully on the concept of making the Marketplace available to third parties/vendors; for now, please use the forum.

**Comment by wuniversales** [comment]
Okay thanks

**Comment by candideu** [comment]
@wuniversales What plugin is it?

**Comment by dziudek** [comment]
I am closing this issue due inactivity. Also it is not strictly related to the Publii core. As I remember we have similar topic in the official forum, where this topic can be continued.
