### ISSUE TITLE
[Feature Request]: Markdown extended syntax

### ISSUE THREAD

**Issue by Grishkaone** [GetPublii/Publii#1089]
### Feature Description

Hello there !

The markdown editor is my favorite way of publishing on my Publii's website. The classic syntax is juste simple and straitforward. But it can lack some stuff.

Here come the [Extended Syntax ](https://www.markdownguide.org/extended-syntax/): It add many capabilities to markdown, such as footnotes, highlight or subscript. 🤩

Could this be integrated into Publii?

**Comment by dziudek** [comment]
Hi,

As I see marked engine used in Publii does not support such features. And changing engine now for other can lead to issues with existing websites using markdown. As a fallback - please remember that you can use pure HTML code for the missing elements.

So at this moment we are not considering adding such feature.
