### ISSUE TITLE
[Bug]: Cusdis plugin is not building the comment form with self-hosted version

### ISSUE THREAD

**Issue by thumbfighter** [GetPublii/Publii#1090]
### Operating system

Elementary OS 6.1

### Publii version

0.39.0 (build 15465)

### Bug description

The new cusdis plugin is great. Less work than adding a cusdis.hbs partial, but the script to build the comment section form is loaded from an external app instead of my self-hosted version of cusdis.

This is the script added in the post. Look at the source. It should have said `https://myselfhostedcusdis.com/js/cusdis.es.js` instead.
```
<script type="[text/javascript]()">
						
			(function () {
				var d = document, s = d.createElement('script');
				s.src = 'https://cusdis-comments-candidexmedia.vercel.app/js/cusdis.es.js';
				s.defer = true;
				(d.head || d.body).appendChild(s);
			})();
		
					</script>
```

### Steps to reproduce

Self-host cusdis
Add the cusdis plugin to Publii
Check the source
The script to build the form is pointing to external source

**Comment by bobmitro** [comment]
The Cusdis plugin has an option, called "Host data" to provide the URL to your self-hosted script version.
<img width="942" alt="screenshot 2022-03-20 at 07 01 16" src="https://user-images.githubusercontent.com/1391007/159150318-9b00cfbb-f5fb-4a58-8516-c380bec76c63.png">

**Comment by thumbfighter** [comment]
The Data host already has my self-hosted url but doesn't get picked up.

**Comment by bobmitro** [comment]
Could you provide with me the URL to your locally hosted  cusdis.es.js script?

**Comment by thumbfighter** [comment]
Here: https://comments.simbly.me/js/cusdis.es.js

**Comment by bobmitro** [comment]
Try with this version:
[cusdisComments_1.1.0.zip](https://github.com/GetPublii/Publii/files/8310707/cusdisComments_1.1.0.zip)

**Comment by thumbfighter** [comment]
That worked. Thank you!

**Comment by bobmitro** [comment]
great, thanks for your help.
