### ISSUE TITLE
[Feature Request]: News Websites with Publii

### ISSUE THREAD

**Issue by ceodigvijay** [GetPublii/Publii#1093]
### Feature Description

News websites have a specific sitemap format as described by google https://developers.google.com/search/docs/advanced/sitemaps/news-sitemap

But I see Publii create the standard sitemap for articles.

Is it possible to create a custom google news sitemap with Publii.

It will also be great to change the type of structured data from Article to NewsArticle.
<script type="application/ld+json">{"@context":"http://schema.org","@type":"Article","mainEntityOfPage":{"@type":"WebPage","@id".........

**Comment by dziudek** [comment]
Hi,

It looks like a niche feature, which should be solved rather using plugin than as a core feature.
