### ISSUE TITLE
[Bug]: Manual deployment process aborts in heavier sites

### ISSUE THREAD

**Issue by gorkasiron** [GetPublii/Publii#1099]
### Operating system

Windows 10 Pro N

### Publii version

0.39.1 (build 15483)

### Post editor

Block editor

### Bug description

Hi,
I’m facing an issue. I'm using “Manual upload” to zip the website. The whole site surpases like 2GB of size and Publii cant zip it . If abort the process the next alert appears:
![alert](https://user-images.githubusercontent.com/94943200/162478837-1900230c-ab9a-49b2-a3cb-d76b271c9a1d.png)

The JS stacktrace of deployment errors log says: FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory

So its a problem with the memory assigned? I have noticed that a new process runs in task manager when deployment runs and when it reaches 1GB of memory usage it closes
![image](https://user-images.githubusercontent.com/94943200/162480776-6d981ff7-1888-4b83-b2db-0252f1d3e624.png)

I've created another new project just to test if the size is the main cause of the issue, and with his 3MB of content causes no errors when zip.
Does someone have deal with a similar problem?

### Steps to reproduce

1. Create a website who sizes at least 1.5GB of content
2. Choose Manual upload. The options into Manual uploads doesnt matter.
3. Start sync

### Relevant log output

```shell
<--- Last few GCs --->
[21592:000047960032C000]     3649 ms: Scavenge 214.4 (233.1) -> 214.4 (233.1) MB, 39.2 / 0.0 ms  (average mu = 0.987, current mu = 0.987) allocation failure 
[21592:000047960032C000]     5980 ms: Mark-sweep 406.4 (425.1) -> 214.4 (233.2) MB, 190.5 / 0.0 ms  (+ 0.2 ms in 1 steps since start of marking, biggest step 0.2 ms, walltime since start of marking 2332 ms) (average mu = 0.962, current mu = 0.957) allocat

<--- JS stacktrace --->
FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory
 1: 00007FF7A07B6A06 node::Buffer::New+50294
 2: 00007FF7A07B6C0F node::OnFatalError+463
 3: 00007FF7A3054F8A v8::Data::IsFixedArray+842
 4: 00007FF7A3054EDC v8::Data::IsFixedArray+668
 5: 00007FF7A3126873 v8::JSHeapConsistency::CheckWrapper+68227
 6: 00007FF7A1F756FE v8::CppHeap::GetHeapHandle+1342030
 7: 00007FF79F7F7D99 cppgc::DefaultPlatform::MonotonicallyIncreasingTime+521033
 8: 00007FF79F7F7806 cppgc::DefaultPlatform::MonotonicallyIncreasingTime+519606
 9: 00007FF7A1F4B5C4 v8::CppHeap::GetHeapHandle+1169684
10: 00007FF7A1F814A7 v8::CppHeap::GetHeapHandle+1390583
11: 00007FF7A1F3AF2E v8::CppHeap::GetHeapHandle+1102462
12: 00007FF7A1F402FE v8::CppHeap::GetHeapHandle+1123918
13: 00007FF7A2032320 v8::internal::OSROptimizedCodeCache::EvictMarkedCode+699616
14: 000008F007F0B23C
```

**Comment by dziudek** [comment]
Hi,

I supopse that it is an issue with limitations of the archivization library. 
TAR is still working?

I do not know if we will be able to fix it if the used library has such issue, but I will try.

**Comment by dziudek** [comment]
> I discovered the bug while using ZIP compiler but affects in any output option.

Do you mean that even when there are no compression (TAR/ZIP) this problem occurs? I am asking, because it would be strange - I had no errors while relocating a lot of websites once per time during sites location change (it was few GBs of data) and manual deploy without compression is like moving files. Maybe you have some problematic or very big file in your website?

**Comment by gorkasiron** [comment]
> > I discovered the bug while using ZIP compiler but affects in any output option.
> 
> Do you mean that even when there are no compression (TAR/ZIP) this problem occurs? I am asking, because it would be strange - I had no errors while relocating a lot of websites once per time during sites location change (it was few GBs of data) and manual deploy without compression is like moving files. Maybe you have some problematic or very big file in your website?

The problem occurs even using manual sync without compression, but I've been testing and, yeah, the problem is related with the size of one file and not the size of the whole website. At least in my case just uploading an 100MB file in any place of the website (like uploading a zip into file manager tool) the process of syncronization get stuck.

I think it's okay if Publii cannot withstand any file bigger than that size; but maybe an alert could be useful to understand why this happens

**Comment by dziudek** [comment]
Hi,

This issue will be fixed in v.0.40 - I have found that Publii tried to calculate MD5 sum on bigger files what caused the described issue
