### ISSUE TITLE
[Bug]: Theme/Website primary logos should not be lazily loaded.

### ISSUE THREAD

**Issue by m00tiny** [GetPublii/Publii#1104]
### Operating system

Manjaro Linux

### Publii version

Latest Stable

### Bug description

When enabling lazy loading of images, the main or primary logo should not be lazily loaded. It is always rendered above the fold.

### Steps to reproduce

Enable lazy loading, sync website.

**Comment by bobmitro** [comment]
What theme do you use?

**Comment by m00tiny** [comment]
Technews 2.4.0.0  

I apologize if it is not maintained by the Publii team. I assumed all of the open themes were, and now realize that could've been an error or that this may not be the right place to submit the issue.

**Comment by dziudek** [comment]
I am closing this issue as it is not strictly related to the Publii core but to the themes.

**Comment by m00tiny** [comment]
> I am closing this issue as it is not strictly related to the Publii core but to the themes.

I'm not objecting to closing it. But, to be clear, I simply didn't myself test with any other themes. But, I would assume it has more to do with the Lazy Loading code than any particular theme.
