### ISSUE TITLE
[Bug]: Cannot install UI language pack

### ISSUE THREAD

**Issue by StefanoAgazzi** [GetPublii/Publii#1105]
### Operating system

macOS Monterey 12.3.1 (21E258)

### Publii version

0.39.1 build 15483

### Bug description

Cannot install UI language pack, get an error message when installing new UI language.

### Steps to reproduce

1. Enable the experimental feature
2. Download `it.zip` from [here](https://github.com/GetPublii/Publii-ui-locales/tree/main/downloads)
3. Click on the install button in the app and select that zip file
4. This error shows up

![image](https://user-images.githubusercontent.com/2686945/162898569-8e32d8a8-0100-4b4e-b482-082e5fd8f82f.png)

```
Uncaught Exception:
Error: EEXIST: file already exists, mkdir '/Users/stefanoagazzi/Documents/Publii/languages/__TEMP__'
at Object.mkdirSync (node:fs:1334:3)
at IpcMainImpl.<anonymous> (/Applications/Publii.app/Contents/Resources/app.asar/back-end/events/app.js:253:24)
at IpcMainImpl.emit (node:events:390:28)
at IpcMainImpl.emit (node:domain:475:12)
at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:10120)
at EventEmitter.emit (node:events:390:28)
at EventEmitter.emit (node:domain:475:12)
```

**Comment by JoKeyser** [comment]
Hm, it works for me, also using Publii Version: 0.39.1 (build 15483), but on Arch Linux.

**Comment by gpsblues** [comment]
[OT]
Hi Stefano, I'm the author of the Italian translation. Please let me know if anything can be improved.

**Comment by dziudek** [comment]
I am closing this issue due inactivity. If any new details will appear - feel free to reopen it
