### ISSUE TITLE
[Bug]: Menubar visible on Fedora

### ISSUE THREAD

**Issue by Verhoeckx** [GetPublii/Publii#1109]
### Operating system

Fedora 35 Silverblue

### Publii version

0.39.1 (build 15483)

### Bug description

When I launch Publii the taskbar at the top is visible (see screenshot below). 
With the taskbar I mean the menu-items `Publii` and `Edit`. 
It's only visible in version 0.39, in previous versions it wasn't. 
I'm not sure if it's related to Publii or Fedora (and it's window manager).

<br>

![Screenshot from 2022-05-20 12-56-46](https://user-images.githubusercontent.com/64807887/169513967-d5a2b9bc-1cdf-44cb-bd8e-9a61f0bbc383.png)

### Steps to reproduce

1. Install version 0.39 of Publii on Fedora (rpm-package).
2. Start Publii.

**Comment by ljgww** [comment]
its visible on ubuntu too. but this is trivial problem. I would be happier if there are some more important (functional) things fixed.

**Comment by bobmitro** [comment]
Hey @ljgww, any example of functional things to fix? We are finalizing our work on a new Publii release this week, so maybe some things are already fixed.

**Comment by dziudek** [comment]
The menu bar issue will be solved in upcoming v.0.40
