### ISSUE TITLE
[Bug]: Cannot Sync sftp

### ISSUE THREAD

**Issue by cristian-milea** [GetPublii/Publii#1116]
### Operating system

macOS Monterey 12.4

### Publii version

0.39.1 (build 15483)

### Bug description

Hi. I made some minor modifications in my theme, just deleted an old pixel code. Then I wanted to sync my website as I always do but it kept freezing at 68/111. Tried to undo modifications, restore from backup, nothing makes it past step 68. Checked the error log and found this.

### Relevant log output

```shell
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.join (node:path:1172:7)
    at /Applications/Publii.app/Contents/Resources/app.asar/back-end/modules/deploy/sftp.js:223:98
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Comment by dziudek** [comment]
Hi,

This issue occurs when upload error occurs - we have a fix for it which will be included in v.0.40 planned for next week: https://github.com/GetPublii/Publii/commit/b215c6b271677e47f7fab5f1aa126c893adc0f43

Temporary you can use manual deployment method if you cannot skip this error during syncing your website.
