### ISSUE TITLE
[Bug]: Gallery won't open, image file is shown instead

### ISSUE THREAD

**Issue by tobip** [GetPublii/Publii#1117]
### Operating system

Linux Manjaro

### Publii version

0.39.1

### Post editor

WYSIWYG editor

### Bug description

I added a gallery to my post containing several pictures. When I publish the page and click on one of these images, the browser will directly load the image file instead of a gallery pop-up.
I testet several different browsers on three different devices.

I am using the simple theme in v.2.4.1.0

Do I have to activate the Photoswipe plugin somewhere? Am I missing something?
I can change settings in Theme > Gallery but this doesn't seem to have any effect on my blog posts.

### Steps to reproduce

Create new Post using WYSIWYG, add gallery containing a couple of images, save & publish.

**Comment by bobmitro** [comment]
Looks like gallery scripts are not loading; any live example?

**Comment by tobip** [comment]
Thanks for your reply, here is a live example: https://holzkiste.pato.at/

I feel like I am missing something obvious but just can't figure out what it is to get it running :/

**Comment by bobmitro** [comment]
Yes, there are no scripts, and CSS Gallery
Maybe you removed some code snippets while modifying the theme, exactly from the head.hbs and footer.hbs files?

**Comment by tobip** [comment]
As far as I know I didn't change anything, its a stock theme I am using. I will try creating a new project from scratch maybe that helps, give me a moment...

**Comment by tobip** [comment]
For some reason my project seems to be unfixable corrupted. 
New projects are fine, thanks for your help.
