### ISSUE TITLE
[Feature Request]: ▲Vercel support

### ISSUE THREAD

**Issue by fu-sen** [GetPublii/Publii#1122]
### Feature Description

I suggest adding ▲Vercel to Publii's server.
https://vercel.com/

Vercel seems to be specialized for static site generators,
but it can also deploy static sites including simple .html etc.
It has been realized since the beginning of the now.sh era.

With the existence of the Vercel API, Publii may be able to control it.
https://vercel.com/docs/rest-api

Or you could allow Publii to execute certain commands so that you can deploy via the Vercel CLI.
(So you can also use Firebase Hosting, Surge.sh, Neocities, etc.)

Vercel supports GitHub and GitLab, so it is currently possible to deploy via them.
However, some users may not want to create a repository for that. Vercel support is convenient.
Of course we now also have the option of Manual Deployment. Therefore, it takes time to enter Vercel CLI commands.

**Comment by dziudek** [comment]
As Vercel has built-in support for Github: https://vercel.com/integrations/github I do not see a reason to prepare separate integration at this moment. Maybe we will come back to this topic when plugins will be able to handle deployment process. But at this moment we have no plans to add new deployment methods to the core, especially if they can be handled via existing methods like Github/Gitlab repositories.

**Comment by fu-sen** [comment]
I expected more items on the server. Because it leads to an increase in appearance support. However, I've seen trouble cases on the forums on Netlify that seem to be API limitations. t takes effort for the development members to know the new Vercel specifications, and it takes days, so going through GitHub or GitLab will be enough to make it work. Thanks for your consideration.
