### ISSUE TITLE
JS error when opening a post

### ISSUE THREAD

**Issue by htejera** [GetPublii/Publii#1124]
After installing the latest version **0.40.0** the following Javascript error is displayed when opening any of the existing posts:

![error-publii](https://user-images.githubusercontent.com/38955523/177857884-62669ecb-26cd-4fb0-bc61-d04d7b929a35.png)

When closing the popup, the post is loaded correctly.

This error started to happen after upgrading from version **0.39.1 (build 15486)** to **0.40.0 (build 15728)**.

OS: Windows 10

**Comment by dziudek** [comment]
Hi - do you have subfolders under media/files catalog?

**Comment by htejera** [comment]
Hi Tomasz;

I have three files in the directory input/media/files:

![media-files](https://user-images.githubusercontent.com/38955523/177877068-c588cbf7-311a-46c7-8bc2-0c4ceef411ed.png)

**Comment by dziudek** [comment]
@htejera - hmm, and what about /input/root-files? Is some catalog there?

**Comment by htejera** [comment]
@dziudek Yes, I have one folder (whit some content inside), and several files, as can be seen in the following screenshot:

![root-files](https://user-images.githubusercontent.com/38955523/177880093-73c88744-02d3-40f6-9116-3ce938312904.png)

**Comment by dziudek** [comment]
@htejera - thanks for your feedback - that's the reason of this issue - we will release at Friday v.0.40.1 with a fix for it :)

**Comment by htejera** [comment]
@dziudek Great! Thanks to you for your help.

**Comment by dziudek** [comment]
@htejera - problem fixed in newly released v.0.40.1 :)
