### ISSUE TITLE
[Bug]:  Unlimited Wine Popup messages

### ISSUE THREAD

**Issue by meanindra** [GetPublii/Publii#1125]
### Operating system

Pop! os 22.04 LTS

### Publii version

0.40.1 Appimage

### Bug description

Unlimited times wine "DDE failure popup" message after click save and preview button.

![Screenshot from 2022-07-08 19-22-24](https://user-images.githubusercontent.com/36324543/178006830-983e8fcb-b16a-4fb2-87a5-b3332e0a65d3.png)
![Screenshot from 2022-07-08 19-22-14](https://user-images.githubusercontent.com/36324543/178006833-13d0c616-bfce-4422-aa5e-b4759128d84f.png)
.

### Steps to reproduce

Install Lutris+Wine -> Open Publii ->  Change some settings -> Click save and preview button

**Comment by dziudek** [comment]
Sorry, we are not supporting Wine at all - it is "compatibility platform" which can have unexpected behaviours. Please use  Publii versions for available platforms, without additional tools if possible.
