### ISSUE TITLE
Rendering process failed, file already exists

### ISSUE THREAD

**Issue by xstefen** [GetPublii/Publii#1130]
Sorry to resurrect #795 but I have the same issue on any type of generation.

OS: Windows 11 21H2
Publii Version: 0.40.2 (build 15735)

```
Rendering process failed
An error occurred during rendering process:
EEXIST: file already exists, mkdir 'X:\Projects\publii-sites\.previews'

Rendering process failed
An error occurred during rendering process:
EEXIST: file already exists, mkdir 'X:\Projects\publii-sites\xstefendev\output'
```

I've tried setting different dirs, keeping defaults, etc. Same result every time.

_Originally posted by @xstefen in https://github.com/GetPublii/Publii/issues/795#issuecomment-1193278797_

**Comment by xstefen** [comment]
Error was caused due to having empty values set for tag prefix, author prefix, and search page. After entering values in for these, site generated successfully. 

I would never have guessed that based on the error returned, and looking at the log files proved to be unhelpful as well.

An option to disable these would be nice, I think not everyone cares to use tags etc. I'd submit a PR but trust me, you don't want that from me :)

Thanks for your time and releasing your work for free to use, I appreciate you

**Comment by ppp-one** [comment]
I'm having similar issues with 0.40.2 (build 15735) for Windows as well.  First time trying to render the whole site:
```
Rendering process failed
An error occurred during rendering process:

EPERM: operation not permitted, rmdir 'C:\Users\peter\Documents\Publii\sites\test-website\preview\media\authors'
```
I see prefixes set under Site settings -> Advanced options -> URLs, but I have values already there. So can't recreate the fix suggested above.

I can preview "front page only", but not the full website.

**Comment by ppp-one** [comment]
If it's any help for whoever is capable of debugging - I have previously installed node/npm/electron on my laptop prior (for unrelated things) to using Publii. So, I don't know there's somehow some conflict.   I tested Publii on a friend's laptop and everything ran fine there, so something odd is happening here.  Permissions for the respective directories seem like everything should work 🤷‍♂️

**Comment by dziudek** [comment]
@xstefen - tags and other page types can be disabled under renderer settings: https://getpublii.com/dev/how-to-configure-rendering-process-of-your-website/ 

@ppp-one - I have found one place which could cause your issue. I will include this fix in v.0.41.

**Comment by slymeasy** [comment]
I had this same issue today, but I managed to fix it by replacing the sites folder with a backup I made just 30 minutes prior. I was playing with the Gravatar options and got an error trying to sync and then after that it stopped working and I started getting this error. Thankfully, I managed to create my first back up just minutes earlier.
