### ISSUE TITLE
[Bug]: 504 gateway time-out problem

### ISSUE THREAD

**Issue by kangaroo0126** [GetPublii/Publii#1131]
### Operating system

window 10

### Publii version

0.40.2

### Post editor

Block editor

### Bug description

When I update my website on github ,it show "504 gateway time-out"
But preview my changes is ok.
So,how to solve this problem?
Thanks.
[https://i.imgur.com/aH0OxlF.png](url)

**Comment by dziudek** [comment]
Hi,

Do you still have this issue? Looks like a temporary issue with Github API

**Comment by kangaroo0126** [comment]
Yes,I still have this problem.
It continued for four days.

**Comment by dziudek** [comment]
@kangaroo0126 - this issue appeared after Publii update? Also - did you add some bigger files to your website?

**Comment by Samudra888** [comment]
please my publii software can't be opened and the error description is like the image link on my google drive.
please help me for this problem..
https://drive.google.com/file/d/1zmIXHFLPzpWs5t7d06XC6SsMsCGIvYTM/view

**Comment by dziudek** [comment]
@Samudra888 - could you make this file publicly available? I cannot access it so I do not know what is your issue

**Comment by dziudek** [comment]
I am closing this issue due inactivity - please reopen it if necessary
