### ISSUE TITLE
[Bug]: Synchronization is always complete every time

### ISSUE THREAD

**Issue by jeckyl** [GetPublii/Publii#1132]
### Operating system

macOS 12.2.1 (21D62)

### Publii version

0.40.2 (0.40.2)

### Post editor

WYSIWYG editor

### Bug description

It seems that the synchronization script can't reuse the last synchronization date because it does a full synchronization every time.

-----------

Il semble que le script de synchronisation n'arrive pas à réutiliser la date de dernière synchronisation, car il me fait une synchronisation intégrale à chaque fois.

**Comment by dziudek** [comment]
Hi,

Are you sure that Publii sends all files? Maybe it sends a lot of files but not all? For example - if you change some parts of footer/main menu then Publii must update all HTML files, so it can look that the whole page is synced.

**Comment by jeckyl** [comment]
Hi,

My site is quite small, just a hundred or so articles, and it syncs 4162 files, which I found this morning after my new article.

So, yes, I think it synchronizes the whole thing each time, because normally, I should only have a hundred files at most.

I haven't updated the template to its latest version, maybe it will have an impact, but I doubt it.

**Comment by dziudek** [comment]
@jeckyl - which deployment method are you using? Do you have file `files.publii.json` on your server?

**Comment by jeckyl** [comment]
TFP and yes i have this file.
I made new test without trouble.
very strange.

**Comment by dziudek** [comment]
Ok, if the problem will reappear - please let me know in this thread. Now I am closing this issue.
