### ISSUE TITLE
[Feature Request]: Use EXIF data as image comment

### ISSUE THREAD

**Issue by j0el** [GetPublii/Publii#1135]
### Feature Description

New to Publii and it is working fine.  I would like to put EXIF info into images, i.e. aperature, shutter speed, lens, comments...
Would this be best as a plug-in, part of a theme or a base feature?

**Comment by dziudek** [comment]
Hi,

It looks like a niche feature, which should be solved as a plugin, not a core feature. But it can be also problematic, because as I remember - sharp library used for creating thumbnails probably removes EXIF data during image optimization.

**Comment by j0el** [comment]
I will try to write a plugin.  For photographers it is not a niche feature
as usually the fstop, shutter speed and ISO are interesting, but I agree
for most people it is probably a niche.  I think it would only be displayed
on the larger views.  I see it as an addition to captions.  The easy way to
do it would be to pull selected exif data and add it to the caption.

Anyway I will try to figure out how plugins integrate.  I am not familiar
with handlebars, but perhaps a helper function and handlebars could just
pull the info and append to the caption.

Thanks for responding.
