### ISSUE TITLE
[Bug]: Button visibility problem in "Authors", "Tags" pages

### ISSUE THREAD

**Issue by bgodole** [GetPublii/Publii#1137]
### Operating system

Windows 10

### Publii version

0.40.2

### Bug description

When using Albanian as UI language, at least one of the three buttons at the bottom of the "Authors" and "Tags" pages is not entirely visible. I could delete some word in Albanian until all three buttons fit as in the English version. But can it be fixed with CSS on Publii's side so the third button drops to a new line when it exceeds the boundary of the div?

![183379293-4377e386-c958-4936-af75-661b529c69bd](https://user-images.githubusercontent.com/15838230/184527174-bde9ad35-6f2b-498a-bd5e-374f4fce7e0f.png)

### Steps to reproduce

Switch UI language to Albanian (download from [Publii-ui-locales)](https://github.com/GetPublii/Publii-ui-locales). Go to the site's Authors page and click one of them.

**Comment by dziudek** [comment]
@bgodole - we will increase the available space and also add different flex style for these buttons so for longer translations the last button will go to the next row. I do not see any other solution if we want to avoid too much free space on languages with shorter translations.

**Comment by bobmitro** [comment]
Fixed, available in the next Publii release.
