### ISSUE TITLE
[Feature Request]: Create AVIF/WebP images

### ISSUE THREAD

**Issue by uwe-schwarz** [GetPublii/Publii#1139]
### Feature Description

With the upcoming support of AVIF in Safari and the already good support of WebP, I would like to have the option to generate all formats.

I'm aware that this will take quite a bit of time to generate the images, but this shouldn't be a big issue for small sites and big sites could toggle the feature to preference.

**Comment by dziudek** [comment]
Hi,

Support for WebP in responsive images will be available in v.0.41 planned for next week. AVIF is still too less popular to handle like WebP. So we have no plan for AVIF support at least for nearest months.
