### ISSUE TITLE
[Bug]: "Publish and Close" ignores custom published date for drafts

### ISSUE THREAD

**Issue by bgodole** [GetPublii/Publii#1140]
### Operating system

Windows 10

### Publii version

0.40.2

### Post editor

Block editor

### Bug description

When working with drafts in Block editor mode, the "Publish and Close" button does not use the custom published date, instead defaults to present time. This issue shares similarities with bug #593. 

### Steps to reproduce

Make a duplicate of an existing post - in my case the post was created using the Block editor. Open the newly created copy and customize the published date to a few days ago. Now select the "Publish and Close" button from the dropdown on the top right.

**Comment by dziudek** [comment]
Hi,

I have added it to my ToDo for the next release
