### ISSUE TITLE
[Bug]: Post Insert/Edit Link function only shows first 1000 files from File Manager

### ISSUE THREAD

**Issue by ymaurer** [GetPublii/Publii#1141]
### Operating system

Windows 10

### Publii version

0.40.2 (build 15735)

### Post editor

WYSIWYG editor

### Bug description

Hi,

I have a lot of PDF files on my site and would like to link those from posts. Currently there are around 1100 files. In the WYSIWYG Editor I am trying to add a link to a PDF that I put in the root-files. I select the "Select link type" option "File from File Manager" and then in "File", I'm scrolling to the end of the list. However the last entry is only the 1000st file and the 100 next files are missing. I cannot select them to point the link to them. Only the first 1000 entries (by alphabetical ordering) are shown.

Would it be possible to change that limit to a higher number? Publii is really great and fast and for the rest it really suits my needs.

Thank you very much

### Steps to reproduce

1. Create a new Publii site
2. take an existing pdf file (e.g. base.pdf)
3. create 1001 copies of it in the root-files directory (e.g. 
```
seq 1 1001 | awk '{printf("%05d.png\n",$1)}' | xargs -l cp /var/tmp/base.pdf
```
4. Create a new post with the WYSIWYG editor
5. click on "Insert/edit link"
6. Choose "File from File Manager" under "Select link type"
7. Click in the "File" dropdown list and scroll to the end.
8. The file 01001.pdf will not appear.

**Comment by dziudek** [comment]
Hi,

It is not a bug, but as I suppose the performance limitation in the library used to generate select dropdowns (dropdown with few thousands of options can be really slow). But for more files you can still use search feature to use all files - please check my example - I have generated ~1200 PDFs. The PDFs with names test820.pdf and over are not initially visible, but you can still access files like test999.pdf via the search functionality:

https://user-images.githubusercontent.com/22004/187020005-6ad2217e-251b-4d02-a23c-62af112c9186.mp4

**Comment by ymaurer** [comment]
Thank you,

That is indeed a good workaround.
