### ISSUE TITLE
[Feature Request]: Add support for other templating languages

### ISSUE THREAD

**Issue by Namerif** [GetPublii/Publii#1147]
### Feature Description

I'm not very familiar with the CMS yet, because I only discovered it today (and I have to say, so far it's _awesome_), but when I got to themes, my first thought was "why does it only support Handlebars?". It would be very nice if you could add support for other templating languages, such as Nunjucks. This one, in my opinion, would be especially useful since there are many languages with similar syntax (Jinja, Twig, Liquid). So in some cases, themes written for them will also work with Publii if Nunjucks is supported. And as far as I understand, it wouldn't be hard to add it since it works pretty much the same way: you just supply the template string with some data, and it gets rendered (correct me if I'm wrong).

**Comment by dziudek** [comment]
Hi,

We have no plans to support other templating languages in any predictable future due fact, that handlebars are deeply coupled with our rendering engine, and now adding support for other templating language is a task which requires huge amount of work - we can spend this time on much more valuable tasks :)
