### ISSUE TITLE
[Bug]: TinyMCE WYSIWYG Editor Additional Valid Elements not Working

### ISSUE THREAD

**Issue by sosukeinu** [GetPublii/Publii#1149]
### Operating system

Ubuntu 22.04

### Publii version

0.40.3

### Post editor

WYSIWYG editor

### Bug description

In site settings I added `model-viewer[*]` to the "Additional valid elements in the WYSIWYG editor" block. However, when I edit a post and add to the raw HTML `<model-viewer alt="my model" src="#INTERNAL_LINK#/file/media/files/some-model.glb" poster="#INTERNAL_LINK#/file/media/files/poster.webp" shadow-intensity="1" camera-controls touch-action="pan-y"></model-viewer>` it is replaced with whitespace.

### Steps to reproduce

Detailed in Bug description.

**Comment by nztomas** [comment]
yes doesn't work me neither... (different tag name)... I've tried to add *[*] to allow all, no change still strips everything...

**Comment by berkeleynerd** [comment]
In my case the tag `<input id="cb12" type="checkbox" \>` is replaced by `<input id="cb12" type="checkbox">` and any attempt to add </input> to close the tag results in that ending tag being stripped out. I know it's terrible for public but this is a personal blog so I'd be happy if I could just disable tiny MCE's attempts to sanitize my HTML altogether. If this is possible by flipping a switch somewhere that would be a workaround for me.

**Comment by dziudek** [comment]
@sosukeinu @nztomas - I have found a reason of these problems:

1) The custom tags works if you put them inline with text - then they are wrapper with `<p>` and are not removed e.g. when you put:

```
Viewer: <model-viewer alt="my model" src="#INTERNAL_LINK#/file/media/files/some-model.glb" poster="#INTERNAL_LINK#/file/media/files/poster.webp" shadow-intensity="1" camera-controls touch-action="pan-y"></model-viewer>
```

It will work - without the `Viewer: ` text - not.

2) If you need to put the custom tag as standalone element, you must at this moment add custom config in your theme: https://getpublii.com/dev/how-to-add-custom-config-or-js-for-post-editor/ and use:

```
{
	"custom_elements": "model-viewer"
}
```

I will add in Publii v.0.42 option to set custom elements like extended valid elements from site settings.
