### ISSUE TITLE
[Bug]: Several embeds are not displayed

### ISSUE THREAD

**Issue by Yamakuni** [GetPublii/Publii#1151]
### Operating system

Desktop : Windows 11 (22H2) - Server : Debian 11.5

### Publii version

Version: 0.40.3 (build 15745)
Theme : Simple (v2.5.0.0)

### Post editor

WYSIWYG editor

### Bug description

Hello, 
I think I'll need a hand

When I insert Spotify or Soundcloud embed (via the wysiwyg editor or directly in html), they appear in the editor, but once the preview is generated or the page is online, there is only an empty space.

However, for example with Soundcloud when the "Autoplay" option is activated, it works on the online pages and previews, but is not displayed.

I tested in several browsers: Firefox, Chrome and Edge, and it does not work on any of them

Thanks in advance for your help

**Comment by bobmitro** [comment]
Take a look at this: https://forum.getpublii.com/topic/audio-player-embed/, it seems this might help you.
