### ISSUE TITLE
[Feature Request]: Documentation on how to create a plugin

### ISSUE THREAD

**Issue by svallory** [GetPublii/Publii#1152]
### Feature Description

Hi, I'm evaluating Publii for a project and I'll need to create specific plugins that I'm happy to share with the community. Unfortunately, I couldn't find any documentation on how to do that.

Can you point me to the docs or send me a list of relevant files I need to check to understand how the plugin system works?

Thanks in advance for your time!

**Comment by david-alexander-fleming** [comment]
@svallory I was looking for the same. I found a [post from Tomasz Dziuda in the forum](https://forum.getpublii.com/topic/guide-on-writing-plugin/) from August 13th:

> At this moment documentation for the plugins is unavailable, because plugins API is still experimental, and we want to share documentation, when we will know that API is stable to avoid situation that some Publii changes in API will break plugins created by community.

**Comment by nztomas** [comment]
Can you give us some source code of existing plugin? I'm writing some custom code for myself and instead of hacking it through code change on my sites I would like to create a plugin and for now just manually copy it to each site I'm using.

Also what's the date for opening of api to write plugins to community? It's going to be a killer feature...

**Comment by s3nnet** [comment]
It's basically JS and Json, you can study existing plugins in Publii's plugin folder.

**Comment by candideu** [comment]
> Also what's the date for opening of api to write plugins to community? It's going to be a killer feature...

@nztomas it's possible to submit extensions now: https://getpublii.com/promote-your-extensions/

You can find existing plugins here: https://marketplace.getpublii.com/plugins/

**Comment by dziudek** [comment]
I am working on the documentation draft here: https://github.com/GetPublii/Publii/discussions/1359

So I can close this thread
