### ISSUE TITLE
[Bug]: WebP format is still JPEG

### ISSUE THREAD

**Issue by uwe-schwarz** [GetPublii/Publii#1159]
### Operating system

macOS Ventura 13.0

### Publii version

0.41.0 (build 15910)

### Bug description

Selecting "Convert to WebP format" only changes the file extension of the generated responsive images, they are still JPEG and have the same size.

### Steps to reproduce

1. Select "Convert to WebP format"
2. Regenerate thumbnails

**Comment by j0el** [comment]
Maybe related.  How do I use the Sharp library for generating thumbnails?  I am on OSX.

**Comment by uwe-schwarz** [comment]
Sharp library was preselected for me, never changed it. I started using Publii somewhere around 0.40, maybe 0.39.

**Comment by dziudek** [comment]
@uwe-schwarz - so after regenerating thumbnails you still have JPGs? BTW please make sure that you mean responsive thumbnails with prefixes like `-xs`, `-xl` etc. Because the original images remains untouched.

@j0el - you can change it under app settings https://getpublii.com/docs/publii-global-settings.html - it is located under "three dots" menu in the right upper corner.

**Comment by uwe-schwarz** [comment]
@dziudek

WebP:

```
% file dog-box.jpg responsive/*
dog-box.jpg:               JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, progressive, precision 8, 5315x3567, components 3
responsive/dog-box-l.webp: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=6, orientation=upper-left, xresolution=86, yresolution=94, resolutionunit=2], baseline, precision 8, 1400x940, components 3
responsive/dog-box-m.webp: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=6, orientation=upper-left, xresolution=86, yresolution=94, resolutionunit=2], baseline, precision 8, 700x470, components 3
responsive/dog-box-s.webp: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=6, orientation=upper-left, xresolution=86, yresolution=94, resolutionunit=2], baseline, precision 8, 350x235, components 3
```

JPEG:
```
% file dog-box.jpg responsive/*
dog-box.jpg:              JPEG image data, JFIF standard 1.01, resolution (DPI), density 72x72, segment length 16, progressive, precision 8, 5315x3567, components 3
responsive/dog-box-l.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=6, orientation=upper-left, xresolution=86, yresolution=94, resolutionunit=2], baseline, precision 8, 1400x940, components 3
responsive/dog-box-m.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=6, orientation=upper-left, xresolution=86, yresolution=94, resolutionunit=2], baseline, precision 8, 700x470, components 3
responsive/dog-box-s.jpg: JPEG image data, Exif standard: [TIFF image data, little-endian, direntries=6, orientation=upper-left, xresolution=86, yresolution=94, resolutionunit=2], baseline, precision 8, 350x235, components 3
```

**Comment by dziudek** [comment]
@uwe-schwarz - thank you for spotting this :) I have tested this feature, but now I have discovered that the code was working only when thumbnails has been cropped. The fix is ready - we will release it probably at 7th November :)

**Comment by j0el** [comment]
Got it.  All my thumbnails are now WebP!  Thanks for your help.

**Comment by dziudek** [comment]
@uwe-schwarz - FYI v.0.41.1 with fid for this issue has been released :)
