### ISSUE TITLE
Syntax highlighter?

### ISSUE THREAD

**Issue by curtis86** [GetPublii/Publii#116]
I'd love to try this out for a technical blog; Is it possible to add a code syntax highlighter?

**Comment by bobmitro** [comment]
Do you mean to add it to the WYSIWYG editor or to the theme?

**Comment by curtis86** [comment]
To the WYSIWYG editor, so that it persists across all themes.

PS: Thanks for making this CMS, it's fantastic.

**Comment by bobmitro** [comment]
I think this is a good idea to add this to the Documentation theme only - good news - this week we will release a new theme for technical docs.

**Comment by aj-th** [comment]
@curtis86 -

It looks like Code Block already exists (at least in the Simple theme)

![image](https://user-images.githubusercontent.com/36054829/44030287-60a9815e-9ece-11e8-8848-2e7413fabe9b.png)

1. Write a post.
2. Highlight text.
3. When the WYSIWYG edited opens, select Code from the drop-down menu:
![image](https://user-images.githubusercontent.com/36054829/44030405-acbe8fc6-9ece-11e8-85b9-c3d5ab6357fa.png)

**Comment by curtis86** [comment]
Thanks @aj-th ! I was hoping for some syntax highlighting though, as it makes the code blocks much easier to read :)

**Comment by mattie47** [comment]
@curtis86  I haven't tried it, but this might actually do what you want: https://getpublii.com/docs/highlight-your-code-syntax-with-prism-js.html

**Comment by mattie47** [comment]
@curtis86  Cool. Yeah I too just got it working with Technews :-)

Thought I would post my example instructions if anyone comes across this post on Google...


Followed https://getpublii.com/docs/highlight-your-code-syntax-with-prism-js.html

Found this guide slightly confusing without actual examples. 

What I required to get it to work:

_Now you have to load these files into your website:_
_1. Open the head.hbs file (partials/head.hbs) and add the following code:_
_<link rel="stylesheet" href="{{css "prism.css" }}">_
_2. and to the footer.hbs (partials/footer.hbs) add the following code:_
_<script defer src="{{js "prism.js"}}"></script>_


**So to do this, I:**

partials/head.hbs

```diff
    {{/if}}
    <link rel="stylesheet" href="{{css "style.css" }}">
+   <link rel="stylesheet" href="{{css "prism.css" }}"> 
    {{#is "post"}}
```

partials/footer.hbs

```diff
  </script>
+ <script defer src="{{js "prism.js"}}"></script>
  <script defer src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha256-  k2WSCIexGzOj3Euiig+TlR8gA0EmPjuc79OEeY5L45g=" aria-dropeffect="" crossorigin="anonymous"> 
    </script>
  <script defer src="{{js "scripts.min.js"}}"></script>
  {{#is "post"}}
```


**Getting the languages to show in the editor:**


Added the following to 
`C:\Users\Matt\Documents\Publii\sites\techlifenz\input\themes\technews\config.json`

```diff
    "customElements": [
        {
            "label": "Info",
            "cssClasses": "msg msg--info",
            "selector": "p"
        },
        {
            "label": "Highlight",
            "cssClasses": "msg msg--highlight ",
            "selector": "p"
        },
        {
            "label": "Success",
            "cssClasses": "msg msg--success",
            "selector": "p"
        },
        {
            "label": "Drop cap",
            "cssClasses": "dropcap",
            "selector": "p"
        },
        {
            "label": "Lead",
            "cssClasses": "post__lead",
            "selector": "p"
        },
+       {
+           "label": "Code-markdown", 
+           "cssClasses": "language-markdown", 
+           "selector": "code" 
+        },
+        { 
+           "label": "Code-bash", 
+           "cssClasses": "language-bash", 
+           "selector": "code" 
+        }
    ]
}
```

Now I get the code types appearing in the list (after first restarting publii):


Thus far, I haven't found the code syntax highlighting to be amazing though when using the GUI. Instead, I've found it slightly easier to go to the src code section, and paste in code like so:

```html
<pre>
  <code class="language-bash">
#!/bin/bash
# A bash script meant to take in user input, craft an API call to Github's Gist
# API and send the request, with content and filename filled in by the user

#Sends error on script failure
set -o errexit

function format_file_as_JSON_string() {
    sed -e 's/\\/\\\\/g' \
	-e 's/$/\\n/g' \
	-e 's/"/\\"/g' \
	-e 's/\t/\\t/g' \
	| tr -d "\n"
}
  </code>
</pre>
```

--------------------------------


How've you found pasting, or typing code into the Publii text editor? I'm really looking forward to markdown support in Publii (hopefully by the end of the year)...


Thanks,

Matt

**Comment by MartinCowen** [comment]
This works well but I've found that you have to use the HTML editor to post code into, and replace all tabs with spaces. If you try pasting a block of code into the WYSIWYG editor, it adds code tags around each line and adds line breaks so the formatting gets borked. Would be nice to see a fix for that.

**Comment by tcamde** [comment]
I didn't want to add that extra JS and CSS on every page just for occasional code-highlighting. So I use this workaround:

1. Copy your code
2. Paste into some online code-highlighting tool e.g. https://pinetools.com/syntax-highlighter
3. Get the output HTML with inline styles
4. Copy this into your content as HTML snippet

Work great for me and is much smaller!

**Comment by MartinCowen** [comment]
I like this idea.
This alternative avoids the problem of losing the changes to the hbs files and the prism files that occur when updating the theme. I just updated from Publii 0.35 to 0.36 so it was a good time to also update my theme (Simple) and lost the code highlighting. Although was easy to restore from the version control on my site files.
Downsides to using the syntax highlighter tool are having to choose the same style every time for consistency and then not being able to update them all in one place; and with large number of code samples, it will result in bigger pages; the HTML is messier so would have to go back to source to do even minor edits.

**Comment by dziudek** [comment]
(clearing the backlog)
