### ISSUE TITLE
[Bug]: Publii website form submission doesn't work

### ISSUE THREAD

**Issue by Khoramyar** [GetPublii/Publii#1161]
### Operating system

fedora 36

### Publii version

0.41.1 build 15919

### Bug description

Sorry to post it like this but there is no other way to inform you:

Your website forms do not work. I tried to submit a ticket with latest Firefox browser and when you click submit, it just goes to a coma. Please double check.

**Comment by bobmitro** [comment]
Hello @Khoramyar

It may be due to the browser you are using; I was able to write a test ticket by logging in as you. So, please use a different browser or contact us by e-mail.

**Comment by Khoramyar** [comment]
@bobmitro Ok now it worked, with the same setup / browser as yesterday. Maybe there was some sort of transit or server side issue that was resolved. I will close this issue.
