### ISSUE TITLE
[Bug]: sync.githubPages deletes non-Publii files

### ISSUE THREAD

**Issue by drnw** [GetPublii/Publii#1163]
### Operating system

macOS Monterey 12.5.1

### Publii version

0.41.1

### Bug description

With `sync.githubPages` Publii deletes all files in the branch to which it pushes. 

In my case, the deleted files are a Github action and a json config file for Firebase. These files are required for the deploy Firebase to work automagically.

**Comment by dziudek** [comment]
@drnw - as I have mentioned in other place - please put your additional files in Tools -> File Manager -> root directory - it should help :)

**Comment by drnw** [comment]
thank you @dziudek. Deploying from Publii to Firebase via Github is now working for me :-)

<img width="445" alt="image" src="https://user-images.githubusercontent.com/24733582/202900080-8e1aedb9-da4e-479f-bee8-7c20d9810c83.png">
