### ISSUE TITLE
[Bug]: Github sync keep using old title as post name.

### ISSUE THREAD

**Issue by haizad** [GetPublii/Publii#1167]
### Operating system

Ubuntu 22.04 LTS

### Publii version

0.41.1 (build 15919)

### Post editor

None

### Bug description

Github sync keep using old title as post name.

### Steps to reproduce

- Rename a post title from ABC to DEF 
- Saved and close the post.
- Click on Sync your website
- Bugs happened (Github still use the same title ABC.html)

**Comment by dziudek** [comment]
I am closing this issue due lack of response. Feel free to reopen it, if new details will be available
