### ISSUE TITLE
Roadmap inquiry: timeline for multilingual? 

### ISSUE THREAD

**Issue by jared-will** [GetPublii/Publii#1170]
### Feature Description

The Roadmap on your website listed multilingual functionality as the next milestone. My work is trying to decide on a static CMS, and knowing the anticipated timeline for that feature would really help us, even if it is an approximation. 

Relatedly, we were wondering if the WP Importer tool would support conversion from a website using the WPML plugin. Thanks!

**Comment by bobmitro** [comment]
Currently, we have no plans to develop a multilingual feature, as it would require a significant amount of time and resources. However, we may reconsider this option in the future.
