### ISSUE TITLE
[Feature Request]: Upload backup to external device 

### ISSUE THREAD

**Issue by kporembinski** [GetPublii/Publii#1173]
### Feature Description

For the moment, the copy is made locally.

You could use the settings from Server to send backups there. You could also add options there to create a directory for such copies.

Another solution is to add an option to upload to S3, FTP, Google Drive, etc. in the Backup section - instead of doing it locally.

**Comment by s3nnet** [comment]
For a woraround, you could configure the backup location to be synced with e.g. Nextcloud.

**Comment by s3nnet** [comment]
Of course multiple backup targets would be nice, e.g local, Google Drive, Nextcloud etc.

**Comment by dziudek** [comment]
In the future we will create a plugin for more advanced users to handle hooks for some specific events like successful sync or backup creation. But it won't be a part of Publii core so I am closing this issue.
