### ISSUE TITLE
[Bug]: Relative links not working with zip/manual deployment server type

### ISSUE THREAD

**Issue by RasheedAZ** [GetPublii/Publii#1175]
### Operating system

Linux Pop!_OS 22.04

### Publii version

0.41.1 (build 15919)

### Post editor

WYSIWYG editor

### Bug description

First off, I wanted to say that I love Publii. Thank you for your awesome work, for making it open source and  for maintaining Linux versions!

About the issue, i think i've done everything correctly but it looks like I'm still experiencing #664 and #649 when the server type chosen is .zip/manual deployment.

Changed it to sftp and it generated relative links correctly. 

Installed Publii using the .deb file provided on the website. 

Using the basic default theme.

### Steps to reproduce

1. Install on Linux using the .deb file.
2. Create basic site.
3. Enable relative links.
4. Sync to server using the .zip method.

**Comment by crock** [comment]
Can you show us how links look in your browser? In your browser, right-click on one of the bad links and choose Inspect Element. 

I can look into this issue for you.

**Comment by RasheedAZ** [comment]
Thanks for replying. Sorry, somehow I never saw the websites-files folder and I was looking in the preview folder. Anyway, the files in both folders now give correct relative links when I click build.

Not sure I was doing something wrong or what.  When it was giving full urls like "home/documents/publii/...html" I did inspect the source and it was showing the same full urls inside the ahref tags.

Made a couple of other test sites and the relative links are working so closing this. Thank you.
