### ISSUE TITLE
[Feature Request]: Follow buttons for Fediverse services

### ISSUE THREAD

**Issue by marcmaderhome** [GetPublii/Publii#1176]
### Feature Description

I am, as far as social media is concerned, mostly to be found in Fediverse, therefore I need Follow Buttons for these services. Especially for the following services I need them: Pixelfed (https://pixelfed.org), Peertube (https://joinpeertube.org/) and Mastodon (https://joinmastodon.org/).

**Comment by s3nnet** [comment]
:+1:

**Comment by s3nnet** [comment]
Especially Mastodon is at a point now, where it shouldn't be ignored any more

**Comment by internettips** [comment]
To reduce bloat and the risk of third-party core breakages, maybe plug-in services like anything found in Fediverse should be better provided as plugins: [https://marketplace.getpublii.com/plugins/](url).

**Comment by eros404** [comment]
I think the social links must be handle by the theme and not Publii core.
Personally I created a copy of the base Simple theme and I added a link to my Mastodon account (not a follow button however but I don't know if it's possible/how to do it).

**Comment by bobmitro** [comment]
Please note that this GitHub repository is dedicated to the Publii app. For any requests or inquiries related to themes or plugins, it is best to visit the [community forum](https://forum.getpublii.com/).
