### ISSUE TITLE
[Bug]: Cookies PopUp - ARIA Error

### ISSUE THREAD

**Issue by whollaus** [GetPublii/Publii#1183]
### Operating system

macOS

### Publii version

last

### Post editor

None

### Bug description

Small "error" or optimization. Google pagespeed check gives an accessibility error when using the cookie popup.

> [role] elements do not have all required [aria-*] attributes

> This website uses cookies
> <div id="pcb-title" role="heading" class="pcb__title">

https://dequeuniversity.com/rules/axe/4.4/aria-required-attr

### Steps to reproduce

Example page (but is for all pages with cookie info):
https://pagespeed.web.dev/report?url=https%3A%2F%2Fjohannesarnold.com%2F

<img width="987" alt="image" src="https://user-images.githubusercontent.com/4582757/222109098-bd2b7396-9b64-4caa-84eb-445e93f7bfb1.png">

**Comment by bobmitro** [comment]
The upcoming Publii version will address and fix this issue.  More about it: https://forum.getpublii.com/topic/aria-role-for-cookies-banner-roles-do-not-have-all-required-aria/

**Comment by whollaus** [comment]
Perfect. Thank you very much!
