### ISSUE TITLE
[Feature Request]: Add Hooks

### ISSUE THREAD

**Issue by kporembinski** [GetPublii/Publii#1184]
### Feature Description

Add possibility to run custom shell scripts before or after some actions ex:

 - postWebstieSync() - for example I will run code to clear cache on some CDN
 - preWebsiteSync()  - for example run script that will optimize images
 - etc.

**Comment by dziudek** [comment]
In the future we will create a plugin for more advanced users to handle hooks for some specific events like successful sync or backup creation. But it won't be a part of Publii core so I am closing this issue.
