### ISSUE TITLE
[Feature Request]: Consider adding an optional command that runs after `manual` (aka `zip`) deployments

### ISSUE THREAD

**Issue by michaellenaghan** [GetPublii/Publii#1186]
### Feature Description

Consider adding an optional command that would run after `manual` deployments.

That would enable users to call, say, `rsync` to upload files. Or `wrangler`.***

I can think of two additional nice touches:

 * Publii could report success on a zero exit code, and failure on a non-zero exit code.
 * Publii could (optionally) show the `stdout` and `stderr` output from the command.

***Publii [documents](https://getpublii.com/docs/configure-cloudflare-pages-with-publii.html) deployment to Cloudflare Pages via GitHub, but v2 of Cloudflare's `wrangler` tool now supports [direct uploads](https://developers.cloudflare.com/pages/platform/direct-upload/). In other words, you can now upload a directory directly to Pages, without using `git` or `GitHub` at all.

**Comment by michaellenaghan** [comment]
One other thing, not so widely known: you can use `npx` to run an `npm`-based command without installing it globally first.

For example, try this:

    npx wrangler help

The first time you'll get a confirmation prompt. The second and subsequent times you won't.

That's actually better than a global install, because you don't need special privileges. (Global installs sometimes require the use of `sudo`.)

**Comment by dziudek** [comment]
In the future we will create a plugin for more advanced users to handle hooks for some specific events like successful sync or backup creation. But it won't be a part of Publii core so I am closing this issue.

**Comment by egrieco** [comment]
@dziudek This really doesn't need to be a whole plugin. A field to run a single post-build shell script is all that this would require.

A somewhat over-complicated workaround for now might be to use a post-commit hook on a Git Repository deployment.
