### ISSUE TITLE
[Bug]: You can't choose a theme until you've saved theme settings

### ISSUE THREAD

**Issue by michaellenaghan** [GetPublii/Publii#1188]
### Operating system

macOS Ventura 13.2.1

### Publii version

0.41.1

### Post editor

None

### Bug description

You can't choose a theme until you've saved theme settings.

### Steps to reproduce

* Install a theme.
* Create a new website.
* Go to Site settings.
* Choose the new theme.
* Click Save Settings.
* Go to Theme.
* Go to Site settings.
* Notice that the Current theme is the original theme, not the new one that you selected and saved.
* Repeat trying to choose and save the new theme, etc.
* Give up. :-) 
* Go to Theme.
* Click Save Settings.
* Go to Site settings.
* Choose the new theme.
* Click Save Settings.

This time you'll get a confirmation that the settings were saved — and the new theme will become the current theme.

**Comment by greenwaym** [comment]
I can confirm, I have the same issue. It took quite a while to figure out how to circumvent the problem, thanks for the workaround.

**Comment by dziudek** [comment]
@greenwaym - please check Publii v0.42 - we have fixed many issues regarding theme options and I think that this problem should be also solved now :)
