### ISSUE TITLE
[Bug]: Keep unaccented characters in "custom ID" field

### ISSUE THREAD

**Issue by bgodole** [GetPublii/Publii#1190]
### Operating system

Windows 10

### Publii version

0.41.1

### Post editor

Block editor

### Bug description

When using the Block Editor, Publii gives one the option to customize header IDs and CSS classes. If the original header contains diacritical marks (e.x. words in French, German etc.), Publii removes the accented characters entirely from the auto-generated ID string. Letters such as ë, ç, ß should be replaced with their unaccented equivalent (e, c, ss/sz) instead.

![kapitulli](https://user-images.githubusercontent.com/15838230/225850255-7555fbc4-a99c-4efb-8334-a4be3f9e943b.png)

### Steps to reproduce

Using the Block Editor, add an H2 header that includes words with accented characters, for example etatmäßig, traçage, çoç.

**Comment by dziudek** [comment]
@bgodole - indeed - block editor used simplified fallback function - new version (v.0.42) will use proper slug function which replaces letters to similiar ones instead of removing them
