### ISSUE TITLE
[Bug]: svg social media icons don't appear in the live site (Mercury Theme)

### ISSUE THREAD

**Issue by candideu** [GetPublii/Publii#1191]
### Operating system

Windows 10

### Publii version

Version: 0.41.1 (build 15919)

### Post editor

None

### Bug description

When I preview my site from Publii, I'm able to see the social media icons in the footer:

![image](https://user-images.githubusercontent.com/55474996/226070807-1f464cad-fc89-4781-a2ff-cfd9a8de8870.png)

However, they are not visible on the live site:

![image](https://user-images.githubusercontent.com/55474996/226070870-32764a8e-e45f-4326-8c3d-823ba4012a8f.png)

I'm using Mercury v 2.4.0.0

### Steps to reproduce

It appears to be some kind of svg-map error:

**Live site (on Firefox)**
![image](https://user-images.githubusercontent.com/55474996/226071232-3737374f-2566-4deb-8a43-beeda62b12a9.png)

**Preview**
![image](https://user-images.githubusercontent.com/55474996/226071167-f23ea960-33a8-44af-b266-8a3bff072b57.png)

**Comment by bgodole** [comment]
Could it be the same issue as this (https://forum.getpublii.com/topic/twitter-and-facebook-icons-not-showing-up-in-the-footer/) ? Try loading the live site with the www prefix.

**Comment by bobmitro** [comment]
Thanks for raising this issue. However, this repository is dedicated explicitly to app development and related issues. You can report your concerns on the community forum for support related to themes or other non-app-related topics.

You can find the community forum here: https://forum.getpublii.com

**Comment by candideu** [comment]
@bgodole Thank you for pointing me to that post! Unfortunately, I don't think it's the same issue. My site doesn't use the `www.` subdomain, and neither does the svg file...

**Comment by candideu** [comment]
Hi @bobmitro : the question [has been moved to the forum](https://forum.getpublii.com/topic/svg-social-media-icons-dont-appear-in-the-live-site-mercury-theme/).

**Comment by candideu** [comment]
@bgodole Well, looks like I _am_ using the www. subdomain... 🤦🏿😅 You were right! Thank you for pointing me in the right direction, and thank you for the reminder, Bob!
