### ISSUE TITLE
[Bug]: The difference between Layout | Author page options and Author options isn't clear

### ISSUE THREAD

**Issue by michaellenaghan** [GetPublii/Publii#1195]
### Operating system

macOS Ventura 13.2.1

### Publii version

0.42.0

### Post editor

None

### Bug description

Publii 0.42.0 introduced **Author options**, **Post options** and **Tag options** in **Theme Settings** — at least, in the default Simple theme.

<img width="944" alt="Screenshot 2023-03-29 at 6 04 33 PM" src="https://user-images.githubusercontent.com/176481/228679062-0883b67c-193a-4912-9b9e-948df75c3d91.png">

**Layout** in **Theme Settings** already had (and still has) **Author page**, **Tags page** and **Tag page** options.

<img width="541" alt="Screenshot 2023-03-29 at 6 04 09 PM" src="https://user-images.githubusercontent.com/176481/228679096-309e0b61-7b0f-4b0f-b12f-11d2fb634458.png">

The difference between the two isn't clear. For example, what's the difference between **Layout | Author page | Featured image** and **Author options | Display featured image**?

Well, looking at [the code](https://github.com/GetPublii/Publii/blob/master/app/default-files/default-themes/simple/author.hbs), I can see that:

* all of the author options — i.e., from both **Layout | Author page** and **Author options** — only affect the author page;
* the old options, **Layout | Author page**, only affect the "bottom" of the author page — i.e., each post listed on the author page;
* the new options, **Author options**, only affect the "top" of the author page — i.e., the hero section above the post list.

So the answer is that **Layout | Author page | Featured image** determines whether or not each *post's* featured image is shown on the author page, while **Author options | Display featured image** determines whether or not the *author's* featured image is shown at the top of the author page.

Not obvious!

A suggestion: group all of the options for each kind of page together in one spot, with the options that affect the top of the page, i.e. the hero, at the top, and the options that affect the bottom of the page, i.e. the post list, at the bottom. (Maybe some of the per-page SEO options should also migrate to these new per-page spots?)

By the way, there should also be **Tags options**. Right now you can turn off the Post count at the top of the Author and Tag pages, but you can't turn off the Tag count at the top of the Tags page.

**Comment by bobmitro** [comment]
The options in the Layout tab are responsible for the appearance of the post list displayed on the pages as tag or author. However, you are right that the terminology used for the new tag and author config options may contribute to the confusion surrounding the Layout tab's options.

So, I have made some revisions to the theme and implemented a few corrections. Now, it should both sound and look much better :)

**Comment by bobmitro** [comment]
> Use switches/toggles in Author options, etc., rather than drop-downs

It's infeasible :) The Author/Tag Options encompass three choices: On/Off/Global. So, a drop-down menu is needed.

**Comment by michaellenaghan** [comment]
I think we're talking about different things? I was talking about the newly added **Author options**, etc.:

<img width="713" alt="Screenshot 2023-04-03 at 10 46 53 AM" src="https://user-images.githubusercontent.com/176481/229545554-2739382e-3722-47ed-b650-38c1043052ba.png">

I was contrasting them with the similarly named options in **Layout**:

<img width="285" alt="Screenshot 2023-04-03 at 10 49 56 AM" src="https://user-images.githubusercontent.com/176481/229546299-5274637f-fdb0-405d-927f-25104fba27ad.png">

(Obviously, those screenshots are from 0.42.0, not 0.42.1. Btw, another small newly introduced difference: 0.42.1 now uses "*Show* featured image" in **Layout**, while **Author options**, etc. uses "*Display* featured image". Not a problem, just noting.)

**Comment by bobmitro** [comment]
Ok, now I see that you are referring to the global settings for post/author/tag options. However, I think I will keep them in a drop-down menu to maintain consistency and unify the appearance with the options for individual pages.

**Comment by bobmitro** [comment]
The post configOptions refers to the options that are only displayed on the post page. The tag/author config Options apply to the list of posts. 
Where did you find the date switch? Are you using the new Simple 2.6.1.10 version?

**Comment by bobmitro** [comment]
> In 2.6.1 the label changed, but it's still a checkbox
This is ok for me. These options refer to the post listings, sometimes called cards. These settings are not related to the new tag/author Config Options that apply to author and tag pages and are available when editing tag and author.

**Comment by michaellenaghan** [comment]
Ah, I think I see now. 

I made a mistake.

[This comment](https://github.com/GetPublii/Publii/issues/1195#issuecomment-1494546671) has two screenshots.

The first is from the **Other options** in a post. The drop-down has three values, one of which is "Use global configuration."

The second screenshot is from what's called **Layout** in 2.6.0.

I thought the second screenshot was the source of the global configuration the first screenshot referred to. So I was suggesting that they be labelled and presented the same way. But, no, that wasn't right; the newly introduced options are the source. 

Oops.

Sorry about the confusion!

I think this issue can be closed now?
