### ISSUE TITLE
[docs] Correction - GitHub Pages now supports HTTPS with custom domains

### ISSUE THREAD

**Issue by andrewnicolalde** [GetPublii/Publii#1196]
[The Publii docs say](https://getpublii.com/docs/host-static-website-github-pages.html#issslavailableforyourcustomdomain) that GitHub Pages sites using custom domains don't support HTTPS, however [this changed in 2018](https://github.blog/2018-05-01-github-pages-custom-domains-https/).

<img width="782" alt="image" src="https://user-images.githubusercontent.com/21282811/229355502-e2bcbfee-4a45-4dc5-b9a9-46817e676037.png">

This section of the Publii GitHub Pages docs should be removed to reflect GitHub Page's support for HTTPS for sites using custom domains.

Relevant GitHub docs: https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#about-https-and-github-pages

**Comment by bobmitro** [comment]
Thank you for the advice; the docs has been updated.
