### ISSUE TITLE
[Bug]: Pagination broken links

### ISSUE THREAD

**Issue by freezenova** [GetPublii/Publii#1197]
### Operating system

Windows

### Publii version

0.42.0 (build 16217)

### Post editor

None

### Bug description

Hello,

Website doesn't use pretty links and the always add index.html in URLs is checked. 
Pagination is generating broken links.
There are some links in pagination that get a / at the end of the link.

<span class=”html-tag”><span class=”html-attribute-name”>class</span>=”<span class=”html-attribute-value”>pagination-active</span>“></span>1 <span class=”html-tag”></span><span class=”html-tag”><a <span class=”html-attribute-name”>href</span>=”[./page/2/index.html/](https://lichgames.s3.amazonaws.com/page/2/index.html/)“></span>2 <span class=”html-tag”></span><span class=”html-tag”><a <span class=”html-attribute-name”>href</span>=”[./page/3/index.html/](https://lichgames.s3.amazonaws.com/page/3/index.html/)“></span>3<span class=”html-tag”></span><span class=”html-tag”></span><span class=”html-tag”><a <span class=”html-attribute-name”>href</span>=”[./page/2/index.html](https://lichgames.s3.amazonaws.com/page/2/index.html)” <span class=”html-attribute-name”>class</span>=”<span class=”html-attribute-value”>pagination__nex</span></span>

The links from pagination similar to “[./page/2/index.html/](https://lichgames.s3.amazonaws.com/page/2/index.html/)” are generating broken links

The slash / at the end of the link isn’t compatible with my webhost.

Thank you.

### Steps to reproduce

Use pretty links - not checked
Always add index.html in URLs - checked
Pagination: infinite scroll or pages. (both options generate the same links)
Broken links appear with / 
The bug appears after deployment to server, I couldn't reproduce it in preview. 
After checking preview and output directory, this issue appears only in output directory. 

I think the issue is on:
Publii-master\app\back-end\modules\render-html\handlebars\helpers\page-url.js

line 31
current line: if(!rendererInstance.previewMode) {
fix:  if(!rendererInstance.previewMode && !rendererInstance.siteConfig.advanced.urls.addIndex) {

Thank you.

**Comment by freezenova** [comment]
I think the issue is on:
Publii-master\app\back-end\modules\render-html\handlebars\helpers\page-url.js

line 31

current line: if(!rendererInstance.previewMode) {

fix: if(!rendererInstance.previewMode && !rendererInstance.siteConfig.advanced.urls.addIndex) {

Thank you.

**Comment by dziudek** [comment]
Hi @freezenova - to be honest - I am unable to reproduce this issue on my local instance, but yes - the suggested fix should be used according how the code works, so I have added this patch to Publii v.0.42.1 planned for the next week :)
