### ISSUE TITLE
Add Algolia as a search option

### ISSUE THREAD

**Issue by pagelab** [GetPublii/Publii#120]
Hello,

Is it possible to add the [free community version of Algolia](https://www.algolia.com/pricing) as a search option?

It's quite fast and allows lots of records, more than enough for the kind of site Publli creates.

They also have a [great API](https://www.algolia.com/doc/api-reference/) and [docs](https://www.algolia.com/doc/), so it should be easy to integrate.

BTW, thanks for creating Publii, it really makes publishing a website easy, performant and cheap at the same time.

**Comment by bobmitro** [comment]
Argolia is not free for everyone, just for the open-source projects. 
We will contact them and ask about the discount for Publii users - having it,  we will add a new search option to all of the themes. 
Now, we are working on the release of the new "Documentation" theme with built-in support for Argolia search :)

**Comment by pagelab** [comment]
Great! :) Yes, they have a "community version" that explicitly says that is free for everyone, check out the pricing page. 

It's different from the "essential" plan, which is the one free for open source projects.

**Comment by bobmitro** [comment]
Are you talking about this https://github.com/algolia/docsearch ?

**Comment by pagelab** [comment]
> Are you talking about this https://github.com/algolia/docsearch ?

Not this one, I'm talking about the "community plan" from the main Argolia Search itself.

You can create a free account there visiting the [pricing page](https://www.algolia.com/pricing):

![argolia](https://user-images.githubusercontent.com/1451087/44228228-25a5de00-a16b-11e8-97a1-a304a39d6f47.gif)

After that, you can create a free index and upload the JSON data [using Argolia APIs](https://www.algolia.com/doc/tutorials/indexing/importing-data/importing-with-the-api/). The index can then be used in the actual site search, which would be integrated using the provided utilities, like  [instantsearch.js](https://community.algolia.com/instantsearch.js/) and [autocomplete.js](https://github.com/algolia/autocomplete.js).

Another simpler option would be [JS-Search](https://github.com/bvaughn/js-search), which isn't very performant as Argolia.

**Comment by HexaCubist** [comment]
Hi all, just dropping by to say that the search engine is called "Algolia" not Argolia, which is instead the name of a game server I used to run many years ago, which still notifies me when people mention it online :)

I also make the mistake often, Algolia just doesn't sound right to me

**Comment by pagelab** [comment]
Good catch, @HexaCubist.

**Comment by rsipakov** [comment]
I installed https://app.swiftype.com easily. Is it possible with Algolia? )

**Comment by bobmitro** [comment]
With the advent of plugins, three different search engines have been added. Now you can use Google search, Docsearch, and our native search based on the Flexsearch. More details can be found in our marketplace: https://marketplace.getpublii.com/plugins/
