### ISSUE TITLE
[Bug]: can test connection to s3, but won't upload any files/objects into bucket

### ISSUE THREAD

**Issue by xcitedboutai** [GetPublii/Publii#1204]
### Operating system

mac os big sur 11.6.8

### Publii version

Version: 0.42.1 (build 16233)

### Post editor

None

### Bug description

followed tutorial for uploading to s3, but it won't upload any files into bucket

it said "some files were not synced properly
please check the hard-upload-errors-log.txt file using the tools &gt, log wiever

but I don't have that txt file anywhere under publii directory

**Comment by xcitedboutai** [comment]
ok, in S3 server settings, under ACL it needs to be changed to "Bucket owner full control", instead of "public read" which it wrongly states in tutorial. then it can upload the files

**Comment by Resonanz** [comment]
Why has this been closed -- the instructions on the publii website have not been fixed. This just wasted me 30 minutes :-(

https://getpublii.com/docs/setup-static-website-hosting-amazon-s3.html
