### ISSUE TITLE
Devtools showing at startup

### ISSUE THREAD

**Issue by momorgan** [GetPublii/Publii#1211]
Developer tools window always opens by default.

Some things that don't stop that happening:
- 'Esc' shortcut
- Command-Option-I
- F12 key
- Clicking x on the window: will close the window but it'll open by default next time the app starts.

Publii Version 0.42.1
Ventura 13.2.1
Intel

![Screenshot 2023-05-19 at 07 48 22](https://github.com/GetPublii/Publii/assets/223823/f531fcb0-2ecb-422f-97b2-bf7adbcb84a7)

**Comment by dziudek** [comment]
Hi,

By default dev tools are hidden - most probably you have enabled them under App Settings - Please check if there option of automatically opening dev tools is disabled (under options for developers)

**Comment by momorgan** [comment]
Aaah thank you, that's solved it. I did skim these options but obviously didn't skim them hard enough :)

Is there a keyboard shortcut associated with this toggle? It may be user error but I certainly don't remember seeing it before let alone enabling it. But I can imagine an instance of the cat stamping on the keyboard...

**Comment by dziudek** [comment]
@momorgan - there is no keyboard shortcut which toggles it - it must be enabled manually under App Settings :)

**Comment by momorgan** [comment]
User error, then. Can't blame the cat for that :)

Thanks again
