### ISSUE TITLE
RSS feed xml pubdate versus updated

### ISSUE THREAD

**Issue by Krotosz6** [GetPublii/Publii#1221]
### Feature Description

I have a question. Publii generates RSS with a post tag only `updated`, even if I set the list of posts on the page to be after the date of original publication, not after the update. It is possible to change it somehow so that Publii generates RSS in the same way as on post list website for example with `PubDate` tag? It's a bit confusing, because in an RSS application, e.g. FreshRss, it refreshes posts ad the newest as soon as I change something. This is unnecessary in my opinion because of the audience of the feed.

**Comment by dziudek** [comment]
Hi,

It will be solved in v.0.45: https://github.com/GetPublii/Publii/commit/36e6a434d8b2ab23c9935631a89ae500274b821e

By default `createdAt` date will be used in `<updated>` and there will be an option to change it to `modifiedAt` date

**Comment by Krotosz6** [comment]
Thank You / Dziękuję.
