### ISSUE TITLE
[Bug]: Publii Appimage doesn't run on Debian 12 Bookworm

### ISSUE THREAD

**Issue by gcomi1977** [GetPublii/Publii#1228]
### Operating system

Debian 12

### Publii version

0.42.1

### Post editor

None

### Bug description

helllo, when I launch the appimage on my debian 12 installation I get this error
![Schermata del 2023-07-11 16-57-20](https://github.com/GetPublii/Publii/assets/22715548/f36871ba-ebfd-4905-a743-870a6e65393f)
thanks in advance

### Steps to reproduce

fresh installed debian 12, just launch the appimage

**Comment by gcomi1977** [comment]
problem solved, I had to delete my preview folder once done publii worked again

**Comment by RasheedAZ** [comment]
That's a relief :) You should close this in that case...

**Comment by gcomi1977** [comment]
thank you!
