### ISSUE TITLE
[Bug]: Preview Your Changes Button opens another Program (Zoho Cliq)

### ISSUE THREAD

**Issue by janrippl** [GetPublii/Publii#1229]
### Operating system

Ubuntu 20.04.6 LTS

### Publii version

0.42.1 (build 16233)

### Post editor

None

### Bug description

Click on "Preview Your Changes" Button opens another installed Program (Zoho Cliq | https://www.zoho.com/cliq/desktop/linux.html).

**Comment by janrippl** [comment]
![Snímek obrazovky pořízený 2023-07-13 16-50-00](https://github.com/GetPublii/Publii/assets/33397305/fa2dc505-32f5-4e18-8230-b21129d2e337)
I have set it correctly in system (screen).

**Comment by janrippl** [comment]
![Snímek obrazovky pořízený 2023-07-13 16-52-02](https://github.com/GetPublii/Publii/assets/33397305/47df70f1-c664-433f-9fee-094a52e3e377)
Ahhhhh! Failure :-D

**Comment by dziudek** [comment]
But please remember that "Document HTML" is not the same as "Web" - you can have two different apps set for it - please configure app for opening "Document HTML" not "Web" - "Web" refers to URLs like https://getpublii.com :)

**Comment by janrippl** [comment]
Now I set it back to default Broser (Brave) and Publii working now properly :) I informed via e-mail developers of Zoho applications about this issue now, and I hope that they will change it :) Thank You for Your help :)
