### ISSUE TITLE
[Bug]: OG image not showing up in whatsapp

### ISSUE THREAD

**Issue by kmanadkat** [GetPublii/Publii#1230]
### Operating system

mac os 13.4.1

### Publii version

0.42.1

### Post editor

Block editor

### Bug description

I am facing problem with OG tags. I see preview image of my Post in Instagram & Twitter. In whatsapp however it shows only Text, no preview image. Please find examples before:

**Twitter**
![IMG_2869](https://github.com/GetPublii/Publii/assets/25281055/65adf86f-7da5-472c-8ba4-eb0343186e8f)

**Instagram**
![IMG_2870](https://github.com/GetPublii/Publii/assets/25281055/4257cf55-07a3-4a61-a945-ebfa54af452f)

**Whatsapp**
![IMG_2868](https://github.com/GetPublii/Publii/assets/25281055/4dc0ce05-7c04-40c2-951f-a3699d145b74)

After searching a bit I found that whatsapp ignores `og:image` url if `og:image:width` or `og:image:height` is more than 300.

I am not finding any option to set those tag values myself. I checked the blog theme source code too, it seems it is just populating value what is passed in handlebar variables by Publii.

<img width="1212" alt="Screenshot 2023-07-22 at 10 50 52 PM" src="https://github.com/GetPublii/Publii/assets/25281055/72e18c56-ca58-4ecb-9b54-29027649d774">

> Also, how do i remove this  from all my site pages?
```html
<meta name="generator" content="Publii Open-Source CMS for Static Site">
```

Thanks

### Steps to reproduce

Paste this link in whatsapp messages:
https://krupeshanadkat.com/running-mysql-and-phpmyadmin-with-docker/

**Comment by dziudek** [comment]
Hi,

It is not a problem with Publii, but with fact that your OG image is greater than 300kB - please optimize it and try again: https://stackoverflow.com/a/39182227

So you must to optimize your featured image to fix this.

**Comment by kmanadkat** [comment]
@dziudek 
By 300 i meant 300pixels not the file size. Practically no blog post header will be just 300px in size width or height. We just need to put value of 300px because behind the scenes Publii is already making images responsive.

Please allow us an option to edit these meta tags.

**Comment by dziudek** [comment]
@kmanadkat - did you read the linked post? it mentions 300kB not 300x300px - it would be ridicolous, because Facebook prefers 1200x630px for OG images, and it is not possible to serve multiple og:images AFAIK

**Comment by kmanadkat** [comment]
@dziudek oh sorry, my bad, I read your latest message and missed the above one. I will recheck the image size coming through og url. If its less than 300kb then I will reach again for help

Thanks 🤝

**Comment by kmanadkat** [comment]
@dziudek I decreased the image size ~264kb & it worked.
