### ISSUE TITLE
[Feature Request]: Option to Add Custom Meta Tags or Scripts in <head> Per Post

### ISSUE THREAD

**Issue by kmanadkat** [GetPublii/Publii#1231]
### Feature Description

I want to add custom meta tags & JSON-LD scripts for SEO. This can differ post by post, so hardcoding in Theme might not be right.

Can we please have an option somewhere in the post settings sidebar, or anywhere it feels feasible?

<img width="931" alt="Screenshot 2023-07-23 at 11 00 07 AM" src="https://github.com/GetPublii/Publii/assets/25281055/f5d0e49c-24a6-4550-b507-6edcc6e1aea8">

Example content to add in <head> (it can be other stuff too like additional meta tags):
<img width="1512" alt="Screenshot 2023-07-23 at 11 02 31 AM" src="https://github.com/GetPublii/Publii/assets/25281055/28b565e2-db93-495f-98d7-d714f3a49440">

**Comment by bobmitro** [comment]
You need to add a textarea via the Post Config option. More information can be found here: https://getpublii.com/dev/post-config-options/

**Comment by kmanadkat** [comment]
> You need to add a textarea via the Post Config option. More information can be found here: https://getpublii.com/dev/post-config-options/

Cool, checking it. Thanks

**Comment by kmanadkat** [comment]
@bobmitro I tried cloning repository & following https://github.com/GetPublii/Publii/wiki/App-build-process

Seeing error:
<img width="2056" alt="Screenshot 2023-07-23 at 12 28 06 PM" src="https://github.com/GetPublii/Publii/assets/25281055/75f874b8-e123-4d92-9a9f-e927fcbd8f8f">


macos Ventura v13
Node v16.20.0
Xcode v14.3.1

I tried rebuilding better-sqlite package by :
```bash
cd app/node_modules/better-sqlite3
npm install
npm run install  # strangely, package had install script
npm run rebuild-release
```

Restarted things in root of project:
```
npm run dev
npm run build # Another terminal tab
```

can you please help ?

**Comment by kmanadkat** [comment]
@bobmitro it worked, I misunderstood earlier. I just added below in `config.json` of theme
```json
		{
			"name": "displayTextarea",
			"label": "Additional Head Tags",
			"value": "",
			"type": "textarea"
		},
```
Like how you suggested with the Post Config options link &   added below in `head.hbs`
```hbs
{{{@config.post.displayTextarea}}}
```

<img width="477" alt="Screenshot 2023-07-23 at 2 25 15 PM" src="https://github.com/GetPublii/Publii/assets/25281055/e42d61d8-4ea6-4fc2-9b6a-d12dc73ee3c4">


This solves the requirement, hence closing ticket.

Off the topic, do you happen to know by any chance if it is ok to have multiple `"application/ld+json"` script tags?

**Comment by bobmitro** [comment]
> Off the topic, do you happen to know by any chance if it is ok to have multiple `"application/ld+json"` script tag

I think it's fine to have multiple JSON-LD data on a single page for example to represent different types of data.

**Comment by kmanadkat** [comment]
Thanks
