### ISSUE TITLE
[Bug]: Can't upload featured image with certain image types

### ISSUE THREAD

**Issue by tobip** [GetPublii/Publii#1233]
### Operating system

Linux Manjaro sway edition

### Publii version

0.42.1 build 16233

### Post editor

WYSIWYG editor

### Bug description

When I want to add a featured image it won't work with certain files. 

### Steps to reproduce

1. Edit a post
2. Klick on "add featured image"
3. Select certain jpg files that don't work
Example file: 
![holzkisten2](https://github.com/GetPublii/Publii/assets/3918330/4d3ba48e-ff7c-430c-b5b5-f0c66c7ae011)

### Relevant log output

```shell
(process:90384): GLib-CRITICAL **: 13:35:35.246: g_datalist_id_set_data_full: assertion 'key_id > 0' failed
```

**Comment by dziudek** [comment]
Hi,

Most probably it is not related to filename but to your file itself. Please try to compress your file with tool which removes EXIF metadata and try again

Unfortunately Sharp sometime has issues with some files. For me your file is working fine

**Comment by tobip** [comment]
Thanks a lot, removing exif data solved my issue!
