### ISSUE TITLE
[Feature Request]: Make custom links default in the link dialog

### ISSUE THREAD

**Issue by s3nnet** [GetPublii/Publii#1235]
### Feature Description

At least for me as a blogger, custom / external links are far more frequently used than post links. Therefore I'd like to see custom links the default option for links. Ideally, with custom link preselected and the focus on the url field to facilitate linking sparing two clicks.

**Comment by bobmitro** [comment]
Hey, just a heads-up: we tweaked the links in Publii 0.44.2. Check out the release notes https://getpublii.com/blog/release-044.html#hotfixes
