### ISSUE TITLE
[Feature Request]: Allow to upload set a link to non-picture files

### ISSUE THREAD

**Issue by jpoehlmann** [GetPublii/Publii#1236]
### Feature Description

It may be hidden in the documentation, but i did not find a way to do this:

Upload a file (e.g. of type "PDF", for supplying documents for Printout), and include a link to download this file from the produced web site. 

I think this functionality is not too exotic and will be found useful by web page authors.

**Comment by raramuridesign** [comment]
@jpoehlmann 
Try this, goto your project, click on tools & plugins > file manager
Here you can upload files for your project.

M.

**Comment by jpoehlmann** [comment]
Great, thanks, works like a charm.
Perhaps this great feature needs a bit more documentation.
It would also make sense to to offer a file manager link also in the menu items.

**Comment by raramuridesign** [comment]
I am unsure that this might be added, it should be directed to the dev team
@dziudek
