### ISSUE TITLE
[Bug]: Custom JS Code for TinyMCE is not run when adding a new post

### ISSUE THREAD

**Issue by mrmashal** [GetPublii/Publii#1237]
### Operating system

Windows 10

### Publii version

0.41.1

### Post editor

WYSIWYG editor

### Bug description

My `tinymce.script.js` file in my theme (as described in [the docs](https://getpublii.com/dev/how-to-add-custom-config-or-js-for-post-editor/)) is not run when adding a new post. It is only run when editing existing posts.

I investigated the source code and seems like the script is only injected in the `loadPostData()` method (`PostEditorTinyMCE.vue:229`).

### Steps to reproduce

Put a `tinymce.script.js` file with some test code in your theme and click on "Add new post". Don't forget to add the following section to the theme's `config.json` file:

```
    "extensions": {
        "postEditorCustomScript": true
    }
```

**Comment by dziudek** [comment]
@mrmashal - thank you for spotting this and for your pull request, which helped me to prepare a final solution which will be used in Publii v.0.43 :)
