### ISSUE TITLE
Mac version shows the default app icon

### ISSUE THREAD

**Issue by pagelab** [GetPublii/Publii#124]
Tested on Mac OS 10.12.6 (Sierra)

![screen-shot-2018-08-16-18-37-20](https://user-images.githubusercontent.com/1451087/44281814-69621b80-a22f-11e8-89c7-837fc8d3cfd2.png)

**Comment by dziudek** [comment]
That's weird - I am installing every new version of Publii and I have always had a proper icon. 

If other users will report it - we will deeper investigate it, but at this moment I am unable to reproduce this issue and fix it.

**Comment by pagelab** [comment]
I just tested on another Mac I have here, and got the same issue with the icon.

The default icon is shown in the installer window itself.

![screen-shot-2018-08-18-09-08-18](https://user-images.githubusercontent.com/1451087/44299128-7b42cd80-a2c6-11e8-9581-996e2ed5c5d4.png)

**Comment by dziudek** [comment]
I have just downloaded the DMG package: 
<img width="680" alt="image 2018-08-19 at 3 56 07 pm" src="https://user-images.githubusercontent.com/22004/44309530-6cdcda80-a3c8-11e8-800c-d5ebd2606229.png">

**Comment by pagelab** [comment]
On the newest version MacOS v10.13 (High Sierra), the icon appears as expected for me.

So, this happens only in MacOS v10.12 (Sierra).

**Comment by dziudek** [comment]
Now I saw that you mean the older version of MacOS. Unfortunately I have no possibility to test it on this version of macOS as all my macs are using the latest version. As it is not a critical issue, at this moment we cannot do anything more with it.
