### ISSUE TITLE
[Bug]: Post Featured image is not responsive

### ISSUE THREAD

**Issue by briff** [GetPublii/Publii#1241]
### Operating system

Windows 11

### Publii version

0.42.1

### Post editor

WYSIWYG editor

### Bug description

When I create a new post (with the default Simple theme) the featured image is used as is, not the responsive (-xl) version.

**Comment by bobmitro** [comment]
I didn't notice it in the Simple theme, you don't provide any examples, so I can't address your problem.

**Comment by atomGit** [comment]
it happens in the Simple theme (=< 2.7.0.0) with or without responsive images being enabled - if you create a post and add a large featured image, then view it in a browser with dev tools and responsive design mode enabled, the image stops resizing at around 1280px in width, though this may depend on the image size used

**Comment by briff** [comment]
1. I created a site using the Simple theme.
2. Posts have their individual featured images.
3. The theme hero image is correctly downloaded from the responsive folder like: 
media/website/responsive/songbird-8348139_1920-md.webp
5. However, other posts featued image ignore both the webp setting and the responsive setting, they just download from: 
media/posts/1/glacier-8329668_1920.jpg

All the files are correctly generated to */responsive/*.webp, but they are not used from individual post pages.

[publii-1241.zip](https://github.com/GetPublii/Publii/files/13237765/publii-1241.zip)

**Comment by bobmitro** [comment]
@briff The attached rendered files say nothing. Please attach a full site backup on the [forum](https://forum.getpublii.com/) in private mode, as this repository is for the Publii app only.
