### ISSUE TITLE
[Feature Request]: single folder for all images / a proper image gallery

### ISSUE THREAD

**Issue by atomGit** [GetPublii/Publii#1251]
### Feature Description

currently it is forced that every image is copied to the relative post folder which results in a few issues...

1. it can make finding and reusing images in different posts very difficult
2. it's a waste of storage space when one wants to reuse the same image in multiple posts when the images are stored in a global folder (media/files)
3. it apparently makes it impossible to add image (src=) html manually in the wysiwyg code editor using file:/// urls since publii changes the url to the relative post folder/id and therefore breaks it

what is needed, imo, is a proper image gallery where all images, and thumbnail versions thereof, are stored in a single folder with the ability to display and select (multiple) images when inserting an image

**Comment by dziudek** [comment]
Duplicate: https://github.com/GetPublii/Publii/issues/620
