### ISSUE TITLE
Javasript error after update on Debian

### ISSUE THREAD

**Issue by Krotosz6** [GetPublii/Publii#1252]
### Operating system

MX Linux on Debian 11 (bullseye)

### Publii version

0.43

### Post editor

None

### Bug description

After update from 0.42. there is after open:

Error 
A JavaScript error occurred in the main process Uncaught Exception: Error: /lib/x86_64-linux-gnu/libc.so.6: version GLIBC_2.33' not found (required by /opt/- Publii/resources/app.asar.unpacked/node_modules/better-sqlite3/build/Release/- better_sqlite3.node) at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:2131) at Object.<anonymous> (node:internal/modulesMs/loader:1356:18) at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2358) at Module.Ioad (node:internal/modules/cjs/Ioader:1126:32) at node:internal/modules/cjs/Ioader:967:12 at Functionjoad (node:electron/js2c/asar_bundle:2:13327) at Module.require (node:internal/modules/cjs/Ioader:1150:19) at require (node:internal/modules/cjs/helpers:110:18) at bindings (/opt/Publii/resources/app.asar/node_modules/bindings/bindings.js:112:48) at new Database (/opt/Publii/resources/app.asar/node_modules/better-sqlite3/lib/- database.js:48:64)

**Comment by atomGit** [comment]
give your issue a title :)

**Comment by Krotosz6** [comment]
I tried appimage and there is the same situation.

**Comment by dziudek** [comment]
It seems that it is an issue with dependencies on your OS: https://superuser.com/questions/537683/how-to-fix-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-14-not-found - the native module for SQLite requires at least glibc 2.33 and probably your system has older one

**Comment by dziudek** [comment]
@Krotosz6 - as it seems to be a bigger issue, we will temporary downgrade better-sqlite3 to v.8.2.0 in Publii v.0.44 and in v.0.45 we will probably migrate to WASM SQLite solution, to avoid issues with native modules in the future.

**Comment by dziudek** [comment]
FYI - problem finally solved with migrating better-sqlite3 to WASM module: https://github.com/GetPublii/Publii/issues/1294#issuecomment-1817810447
