### ISSUE TITLE
[Feature Request]: allow reusable code snippets (TinyMCE)

### ISSUE THREAD

**Issue by atomGit** [GetPublii/Publii#1253]
### Feature Description

a super handy feature i saw in another SSG that uses TinyMCE is the ability to add custom code snippets which can be selected via a drop-down menu

i'd like to suggest enabling this by default along with an editor in the GUI for handling the code

ref: https://stackoverflow.com/questions/50100026/tinymce-inserting-simple-snippets-of-text-via-dropdown

**Comment by dziudek** [comment]
Hi,

It will be solved via the plugin which is work in progress, so I am closing this issue as it won't be part of the app core
