### ISSUE TITLE
[Feature Request]: easier editing of hyperlink text

### ISSUE THREAD

**Issue by atomGit** [GetPublii/Publii#1260]
### Feature Description

editing the text for a hyperlink should be possible without having to open it's properties editor, perhaps by double clicking it

**Comment by dziudek** [comment]
Hi,

Double click is a bad idea, because it triggers the inline menu which allows operations on the selected text. At this moment we have no plans to change this behaviour

**Comment by atomGit** [comment]
> Double click is a bad idea, because it triggers the inline menu ...

the little pop-up menu opens when a link is clicked once, not twice, and dbbl clicking the link does nothing in my case (the menu just remains open)

so the only way the text can be edited without opening the link properties is to place the cursor before/after the link and use the left/right arrow keys to move the cursor into the link - i've never seen this issue with tinymce before
