### ISSUE TITLE
[Feature Request]: faster searching for 'find' function

### ISSUE THREAD

**Issue by atomGit** [GetPublii/Publii#1262]
### Feature Description

when using the 'find' function (Ctrl+F) to search through post text, etc., searching should begin immediately when text is pasted (Ctrl+V) in the 'find' bar

**Comment by dziudek** [comment]
Hi,

Unfortunately it is probably unfixable, because it is a TinyMCE plugin. Maybe after TinyMCE upgrade it will behave better, but in general it is out of our control.
