### ISSUE TITLE
[Feature Request]: gallery - remember last directory

### ISSUE THREAD

**Issue by atomGit** [GetPublii/Publii#1270]
### Feature Description

when inserting gallery images, the last directory is not remembered when adding additional images

**Comment by dziudek** [comment]
Hi,

As it uses native OS control to select image, we cannot control this behavior

**Comment by atomGit** [comment]
it does not appear to be using the native open file dialog - it's using the GtkFileChooserDialog that's apparently part of electron (the window class is electron)
