### ISSUE TITLE
[Feature Request]: bulk tag editing

### ISSUE THREAD

**Issue by atomGit** [GetPublii/Publii#1272]
### Feature Description

ability to bulk add (new or already defined) and remove tags from all selected posts without affecting additional tags

when done with WP, as i recall, bulk editing replaced all tags with new ones and this is no good - it would be much better to add/remove without affecting the unmatched tags

post 1 tags: a, b
post 2 tags: a, c

bulk add 'd'...
post 1 tags: a, b, d
post 2 tags: a, c ,d

bulk remove 'a'...
post 1 tags: b, d
post 2 tags: c, d

tangentially related: #1258

**Comment by dziudek** [comment]
Hi,

We have no plans for such feature at this moment. If there will be more request for such feature we will reconsider this idea.
