### ISSUE TITLE
[Feature Request]: new menu link type: 'featured'

### ISSUE THREAD

**Issue by atomGit** [GetPublii/Publii#1278]
### Feature Description

consider adding 'featured' to the link types when adding menu items - this would generate a page with all posts for which the 'featured' option was enabled

**Comment by dziudek** [comment]
Hi,

There is no need for that - if somebody needs it it can be created by custom theme modification. There was no such requests before so sounds like a niche feature

**Comment by atomGit** [comment]
[Featured posts on top of list of posts](https://forum.getpublii.com/topic/featured-posts-on-top-of-list-of-posts/)

[Can I have selected post and a blog page too?](https://forum.getpublii.com/topic/can-i-have-selected-post-and-a-blog-page-too/)

it's a useful feature, especially for news blogs where one wants to sticky a post for a period of time, hence why it's core in wordpress and i'm sure other platforms
