### ISSUE TITLE
[Bug]: v.0.43.1 not Working on Debian 11

### ISSUE THREAD

**Issue by kevinmatthes** [GetPublii/Publii#1282]
### Operating system

Debian 11

### Publii version

v.0.43.1 (Build 16393)

### Post editor

None

### Bug description

Previously, I used Publii v.0.42.1 and everything worked fine.  Because the new version v.0.43.1 was published, I decided to upgrade to it.  When I try to launch the new version now, the application will report an uncaught JavaScript exception that a certain version of a dependency library would not be available.  Projects cannot be loaded anymore, so a core functionality of Publii cannot be accessed anymore.

### Steps to reproduce

1. Install Publii v.0.43.1 (Build 16393) from the official website.
2. Start Publii.

**Comment by dziudek** [comment]
Hi,

In this case you must update your dependencies according to the error message. There is no other way to solve this issue. I suppose that it is a problem with glibc library used by Better SQLite native module

**Comment by dziudek** [comment]
Problem finally solved by changing better-sqlite3 to WASM module: https://github.com/GetPublii/Publii/issues/1294#issuecomment-1817810447
