### ISSUE TITLE
[Bug]: Publii community forum registration bug

### ISSUE THREAD

**Issue by gurubyte** [GetPublii/Publii#1289]
### Operating system

Windows 10

### Publii version

0.40

### Post editor

None

### Bug description

This is not exactly bug for application but for your official forum, there isnt any place to report it except from here.

When I registered I entered email number 1. Confirmation email didnt come. Then after 20mins I tried registering again but with my 2nd email and confirmation didnt arrive. So now Im locked out of registering and need to made 3rd email just in order to register on forum. Also, I cant use first 2 emails nor restart password for them since email didnt arrive.

**Comment by gurubyte** [comment]
Now I tried registering with 3rd email and it didnt work again. I didnt receive confirmation email nor I will. So I wasted 3 emails in order to register, and still didnt succeed.

**Comment by bobmitro** [comment]
We do not note any problems with registration on the forum; it may be a random case. Please try again. The topic is closed since it is not related to the application.
