### ISSUE TITLE
[Bug]: Tag description shows html syntax

### ISSUE THREAD

**Issue by drm-wntd** [GetPublii/Publii#1292]
### Operating system

Windows 10

### Publii version

0.43.1

### Post editor

None

### Bug description

If you enter a description for a tag,  HTML elements in the description are added to final text and displayed on the tag page. Even if you just type text without formatting, the Tiny editor adds `<p></p>` around your description.

With previous versions of publii that didn't use Tiny to edit the tag description, this problem did not occur.

**Screenshot : Creating a new tag with a description:**
![newtag](https://github.com/GetPublii/Publii/assets/2616375/7c1d883f-cfdb-4553-9978-fa39c692cfc8)

**Screenshot : When viewing Tag page :  Tag description includes** `<p>`, `strong`, `em`
![tagpage](https://github.com/GetPublii/Publii/assets/2616375/23c2e5ea-f46d-4c25-8055-2f6dbbb73265)

### Steps to reproduce

1) create new tag and add text in description field
2) add the newly created tag to a post
3) publish
4) view tag page for the newly created tag, the tag description with include HTML syntax.

**Comment by bobmitro** [comment]
Just update your theme to the most recent version. The modifications to the tag description were implemented in Publii version 0.42

**Comment by drm-wntd** [comment]
Thanks! That did it! sorry for the trouble.
