### ISSUE TITLE
[Bug]: Custom S3 Provider settings with Region Missing Bug

### ISSUE THREAD

**Issue by Cineray** [GetPublii/Publii#1297]
### Operating system

Windows 10

### Publii version

0.44.0

### Post editor

None

### Bug description

Hi, i have setting my host in custom S3 Provider (Tencent)

Everything just be find before version 0.44.0

However, there is new error came out in version 0.44.0 like:

Error! Application was able to connect with your server but was unable to store files,

Please check file permission on your server : Region is missing.

but there is not region setting in custom S3 provider.

![image](https://github.com/GetPublii/Publii/assets/12690775/a8157dfc-47d9-44a5-9349-2b03cbde08b5)

![image](https://github.com/GetPublii/Publii/assets/12690775/cd101a6c-6469-4446-ab58-1903a9d6e65b)

### Steps to reproduce

Just use custom S3 Provider

**Comment by dziudek** [comment]
@Cineray - thank you for spotting this - I will try to fix it today as we want to release Publii v.0.44.1

**Comment by dziudek** [comment]
@Cineray - as I have read - now AWS SDK v3 requires region always so in v.0.44.1 we will show region text field

**Comment by Cineray** [comment]
Hi，

I have update it to 0.44.1. and fill the region setting. it still shows error as region is missing.

![image](https://github.com/GetPublii/Publii/assets/12690775/8c486a9f-0606-4199-a3fc-137e9843f5b7)

![image](https://github.com/GetPublii/Publii/assets/12690775/92445f5b-8168-415e-b507-bedec992eb71)

**Comment by Cineray** [comment]
@dziudek is my server of new AWS SDK v3 compatibly problem? have you try it on any custom s3 provider.

please check it out. thank you.

**Comment by dziudek** [comment]
@Cineray - please save the config anyway and try to sync - for me it is working with Clever Cloud. The error is connected with wrong implementation of the test connection - I will fix it in v.0.44.2

Please also try to add `https://` to your endpoint - for me endpoint without it was not working and returned invalid URL error in the logs

**Comment by Cineray** [comment]
> @Cineray - please save the config anyway and try to sync - for me it is working with Clever Cloud. The error is connected with wrong implementation of the test connection - I will fix it in v.0.44.2
> 
> Please also try to add `https://` to your endpoint - for me endpoint without it was not working and returned invalid URL error in the logs

@dziudek that's cool, those two solution is working. thank you. Are you consider to make `https` as default prefix by the way?

**Comment by dziudek** [comment]
@Cineray - I have added a code which will add `https://` if the S3 endpoint value does not contain "://" :)
