### ISSUE TITLE
[Bug]: Big bug with netlify ID and duplicate sites

### ISSUE THREAD

**Issue by iamadlx** [GetPublii/Publii#1298]
### Operating system

Somona 14.0

### Publii version

0.44.1

### Post editor

None

### Bug description

Hi Tomasz,

About this  : https://forum.getpublii.com/topic/big-bug-with-netlify-id-and-duplicate-sites/
The problem is still present in version 44.1.

as you've closed the topic, I can't reply to it any more :)

### Steps to reproduce

https://forum.getpublii.com/topic/big-bug-with-netlify-id-and-duplicate-sites/

**Comment by dziudek** [comment]
Hi,

The mentioned topic is open - I did not closed it :)

Regarding the problem - if you have created duplicate on old version of Publii then the problem will persist. It is fixed for newly duplicated websites only. For websites created with old version of Publii you must manually change website UUID to new one under input/site.config.json

**Comment by iamadlx** [comment]
![Screenshot 2023-11-17 at 09 59 09](https://github.com/GetPublii/Publii/assets/60820173/1ff8e3ff-26bd-412a-a32e-2eb6325c739a)
That seems to be the case for me. 
But it doesn't matter, thanks for your quick reply as usual! I didn't know that the update wouldn't work for old duplicate websites. So I'm going to use the site.config

**Comment by dziudek** [comment]
@iamadlx - ok now I see small text `This topic is marked as closed to new replies, however your posting capabilities still allow you to reply.` - probably Bob marked it as closed after resolving the issue :) 

Anyway - please just try to change 1 number in the UUID - it should help :)
