### ISSUE TITLE
[Bug]: After site rename plugins selector are disabled

### ISSUE THREAD

**Issue by gpsblues** [GetPublii/Publii#1302]
### Operating system

Win 10

### Publii version

0.44.1 (build 16519)

### Post editor

None

### Bug description

After renaming the site all installed plugins are deactivated, but they work.
If you try to activate them, the error "Cannot activate plugin - please try again" appears.
Upon leaving and returning to P. everything goes back to normal.

**Comment by dziudek** [comment]
Hi,

Thank you for finding this - it will be fixed in the upcoming v.0.44.2
