### ISSUE TITLE
[Feature Request]: Ability to activate a lightbox for featured images

### ISSUE THREAD

**Issue by Kalistia** [GetPublii/Publii#1304]
### Feature Description

It would be really nice to have the option to activate or not a **lightbox view** for the **featured images** on the articles

**Comment by atomGit** [comment]
...or any single image for that matter

**Comment by bobmitro** [comment]
I'm closing this topic because it's more relevant to a Publii plugin rather than the core functionality of Publii itself.

**Comment by atomGit** [comment]
you have an album feature and the code to support it - why would providing lightbox functionality for single images not be handled by the very same code?

**Comment by Kalistia** [comment]
Thanks Bob for the follow-up!

Could you explain why you think it should be an extension? Because I don't agree, as it's imo a pretty useful thing to have in the basic website builder!

**Comment by bobmitro** [comment]
The lightbox requires CSS and JavaScript, which must be attached to your site. In the Gallery, despite the UI delivered with Publii, the scripts are provided by the theme, not the app. 

The lightbox in my option should work automatically; when the user clicks the image, the script should detect this image and display the original (big) image in the popup. The best for that will be a plugin that will catch the pictures and display them in the Lightbox. 

Not everyone requires this feature, so it's unnecessary to clutter the interface overly. Incorporating every user-requested option could result in an excessively crowded interface. 

Also, a plugin will be easier to maintain and update.

**Comment by dziudek** [comment]
Definitely - decoupling lightbox mechanism from Publii is a good solution. When we will add this, then there will be people who wants other script/effect etc. It should be solved on theme/plugin level

**Comment by Kalistia** [comment]
Thanks guys, that makes more sense to me now :)
