### ISSUE TITLE
[Feature Request]: reduce title font size (wysiwyg)

### ISSUE THREAD

**Issue by atomGit** [GetPublii/Publii#1305]
### Feature Description

in the interest of providing more space for the editor, the post title font size could be greatly reduced

**Comment by bobmitro** [comment]
You can scale the interface or change the font size in the editors to provide more space. Since no one else has raised a similar request, I believe this is a unique user need. Considering this, I'm closing the topic as we don't see a need to make this change universally.

**Comment by atomGit** [comment]
> I'm closing the topic as we don't see a need ...

why not give visitors a chance to comment before you guys habitually close topics before ever seriously thinking about the requests?

you did this with every topic regarding requests to be able to scale the UI ... then finally added the functionality 

whatever

**Comment by bobmitro** [comment]
For several reasons, we are only two people and don't have the time to engage in lengthy "verbal skirmishes." Since your request is marginal because it is a single inquiry, we're not going to think about it now. The change in the app's font size has been raised multiple times, so we eventually paid attention to it.

PS: Instead of bombarding us with requests for changes that are important to you, why not make those changes on your own end? Remember, this is open-source software, and we are always open to contributions.

**Comment by atomGit** [comment]
> Since your request is marginal because it is a single inquiry, ...

hence my comment "why not give visitors a chance to comment before you guys habitually close topics"

the "verbal skirmishes" you refer to are a direct result of you guys essentially ignoring requests by closing issues with little or no consideration, often within minutes of each other

> The change in the app's font size has been raised multiple times, so we eventually paid attention to it.

i [offered a solution](https://github.com/GetPublii/Publii/issues/950#issuecomment-1772598269) which users could easily implement - prior to that, requests to scale the UI were torpedoed, the most silly of which was: "Making font sizes customizable in the Publii interface in different sections is quite a challenge due to the different screen sizes and complexity of the user interface.", which is exactly _why_ scaling the UI was necessary ... and it turns out it wasn't so difficult after all because it was built in to electron all along

> why not make those changes on your own end?

because i don't code JS Bob, but if i were able to put up a program like this, i'd be a hell of a lot more open to suggestions, as i have in the past and the present with all the bash and autoit scripts i've released over the decades - i _listen_ to users and treat them with respect, and if they request a feature that makes _logical sense_, regardless of the number of users that requested it, it gets implemented

**Comment by bobmitro** [comment]
👍

**Comment by atomGit** [comment]
yeah, i suppose i shouldn't have expected anything more thanthat
