### ISSUE TITLE
[Bug]: tag hyperlinks not editable

### ISSUE THREAD

**Issue by atomGit** [GetPublii/Publii#1308]
### Operating system

linux

### Publii version

0.44.1, build 16519 (and prior)

### Post editor

WYSIWYG editor

### Bug description

tag hyperlinks are not editable from the Inset/Edit link dialog (there is no field for holding the URL)

### Steps to reproduce

create a tag hyperlink, edit it using the link editor from the tool-bar or the pop-up

**Comment by dziudek** [comment]
Hi,

Could you better describe the issue? Tag links has no field for the URL, because you just select a tag to use in the link and the URL is generated automatically

**Comment by atomGit** [comment]
ok, that makes sense - not a bug then
