### ISSUE TITLE
Request to add the option to add H1 heading to Technews template frontpage

### ISSUE THREAD

**Issue by internettips** [GetPublii/Publii#131]
Some Publii prebuilt templates include an option to add a H1 HTML title to the home page / frontpage. I'm working on a project that uses your great Technews template, which seems to currently omit the H1 home page feature. 

While I can of course add HTML H1 home page heading on the "output" end, I can't see an option to easily add the home page H1 heading on the "input" side (preferred). 

Though, it looks like template overrides could fix the issue, hopefully, keeping such custom changes with subsequent template updates. 

However, if template overrides is the way to go for this item, please outline the process (or refer me to the relevant docs), to add H1 heading to home page. Cheers.

**Comment by bobmitro** [comment]
Hey,
Technews was designed as is, so I don't think so it will look good when we add a heading to the frontpage. 
To achieve the effect you are writing about, proceed as follows:
1. Open config.json file and add the following code:
```
 {
            "name": "frontH1",
            "label": "Content",
            "group": "Layout",
            "value": "",
            "type": "wysiwyg"
},
```

2. Now we have to edit the index.hbs file and add here our H1 section (on the top of <main> section):
```
<div class="page" id="frontTitle">
      {{{@config.custom.frontSekcjaTekstowaText}}}
</div>
```

3. Everything else you have to do is playing with CSS to achive the desire effect e.g.: add to the **FrontTitle** id  the following CSS rule:
```
#frontTitle {
     grid-column: span 2;
}
```

PS: Next time, if you need the assistance with the Publii themes please use our  [forum suport](https://publii.ticksy.com/). Our Github account is more application-oriented than the addons. Thank you in advance.
