### ISSUE TITLE
S3 sync: Trashed posts still published and accessible

### ISSUE THREAD

**Issue by dpatriarche** [GetPublii/Publii#132]
SETUP: Using the "Simple" theme. Two posts have been created. Each post is tagged with two tags "Foo" and "Bar". The site has a "Tags" menu with menu items that link to each tag.

PROCEDURE: On the Posts page, select one of the posts and then click "Move to trash". The post moves to the trash. Then "Sync your website".

EXPECTED: The trashed post will not be published to the site, and will not be accessible to readers.

ACTUAL: The trashed post is not visible on the front page of the site, but it is published to the site, and it is visible on the tags pages for "Foo" and "Bar".

**Comment by bobmitro** [comment]
Hi,
I've checked it and works as should. Could you provide us with the backup of your website (via PM https://publii.ticksy.com/ )

**Comment by dpatriarche** [comment]
Unfortunately I'd already permanently deleted the "trashed" post.

So I added a new post, trashed it, and then previewed it, and this time Publii worked like it should (i.e. the trashed post was not published to the site). But I didn't imagine it! I can look at my [public site](https://www.patriarche.net) and see the problem: Under the "Topics" menu click the "Software Development" link. There is a post there titled "Hello world!" that had been previously trashed.

Maybe something more subtle is going on? Seems like the trashed post might be published only under certain conditions. Like maybe if it was the first post made to the site? Or if it's the only post with a given tag?

**Comment by dpatriarche** [comment]
As requested, I create a [ticket on Ticksy](https://publii.ticksy.com/ticket/1702213/).

**Comment by dziudek** [comment]
Hi @dpatriarche,

I will deeper analyse this issue in this week. It seems that there is some bug in the S3 library which is used by Publii to sync the files.
