### ISSUE TITLE
[Bug]: Publii not creating sitemap.xml

### ISSUE THREAD

**Issue by hubyhuby** [GetPublii/Publii#1323]
### Operating system

Ubuntu Mat 22.04 / deb package

### Publii version

0.44.4

### Post editor

None

### Bug description

I have created a site with Publii, and even though I have sitemap toggled on, it is not generating a sitemap.xml

Is there anything I can try/adjust to correct this?
Same as this closed bug : https://github.com/GetPublii/Publii/issues/887
![image](https://github.com/GetPublii/Publii/assets/26340942/977a1440-8cdc-46c2-83f8-6c2ac514117b)
![image](https://github.com/GetPublii/Publii/assets/26340942/8afbc8ef-7041-4bdf-a6b1-3000de17893c)

![image](https://github.com/GetPublii/Publii/assets/26340942/0675004a-2465-47c1-a0e2-e3130f0105fc)

Tried aswell without pretty urls, but no luck
![image](https://github.com/GetPublii/Publii/assets/26340942/96974f71-e709-4306-871e-c551565c1e69)

**Comment by dziudek** [comment]
Hi, notices will be added for sitemap and RSS/JSON feeds in v.0.45 :)
