### ISSUE TITLE
[Feature Request]: Add a way to regenerate file names

### ISSUE THREAD

**Issue by warpdesign** [GetPublii/Publii#1324]
### Feature Description

When creating a post, it seems by default, Publii uses the title as name for the file. So for example, creating a file with the title `My Best Recipes` would result in the creation of `my-best-recipes.html` for the post.

The problem is that when I duplicate a post or change the title, it won't rename the file. So if I duplicate the previous post, but put unrelated content, for example: `My Best Songs`, the html file name would be `my-best-recipes2.html` which can be misleading.

There should be a way to update the file names once the context/title has been changed.

**Comment by bobmitro** [comment]
It's possible, just look at the SEO option and change the slug name.

**Comment by warpdesign** [comment]
That's already possible :)
