### ISSUE TITLE
[Feature Request]: utilize server side includes (SSI)

### ISSUE THREAD

**Issue by atomGit** [GetPublii/Publii#1326]
### Feature Description

[SSI](https://en.wikipedia.org/wiki/Server_Side_Includes) could greatly reduce the number of file transfers when syncing with a remote server, as well as save some storage space, the cost of which is still at a premium for hosting companies

currently, when updating a global page component such as a menu or a footer, every post/page is re-uploaded to the server, whereas with SSI the pages would be split into 3 or more sections -- menu, post, footer -- each of which would exist as a single, separate file which is then included by the http server in each page

potential caveats...

* extra load on the server, though i don't know how relevant a concern this may be given both server-side and browser cache
* may not be entirely feasible for static hosts, such as github - in such cases either some JS may be necessary (looks like [Jekyll](https://stackoverflow.com/questions/22326742/server-side-includes-alternative) does this), or the feature could be disabled
* ...

**Comment by dziudek** [comment]
Due lack of global compatibility and big complexity of implementation in themes (needs to support both ways of rendering theme what requires changes in all existing themes) and potential issues with parts like menu (it is impossible to mark current item in this approach on html level) we won't make this as a part of Publii core
