### ISSUE TITLE
[Feature Request]: add more social options by default (Telegram)

### ISSUE THREAD

**Issue by sxiii** [GetPublii/Publii#1328]
### Feature Description

We lack some super popular social options out there!

Telegram is 100% needed. I've seen the [issue](https://github.com/GetPublii/Publii/issues/1044) but it should be built-in function. Would also be great to have some other social networks too, like Medium, etc.

**Comment by GetPublii** [comment]
Closed due to lack of relevance to the application. 
You can add more platforms via a theme or by using dedicated plugins for Follow or Sharing buttons: https://marketplace.getpublii.com/plugins/
