### ISSUE TITLE
[Feature Request]: Helper to display an array of Maintags

### ISSUE THREAD

**Issue by candidexmedia** [GetPublii/Publii#1329]
### Feature Description

Hello! This feature request hopes to address the confusion surrounding the filter by [Maintags](https://github.com/GetPublii/Publii/issues/355) function found in certain themes:
- https://forum.getpublii.com/topic/mercury-maintag/
- https://forum.getpublii.com/topic/homepage-tag-list-not-contained-mercury-theme/
- https://forum.getpublii.com/topic/mercury-theme-front-page-filter-by-maintag-has-no-effect-on

Many believe that filtering posts by their Maintag means that only Maintags will be displayed in the list of filters, but that isn't the case (or possible at the moment). My wish would be to have some kind of helper similar to `#each tags`, but for maintags (ie `#each maintag`).

**Comment by dziudek** [comment]
@candidexmedia - it will be available on v.0.45 as:

```hbs
{{#each mainTags}}
...
{{/each}}
```

It will work like `{{#each tags}}...{{/each}}` but will be limited only to tags set as main tag :)

**Comment by candidexmedia** [comment]
Amazing, thank you!

**Comment by candidexmedia** [comment]
Hi @dziudek! Is it possible to exlude mainTags from an array, like:

```hbs
{{if its a tag}}
 {{#each tag EXCEPT mainTags}}
...
{{/each}}
{{/if}}
```

or

```hbs
{{getTags isNot mainTag}}
..
```

**Comment by dziudek** [comment]
@candidexmedia - there is unfortunately no simple way.

The easiest solution would be creating a custom helper https://getpublii.com/dev/how-to-create-a-custom-helper/ which receives mainTags and ID of tag to check - something like:

```
mainTagChecker: function(mainTags, id) {
    return mainTags.some(tag => tag.id === id);
}
```

And then use it as:

```
{{#if tags}}
    {{#each tags}}
        {{#unless (mainTagsChecker mainTags this.id)}}
            <a href="{{url}}">{{name}}</a>
        {{/unless}}
    {{/each}}
{{/if}}
```

In Publii v.0.46 I will try to add some flag like "isMainTag" to the tags object

**Comment by candidexmedia** [comment]
Thank you for the help @dziudek!

cc: @much.fun

**Comment by candidexmedia** [comment]
Thank you for the help @dziudek!

cc: @3muchfun
