### ISSUE TITLE
[Bug]: Tags that are relative only to hidden post breaks

### ISSUE THREAD

**Issue by hubyhuby** [GetPublii/Publii#1336]
### Operating system

Ubuntu mate 22.04 LTS

### Publii version

0.44.4

### Post editor

None

### Bug description

If you create ONLY pages hidden, the tags are broken.
Publii does NOT create the relative folder tags/MY-hidden-post-tag
The site is giving 404 each time this tag is mentionned 

WORK AROUND :
every tag in the system must be related at least to one NONE hidden post

**Comment by bobmitro** [comment]
This is not a bug but intended behavior. For posts, "hidden" means removing the post from the loop of posts, making these posts act as a static page. In the case of tags, this would not make sense, therefore marking a tag as hidden results in the tag not being displayed or generated. This is useful for internal tagging of posts.

**Comment by hubyhuby** [comment]
The site is giving 404 each time this tag is mentionned... which shouldn t happen ;)
The tags are some how created...but broken

**Comment by dziudek** [comment]
@hubyhuby - to avoid this you can hide tag as well: Basic Information -> Hide tag (under tag edit form)
