### ISSUE TITLE
[Feature Request]: SSH support for the Git deployment option

### ISSUE THREAD

**Issue by TheDevMinerTV** [GetPublii/Publii#1339]
### Feature Description

Please allow us to push to Git repositories over SSH. Currently the application throws the following error:
![image](https://github.com/GetPublii/Publii/assets/29845135/be125652-67ae-4274-842d-8a8319d60df3)

**Comment by dziudek** [comment]
Unfortunately used git library does not support SSH. But it is at this moment the only good solution which not requires native bindings, so we have no plan to change it.
