### ISSUE TITLE
[Bug]: Tags category configuration : certain charactere will duplicate the tags

### ISSUE THREAD

**Issue by hubyhuby** [GetPublii/Publii#1356]
### Operating system

Ubuntu mate 22.04 LTS

### Publii version

0.44.4

### Post editor

None

### Bug description

WHen I tried to modify an existing tag from  "Crédit impôt recherche (CIR)" to  "Crédit d'impôt recherche (CIR)".
The system created TWO taggs instead of modifying the tag : 
1) one tag with the current name and a new SLUG (apparentely correcte)
2) One new tag (nor requested) which was a copy of the previous one.

Crédit d'impôt recherche (CIR)

### Steps to reproduce

I must say I was in a panic, because I had deployed on my server double tags every where...
So it might not be the best description.
My understanding is that if you modify the name of a tag with the charactere **'** like string "**d'**" , it will do the bug.
I had done it 3 times because I modified 3 tags, so ended up with 6 tag categories

### Relevant log output

![image](https://github.com/GetPublii/Publii/assets/26340942/062da9c5-3a9e-47d0-96bd-1a739d955341)

**Comment by dziudek** [comment]
Hi,

Sorry but I am unable to reproduce this issue on the latest Publii release - I have checked macOS and Linux releases of v.0.44.

I have created tag "test test", saved it and then renamed to "test d'test" - no issues found

**Comment by hubyhuby** [comment]
Hi 
thanks for investigating.
Unfortunately I am afraid of breaking again my setup...  I will not change the tag names anymore for a while.
I am pretty sure there is a way to replicate since it duplicated the 3 tags I had into 6. It s not like I made one mistake that led to one duplicate.
Lets close it I guess . And reopen if we can reproduce.

**Comment by dziudek** [comment]
Ok, I will wait for more details :)
