### ISSUE TITLE
Add support for app UI localization

### ISSUE THREAD

**Issue by pagelab** [GetPublii/Publii#137]
International users will greatly benefit from this. I can contribute with Portuguese translation.

**Comment by bobmitro** [comment]
Hey, 
We have a plan to do this next year.

**Comment by EryouHao** [comment]
I can contribute with Chinese translation.😊

**Comment by Izzur** [comment]
I can contribute with Indonesian translation.

**Comment by YoavRheims** [comment]
Don't forget French :)

**Comment by gpsblues** [comment]
I can contribute with Italian translation. Will I be technically capable of it? :)

**Comment by loilo** [comment]
I'd be happy to contribute a German translation. 👍

**Comment by pagelab** [comment]
It looks like it's not going to happen, see #628. Can you confirm, @bobmitro?

**Comment by bobmitro** [comment]
Yes, I can confirm. More details: #628

**Comment by pagelab** [comment]
I understand that this represents a lot of work to build and to maintain, but it's sad to see it go.

A large number of international users who don't understand English enough will not benefit from the great ease of use and cost savings that Publii offers.

Did you guys ever consider adding a translation framework to the app and letting the community handle most of the work, including the documentation?

**Comment by ZaferGraph** [comment]
Turkish here. Do you have template? @bobmitro
