### ISSUE TITLE
[Feature Request]: show image caption on post images

### ISSUE THREAD

**Issue by sardaukar** [GetPublii/Publii#1376]
### Feature Description

Is there a way to show a `figcaption` on post images? Or a way to extend the normal tags for them to show them? I'm using the Markdown editor and with the usual 

`![name](url)`

statement, the `name` isn't show as a caption for the image.

**Comment by dziudek** [comment]
@sardaukar - in v.0.45 we will add support for figcaptions. But the syntax will be different:

`![image alt text](https://image.url "image figcaption")`

As it is a built-in syntax - unfortunately our current renderer override skips the "title" argument - I have fixed it now.

**Comment by dziudek** [comment]
@sardaukar - BTW I will also fix in v.0.45 another bug - `<figure>` was improperly wrapped into `<p>` elements
