### ISSUE TITLE
TinyMCE custom config doesn't work in link pop-up

### ISSUE THREAD

**Issue by pagelab** [GetPublii/Publii#139]
Hello,

I've added some custom TinyMCE configs for the `link` plugin (as outlined [here](https://www.tiny.cloud/docs/plugins/link/#rel_list)) but they didn't had any effect.

Here's the exact content of my `tinymce.override.json`, which was added in the root `config` folder:

```json
{
	"toolbar2": "",
	"target_list": [
		{
			"title": "None",
			"value": ""
		},
		{
			"title": "Same page",
			"value": "_self"
		},
		{
			"title": "New page",
			"value": "_blank"
		},
		{
			"title": "Lightbox",
			"value": "_lightbox"
		}
	],
	"rel_list": [
		{
			"title": "No follow",
			"value": "nofollow"
		},
		{
			"title": "Follow",
			"value": "follow"
		}
	],
	"link_class_list": [
		{
			"title": "None",
			"value": ""
		},
		{
			"title": "Button",
			"value": "button"
		},
		{
			"title": "External link",
			"value": "external"
		}
	]
}
```
Only the `"toolbar2": "",` config work as expected.

**Comment by dziudek** [comment]
Hi,

Publii uses custom Link Popup so TinyMCE settings does not affect it. The changes will be visible only if you will click the link icon under toolbar - it still uses the native TinyMCE popup link.

**Comment by pagelab** [comment]
Oh I see. Do you plan to unify the controls from these two modals?

It's confusing to have two separate set of controls in each one.

**Comment by dziudek** [comment]
We have left the old modal to allow users use it if in some cases our link popup won't fill their exceptations. But of course - we will unify the popups in the future to use only our implementation :) Before, we want to improve our popup with new options.

**Comment by pagelab** [comment]
That seems reasonable, thanks for explaining. 👍
