### ISSUE TITLE
Order by priority: &orderby=" @config.custom.position

### ISSUE THREAD

**Issue by georgkaser** [GetPublii/Publii#1391]
### Question

Hi, I am wonder if it's possible to sort the posts by priority adding a custom text field for give the posts a priority number:

`{{#getPostsByTags (concatenate "count=10&allowed=published&tag_as=id" "&excluded_status=hidden" "&tags=" id "&orderby=" @config.custom.position "&ordering=asc")}}`

It's not working, what I am doing wrong?

**Comment by georgkaser** [comment]
It's a text value.

I am a web developer since 2005 and I know from my experience, that my customers are asking me to sort posts (articles) by their order priority. It must be possible. Maybe I can do it with this custom helpers?

**Comment by bobmitro** [comment]
Not now, but most likely, we'll add it in an upcoming new Publii release (in a few days).

**Comment by georgkaser** [comment]
Wow, cool - thank you. Please add it as a number field.

I love your phantastic CMS - thank you for your great work. You will hear from me again with some money.

**Comment by dziudek** [comment]
In v.0.45 the syntax like `orderby=customField&customField=xyz&compareLanguage=fr` will be allowed in the {{getPostsByTags}}
