### ISSUE TITLE
[Bug]: After update to 0.44.4 "database is locked"

### ISSUE THREAD

**Issue by SebastianSolidwork** [GetPublii/Publii#1393]
### Operating system

Windows 10

### Publii version

0.44.4

### Post editor

None

### Bug description

I have update from somewhat 0.41'ish to 0.44.4 and at the start of Publii a error message comes with "database is locked".
It occurs even after a restart.
I fear to loose data by to un- and reinstall Publii. How secure would be that?

Any file in the internal log viewer is empty.
What can I provide you?

![image](https://github.com/GetPublii/Publii/assets/22794134/29b0655c-9022-4026-bba1-6f9e98795126)

**Comment by dziudek** [comment]
Hi,

This issue will be solved in the upcoming v.0.45 - we will restore previous SQLite library for Windows and mac OS

**Comment by SebastianSolidwork** [comment]
Good to hear. How can I work around until that?
Can I somehow downgrade?
My Publii is not usable at all.

**Comment by dziudek** [comment]
@SebastianSolidwork - you can try to use v.0.44.1 which used old module for SQLite: https://getpublii.com/download/Publii-0.44.1.exe

**Comment by SebastianSolidwork** [comment]
Thanks. That works. Hell, was I scared.
