### ISSUE TITLE
Support for Relative URLs

### ISSUE THREAD

**Issue by aksanoble** [GetPublii/Publii#141]
Is there a way to generate output with just relative urls instead of domain name inserted in the assets source.

**Comment by dziudek** [comment]
Hi,

I will check if it is possible to do in an easy way - if yes, I will add it in the nearest release :)

**Comment by aksanoble** [comment]
Thank you! I'm trying to publish the website on IPFS which will not work with absolute URLs. If you could point me, I can take a stab at fixing it. Thank you!

**Comment by dziudek** [comment]
I have made an issue for the IPFS support ( https://github.com/GetPublii/Publii/issues/146 ) for the 0.31.* release - I do hope that I will be able to implement it :)

**Comment by dziudek** [comment]
This change can create relative URLs in the whole deployment output: https://github.com/GetPublii/Publii/commit/1dc2efb3344f090d87cc74b6906628e456e34b37#diff-d9881c828b537e8b79fb7f38c3f8570e

**Comment by dziudek** [comment]
I will firstly check IPFS requirements and then I will consider it this kind of option is required, maybe it will be triggered only when IPFS is used as a deployment method :)

**Comment by aksanoble** [comment]
> This change can create relative URLs in the whole deployment output: [1dc2efb#diff-d9881c828b537e8b79fb7f38c3f8570e](https://github.com/GetPublii/Publii/commit/1dc2efb3344f090d87cc74b6906628e456e34b37#diff-d9881c828b537e8b79fb7f38c3f8570e)

Great! Let me pull these changes in and test it out.

**Comment by aksanoble** [comment]
> I will firstly check IPFS requirements and then I will consider it this kind of option is required, maybe it will be triggered only when IPFS is used as a deployment method :)

I believe support to relative URLs might be relevant in other cases other than IPFS for example if we have to host a blog on a relative URL such as `/blog/` For example the path-prefix option on [Gatsby](https://www.gatsbyjs.org/docs/path-prefix/)

**Comment by dziudek** [comment]
Changing:

```
if(this.previewMode) {
     this.siteConfig.domain = 'file://' + this.outputDir;
}
```

into:

```
if(this.previewMode) {
    this.siteConfig.domain = 'file://' + this.outputDir;
} else {
     this.siteConfig.domain = '/test';
}
```

Almost covers 100% of issues with URLs (`/test` can be replaced with any subcatalog name or with `''` - empty string if the domain is in root). But it affects Open Graph and social sharing features.

I suppose that we can consider adding an option to use relative paths (and remember to remove the trailing slash from it), but we have to think what to do with social sharing features.

**Comment by pavelloz** [comment]
Hey, great work on the Publii - im very impressed with what it does and how it does it :)

So far having possibility to use relative URLs (relative to lets say index.html) in the output is my only wish. It would make less tech-savvy people life's easier :)

**Comment by novalore** [comment]
It's a great feature to have. Especially useful for offline use in training, for example (to build websites that can be consulted on a usb stick or on a cd-rom)

**Comment by Goozoon** [comment]
i just wish it is a working feature
not, as of now :(
