### ISSUE TITLE
[Bug]: Json Feed show only Default Author name

### ISSUE THREAD

**Issue by janrippl** [GetPublii/Publii#1411]
### Operating system

Ubuntu 23.04

### Publii version

Version: 0.44.4 (build 16557)

### Post editor

None

### Bug description

Regardless of who is the author of the article, feed.json always contains only the name of the default author as the author of the article. The same bug occurs with feed.xml.

**Comment by dziudek** [comment]
Hi,

Thank you for finding this bug - it will be fixed in v.0.45 :)
