### ISSUE TITLE
Not able to hoook it up to my existing gh-pages hosted site whose repository have a dot "." in it

### ISSUE THREAD

**Issue by vongomben** [GetPublii/Publii#142]
I guess I've foind a little problem in the server settings UI: my repository has a dot "." in it: what to do with it? Publii is unable to load it..

![immagine](https://user-images.githubusercontent.com/1215847/45700184-2e277500-bb6c-11e8-96ab-52723e5b05f4.png)

**Comment by dziudek** [comment]
Hi @vongomben ,

Could you provide more details?

I have tried to reproduce this issue on this repository: https://dziudek.github.io/publii.test/

But all is working fine - my settings are visible below:

<img width="990" alt="image 2018-09-20 at 12 12 30 pm" src="https://user-images.githubusercontent.com/22004/45811946-c2115200-bcce-11e8-8df1-37691a3c898e.png">
