### ISSUE TITLE
How to use publii without the installed themes?

### ISSUE THREAD

**Issue by vongomben** [GetPublii/Publii#143]
I was finally able to connect Publii to an existing server, yet is unable to update (download) the previous posts from it. 

alla I can see is **syinc your website** that pops up the window:

![immagine](https://user-images.githubusercontent.com/1215847/45701188-dc341e80-bb6e-11e8-8762-c3642da71560.png)

Any clues?

**Comment by dziudek** [comment]
Hi,

You cannot use Publii without selected theme as then it is impossible to render the website.

I suppose that you have misunderstand the way how "sync website" button works - it just renders the content existing in the Publii using a selected theme and the uploads it to the server. It won't download the existing content from your website.
