### ISSUE TITLE
[Bug]: [Windows 11] Crash upon launching - "A Javascript error occured in the main process"

### ISSUE THREAD

**Issue by CaseyLabs** [GetPublii/Publii#1434]
### Operating system

Windows 11 - Version 23H2 (OS Build 22631.3296)

### Publii version

0.45.2 (build 16609)

### Post editor

None

### Bug description

- Fresh install of current version of Publii (0.45.2) on a new Windows 11 laptop

- Install succeeded with no issues ( I have also uninstalled/reinstalled Publii to verify the issue)

- Every attempt to launch the app results in this error message however:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: UNKNOWN: unknown error, read
at Object.readSync (node:fs:751:3)
at tryReadSync (node:fs:451:20)
at Object.readFileSync (node:fs:489:19)
at t.readFileSync (node:electron/js2c/node_init:2:9771)
at App.checkThemes
(C:\Users\$env:username\AppData\Local\Programs\Publii\resources\app.asar\back-end\app.js:168:55)
at new App
(C:\Users\$env:username\AppData\Local\Programs\Publii\resources\app.asar\back-end\app.js:76:14)
at App .< anonymous>
(C:\Users\$env:username\AppData\Local\Programs\Publii\resources\app.asar\main.js:40:19)
at App.emit (node:events:517:28)

OK
```

I am unable to load Publii because of this error. Any suggestions? Thanks!

**Comment by dziudek** [comment]
Hi,

This error suggest that there is some issue with the default simple theme. Please check if file /sites/your-site-name/input/themes/Simple/config.json exists

If yes - please check if it is not corrupted.

Other possible reasons - problem with permissions or file is blocked by different process

Did you tried to uninstall Publii and remove the website files?
