### ISSUE TITLE
IPFS support - research

### ISSUE THREAD

**Issue by dziudek** [GetPublii/Publii#146]
We should consider adding built-in support for IPFS: https://ipfs.io/

**Comment by dzmitry-lahoda** [comment]
i recently tried zeronet and created site. it worked well. each site in zeronet need js file to be embedded into. i am going to cross publish my 5 static sites onto on of p2p internet(being it ipfs or other). and i like relative links.

**Comment by Yinchie** [comment]
I haven't tried it yet bus is https://getpublii.com/docs/server-configuration.html#manual possible for IPFS?
Adding the entire folder to the IPFS desktop application and make it available that way?
https://github.com/ipfs-shipyard/ipfs-desktop

**Comment by dziudek** [comment]
As creating websites using relative paths seems to be enough for IPFS websites (also we have ipfs protocol on the list in the domain field), I think that we can close this issue right now.
