### ISSUE TITLE
Button - Back to top

### ISSUE THREAD

**Issue by rsipakov** [GetPublii/Publii#149]
Hey there,

I'm looking for help in resolving the question about Back to top button.

I created:

1) .js file 
// When the user scrolls down 20px from the top of the document, show the button
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
    if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
        document.getElementById("BtnTop").style.display = "block";
    } else {
        document.getElementById("BtnTop").style.display = "none";
    }
}

// When the user clicks on the button, scroll to the top of the document
function topFunction() {
    document.body.scrollTop = 0; // For Safari
    document.documentElement.scrollTop = 0; // For Chrome, Firefox, IE and Opera
}

2) Add to main.css
#BtnTop {
    display: none; /* Hidden by default */
    position: fixed; /* Fixed/sticky position */
    bottom: 50px; /* Place the button at the bottom of the page */
    right: 30px; /* Place the button 30px from the right */
    z-index: 99; /* Make sure it does not overlap */
    border: none; /* Remove borders */
    outline: none; /* Remove outline */
    background-color: #00a4bd; /* Set a background color */
    color: white; /* Text color */
    cursor: pointer; /* Add a mouse pointer on hover */
    padding: 12px; /* Some padding */
    border-radius: 10px; /* Rounded corners */
    font-size: 10px; /* Increase font size */
  }
  #BtnTop:hover {
    background-color: #ff6d37; /* Add a dark-grey background on hover */
}

3. Add to head.hbs
<button onclick="topFunction()" id="BtnTop" title="Back to top">Top</button>
<script src="assets/js/scroll-back-to-cust.js"></script>

This button is work on the front page. But on other pages don't work. Anyone, can you help me to fix it?

Thank you!

**Comment by bobmitro** [comment]
Hi,
Your issue is related to the theme, not the Publii app, so please create a ticket https://publii.ticksy.com/ and attach your website back up.
