### ISSUE TITLE
Support for GitLab Pages

### ISSUE THREAD

**Issue by dziudek** [GetPublii/Publii#15]
Needs bigger research.

ref. https://github.com/jdalrymple/node-gitlab
ref. https://docs.gitlab.com/ee/api/
ref. https://docs.gitlab.com/ee/user/project/pages/

**Comment by mishak87** [comment]
Will you also write documentation for it at https://getpublii.com/docs/server-configuration.html? Maybe GitLab team would like to help.

**Comment by dziudek** [comment]
Hi @mishak87,

I have written the article yesterday, now it is reviewed and polished. It will be available with the next Publii release on the nearest Friday or Monday :)

**Comment by bobmitro** [comment]
Hi @mishak87,

Recently we published it here https://getpublii.com/docs/host-static-website-gitlab-pages.html
