### ISSUE TITLE
[Bug]: Matomo plugin URL malformed

### ISSUE THREAD

**Issue by nukeador** [GetPublii/Publii#1536]
### Operating system

Ubuntu

### Publii version

0.45.2 (build 16609)

### Post editor

None

### Bug description

The Matomo plugin is missing a slash somewhere, because I see network request with mydomain.commatomo.php

https://mydomain.commatomo.php/?action_name=Blog&idsite=9&rec=1&r=965961&h=23&m=26&s=44&url=https%3A%2F%2Fmydomain.com%2F&_id=0c7a1e4ca0624e77&_idn=0&send_image=0&_refts=0&pv_id=gYGbmy&pf_net=239&pf_srv=332&pf_tfr=0&pf_dm1=34&uadata=%7B%7D&pdf=1&qt=0&realp=0&wma=0&fla=0&java=0&ag=0&cookie=1&res=3840x2160

Interestingly there is also a previous request using the right url:

https://mydomain.com/matomo.js

My config url is https://mydomain.com

If I config it as https://mydomain.com/ there is a double // on the request https://mydomain.com//matomo.js

**Comment by bobmitro** [comment]
Hey, make sure to check out the new plugin [version 1.0.2](https://marketplace.getpublii.com/plugins/matomo-analytics/). The update should fix the issue.
