### ISSUE TITLE
[Bug]: Publii does not start at all (Illegal instruction)

### ISSUE THREAD

**Issue by visnotjl** [GetPublii/Publii#1553]
### Operating system

Linux MInt 21.3 x86/64

### Publii version

latest (not shown in package, neither at launch)

### Post editor

None

### Bug description

Publii does not start at all. _Don't know where coredump is created neither the file name

![illegal_instruction](https://github.com/GetPublii/Publii/assets/68055518/8ac935e2-5e36-4a61-8329-de1b17a31adb)
![working_environment](https://github.com/GetPublii/Publii/assets/68055518/db7c32d0-c853-41c4-9734-acefb25b54ce)

**Comment by damalix92** [comment]
Hi,

I have the same issue here, with the two last versions.
It ran well with version ~38 and I wanted to update. So I downloaded the latest package (45.2) and can't launch it anymore. Then I tried to get the previous version (44.4) with no more luck.

<pre><font color="#8AE234"><b>minou@dam</b></font>:<font color="#729FCF"><b>~</b></font>$ Publii 
Instruction non permise (core dumped)
<font color="#8AE234"><b>minou@dam</b></font>:<font color="#729FCF"><b>~</b></font>$ neofetch
<b>             ...-:::::-...</b>                 <font color="#8AE234"><b>minou</b></font>@<font color="#8AE234"><b>dam</b></font> 
<b>          .-MMMMMMMMMMMMMMM-.</b>              --------- 
<b>      .-MMMM</b><font color="#8AE234"><b>`..-:::::::-..`</b></font><b>MMMM-.</b>          <font color="#8AE234"><b>OS</b></font>: Linux Mint 21.3 x86_64 
<b>    .:MMMM</b><font color="#8AE234"><b>.:MMMMMMMMMMMMMMM:.</b></font><b>MMMM:.</b>        <font color="#8AE234"><b>Host</b></font>: GA-880GM-UD2H 
<b>   -MMM</b><font color="#8AE234"><b>-M---MMMMMMMMMMMMMMMMMMM.</b></font><b>MMM-</b>       <font color="#8AE234"><b>Kernel</b></font>: 5.15.0-113-generic 
<b> `:MMM</b><font color="#8AE234"><b>:MM`  :MMMM:....::-...-MMMM:</b></font><b>MMM:`</b>    <font color="#8AE234"><b>Uptime</b></font>: 4 hours, 4 mins 
<b> :MMM</b><font color="#8AE234"><b>:MMM`  :MM:`  ``    ``  `:MMM:</b></font><b>MMM:</b>    <font color="#8AE234"><b>Packages</b></font>: 2422 (dpkg) 
<b>.MMM</b><font color="#8AE234"><b>.MMMM`  :MM.  -MM.  .MM-  `MMMM.</b></font><b>MMM.</b>   <font color="#8AE234"><b>Shell</b></font>: bash 5.1.16 
<b>:MMM</b><font color="#8AE234"><b>:MMMM`  :MM.  -MM-  .MM:  `MMMM-</b></font><b>MMM:</b>   <font color="#8AE234"><b>Resolution</b></font>: 1920x1080 
<b>:MMM</b><font color="#8AE234"><b>:MMMM`  :MM.  -MM-  .MM:  `MMMM:</b></font><b>MMM:</b>   <font color="#8AE234"><b>DE</b></font>: Cinnamon 6.0.4 
<b>:MMM</b><font color="#8AE234"><b>:MMMM`  :MM.  -MM-  .MM:  `MMMM-</b></font><b>MMM:</b>   <font color="#8AE234"><b>WM</b></font>: Mutter (Muffin) 
<b>.MMM</b><font color="#8AE234"><b>.MMMM`  :MM:--:MM:--:MM:  `MMMM.</b></font><b>MMM.</b>   <font color="#8AE234"><b>WM Theme</b></font>: Mint-Y-Dark-Purple (Mint-Y 
<b> :MMM</b><font color="#8AE234"><b>:MMM-  `-MMMMMMMMMMMM-`  -MMM-</b></font><b>MMM:</b>    <font color="#8AE234"><b>Theme</b></font>: Mint-Y-Dark-Purple [GTK2/3] 
<b>  :MMM</b><font color="#8AE234"><b>:MMM:`                `:MMM:</b></font><b>MMM:</b>     <font color="#8AE234"><b>Icons</b></font>: Mint-Y-Dark-Purple [GTK2/3] 
<b>   .MMM</b><font color="#8AE234"><b>.MMMM:--------------:MMMM.</b></font><b>MMM.</b>      <font color="#8AE234"><b>Terminal</b></font>: gnome-terminal 
<b>     &apos;-MMMM</b><font color="#8AE234"><b>.-MMMMMMMMMMMMMMM-.</b></font><b>MMMM-&apos;</b>       <font color="#8AE234"><b>CPU</b></font>: AMD Athlon II X3 440 (3) @ 3.00 
<b>       &apos;.-MMMM</b><font color="#8AE234"><b>``--:::::--``</b></font><b>MMMM-.&apos;</b>         <font color="#8AE234"><b>GPU</b></font>: AMD ATI Radeon HD 4250 
<b>            &apos;-MMMMMMMMMMMMM-&apos;</b>              <font color="#8AE234"><b>Memory</b></font>: 2228MiB / 3404MiB 
<b>               ``-:::::-``</b>
                                           <span style="background-color:#2E3436"><font color="#2E3436">   </font></span><span style="background-color:#CC0000"><font color="#CC0000">   </font></span><span style="background-color:#4E9A06"><font color="#4E9A06">   </font></span><span style="background-color:#C4A000"><font color="#C4A000">   </font></span><span style="background-color:#3465A4"><font color="#3465A4">   </font></span><span style="background-color:#75507B"><font color="#75507B">   </font></span><span style="background-color:#06989A"><font color="#06989A">   </font></span><span style="background-color:#D3D7CF"><font color="#D3D7CF">   </font></span>
                                           <span style="background-color:#555753"><font color="#555753">   </font></span><span style="background-color:#EF2929"><font color="#EF2929">   </font></span><span style="background-color:#8AE234"><font color="#8AE234">   </font></span><span style="background-color:#FCE94F"><font color="#FCE94F">   </font></span><span style="background-color:#729FCF"><font color="#729FCF">   </font></span><span style="background-color:#AD7FA8"><font color="#AD7FA8">   </font></span><span style="background-color:#34E2E2"><font color="#34E2E2">   </font></span><span style="background-color:#EEEEEC"><font color="#EEEEEC">   </font></span>


<font color="#8AE234"><b>minou@dam</b></font>:<font color="#729FCF"><b>~</b></font>$ 
</pre>

I'll try to get older versions to see if I can get it running...

**Comment by damalix92** [comment]
Latest version 0.46.1 is also affected.

**Comment by dziudek** [comment]
Hi,

Could you try to run:

```
strace -o output.txt ./Publii
```

And then check what is in output.txt

I suppose that electron-builder compiled app using instructions which are not supported by your computer. Also as I see your processor is ~14 years old, so I suppose that it can be incompatible with newer Electron builds. They have abandoned older Windows some time ago

**Comment by damalix92** [comment]
Hi there,

Thank you for your directions. I'm not running Windows, but I can understand that my computer is getting old for some actions.

I ran the command line you gave and got a 5.7k lines output file.
Electron is mentioned once in the middle of the file and does not seem to trigger immediate core dump, but that doesn't mean it is not the issue. Maybe there is a way to test the electron environment?
Also in the file, there are quite a lot of "no file or folder with this name" lines, so I thought that there could be some missing depencencies. I tried to install libvips for test, but it induced no change in the output file.

I'm not sure thet this will help, but the end of the file looks like that (or maybe there is something specific to look for?):

> openat(AT_FDCWD, "/opt/Publii/resources/app.asar.unpacked/node_modules/@img/sharp-linux-x64/lib/../../../../../@img-sharp-
> libvips-linux-x64-npm-1.0.2-69e740ab3d/node_modules/@img/sharp-libvips-linux-x64/lib/x86_64/x86_64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (Aucun fichier ou dossier de ce nom)
> newfstatat(AT_FDCWD, "/opt/Publii/resources/app.asar.unpacked/node_modules/@img/sharp-linux-x64/lib/../../../../../@img-sharp-libvips-linux-x64-npm-1.0.2-69e740ab3d/node_modules/@img/sharp-libvips-linux-x64/lib/x86_64/x86_64", 0x7ffdf93e8440, 0) = -1 ENOENT (Aucun fichier ou dossier de ce nom)
> openat(AT_FDCWD, "/opt/Publii/resources/app.asar.unpacked/node_modules/@img/sharp-linux-x64/lib/../../../../../@img-sharp-libvips-linux-x64-npm-1.0.2-69e740ab3d/node_modules/@img/sharp-libvips-linux-x64/lib/x86_64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (Aucun fichier ou dossier de ce nom)
> newfstatat(AT_FDCWD, "/opt/Publii/resources/app.asar.unpacked/node_modules/@img/sharp-linux-x64/lib/../../../../../@img-sharp-libvips-linux-x64-npm-1.0.2-69e740ab3d/node_modules/@img/sharp-libvips-linux-x64/lib/x86_64", 0x7ffdf93e8440, 0) = -1 ENOENT (Aucun fichier ou dossier de ce nom)
> openat(AT_FDCWD, "/opt/Publii/resources/app.asar.unpacked/node_modules/@img/sharp-linux-x64/lib/../../../../../@img-sharp-libvips-linux-x64-npm-1.0.2-69e740ab3d/node_modules/@img/sharp-libvips-linux-x64/lib/x86_64/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (Aucun fichier ou dossier de ce nom)
> newfstatat(AT_FDCWD, "/opt/Publii/resources/app.asar.unpacked/node_modules/@img/sharp-linux-x64/lib/../../../../../@img-sharp-libvips-linux-x64-npm-1.0.2-69e740ab3d/node_modules/@img/sharp-libvips-linux-x64/lib/x86_64", 0x7ffdf93e8440, 0) = -1 ENOENT (Aucun fichier ou dossier de ce nom)
> openat(AT_FDCWD, "/opt/Publii/resources/app.asar.unpacked/node_modules/@img/sharp-linux-x64/lib/../../../../../@img-sharp-libvips-linux-x64-npm-1.0.2-69e740ab3d/node_modules/@img/sharp-libvips-linux-x64/lib/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (Aucun fichier ou dossier de ce nom)
> newfstatat(AT_FDCWD, "/opt/Publii/resources/app.asar.unpacked/node_modules/@img/sharp-linux-x64/lib/../../../../../@img-sharp-libvips-linux-x64-npm-1.0.2-69e740ab3d/node_modules/@img/sharp-libvips-linux-x64/lib", 0x7ffdf93e8440, 0) = -1 ENOENT (Aucun fichier ou dossier de ce nom)
> openat(AT_FDCWD, "/opt/Publii/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (Aucun fichier ou dossier de ce nom)
> openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 43
> newfstatat(43, "", {st_mode=S_IFREG|0644, st_size=83607, ...}, AT_EMPTY_PATH) = 0
> mmap(NULL, 83607, PROT_READ, MAP_PRIVATE, 43, 0) = 0x7f8792ff1000
> close(43)                               = 0
> openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 43
> read(43, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
> newfstatat(43, "", {st_mode=S_IFREG|0644, st_size=2260296, ...}, AT_EMPTY_PATH) = 0
> mmap(NULL, 2275520, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 43, 0) = 0x7f8792dc5000
> mprotect(0x7f8792e5f000, 1576960, PROT_NONE) = 0
> mmap(0x7f8792e5f000, 1118208, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 43, 0x9a000) = 0x7f8792e5f000
> mmap(0x7f8792f70000, 454656, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 43, 0x1ab000) = 0x7f8792f70000
> mmap(0x7f8792fe0000, 57344, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 43, 0x21a000) = 0x7f8792fe0000
> mmap(0x7f8792fee000, 10432, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f8792fee000
> close(43)                               = 0
> mprotect(0x7f8792fe0000, 45056, PROT_READ) = 0
> mprotect(0x7f8793e6e000, 712704, PROT_READ) = 0
> mprotect(0x7f87941ed000, 4096, PROT_READ) = 0
> --- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPN, si_addr=0x7f879333933c} ---
> +++ killed by SIGILL (core dumped) +++
>

**Comment by dziudek** [comment]
It seems that native module used to generate thumbnails uses processor operations not supported by your processor :/

**Comment by Agliotto** [comment]
I've the same issue with a 'AMD Phenom(tm) II X4 955 Processor', and Debian Trixie. I will test Publii with an Intel i7 (quite old, 2012 I think), then probably I will give up testing Publii: it's frustrating to have to think to the CPU instruction set each time you're running something...
