### ISSUE TITLE
[Bug]: .htpasswd file is not being synchronised

### ISSUE THREAD

**Issue by BestNickName** [GetPublii/Publii#1565]
### Operating system

Linux Debian Bookworm

### Publii version

0.45.2 (build 16609)

### Post editor

None

### Bug description

I added a .htaccess and a .htpasswd file to the root directory via the file manager.
![Bildschirmfoto-vom-2024-07-03-12-46-03](https://github.com/GetPublii/Publii/assets/107303380/f4e5ac0b-7919-4c37-9acf-d2c75faf0588)

During synchronization (ftps), only the .htaccess is transferred to the server. The .htpasswd file also does not appear in the Publii log file.
It’s not due to the FTP server. When I access the server via an FTP client using the same credentials (ftps, host, port, account/password), I can transfer a .htpasswd file without any problems.
Therefore, I assume it is due to the Publii synchronization routine.

### Steps to reproduce

Add a .htaccess and a .htpasswd file with the filemanager and try to upload it via ftps to a ftp-server.

**Comment by bttrx** [comment]
This is also discussed in #1798.
