### ISSUE TITLE
[SORRY, no Bug report] After update to 0.46.0 window title bar has gone

### ISSUE THREAD

**Issue by mave-git** [GetPublii/Publii#1612]
### Discussed in https://github.com/GetPublii/Publii/discussions/1609

<div type='discussions-op-text'>

<sup>Originally posted by **mave-git** August 16, 2024</sup>
### Operating system

Ubuntu 22.04

### Publii version

0.46.0 (build 16889)

### Issue type

Application

### Bug description

After update to 0.46.0 window title bar has gone.
![Bildschirmfoto vom 2024-08-16 08-14-59](https://github.com/user-attachments/assets/afbc3eef-0776-4ee5-ae67-98e726ed6a2b)

### Relevant log output

_No response_</div>

**Comment by mave-git** [comment]
Sorry, now I see title bar / menu ist inside Gnome Panel. That's Gnome 3, not fine, because many other application don't use this "feature", needing ALT / SUPER-KEY + Space gives the window menu doing things like resize or using mouse. Not my way, reason to quit Gnome ...

**Comment by bobmitro** [comment]
Hey, 

I've just uploaded a new version ([build 16890](https://getpublii.com/download/)) that should fix the issue with the top bar. Please update the app and let us know if the problem is resolved.

**Comment by mave-git** [comment]
Hi bobmitro,

top bar is back again. Thanks!

**Comment by mave-git** [comment]
Hello bibmitro,

top bar is lost again (Version: 0.46.1 / build 16918, Ubuntu 24.04.1 LTS) ;-(
Regards

**Comment by dziudek** [comment]
@mave-git - that's weird, because we didn't make any changes in this aspect since build 16890: https://github.com/GetPublii/Publii/commit/079438fe53b7cc72e23ebc7e66c7422c3a443e1e
