### ISSUE TITLE
[Bug]: Hero image not shown. 0.46.0; Simple 3.0.0.0.

### ISSUE THREAD

**Issue by danielrpfeiffer** [GetPublii/Publii#1628]
### Operating system

Linux. Appimage

### Publii version

 0.46.0 (build 16910)

### Post editor

WYSIWYG editor

### Bug description

Hero image not shown. Simple 3.0.0.0.

### Steps to reproduce

Hero image gone after upgrading from 0.45.2 (build 16609) (Linux, Appimage).
Deleting hero-image and re-enabling did not help. Tried several file formats jpg, png.
Tested only in preview.

**Comment by dziudek** [comment]
@danielrpfeiffer - could you better describe your case? What do you mean by "hero image gone"? 

I have tested AppImage and I have put SVG as hero image - it works fine in preview.

The image is visible under theme settings? Do you have similiar problem with other images like featured image?

Did you tried to switch image processing engine to jimp under App settings?

**Comment by danielrpfeiffer** [comment]
The old site used the previous simple theme without any modifications. The site had a hero image set up in the theme settings. The hero image was always shown at the top below the menu, overlayed by the post name. 
Opening the existing site, using the latest Linux Appimage and the latest theme simple v3, does not present me the hero image anymore at the top of post pages. Newly created posts and pages also don't show the hero. 

For testing, I created a new site and only set the hero in the theme settings for the simple theme v3.0.0.0. The image is shown but not at the top of a post or page. Instead, the image I set as hero in the theme settings shows up like a featured image under the header/page name.

I would like to continue working on my existing site, taking advantage of the new features of publii and the simple theme v3. To me it looks like a theme incompatibility.
Sorry, I'm not a web developer. I'm rather a user of the target group.

**Comment by bobmitro** [comment]
The Simple v  features a new design, which you can see when watching the site demo. If you prefer to keep your current design, it's best to stick with Simple v2 and manually incorporate the updates from the latest Publii release. You can find all the details in the latest Publii release note here: https://getpublii.com/blog/release-046.html

Based on your initial description, it appears that the image does not work completely. Please provide specific details next time, as this will help to identify the issue accurately.

**Comment by danielrpfeiffer** [comment]
I get the point with the design change. I will use v2 and modify it.

However, I don't know how to be more specific regarding the main point. Switching from V2.8.3.0 to 3.0.0.0 made my hero image disappear. Even deleting it and setting it again did not make it show up again.

**Comment by bobmitro** [comment]
> The image is shown but not at the top of a post or page. Instead, the image I set as hero in the theme settings shows up like a featured image under the header/page name.

From your second description, it seems the image does appear, just not in the same place as before (simple v.2). This is why I concluded that the issue is more related to design rather than the image not appearing at all. 

As for the images, I can't reproduce the issue in any way. The hero image options were also not changed in Simple v.3, so the image uploaded earlier should stay visible after updating to v.3.

**Comment by danielrpfeiffer** [comment]
Thanks for your quick reply. I guess I found the reason for this (and other) issues.
The sqlite db seems to be corrupted.

**Comment by Kakunas** [comment]
I think i have the same problem. In the attachements i have a picture of what @danielrpfeiffer means and what problem i also have ;) the right picture in the screenshot ist the old version v2.8.3.0 and left the new V3.0
Additionally the Hero Image dissapear when i go away from the startpage to a blog post without any additional header image

<img width="1880" alt="Screenshot 2024-08-23 145353" src="https://github.com/user-attachments/assets/1bcf9300-ce7a-4cf8-b31a-a6e63e416915">

**Comment by bobmitro** [comment]
> I think i have the same problem...

The hero image works as it should; the difference is in the design of versions 2 and 3. It's not that the image doesn't display; it just appears in a different location. If you don't want to use v.3, you can still download v.2 (check the theme's changelog for the download link).

v.2 live demo: https://demo.getpublii.eu/themes/simple/v2/
v.3 live dmoe: https://demo.getpublii.eu/themes/simple/v3/

PS: Please read the release notes more carefully: https://getpublii.com/blog/release-046.html – everything is explained there.

**Comment by danielrpfeiffer** [comment]
I managed to add the pages' functionality to the 2.8 according to the documentation.
However, manual backporting functionality feels a bit like riding a dying horse. .. and considering the target user group, it's not appreciated.
 
Having an officially supported and updated V2.8 would be much better. V3 in my eyes, is a different template rather than a successor to the 2.8. Calling it V3 is confusing. I bought some templates from the marketplace, but none convinced me like the V2.8. I'm open to paying for a supported 2.8, rather than tinkering with the code.
