### ISSUE TITLE
[Feature Request]: [Mono theme. Make newsletter heading and description fields that can be user modified.

### ISSUE THREAD

**Issue by bjazmoore** [GetPublii/Publii#1667]
### Feature Description

Currently those two elements (newsletter and newsletterDesc) are defined in the mono.lang.json.

![4](https://github.com/user-attachments/assets/c94a8a20-c32a-4f5b-8a6a-9fbea15fafbb)

Yes they can be changed there, but that makes it hard to use this theme for clients who will not know how to modify a json file should the theme be updated.

Please move these two fields to the config.json so that they are in the theme settings and modify the theme file partials/sidebar.hbs as needed. Other files may need modified - I am not sure.

**Comment by bjazmoore** [comment]
Here is a modified theme: 

[mono 2.0.2.0.zip](https://github.com/user-attachments/files/16882333/mono.2.0.2.0.zip)

**Comment by bobmitro** [comment]
Not related to the app.
