### ISSUE TITLE
desktop language in spanish?

### ISSUE THREAD

**Issue by avocadoras** [GetPublii/Publii#167]
Is there a plan to have the desktop app in Spanish? if it is possible now, can someone point me to a way to enable this? cannot locate it on settings

**Comment by dziudek** [comment]
Hi @avocadoras ,

At this moment it is not possible - I do hope that in the next year we will allow preparation of the app translations. But implementation is a big task so at this moment I cannot provide you any ETA :(

**Comment by avocadoras** [comment]
@dziudek thanks for your response. No worries. Let me know if you need help translating. Or let me know how I can help with that if possible.

**Comment by YoavRheims** [comment]
@avocadoras - have a look to the [roadmap](https://getpublii.com/roadmap/).

**Comment by bobmitro** [comment]
More details: #628
