### ISSUE TITLE
[Bug]: Link to homepage in menu generates wrong url

### ISSUE THREAD

**Issue by Valgard** [GetPublii/Publii#1676]
### Operating system

macOS 14.6.1

### Publii version

0.46.1 (0.46.1)

### Post editor

None

### Bug description

I have created a home page link in my main menu. But when I click on the link on the generated page, I always get `404 NOT FOUND`. When I click on the site title, I get the home page.
I have compared the two links. The website link is `/index.html` and the menu link is `/startpage/index.html`.

### Steps to reproduce

1. Create a Page
2. Enable `Site settings -> SEO -> Homepage -> Set page as homepage` and select the page under `Select page`
3. Create a menu and assign it as `Main Menu` (`Max level` -> `-1`)
4. Create a menu item under the created menu as type `Page link` and select the page as `Page`
5. Click `Preview your changes` button
6. Clicking the link produces 404 NOT FOUND

**Comment by bjazmoore** [comment]
I can confirm that this happens.  If you just want to make a link that goes back to the home page then use the link "Homepage link" which works great.  All other pages also link fine as page links.

**Comment by dziudek** [comment]
Hi @Valgard @bjazmoore 

yes it is a bug, we have a code to detect page as a homepage in frontpage menu links, but for pages there is no similiar code so if somebody sets a page link to a page which is a homepage will retrieve invalid URL. I will fix it in the next release (v.0.46.2 or v.0.47 depending from founded issues priority)
