### ISSUE TITLE
[Feature Request]: Gallery Enhancement - Images span rows & columns

### ISSUE THREAD

**Issue by bjazmoore** [GetPublii/Publii#1679]
### Feature Description

Photoswipe has the ability to set some images to span multiple rows and columns.  It would be neat if Publii could support that.  Maybe an option to span 2x rows/columns for any format that is 2 columns or more.  I imagine it like this:
![1](https://github.com/user-attachments/assets/3daa1b28-464a-4146-8b8c-e36cec68b303)
![2](https://github.com/user-attachments/assets/154c6665-bae1-4e60-89a7-9150d2cfaff5)

Images are pretty rough as I just quickly mocked them up.

**Comment by bobmitro** [comment]
This should be implemented in your theme, not the app. These are stylistic matters that should be handled by the theme.

**Comment by bjazmoore** [comment]
Thank you Bob.  I will look into that.  I am closing this request.
