### ISSUE TITLE
[Feature Request]: Support "Use relative URLS" and setting a website URL

### ISSUE THREAD

**Issue by johnobrien** [GetPublii/Publii#1690]
### Feature Description

Some of the features (like the "Visit your website" button after synchronizing your site) don't work unless a website URL is set in Server settings, but server settings doesn't support setting both a website URL and using relative URLs. I'd like to be able to use relative urls, so that the links on the site are relative, and also set the website URL, so features like the "Visit your website" button work properly.

**Comment by bjazmoore** [comment]
What is the benefit you see from using relative URL's?  The note for using relative URL's says: "while using relative URLs, some features like Open Graph tags, sitemaps, RSS feeds, JSON feeds etc. will be disabled."  That sitemap is pretty important if you plan to have your website added to the search console.  
Please explain the use case.

**Comment by johnobrien** [comment]
Upon further reflection, I guess I don't really need it. I'll close the ticket.
