### ISSUE TITLE
[Feature Request]: Footnote rendering with content from Markdown editor

### ISSUE THREAD

**Issue by phranck** [GetPublii/Publii#1703]
### Feature Description

When editing content using the Markdown editor, footnotes with `[^1]` won't render correctly. The source text is displayed instead of the correct footnotes.

**Comment by bjazmoore** [comment]
Shouldn't this have been opened as a bug then?

**Comment by dziudek** [comment]
Footnotes are not a part of standard markdown syntax. Maybe it is a topic for consideration as a plugin. We have no plans for such feature in core as it is quite niche feature
