### ISSUE TITLE
[Feature Request]: Pre-connect to server while syncing

### ISSUE THREAD

**Issue by s3nnet** [GetPublii/Publii#1705]
### Feature Description

There is a very notable delay (at least with Netlify) while syncing the site before uploading (connecting to server).
How about pre-connecting the server while building the site providing for a seemless transition from building to uploading?

**Comment by bjazmoore** [comment]
Pre-connecting would let Publii know if it is worth compiling the site also - but, the connection can go away between the beginning to the process until the first transfer needs to be made, so there would need to be some more complicated code to make sure the connection was still up - this is what connecting when needed eliminates.  Six of one and half a dozen of anther I suppose.

**Comment by dziudek** [comment]
We have no plans to do it. It would be hard to specify when to start pre-connecting during rendering process and avoid situation when connection is closed due inactivity.
