### ISSUE TITLE
[Feature Request]: Contact form?

### ISSUE THREAD

**Issue by Thatoo** [GetPublii/Publii#1712]
### Feature Description

Hello,

I couldn't find any way to create a contact form? Is it in the roadmap or does a plugin exist?

**Comment by bjazmoore** [comment]
Contact forms require a back-end to process the form.  This probably would have been a question better ask in the discussion forum.  There are many third-party form processors from Netlify who will do minimal form processing for free - read their documentation to some big names like 

Here are some other links to help you out: https://medium.com/datafire-io/simple-backends-four-ways-to-implement-a-contact-us-form-on-a-static-website-10fc430984a4
https://dev.to/darnocer/quickly-configure-a-contact-form-on-a-static-site-4d14

I went with integrating JotForm.com when I wanted to do this as they have a nice script that drops right into place and they offer the minimal requirements for free.

Hope that helps

**Comment by dziudek** [comment]
This is out of scope of Publii and should be handled by 3rd party service
