### ISSUE TITLE
[Feature Request]: Provide a checkbox for a project's commercial use

### ISSUE THREAD

**Issue by s3nnet** [GetPublii/Publii#1713]
### Feature Description

This one is inspired by #1710.
Commercial use limits the scope of suitable licenses for (Featured) Images. Therefore, there should IMHO be a simple checkbox providing that piece of important information in the site settings, so that Publii can properly react to this fact, e.g. in the context of a built-in downloader for libre images, fonts being used, themes, and generally all licence-encumbered material.

**Comment by dziudek** [comment]
I do not get the idea of adding any separate UI for handling such things and we won't implement such changes. The only issue to solve which I see is to use `{{{ x }}}` for featured image credits instead of `{{ x }}` so links will work also for WYSIWYG editor with featured images
