### ISSUE TITLE
headlesscms.org

### ISSUE THREAD

**Issue by noraj** [GetPublii/Publii#172]
I created a PR on headlesscms https://github.com/netlify/headlesscms.org/pull/112 in order to add Publii to the site. You may want to review and complete it.

**Comment by dziudek** [comment]
Hi,

We are listed under https://www.staticgen.com/ which is a similar service of the same authors. I am not sure if we can be listed under both listings.

**Comment by dziudek** [comment]
I am closing this issue as Publii is now listed on headlesscms.org :)
