### ISSUE TITLE
S3 upload errors not handled correctly

### ISSUE THREAD

**Issue by gkcgautam** [GetPublii/Publii#173]
I was trying to deploy a website to S3 and noticed few issues:

***putObject fails silently***
Errors returned in `putObject` are [suppressed](https://github.com/GetPublii/Publii/blob/4c9723e5ee8f2c930fbd635844cd6f8bd77bc671/app/back-end/modules/deploy/s3.js#L267) and never displayed in the UI.
The progress bar keeps on increasing even if the uploads are failing.

***Missing class properties***
`softUploadErrors` and `hardUploadErrors` variables have been used to track errors in callback of `putObject`, but these are not initialised in the constructor. The upload gets stuck due to this.

***Fixes***
The first issue was caused due to a missing Permission in AWS. The docs do not mention the permissions needed to deploy websites to S3.

While I fixed the second issue by adding the below code in constructor, these variables are not really being used anywhere right now for displaying the errors:
```
this.softUploadErrors = {};
this.hardUploadErrors = [];
```

**Comment by gkcgautam** [comment]
I wanted to create a PR for adding the permissions in the S3 docs, but I couldn't the repository for the website.

**Comment by dziudek** [comment]
Hi,

I will add this issue for the next release. Regarding the documentation - it is not stored on the repository as it is a Publii website which uses SQLite database. If you want to add something to the documentation - feel free write to us - we will update it.
