### ISSUE TITLE
Cache headers for S3 objects

### ISSUE THREAD

**Issue by gkcgautam** [GetPublii/Publii#174]
Right now Publii does not support for adding cache related headers in S3 bucket objects. This leads to few issues:

- Browser needs to request all `assets` and `media` files even if they are available in the browser cache due to the lack of `Cache-Control` header in the response. Browser uses the local cache only after getting a 304 response. 
- No control over the caching of HTML and AMP files in Cloudfront due to the missing `Cache-Control` header. Cloudfront cache needs to be invalidated every time any post content is updated. 

**Solution**
- Set long duration cache headers for assets and media files
- Set `Cache-Control no-cache, no-store` for files that need not be cached.

I'm open to discussing the solution and contributing in the implementation.

**Comment by dziudek** [comment]
Hi,

Thank you for the feedback - I will add this issue for the next release.
