### ISSUE TITLE
[Bug]: Colours for links and links when hovered are reversed in the Simple Theme

### ISSUE THREAD

**Issue by jamescoward** [GetPublii/Publii#1740]
### Operating system

MacOS Monterey 12.6.7

### Publii version

Version 0.46.1 (0.46.1)

### Post editor

None

### Bug description

Links on a Page use the incorrect color variables for the base and :hover states in the Simple Theme.

Link when not hovering uses the `--link-color-hover` variable
<img width="353" alt="Screenshot 2024-10-06 at 19 24 46" src="https://github.com/user-attachments/assets/208b9caf-56de-41fc-b2d7-b993ed4eabf1">

Link when hovering uses the `--link-color` variable
<img width="351" alt="Screenshot 2024-10-06 at 19 24 57" src="https://github.com/user-attachments/assets/a28c77bc-4528-429a-8323-75ea63fe58d9">

I couldn't a GitHub repo for the theme, otherwise I would have made a PR myself.

Thanks!

### Steps to reproduce

Create a Page with a link when using the Simple theme.

**Comment by bobmitro** [comment]
It's ok, just look how it works.

**Comment by jamescoward** [comment]
Possibly I am misunderstanding but it seems like it is not correct.

In the video, the links in the body are red when they are not `:hover`d and then black when `:hover`'d

But the reverse is true for links elsewhere, i.e. in the footer.

If this is the intended behaviour then apologies for raising the issue. 


https://github.com/user-attachments/assets/64a189d6-8be7-49b4-9639-8a590e0e5704
