### ISSUE TITLE
[Bug]: artiicle schema missing time zone

### ISSUE THREAD

**Issue by raramuridesign** [GetPublii/Publii#1746]
### Operating system

n/a

### Publii version

n/a

### Post editor

None

### Bug description

When running a test on the article schema, the timezone of the article published and modified return a small issue. It is not critical, but would be great if the timezone could be returned. 

![image](https://github.com/user-attachments/assets/f13ce1f3-1c27-4fc2-a30c-941c03dd8f98)

So the json should look like this

`"datePublished": "2023-10-10T14:30:00+02:00",`

Would it be possible to add this? 
I am aware that the timezone is no-where to be found in the system... but perhaps it can be added?

M

**Comment by dziudek** [comment]
@raramuridesign - it is fixed in v.0.46.2 planned for the next week: https://github.com/GetPublii/Publii/commit/947b31dde3b74e4fed71363141a609ba0dd6bc42
