### ISSUE TITLE
[Bug]: og:url pointing to an invalid url

### ISSUE THREAD

**Issue by SEGwrites** [GetPublii/Publii#1767]
### Operating system

macOS 15.0.1

### Publii version

Version 0.46.1

### Post editor

WYSIWYG editor

### Bug description

When I share my homepage website link (https://segwrites.com/) through the iOS share sheet, the url is going to a non-existent page (https://segwrites.com/project). This appears to be because the header in the HTML has an “og:url” pointing to this invalid url instead of the homepage.

Note: I use the "/project" url in place of the blog/post option, but it points to the 404 error page.

Thank you, Sara
<img width="1280" alt="Screenshot 2024-10-20 at 7 16 23 PM" src="https://github.com/user-attachments/assets/a3a7ed7d-a9a7-4de4-bc19-7a1ab6fe8363">
<img width="1280" alt="Screenshot 2024-10-20 at 7 16 47 PM" src="https://github.com/user-attachments/assets/3b4469fc-3474-4d97-a43d-bd7d53fe3e0f">

### Steps to reproduce

Provided above

**Comment by dziudek** [comment]
Hi,

First of all - you have something messed up with your theme - your homepage contains double `<!DOCTYPE html>` and also two opening `<head>` tags. I suppose that it is more important to fix. og:url now looks correct - did you fixed it manually?

I see the issue on my test page too - og:url points to the blog listing if page is used as homepage. I will fix it in v.0.46.2 planned for the next week

**Comment by dziudek** [comment]
Problem with `og:url` and `canonical` (it has been also affected) will be solved in upcoming v.0.46.2

**Comment by Enichan** [comment]
Is this really fixed in 0.46.2? Because I'm on that version and having this problem. I posted this bug report before someone found and linked me to this issue https://github.com/GetPublii/Publii/discussions/1820

**Comment by dziudek** [comment]
@Enichan - for me it is working properly - homepage set as a page returns root directory of website instead of page slug
