### ISSUE TITLE
Don't delete the preview directory every time

### ISSUE THREAD

**Issue by thibault** [GetPublii/Publii#177]
Hi,

This is not an issue but a feature request.

Could it be possible to *not* delete the preview directory every time the site is rendered?

Here is the rationale between this request.

To preview the site in conditions as similar to production as possible, I use a small http server to locally serve the "preview" directory.

 - Generate site preview from Publii
 - Open a shell
 - cd path/to/my/Publii/site/preview
 - python3 -m http.server

Which gives me:

> Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/)

Then I can browse `http://localhost:8000` and preview my site with the same urls as the production settings.

Now, the problem is that every time the preview is rendered, the `preview` directory is deleted (not just emptied) and recreated, which means the running http server returns 404 and has to be manually stopped and restarted. It would be very convenient if the directory was just emptied, that way I could just go to my browser and press F5 to see my changes.

I think the problems lies here:

https://github.com/GetPublii/Publii/blob/4c9723e5ee8f2c930fbd635844cd6f8bd77bc671/app/back-end/modules/render-html/renderer.js#L253-L259

This method could be rewritten like this:

```javascript
emptyOutputDir() {
    fs.emptyDirSync(this.outputDir);
}
```

Would you be willing to accept this change?

**Comment by dziudek** [comment]
Hi,

This change makes a sens in your case. I have merged it, but now I see that I should make few improvements. But it will be definitely included in the next release :)
