### ISSUE TITLE
Cannot access custom excerpt when "hide custom excerpt on post pages" is checked

### ISSUE THREAD

**Issue by thibault** [GetPublii/Publii#180]
Hi,

I have a problem with the "excerpt" feature. In my post template, I want to split the top of the post (the excerpt) with the rest.

That's because my template looks like this:

```html
…
{{#post}}
<article class="post">
    <header>
        <div class="container">
            <h1>{{title}}</h1>
            <div>{{{excerpt}}}</div>
        </div>
    </header>

    <div class="container">
        {{{text}}}
    </div>
</article>
{{/post}}
…
```

The problem with this is that the top of the post is repeated when i call the `{{{text}}}` tag.

If a check the "Hide custom excerpts on post pages", then the custom excerpt is removed from the `{{{text}}}` tag, *but* the excerpts value becomes wrong. Instead of containing the content above the "read more" separator, it is re-generated and contains the few characters of the content below the separator.

How can I get the excerpt and the rest of the post in separeted values?

I also enclosed a PR showing how I fixed it for me, but I'm not sure I understand the purpose of the "hide custom excerpt on post pages" setting correctly.

**Comment by dziudek** [comment]
Hi,

Thank you for your PR - it looks correct so I have merged it into Publii code :)
