### ISSUE TITLE
[Bug]: Unable to Add Featured Image

### ISSUE THREAD

**Issue by kernja** [GetPublii/Publii#1810]
### Operating system

Windows 11

### Publii version

0.46.2 (16968)

### Post editor

None

### Bug description

It is not possible to add featured images to a post or page if the `/input/media/posts` folder does not exist. After selecting a photo, the progress spinner will loop endlessly.

If a `/input/media/posts` folder does not exist, one should be created automatically by Publii. The empty `/input/media/posts` folder was likely not created when cloning the Publii project from a GitHub repository.

### Steps to reproduce

1. In Windows Explorer, delete the `/input/media/posts` folder so that only `/input/media` exists.
2. In Publii, try adding a featured image to a post or page.
3. Progress spinner spins endlessly.

### Steps to manually remediate

1. In Windows Explorer, create an empty `/posts` folder in `/input/media`
2. In Publii, try adding a featured image to a post or page
3. Featured image gets added

### Relevant log output

```shell
No logs, but was able to identify problem and solution with steps created above.
```

**Comment by dziudek** [comment]
@kernja - it looks like an edge-case, because under normal conditions you should always have this folder. Anyway I have added recursive creation of folders in many places now, and it solves your issue. Fix will be in v.0.46.3

**Comment by kernja** [comment]
@dziudek, thank you for the update! 

To provide more context on what caused this edge-case, we are version-controlling the website data via git. I was able to add an image in Publii on my original machine, but after pulling down the code from git on a second machine, was no longer able to add images. It's because git does not version control or automatically create empty folders. :)

**Comment by ckyakr** [comment]
I am unable to add a Featured image, but can add images into the post itself. (Publii v 0.46.3 build 17009 on Windows 10 Pro, using Persona v2.1.0.0 theme)

**Comment by 2artisans** [comment]
I'm having this issue even WITH a "posts" folder existing.

**Comment by zomgs** [comment]
Unable to upload Featured image, and logo as well. 

That is Publii creates the folder structure and adds the uploaded image, but it does not go on to create the responsive images.

Running on latest v0.46.3

**Comment by s3nnet** [comment]
Same here. Adding a Featured Image has become a process that never ends, no matter the image format.
Interestingly, it occured out of the blue with an unchanged copy of Publii 0.46.2 Appimage and still wouldn't disappear after installing 0.46.4 from AUR.
So, I guess it might be some weird corner case that came true.

**Comment by s3nnet** [comment]
Also, the regenerate-errors.log shows this:

(process:19268): GLib-CRITICAL **: 20:56:53.930: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

(process:19268): GLib-CRITICAL **: 20:56:54.179: g_datalist_id_set_data_full: assertion 'key_id > 0' failed

Manjaro latest. Issue started to appear yesterday.
