### ISSUE TITLE
[Feature Request]: Add description and other information to each website listed in the website chooser interface.

### ISSUE THREAD

**Issue by bjazmoore** [GetPublii/Publii#1831]
### Feature Description

It would be nice to be able to add a description to each website listed in the website chooser interface.  Maybe an icon with an "i" and a circle around it could expose the details and allow editing of the description.  Show the description below each website name.

![shot_241129_123924](https://github.com/user-attachments/assets/06b35af7-ea9a-46be-826b-a89bf6fcaa66)

**Comment by dziudek** [comment]
@bjazmoore - will be added in v.0.46.3 :)
