### ISSUE TITLE
[Bug]: Preview not opening browser

### ISSUE THREAD

**Issue by noxidsoft** [GetPublii/Publii#1860]
### Operating system

Ubuntu 24.04.1 LTS

### Publii version

Version: 0.46.2 (build 16966)

### Post editor

None

### Bug description

Click "Preview your changes" and it cycles as per usual, but doesn't open a browser window. I use Firefox as default.

Deploys to remote server just fine 👍🏻 

### Steps to reproduce

![image](https://github.com/user-attachments/assets/3f6fafa0-46f6-4167-8699-c18d1f474c8b)

### Relevant log output

```shell
rendering-errors.log
(node:66347) Warning: No such label 'BLOG PAGINATION' for console.timeEnd()
(Use `Publii --trace-warnings ...` to show where the warning was created)

rendering-process.log
CONFIG: 14.783ms
FEATURED TAG IMAGES - QUERY: 14.21ms
FEATURED TAG IMAGES - STORE: 0.003ms
TAGS POST COUNT - QUERY: 2.307ms
TAGS POST COUNT - STORE: 0.008ms
MAINTAGS - QUERY: 0.755ms
TAGS - QUERY: 0.211ms
TAGS - STORE: 0.011ms
FEATURED AUTHOR IMAGES - QUERY: 0.344ms
FEATURED AUTHOR IMAGES - STORE: 0.005ms
AUTHORS POST COUNT - QUERY: 0.215ms
AUTHORS POST COUNT - STORE: 0.002ms
AUTHORS - QUERY: 0.227ms
AUTHORS - STORE: 1.1ms
FEATURED POST IMAGES - QUERY: 0.362ms
FEATURED POST IMAGES - STORE: 0.002ms
FEATURED PAGE IMAGES - QUERY: 0.296ms
FEATURED PAGE IMAGES - STORE: 0.002ms
POST TAGS - QUERY: 0.28ms
POST TAGS - STORE: 0.002ms
POSTS - QUERY: 0.248ms
POSTS - STORE: 0.007ms
PAGES - QUERY: 0.353ms
PAGES - STORE: 0.007ms
CONTENT DATA: 24.857ms
COMMON DATA: 3.34ms
PARTIALS GENERATION: 1.053ms
HOMEPAGE: 78.028ms
POSTS: 0.511ms
PAGES: 0.278ms
TAGS: 0.251ms
TAGS-LIST: 2.792ms
AUTHORS: 0.566ms
404: 2.627ms
FEEDS: 7.678ms
CSS stats: 0.14787903951283643 (61570/72255)
CSS: 50.512ms
[OK] Deleted empty directory:  /home/nole/Documents/Publii/sites/councilwords/preview/media/authors
[OK] Deleted empty directory:  /home/nole/Documents/Publii/sites/councilwords/preview/media/files
[OK] Deleted empty directory:  /home/nole/Documents/Publii/sites/councilwords/preview/media/posts
[OK] Deleted empty directory:  /home/nole/Documents/Publii/sites/councilwords/preview/media/tags
[OK] Deleted empty directory:  /home/nole/Documents/Publii/sites/councilwords/preview/media/website
[OK] Deleted empty directory:  /home/nole/Documents/Publii/sites/councilwords/preview/media
FILES: 12.041ms
SITEMAP: 7.359ms
RENDERING: 211.883ms
```

**Comment by erdemklync** [comment]
I had the same issue. I changed the "Sites location" from the app settings menu, and now it's working.

**Comment by noxidsoft** [comment]
I just tried to change my Sites location also, as before, doesn't matter if I set back to default or send to another custom location, still not opening my default browser for preview. I'll keep trying and report back if I find a solution.

**Comment by noxidsoft** [comment]
Alrighty, this was an issue on my end, a bad default setting for *.html files. For some reason Thunderbird was the default opener, not sure how that slipped by with all my dev work, I do use a remote server after all.

I discovered after setting a custom `Preview` directory, then turning on dev tools for the button `Generate preview files`.
![image](https://github.com/user-attachments/assets/f68e3f1b-7046-4aea-9428-a2a514edfb29)

![image](https://github.com/user-attachments/assets/1ff63e09-3cc4-48d6-9073-66505a158c30)

So, if someone else has this issue on Ubuntu, Mint, etc triple check
![image](https://github.com/user-attachments/assets/6dba4195-8388-41a0-ad09-5d067713624a)

Conclusion: I'm a doofus

**Comment by noxidsoft** [comment]
You put me on the right track @erdemklync
