### ISSUE TITLE
[Feature Request]: Reduce or rearrange theme selector options

### ISSUE THREAD

**Issue by treelistener** [GetPublii/Publii#1882]
### Feature Description

 Themes are installed via system menu with 3 dots. In my understanding if I installe a theme there, a theme is installed in Publii. 
Under Site settings - _Current theme_ you could change your theme by "_SELECT Theme_ Listbox" selecting a already installed (3dots) theme out of three options: Use, Install&Use and Uninstall. Use means using an previously installed theme, but Install & Use and Uninstall does not make sense for regular users. I suggest a checkbox for install. But uninstall shoud be done by the system menu in 3dots IMHO.

**Comment by dziudek** [comment]
@treelistener - uninstall is regarding site not the app. That's why it is in this selector. Under three dots menu you manage themes available globally, while under site settings you manage themes for your specific website

**Comment by treelistener** [comment]
Ok, I see this two layers of theme install, from a multisite perspective then it makes sense, from a one site perspective it looks like a duplicated theme installation part. So I revise my feature request, its ok for now,
