### ISSUE TITLE
[Bug]: Copyright text can not be left blank (under Theme -> Footer)

### ISSUE THREAD

**Issue by IO101010** [GetPublii/Publii#1897]
### Operating system

macOS 15.2 (24C101)

### Publii version

0.46.2 (build 16967)

### Post editor

None

### Bug description

Under Theme -> Footer, I can change the text "Powered by Publii" to something else, even just a dot (.). But if I leave it blank (which is what I actually want), the "Powered by Publii" text returns again. 

The expected behaviour would be to show nothing if I've removed the text from Theme -> Footer. 

I'm viewing the site completely in preview mode so if there is a different behaviour for a deployed site I wouldn't know.

### Steps to reproduce

Go to Under Theme -> Footer and delete the text in the box. Save. Preview any page. The default text reappears despite the deletion.

**Comment by bobmitro** [comment]
It is intentional. Instead of resetting all theme settings, the user can reset only the needed field (usually containing an HTML structure) and start modifying it again. Fields with a set value, not a placeholder, behave this way.
