### ISSUE TITLE
[Bug]: Setting Homepage to Page also replaces blog index to that same page.

### ISSUE THREAD

**Issue by IO101010** [GetPublii/Publii#1898]
### Operating system

macOS 15.2

### Publii version

0.46.2 (build 16967)

### Post editor

None

### Bug description

I enabled "set page as homepage". It worked, but I lost my blog. I'm using the default theme - I haven't changed anything.

### Steps to reproduce

Create a menu entry set to "Posts index link". Preview confirms that it does display an index of posts.
Now go to Site settings -> Homepage. Check the box "Set page as homepage". Select a page.
Result: The homepage will now show the desired page, but if you click on the menu entry for the posts index link, it will take you to the same page as the homepage.

**Comment by bobmitro** [comment]
If the theme does not have a dedicated blog index template, it uses the index template for the blog posts page.

**Comment by mavgit1** [comment]
I was a new user of Publii and had the same issue. Setting a "post prefix" fixed it, as I then was able to user the "Post Index" page and add it to my menu.

But from a readability stanpoint it is reallly not clear as a first time user that that would be necessary...
