### ISSUE TITLE
[Feature request] 2 Logos for light and dark mode 

### ISSUE THREAD

**Issue by treelistener** [GetPublii/Publii#1920]
### Discussed in https://github.com/GetPublii/Publii/discussions/1919

Today its possible to include a logo in a premium theme, theme lignes in my case. Currently a user can switch between light/dark mode, thats supported with most themes. 

Fact: 
A logo upload is possible, but only set for the light mode. For the dark mode you cant upload a second logo, which supports also the dark mode (inverse colors or so). 

Request: 
Possibility to upload second logo and correct code loading while in dark mode.

**Comment by treelistener** [comment]
If you have a white background and a logo with a with a transparent background and with black typo in the designed logotext or wordmark in light mode, then as a consequence the logo and the text will not be visible in dark mode, because an uploaded logo is today prepared only for one of both modes., mostly light mode.

For the mode switching it is a must to upload a second logo, which supports the dark mode (inverse colors or so). And the correct code.
Thats missing currently.

**Comment by bobmitro** [comment]
We've closed this because posting the same thread in both issues and discussions can be considered spamming. Please keep the discussion to one place for a more efficient response.

**Comment by treelistener** [comment]
OK. I understand. My fault I wanted a feature request.
