### ISSUE TITLE
Feature request: Backup to GitHub on sync

### ISSUE THREAD

**Issue by Trost123** [GetPublii/Publii#199]
Wouldn't it be great if Publii could push the source (input folder) when you press sync?
This way I wouldn't have to worry about losing the source.
You could use a directory inside same branch where the build is pushed, or push to other branch.

**Comment by dziudek** [comment]
Hi,

In my opinion it is a bad idea as it will at least duplicate data transfer during sync. If you are afraid regarding your input source files, you can create backups in Publii or create a repository inside the input folder and store these data in the different repository.

Another disadvantage - this kind of mechanism will lead to leak of the potentially non-public data like draft post with notes or comments which shouldn't be seen by readers.

**Comment by Trost123** [comment]
I know I can run Dropbox and set Publii to backup my files to Dropbox\Google Drive. But I don't use those now and I'd prefer to avoid their tools running 24\7 on my PC just for my blog that I post once a month on :wink:
Pushing input manually is, well, tedious manual work.
I just thought that it would be cool if you could publish your site and not worry about your local source getting lost for whatever reason. (Like it works with any online blog)
Because right now if you lose the source - you can't add any new content AFAIK?
You're right about leaking, but I'm ok with that. Maybe add a warning when you turn on that feature and make it off by default?
As for data double - Git doesn't re-upload unchanged files, right?

**Comment by dziudek** [comment]
> But I don't use those now and I'd prefer to avoid their tools running 24\7 on my PC just for my blog that I post once a month on 😉

> Pushing input manually is, well, tedious manual work.

It would be a problematic manual work, if you are updating your blog 5 times per day ;) In your case - in my opinion it is not a problem to backup one folder.

> Because right now if you lose the source - you can't add any new content AFAIK?

If you lose the source you cannot easily add new content, but you still have HTML files which can be changed and edited by code editor.

To be honest - you should have a daily backup of your disk - if your computer or disk will be damaged - you will lose all of your data. And the daily backup solves a problem with losing website data too.

> You're right about leaking, but I'm ok with that. Maybe add a warning when you turn on that feature and make it off by default?

It can cause many implications in the future - at this moment it is only access to draft post, but in the future it can be connected with more critical data. And then this feature will be very problematic to handle. Please remember that we must to look not only for today but also for the future features.

> As for data double - Git doesn't re-upload unchanged files, right?

Yes, but still - when you add a new post with images, you have to upload it to two locations on the git repository, also the SQLite database can be a quite big file on bigger websites and must be synced every time as it is a binary file.

In my opinion this kind of feature is useful in some limited cases. At this moment we have no plans to implement it. But I will leave this issue open for discussion and other users requests.

**Comment by dzmitry-lahoda** [comment]
@dziudek , I am choosing CMS for my wife site (lahoda dot bio). As of now i have to ask her to do 2 steps:
1. Publish changes via Publii.
2. Open Github for Windows and publish changes for backup.

Any ideas to simplify this to one button? What if second step has conflicts with my changes?

I am choosing solution for my relatives sites, and having one button solution is important for them.

**Comment by Trost123** [comment]
> @dziudek , I am choosing CMS for my wife site (lahoda dot bio). As of now i have to ask her to do 2 steps:
> 
> 1. Publish changes via Publii.
> 2. Open Github for Windows and publish changes for backup.
> 
> Any ideas to simplify this to one button? What if second step has conflicts with my changes?
> 
> I am choosing solution for my relatives sites, and having one button solution is important for them.

@dzmitry-lahoda For less tech-savvy users I'd avoid Publii. Take a loot at [Google Pages](https://sites.google.com/), [Wordpress.org](https://wordpress.org/), [Blogger](https://www.blogger.com/) or something like that.
I have nothing against this tool, but IMO those solutions are a better for a simple personal web page.

**Comment by dzmitry-lahoda** [comment]
```cmd
mkdir .temp
curl  https://cdn.getpublii.com/Publii-0.33.3.exe -o .temp/publii.exe
.temp/publii /silent
git lfs track input/db.sqlite
git lfs track input/media/*
```

```gitignore
.temp/
output/
preview/
```

`db.sqlite` and other `input` files has no tokens or passwords for simple setup for `gitlab`. but there are fields named such, so there is danger that in future they will appear here.
