### ISSUE TITLE
<title>title</title> in head.hbs does not honour SEO settings

### ISSUE THREAD

**Issue by pamtbaau** [GetPublii/Publii#213]
It seems that, contrary to meta description, that the <title>title</title> field in head.hbs does not make use of the SEO options in Settings, nor SEO options set in individual pages.

As a workaround, I have created the following helper:
```javascript
metaTitle: function (options) {
    if (options.data.root.metaRobotsRaw.indexOf('noindex') !== -1) {
        return '';
    }

    if (options.data.root.metaTitleRaw !== '') {
        return options.data.root.metaTitleRaw;
    }

    return '';
}
```
I then use the return value in `head.hbs`.

Because all themes I have examined use the same logic to add the <title> property, I wonder if I'm overlooking something...

**Comment by dziudek** [comment]
Hi,

Do you want to hide the page title when noindex is active for the specific page? Do you know that it will lead to an empty tab name?

**Comment by pamtbaau** [comment]
I have noticed that 'noindex' will skip the creation of meta properties and have switched it off. But even then, the page title is not generated properly. The following code I see in every theme does not generate a proper <title> using templates like `%pagetitle | %sitename` as defined in the SEO sections in 'Settings' and for every page.

Therefor I created the extra helper function.

**Comment by pamtbaau** [comment]
In `head.hbs` I use the bare title as fallback:
```
<title>{{#if (metaTitle)}}{{metaTitle}}{{else}}{{title}}{{/if}}</title>
```

Maybe i should move this logic into the helper...

**Comment by dziudek** [comment]
Hi again,

I am unable to reproduce your issue. I have set title for the frontpage to `My blog - %sitename` and then I have tested it with setting `Noindex website` enabled and disabled - I have got the same proper results. The same situation when I have used custom post page title.

**Comment by dziudek** [comment]
Even if I disabled indexation of the specific post I got a proper title - for custom title and title using schema defined under SEO settings.

**Comment by pamtbaau** [comment]
Then maybe I might have been doing something wrong... Will have a look at it asap and get back to you!

**Comment by pamtbaau** [comment]
Ouch, my bad... I hadn't noticed that a post object was being wrapped inside another object, which carries the proper formatted title... I though the post.title itself was replaced with the formatted title during rendering. 

I used the post itself inside the 'head.hbs'.

Thanks for your time!
