### ISSUE TITLE
Inject Handlebars into helper functions

### ISSUE THREAD

**Issue by pamtbaau** [GetPublii/Publii#214]
Helper functions and their usage could be improved quit a bit when the helper could make use of the Handlebar object to return safe html strings:
```
return new Handlebars.SafeString(output);
```

I've tried `require`-ing handlebars but to no avail.

**Comment by dziudek** [comment]
After applying changes from this commit: https://github.com/GetPublii/Publii/commit/e1af7b4d36111c7bd830028feebb1580bbc472b3

You can write the helpers in the following form:

```js
module.exports = function (Handlebars) {
	return {
	    functionName: function(arg) {
	        // ...
	        return new Handlebars.SafeString(arg);
	    }
	};
};
```

**Comment by pamtbaau** [comment]
Looks just great. Will try asap... Thank you very much!
