### ISSUE TITLE
Non destructive manual upload/non-compressed catalog on localhost

### ISSUE THREAD

**Issue by pamtbaau** [GetPublii/Publii#215]
During synchronisation using FTP or other means, the target folders are not cleared during sync. However when using manual upload with non-compressed catalog on localhost, the output folder does get cleared.

I would be nice, if this type of synchronisation behaves like the other options.

Rationale:
I have created a multi-lingual website and a nested structure of folders would be optimal. Eg. 
```
localhost/mydomain/
   assets/
   ..../
   index.html
   fr/ 
      assets/
      .../
      index.html
```
However, on each sync of the main language, all alternative languages will be deleted.

As a workaround I use sibling folders like:
```
localhost/mydomain/
  en/
     assets/
     ..../
     index.html
  fr/ 
     assets/
     .../
     index.html
```
This workaround requires a .htaccess for redirecting the main language pages to a sub-folder. When using FTP for synchronisation with the production server, nested folders can be used.

It would be nice if my  localhost could behave the  same as in production.

**Comment by dziudek** [comment]
Hi,

If I correctly understand - option to skip some predefined folders before removal during manual deployment output catalog clearing would solve your issue?

**Comment by dziudek** [comment]
On FTP problem does not exist, because Publii removes only files which was uploaded by the app and has been removed e.g. from the posts.

**Comment by dziudek** [comment]
I am closing this issue, because it looks like a niche feature, which can be solved by merging Publii manual deployment output with some additional necessary files for e.g. with use of some shell scripts after rendering a website.
