### ISSUE TITLE
npm install fails in /app

### ISSUE THREAD

**Issue by pamtbaau** [GetPublii/Publii#218]
Environment:
- Windows 10
- Installed all requirements

$ npm install 
&gt; finished without errors
$ cd /app
$ npm install
&gt; Error halfway:
c:\users\Me\documents\development\typescript\publii\app\node_modules\node-expat\node_modules\nan\nan_maybe_43_inl.h(112): error C2039: 'ForceSet': is
not a member of 'v8::Object' (compiling source file ..\node-expat.cc) [C:\Users\Me\Documents\Development\typescript\Publii\app\node_modules\node-expat
\build\node_expat.vcxproj]

&gt; Final error:
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Me\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Me\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Me\Documents\Development\typescript\Publii\app\node_modules\node-expat
gyp ERR! node -v v11.3.0
gyp ERR! node-gyp -v v3.8.0

**Comment by pamtbaau** [comment]
Tried it again:
- Fresh Windows 10 install (v. 1809)
- Install of nodejs with new included installation script installing all node-gyp dependencies.

`npm install` fails again in '/app'

**Comment by dziudek** [comment]
If you are using code from the branch 0.32-release then you should use node 10.* - maybe it will solve your issue.

**Comment by pamtbaau** [comment]
Darn, I'm using the latest node 11.4.0 as usual... Just notive Publii requires 8.*

Will give it a new try with node 8.*

**Comment by dziudek** [comment]
`master` uses node `8.*`, `0.32-release` uses node `10.*`
