### ISSUE TITLE
Rsync Support 

### ISSUE THREAD

**Issue by iedmrc** [GetPublii/Publii#219]
It would be nice if we could sync the `site directories` with a server just one click through rsync in addition to dropbox.

**Comment by dziudek** [comment]
Hi,

Do you think that a possibility of running a custom CLI commands instead of the default deployment process would be enough to fill your needs? I have considered a plugin for this kind of feature.

**Comment by iedmrc** [comment]
Hi,
I thought this 'rsync feature' for backing up and for collaborating with team - not for deployment. But It can also be used for deployment. As I see in issues, how to back up files and work collaboratively is a common concern. Rsync can be another alternative to this.
That's just an idea. Thanks your interest.

**Comment by jhf2442** [comment]
I'd like to request the rsync feature for deployment - a generic "run a deployment script" would also do the job

**Comment by dziudek** [comment]
Hi,

I have note this deployment method as a possible plugin in the future. As we want to release plugin support later this year, we won't add any new deployment methods to the Publii core - all new deployment methods will be developed as plugins.

**Comment by egrieco** [comment]
A plugin seems like overkill for simply calling a single shell script. If a pull request adding a post-build deploy script was submitted, would that have a chance of being merged or would it be rejected outright?
