### ISSUE TITLE
Can't sync. (An error occurred during connecting to server.)

### ISSUE THREAD

**Issue by Trost123** [GetPublii/Publii#222]
I press "Sync your website as usual", it connects and goes all the way up to "Uploading website (179 of 192 operations done)" and then it goes like this:
![](https://i.imgur.com/pl721eC.png)
Great. How do I debug\fix this?

**Comment by dziudek** [comment]
Please check deployment-errors.log and deployment-progress.log files under Tools -> Log Viewer

**Comment by Trost123** [comment]
deployment-errors.log is empty,
 deployment-progress.log
`(!) TRIED AGAIN FAIL
(api) => api.gitdata.createBlob
(!) TRIED AGAIN FAIL
(api) => api.gitdata.createBlob
(i) TRIED AGAIN
(api) => api.gitdata.createTree
(!) TRIED AGAIN FAIL
(api) => api.gitdata.createBlob
(i) TRIED AGAIN
(api) => api.gitdata.createBlob
(!) TRIED AGAIN FAIL
(api) => api.gitdata.createTree
{ [Error]
  message: '',
  code: 500,
  status: 'Internal Server Error',
  headers: 
   { server: 'GitHub.com',
     date: 'Tue, 11 Dec 2018 13:01:47 GMT',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '0',
     connection: 'close',
     status: '500 Internal Server Error',
     'x-ratelimit-limit': '5000',
     'x-ratelimit-remaining': '4815',
     'x-ratelimit-reset': '1544536885',
     'x-oauth-scopes': 'repo',
     'x-accepted-oauth-scopes': '',
     'x-github-media-type': 'github.v3; format=json',
     'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type',
     'access-control-allow-origin': '*',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'x-frame-options': 'deny',
     'x-content-type-options': 'nosniff',
     'x-xss-protection': '1; mode=block',
     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
     'content-security-policy': 'default-src \'none\'',
     'x-github-request-id': 'D44D:668D:D1CA90:1F0766F:5C0FB539' } }`
Always fails at "179 of 192 operations done"...

**Comment by dziudek** [comment]
It seems that Publii is unable to upload some file, could you provide your backup to check it? If you do not want to share it publicly - feel free to use ticksy and the private message: https://publii.ticksy.com/

**Comment by Trost123** [comment]
Sorry for the delay, been busy. Here you go:
https://www.dropbox.com/s/8uy2jfvi8v4j0y5/backup-12-30-2018-23-51-44.tar?dl=1
You can use https://trost123.github.io/ for reference, to rule-out the posts that didn't cause the issue.

**Comment by dziudek** [comment]
Hi @Trost123 - I have spend a lot of hours and finally I have found a reason of your issue (sorry that it take so long, but it was very complicated). The problem is caused by fact that currently Publii sends in parallel a lot of requests, which causes that in some cases some or even many of them returns an error and leads to creation of invalid tree data. What leads to your issue.

I have totally rewritten the github deploy method - now it works for me in my test website. I need to improve it in a few ways (e.g. make it working faster as now it is quite slow) and then I will include it in the upcoming Publii v.0.33 (which should be available in the next week).

**Comment by Trost123** [comment]
That's good news. I hope it was worth your time and my case will prevent future issues for other users, not just me. :sweat_smile:

**Comment by BarkBarklington** [comment]
> 
> 
> Hi @Trost123 - I have spend a lot of hours and finally I have found a reason of your issue (sorry that it take so long, but it was very complicated). The problem is caused by fact that currently Publii sends in parallel a lot of requests, which causes that in some cases some or even many of them returns an error and leads to creation of invalid tree data. What leads to your issue.
> 
> I have totally rewritten the github deploy method - now it works for me in my test website. I need to improve it in a few ways (e.g. make it working faster as now it is quite slow) and then I will include it in the upcoming Publii v.0.33 (which should be available in the next week).

I'm still receiving this error and I don't understand how to rectify, please can someone tell me what I need to do to resolve this issue, thank you!

**Comment by dziudek** [comment]
@BarkBarklington - please check your `deployment-progress.log` for more details. Maybe a reason of your issue is different.
