### ISSUE TITLE
Disable inline toolbar for some elements

### ISSUE THREAD

**Issue by dziudek** [GetPublii/Publii#224]
Disable inline toolbar for:

- images,
- galleries,
- TOC

**Comment by bobmitro** [comment]
Disabling an inline editor from links generated by TOC.
<img width="304" alt="screenshot 2018-12-15 o 08 09 46" src="https://user-images.githubusercontent.com/1391007/50040288-cf757880-0040-11e9-9fcb-5c22222008f8.png">
