### ISSUE TITLE
Allow field type wysiwyg for postConfig fields (postViewSettings)

### ISSUE THREAD

**Issue by osopolar** [GetPublii/Publii#235]
I want to extent post content with some additional fields to enable the editor to provide additional content to be shown in the sidebar. There are some hard-coded (`_core`) fields like `metaTitle` or `metaDesc` and there are dynamic fields provided via config.json (`postViewSettings`) like `displayAuthor`, `displayDate` etc. from type `select`. I want to add another field of type `wysiwyg` but that doesn't work. Using type textarea works, but without wysiwyg. Would it be posible to also allow wysiwyg there?

My field definitions in config.json look like:
```
"postConfig": [
    {
        "name": "sidebarContent",
        "label": "Sidebar content",
        "note": "Content for sidebar",
        "value": "",
        "type": "textarea"
    }
    ...
```

That works already, but I would like to use:
```
"postConfig": [
    {
        "name": "sidebarContent",
        "label": "Sidebar content",
        "note": "Content for sidebar",
        "value": "",
        "type": "wysiwyg"
    }
    ...
```

To output the field value I use the following code in sidebar.hbs:

```
{{#if @config.post.sidebarContent}}
    <section class="custom-content box">
        <h3>Custom content</h3>
        {{{@config.post.sidebarContent}}}
    </section>
{{/if}}
```

Is that the only way to add fields to posts, or is there something better?

**Comment by bobmitro** [comment]
What exactly do you mean by "Is there a way to make it appear at its own group on the post form?"

**Comment by osopolar** [comment]
Currently it is below "Other options", that's ok, but I would prefer to have it in it's own section:

<img width="210" alt="publii" src="https://user-images.githubusercontent.com/1523215/50224100-cacffd80-037b-11e9-8294-d90bb51906cb.png">

**Comment by bobmitro** [comment]
I'm afraid there is no easy way to have it as you described.  I think we can add this possibility in one of the future releases, but I cannot determine when exactly.

**Comment by osopolar** [comment]
Thanks @bobmitro, would be nice to see that too. Currently more important would be to enable wysiwyg field type.

It seems to me, that the only way to have additional fields is using the `postViewSettings` (postConfig). Is that the way how it should be used or is it more a hack and may not work in future?

**Comment by bobmitro** [comment]
All available post-config options can be found in our dev docs. https://getpublii.com/dev/post-config-options/
