### ISSUE TITLE
How do I move my website from one computer to another

### ISSUE THREAD

**Issue by jacoy** [GetPublii/Publii#244]
I want to move my website from one computer to another. What should I do？

**Comment by bobmitro** [comment]
Hi Jacoy,

You can do it in many ways:

1. create a backup of your website  (via Tools section) and  restore it on your second device
2. synchronize your website via cloud storage e.g. dropbox (https://getpublii.com/docs/publii-on-multiple-computers-via-dropbox.html)
3. move your sites directory to another device (Documents/Publii/sites/ )

**Comment by jacoy** [comment]
> Hi Jacoy,
> 
> You can do it in many ways:
> 
> 1. create a backup of your website  (via Tools section) and  restore it on your second device
> 2. synchronize your website via cloud storage e.g. dropbox (https://getpublii.com/docs/publii-on-multiple-computers-via-dropbox.html)
> 3. move your sites directory to another device (Documents/Publii/sites/ )

thank u
