### ISSUE TITLE
Add Support for Post Config work in Index or Tags Pages

### ISSUE THREAD

**Issue by Fluxtheme** [GetPublii/Publii#252]
I am a big fan of Publii CMS, but does the publii team have plans to add support for @config.post.* to work outside a single post, as in index or tags pages. Like _.Site.Params_ function on Hugo Generator.

Thanks for this great product.

**Comment by dziudek** [comment]
Hi,

It is impossible, because @config.post.* is different for every post. So it cannot be used on pages where there is more than one post. But you can try to use field `postViewConfig` of the post items. More details here: https://getpublii.com/dev/post-tags/
