### ISSUE TITLE
Error in Post Navigation links

### ISSUE THREAD

**Issue by IgiMar** [GetPublii/Publii#261]
Post Navigation should allow to provide 2 links,  a 'previous' one and  a 'next' one.
The choice of what is 'previous' and what is 'next' should logically reflect the 'Post Listing Options'.

I made a test site:
Added a post titled "First Post" ID 1
Added a post titled "Second Post" ID 2
Set: Settings > Posts Order by: Post ID
Set: Settings > Posts Ordering: Ascending.
Set: Theme > Post options > Display Post Navigation: enabled

What happen is:
the FIRST post shows a navigation link to the SECOND as: [ Previous Post - Second Post]
the SECOND post shows a navigation link to the FIRST as: [ Next Post - First Post]

It's illogical. I would have expect the contrary:
the FIRST post showing a navigation link to the SECOND as: [ NEXT Post - Second Post]
the SECOND post showing a navigation link to the FIRST as: [ PREVIOUS Post - First Post]

It seems like a 'descending' logic is hard coded. Whichever the criterion (ID? Date?)

**Comment by dziudek** [comment]
Hi,

Thank you for your feedback - it is a known issue and has been fixed here: https://github.com/GetPublii/Publii/issues/246 - the fix will be available in Publii 0.33.1 at the end of this month :)

**Comment by IgiMar** [comment]
Hello, just tried ver.033.
It seems like the issue hasn't been fixed.

**Comment by bobmitro** [comment]
Hi Igar,
Have you updated your theme to the new version?

**Comment by IgiMar** [comment]
Yes, sure. I also set a brand new test site with the same characteristics:
2 posts
order by ID
ascending order 
same behavior as before.

**Comment by bobmitro** [comment]
What theme do you use? (let me know the version too)

**Comment by IgiMar** [comment]
Simple 1.7

**Comment by bobmitro** [comment]
Look at the attached video, in my opinion, it works well; unless I do not understand the problem.

[video.zip](https://github.com/GetPublii/Publii/files/2861909/video.zip)

**Comment by IgiMar** [comment]
The video doesn't show the issue.
The issue is:
Navigation in PAGE 1 shows: Previous Post PAGE 2. It should be: Next Post PAGE 2
Navigation in PAGE 2 shows: Next Post PAGE 1. It should be: Previous Post PAGE 1

**Comment by bobmitro** [comment]
1. Posts order by: **ID** and Posts ordering: **Ascending**
The first-page show NEXT, second PREVIOUS 

2. Posts order by: **ID** and Posts ordering: **Descending**
The first-page show PREVIOUS, the second NEXT 

e.g. first-page post dated  2018; second page - with post 2019
So the button must point to the new post, so NEXT, not PREVIOUS.

**Comment by IgiMar** [comment]
Not at all. 
If your version does that, happy for you. The program I just downloaded does not. I t does what I described.
Ordering by ID must follow ID and NOT date. Right?

**Comment by bobmitro** [comment]
You are right, ID - my video exactly shows how it works with ID.

**Comment by bobmitro** [comment]
@IgiMar All I can think to do is ask you for a website backup; just send it via https://publii.ticksy.com/ I will check  it tomorrow morning.
