### ISSUE TITLE
Roadmap and project structure

### ISSUE THREAD

**Issue by Swader** [GetPublii/Publii#267]
I've been using Publii for a while - I run [Bruno.id](https://bruno.id), [Audithor.io](https://audithor.io) and [Valhello.app](https://valhello.app) on it.

I would like to support it when I can with:

1. Donations
2. Coding work

The main thing preventing me from 1) is the lack of a roadmap and clear mission from the team, as well as the inability to donate with crypto.

The main thing preventing me from 2) is a lack of contribution guidelines and examples in the form of technical guides and tutorials.

I believe putting both of those on the home page and in the repo would increase community engagement.

**Comment by bobmitro** [comment]
@Swader Thanks for your support and tips. The roadmap available to the public is a good idea but we have some concerns about it.  Having two years of experience, we know that often our plans change depending on the needs of our growing community. 

At this level of app development, we can not establish a rigid framework for the project. Also, we can not assign more working hours,  Publii is still an unprofitable project, and we have to work with other ones. If we can, one day, focus only on developing our app we will definitely set a stiff roadmap, and we will stick to it.

We would like to be more active, produce great devs materials like documentation, tutorials but the lack of time and money do not let us do it. It would be great if someone helped us in this matter.

I hope, this year will be better and let us focus more on app development.

Ps: nice websites.

**Comment by Swader** [comment]
> The roadmap available to the public is a good idea but we have some concerns about it. Having two years of experience, we know that often our plans change depending on the needs of our growing community.

Changing plans is fine as long as you're verbose about it. Make it known that you're changing something and the community will support you. At the same time you give your community insight into where they may be most helpful.

Can we get some more information about the team and working hours distribution? It helps to have a business plan / profit plan if you intend to make publii full time, and I think it's worth the effort. I'd like to help you out with all this as much as I can, but we (the general public) need more insight into the project's management and plans to be able to be useful there. Anyway, just consider making all the ins and outs of the project more public (management / finance / planning side), maybe it would do good.

> Ps: nice websites.

Thanks but I think the first mission is going to be learning how to properly update templates. I've got Audithor redesigned and waiting to be integrated, so as soon as I've _pro_ed that up, I'll be writing a tutorial for it. Publii definitely needs growth in the theme department, hope it'll encourage people to experiment.

**Comment by bobmitro** [comment]
Hi, 

I have just published a complete Publii's roadmap for 2019
https://getpublii.com/find-out-whats-on-publiis-roadmap-for-2019/
