### ISSUE TITLE
Support for Plugins/Extensions

### ISSUE THREAD

**Issue by iedmrc** [GetPublii/Publii#269]
Hi all,
It would be great if we could extend Publii with plugins/extensions, like vs code, atom etc..

**Comment by dziudek** [comment]
Hi,

Yes, it is in our plans - we will publish a roadmap probably in this week where this topic will be better covered :)

**Comment by bobmitro** [comment]
Hi, 

I have just published a complete Publii's roadmap for 2019
https://getpublii.com/find-out-whats-on-publiis-roadmap-for-2019/

**Comment by IanMayo** [comment]
Hello @bobmitro ,
I see that plugins have now slopped to 2021.

I look forward to building on Publii, including adding the ability for authors to drop in a range of custom blocks of text.

Is any of the planning for plugins public?  I'd like to contribute to the process, potentially including giving developer feedback.
