### ISSUE TITLE
How to enable the relative URL?

### ISSUE THREAD

**Issue by gadgetraja** [GetPublii/Publii#271]
My client is migrating his/her site to netlify.

As of now, we were creating a static output of WordPress website with relative URL and base URL in the head. Netlify was working fine and was loading the static assets ( CSS, js, img, etc ) from the CloudFront CDN.

Now we finally developed a theme for publii because we wanted to use it. Now when we are uploading our site ( automatic or manual ) to netlify, CloudFront CDN is not working.

From our experiments, we can say that this is because of non-availability of relative URL.

Netlify isn't modifying the URL ( even when chosen under the post-processing ) if the HTML or site being uploaded has the absolute URL.

So, is there any way to make publii generate relative URL in the rendered HTML pages.

Thanks.

**Comment by dziudek** [comment]
Hi, at this moment it is not possible, but I will try to implement this feature in the next release till end of this month.

**Comment by dziudek** [comment]
There is #141 which better describes this issue so I will close this one as duplicate - feel free to follow the #141 issue.

**Comment by gadgetraja** [comment]
Thanks, We made the edit and now the CloudFront cdn is working.

We are willing to contribute generous donation if this feature set along with ability to choose custom cdn is added into Publii.

Eg. ability to choose custom cdn links ... assets.domain.com ( which will replace the links of all static assets like img, css, js, etc ).

Problem with cloudfront cdn is that their canonical tags don't point to specific asset file but instead to the domain itself.

Eg. cloudfront78126387.site912.com/assets/img1.png will point to domain.com instead of domain.com/assets/img1.png.

This can have serious implication on SEO.

And thanks for creating such a wonderful and feature-rich application.

**Comment by dziudek** [comment]
@gadgetraja - could you better explain your cdn requirements? Do you need relative paths, but for assets do you want to use specific domains? I think it is not heavy to implement but I need bigger picture of these requirements.

**Comment by dziudek** [comment]
@gadgetraja - thank you for the explanation - I will create a separate issue for the CDN thing :)
