### ISSUE TITLE
File manager display NaN (not a number) for filesizes after upload

### ISSUE THREAD

**Issue by drm-wntd** [GetPublii/Publii#275]
Hi and thanks for the great work on Publii!

Here's a small bug I found : 

In the file manager, if I add files with the «Upload files» button, after the files are uploaded, all the files listed show «NaN undefined» for filesize. If then, I go back to the Tools menu and back to the File manager, the filesize are displayed correctly.

Using the linux version v.0.32.4 (build 11275) Beta. (running the appimage)

![publii_nan](https://user-images.githubusercontent.com/2616375/51203591-d578a680-18d7-11e9-9585-93993b5e50dc.jpg)

**Comment by dziudek** [comment]
Hi again,

I have checked this issue with dev build and also with the latest AppImage build on Ubuntu and I still cannot reproduce this issue. I suppose that it is a specific linux distribution/configuration issue. As it is not critical (file manager shows proper values after refresh) I think it is not worth to further investigate this issue as it seems to be a non-critical glitch limited to a small range of installations.
