### ISSUE TITLE
Bug in editor when mixing <pre> element with following <p> text

### ISSUE THREAD

**Issue by dullroar** [GetPublii/Publii#280]
I am seeing lots of problems with `<pre>` blocks in the editor (v.0.32.4 (build 11275) Beta). Here is one consistently reproducible. If there is a long `<pre>` block followed by a normal `<p>`, the `<p>` block will display in the editor on top of and in the middle of the `<pre>` block. Note that when published the HTML actually displays correctly - this is strictly bad behavior within the editor itself.

Example HTML to show problem:

```html
<pre>This is some pre-formatted code.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.<br>This is some more.</pre>
<p> </p>
<p>This is some final text.</p>
```
Attached is image of how it renders in editor.
![screenshot from 2019-01-21 09-10-52](https://user-images.githubusercontent.com/3743601/51482624-8bbb1080-1d5c-11e9-95af-e94c7de3536d.png)
Also note how the `<pre>` block loses its gray shading halfway down. Also seeing other issues with things like consistently creating new lines (`<br>`) while typing in `<pre>` blocks, cursor keys being mistaken/acting like cut keystrokes, etc. Will probably file separate bugs for those once I can describe them exactly.

**Comment by dullroar** [comment]
Great! Any time frame of when 0.33.1-release will be available for download? For what I am working on taking the time to set up a dev environment to build it myself would feel like yak shaving.

**Comment by dullroar** [comment]
I backed up and then hacked `/opt/Publii/resources/app/dist/css/editor.css` and that seems to have done the trick for me for now.

**Comment by bobmitro** [comment]
You can also override the main **editor.css** file via Publii theme (assets/css/editor.css)

**Comment by dullroar** [comment]
Thought of that, but I wanted it "fixed fixed," and not just per-theme or per-site-instance fixed. I figure the above will work until 0.33.x gets officially released. I do like that there is the capability for per-site/per-theme CSS overrides, though!
