### ISSUE TITLE
Date picker shows 00 for noon by default when in 12-hour mode

### ISSUE THREAD

**Issue by dullroar** [GetPublii/Publii#283]
Steps to reproduce:
1. Work on a Publii post between 12:00pm and 12:59pm.
2. Choose *Set custom post date*.
The hour in the time will default to "00", even though the AM/PM indicator is set to "PM".
![datepicker](https://user-images.githubusercontent.com/3743601/51492581-f7f73d80-1d77-11e9-847f-5280e9ede869.png)

**Comment by dziudek** [comment]
Hi,

We know about this issue and it has been fixed at today's morning: https://github.com/GetPublii/Publii/issues/276 

Till new release, please temporary use 24-hours mode - you can change it under application settings (under three dots menu in the top right corner).
