### ISSUE TITLE
Feature request: load existing website made with publii from github pages

### ISSUE THREAD

**Issue by vchrizz** [GetPublii/Publii#287]
I couldn't find a possibility to import or in any way load an existing website which was previously created with publii.
From the docs I didnt find a way to do that, or am I missing some point?
Created the website on my notebook and sometimes want to edit further on my desktop but for this I would need to hold the files on them both in sync, what I dont want to do manually as we have git(hub) for that ;)

If this is not possible at the moment, this "issue" should serve as a feature-request.

**Comment by dziudek** [comment]
Hi,

At this moment the only way to have websites in sync between different computers is to use shared location like Dropbox or Google Drive to store website files - you can specify on Publii settings where to store the website files.

**Comment by dziudek** [comment]
(clearing the backlog)
