### ISSUE TITLE
[proposal] S3 Custom Config

### ISSUE THREAD

**Issue by jodumont** [GetPublii/Publii#290]
Hi;

I would like to publish my Publii via a S3 compatible host [Exoscale](https://www.exoscale.com/object-storage/)
it would be very nice if it was simply possible to have a custom S3 Destination Server so I'll be able to publish it directly via Publii instead of manually transferring it ;)

After that; this feature would be also usable to publish at [RackSpace](https://www.rackspace.com/cloud/files) and other Object Storage

**Comment by dziudek** [comment]
Hi,

I afraid that it will be more complicated. Currently the used S3 API uses region name to specify the destination: https://github.com/GetPublii/Publii/blob/master/app/back-end/modules/deploy/s3.js#L44

So I suppose that your solution won't work with the AWS.S3 API.

**Comment by jodumont** [comment]
it might help you

I'm trully not an AWS and S3 expert

but this is my .aws

_cat ~/.aws/config_ 

```
[aws-stockholm]
region = eu-north-1

[aws-frankfurt]
region = eu-central-1

[exoscale-frankfurt]
region = de-fra-1
```

than I have a script

`aws s3 --profile exoscale --endpoint-url https://sos-de-fra-1.exo.io sync public/ s3://$BUCKET --delete --acl "public-read"`

**Comment by dziudek** [comment]
I have checked the AWS.S3 npm module code and unfortunately it seems that they do not support custom URLs for the API :(

**Comment by jodumont** [comment]
fair enough, thanks for your research :)
