### ISSUE TITLE
Error on sync with Publii 0.33

### ISSUE THREAD

**Issue by gvagenas** [GetPublii/Publii#302]
Hi,

I updated to Publii 0.33 and now trying to sync the website I get an exception `A Javascript error occurred in the main process". 

See attached screenshot 
<img width="1451" alt="screenshot 2019-02-14 at 10 15 30" src="https://user-images.githubusercontent.com/588875/52772702-dd944500-3041-11e9-854e-7772e586dd67.png">

This is a Netlify connected site and connection is ok.

Any hints? 
Thanks
George

**Comment by dziudek** [comment]
Hi,

I will look at this and I will try to fix it today in 0.33.1 release as we have found few other minor issues in the 0.33.

**Comment by gvagenas** [comment]
Great, thanks

**Comment by dziudek** [comment]
Could you provide me a backup of your website? The issue is not connected with the deployment, but with fact that some errors occurs during the website rendering process.

**Comment by dziudek** [comment]
I have added a fix for the error message, but you will still get an error regarding the failed rendering process.

**Comment by gvagenas** [comment]
You will find the backup of the site here https://we.tl/t-GFREoI4lCb @dziudek 

Thanks

**Comment by dziudek** [comment]
Your problem is fixed in this issue: https://github.com/GetPublii/Publii/issues/306

It seems that it is caused by author who has no posts. We will publish v.0.33.1 tonight with this fix :)

**Comment by gvagenas** [comment]
Great, thanks !!!
