### ISSUE TITLE
YoastSEO.js

### ISSUE THREAD

**Issue by JOduMonT** [GetPublii/Publii#315]
apparently it is possible to [integrate yoast on different platform](https://yoast.com/yoast-seo-platforms/your-platform/)

While I'm reading : You can install [YoastSEO.js](https://github.com/Yoast/yoastseo.js) using npm:

`npm install yoastseo`

it seams pretty easy for me, but I'm bearly using NodeJS without headache, so

**Comment by dziudek** [comment]
As the mentioned library seems to be archived, I am closing this task
