### ISSUE TITLE
TOC expectation

### ISSUE THREAD

**Issue by JOduMonT** [GetPublii/Publii#316]
Hi;

It would be nice if the TOC didn't expect a H3 after a H4 or expect H2 after a H3, ...

### in the editor
![image](https://user-images.githubusercontent.com/5204724/52905982-40a0fa00-3243-11e9-92d2-d0a8d1dc3a8b.png)

### via the navigator
![image](https://user-images.githubusercontent.com/5204724/52906015-c15ff600-3243-11e9-94f6-9d86ec9c309d.png)

## Now
2.3. Cloudflare : the cache machine `H3`
2.3.1 Alternative `H4`
2.4. _which is nothing and disappear if I change Alternative in H3_
3. Before you go `H2`

## Expected
2.3. Cloudflare : the cache machine `H3`
2.3.1 Alternative `H4`
3. Before you go `H2`

**Comment by dziudek** [comment]
I suppose that it will be solved by #429

**Comment by jodumont** [comment]
hopefully, but I'm not using Publii right now

**Comment by dziudek** [comment]
Ok, but please don't close this issue as it seems to be a more general problem and this issue will be a reminder to check the problem after closing #429 :)

**Comment by dziudek** [comment]
It seems that even on the newest TinyMCE 5.1.5 this issue occurs :/
