### ISSUE TITLE
Embedding YouTube URL with timestamp is broken

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#318]
If you insert a YouTube video in an article, the timestamp of the video's URL (`&t=123`) is removed. In general, all GET parameters are deleted.

For example
https://youtu.be/<video_id>?list=<list_id>&t=<timestamp>

becomes

https://www.youtube.com/embed/<video_id>

Not sure but maybe it even breaks No-Cookie-YouTube-URLs.

**Comment by GiantCrocodile** [comment]
Any chance to see this in next release (0.34) @dziudek?

**Comment by dziudek** [comment]
The issue is caused by current version of TinyMCE, so in fact it now depends from #429

**Comment by dziudek** [comment]
Solved thanks to #429 changes
