### ISSUE TITLE
Display no author > author is still shown in source code

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#323]
If you decide to show no author names, the author name is still shown in the source code of the page, although it's not visible on the website.

**Comment by bobmitro** [comment]
Let me know the example of the situation described by you.

**Comment by GiantCrocodile** [comment]
I disabled 'Display author name' for a specific post and for the whole theme.

Regardless of that, I see two JSON objects in the source code. The following one should have been deleted, I think:
```
{
   "@context":"http://schema.org",
   "@type":"Article",
   "mainEntityOfPage":{
      "@type":"WebPage",
      "@id":"file://<path to my article's html file>"
   },
   "headline":"test",
   "datePublished":"2019-02-18T20:07",
   "dateModified":"2019-02-18T20:07",
   "description":"test",
   "author":{
      "@type":"Person",
      "name":"example"
   },
   "publisher":{
      "@type":"Organization",
      "name":"example"
   }
}
```
