### ISSUE TITLE
About Publii - add missing information

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#324]
1. What/who is Dev Zen?
2. What about Electron and privacy policy of it?
3. Privacy policy in general (like what do you/used third party libs collect, etc.)

This should be added for legal and transparency reasons.

PS: Clicking on any of the links make them highlighted in the same color as ordinary text. It's afterwards impossible to see which word is a link and which isn't.

**Comment by bobmitro** [comment]
HI,
Publii does not collect any personal user data, so the privacy policy is not needed.
The licenses of third-party libraries used by our app are listed within the About section (Open Source Software)
