### ISSUE TITLE
add support link to main menu

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#325]
Beside help and report an issue, there should be a link to get support (free and paid).
Same with docs: user docs and developer docs should be linked.

Both as items of a submenu.

**Comment by GiantCrocodile** [comment]
Any reason why this was closed @bobmitro? Not sure if I'm mistaken because I overlooked something relevant here.

**Comment by internettips** [comment]
"Help" already goes to documentation (https://getpublii.com/docs/).

"Report an Issue" goes to support (https://publii.ticksy.com).

So maybe that's why it was closed.
