### ISSUE TITLE
insert video/image: embedd or download and insert

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#334]
Right now, images are downloaded and videos are embedded. I suggest an user choice on this:

Depending on the content you are talking about, it is totally legal to download and embed your own copy of the source (image/video) in your site. I think this is something that should be supported. For example if I write an article about an image or some video, I don't want to see this file being offline. Thus I would like to set a checkbox (embed/upload) and Publii just downloads the source and inserts it in my post. This makes sure that I have a meaningful article even after 10 years where the original source is offline.

**Comment by dziudek** [comment]
Sorry, but I am not sure if this kind of behaviour is legal as you think in all possible countries. Additionally it is hard to implement and in my opinion it is a totally niche feature, which according to the potential legal complications sounds like something we wont implement.
