### ISSUE TITLE
'Remove styles' broken in editor

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#335]
I typed the word 'abcd' in the post's editor and made it italic and bold. Furthermore I set the paragraph style to 'Code'. None of these changes has been undone by 'Remove styles' feature. I did select the appropriate text but it didn't matter.

**Comment by dziudek** [comment]
The "Remove styles" function removes only the styles from the same dropdown - If you have added "success" style, it will remove the success style but it will leave the text formatting inside the "success" block. 

I have added the missing clear formatting button to the editor for that purpose:

![screenshot 2019-03-05 at 12 46 22](https://user-images.githubusercontent.com/22004/53803407-f14a1180-3f44-11e9-892f-70c251a34928.png)

**Comment by dziudek** [comment]
I have also removed the duplicated clear formatting button and I have moved it before HTML, because it was hard to find earlier.
