### ISSUE TITLE
Allow context menu in Publii

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#336]
Sometimes you wanna copy a string from the UI (for example to do a bug report) and it's annoying to be not able to copy a string via context menu. Non techy people or people who have temporary no chance to use the keyboard may wanna do the same but don't know about their OS' shortcut for copying or are not able to bec there is no copy via context menu at all (and thus no mouse support).

**Comment by bobmitro** [comment]
Copying the content of labels is disabled,; you can copy the content of the option description (notes).
