### ISSUE TITLE
Add empty index.html files to directories

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#337]
Most people don't wanna have someone browsing through their site's internals bec. there are empty index.html files missing for each subdir.

**Comment by dziudek** [comment]
It can be fixed by a proper server configuration or by `-Indexes` in the `.htaccess` file. There is no sense to drastically increase amount of files to upload to fix such thing, which should be solved on a server level.

**Comment by GiantCrocodile** [comment]
Maybe we should provide a basic .htaccess file with Publii @dziudek?

**Comment by dziudek** [comment]
It is useless:
1) many servers are not based on Apache (nginx)
2) if your hosting does not disable directory listings by default - change it to a more secure one ;)

**Comment by internettips** [comment]
@GiantCrocodile said:
> Most people don't wanna have someone browsing through their site's internals bec. there are empty index.html files missing for each subdir.

Here's a solution.

Using empty / blank index.html files isn't really needed today. 

Instead, you can just create a .htaccess file that includes some code to stop people:

- (a) reading your .htaccess file, and ... 

- (b) scanning your website folders.

For example, if your web hosting server is using Apache, maybe the following entries in your .htaccess file would meet the goals above, without you needing to create any empty index.html files :

`<Files .htaccess>`
`order allow,deny`
`deny from all`
`</Files>`

`## Turn on no permission to view directory listings -- BEGIN`
`IndexIgnore *`

`Options -Indexes`

`## No directory listings -- END`
