### ISSUE TITLE
Add mouse listener/link to search field icon

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#344]
You have to press ENTER in the search field to search for your relevant term. It should be possible to click on the search icon of the search field to trigger a search, as like as ENTER.

**Comment by dziudek** [comment]
What is a sense to press enter, if the search works directly while typing phrase on the collections in the Publii UI?

**Comment by GiantCrocodile** [comment]
I'm not sure if we talk about the same thing. I think I did explain it not enough. I talk about search fields like these in the themes like Technews:
![grafik](https://user-images.githubusercontent.com/6271057/53201628-c991aa00-3624-11e9-996a-3124a885af3e.png)

It is not possible to click this icon and I think the search is not working while typing, although I didn't test it because I have no search configured.

**Comment by dziudek** [comment]
You should mention that you wrote about the themes :) 

Publii has search fields too, that's why I have been surprised :)

**Comment by GiantCrocodile** [comment]
I'm sorry for the confusion and I appreciate your support!

**Comment by bobmitro** [comment]
It's very normal behavior, to enter search entry you have to use a keyboard so what a problem to use an ENTER key?

**Comment by GiantCrocodile** [comment]
The icon looks like the user can interact with it, otherwise it doesn't provide much value. If you are too lazy to use your keyboard (simply because t's too far away. you just copy and pasted something via mouse or if it's currently unavailable) or if you are on a mobile phone, it's handy to click on the icon. Of course this depends on the users way of interacting but in general it doesn't hurt to add it. It may be even beneficial for disabled site visitors.
