### ISSUE TITLE
Add info why Live Preview is disabled

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#346]
The client offers zero feedback why the Live Preview is disabled. New users may stumble why it's disabled. It wasn't obvious to me what this button will cause and that it is linked to the sync to some remote server.

**Comment by dziudek** [comment]
The "Live preview" button has a tooltip, and it is enought for that in my opinion.

**Comment by GiantCrocodile** [comment]
Nevermind, I didn't see the tooltip - maybe I didn't wait long enough or just clicked it at a bad timing in the past.
