### ISSUE TITLE
No logging for client crashes

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#347]
When there is an internal error in the client, and this results in some stack trace displayed to the user, there is no logging for this. There should be another log file, just for those cases because right now it's never logged and it's not related to rendering, deployment or connection issues.

This request is related to the issue #319 where I'm unable to provide further information because I forgot to take a screenshot and it's lost after closing the client.

**Comment by dziudek** [comment]
v.0.35.1 should minimalize this issue: https://github.com/GetPublii/Publii/issues/523
