### ISSUE TITLE
Test connection shouldn't trigger save settings

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#349]
Right now the Test Connection feature triggers a Save Settings. This is not desired because a non-working test could override a saved working connection.

**Comment by dziudek** [comment]
We have changed this behaviour to the current one, due fact that many users forgot to save settings after the test. And at this moment we have no plans to change it.

**Comment by GiantCrocodile** [comment]
Maybe it should be saved only when it was a successful test @dziudek?

**Comment by dziudek** [comment]
Good point :)
