### ISSUE TITLE
Remove site is not working - crash

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#350]
I entered the correct site name (like displayed in the dialog) and it produces this crash:
![grafik](https://user-images.githubusercontent.com/6271057/53210099-e89c3600-363c-11e9-8484-b4a228fa0526.png)

**Comment by dziudek** [comment]
I have tested it on macOS - it is working fine. It is possible that some query did not closed correctly. In the next version I will add an additional check for that case.

**Comment by GiantCrocodile** [comment]
@dziudek I just failed with pasting a screenshot. Does your repository support deleting an issue? I would repost it with stack trace.

**Comment by dziudek** [comment]
I got the image on my e-mail and it is also visible in the issue now ;)

**Comment by GiantCrocodile** [comment]
The point was that I forgot to redact the local username in the screenshot, although it's a not too bad mistake (useless information anyway).
