### ISSUE TITLE
Restoring a backup causing problems

### ISSUE THREAD

**Issue by Swuap1** [GetPublii/Publii#359]
I have all my articles backed up but can't restore anything because of updating to the latest publii weeks ago now caused me to lose all my articles!

It won't let me restore my backups, none of them and I have over 5 from various timelines, yet I can't restore crap! Same issue as this guy https://github.com/GetPublii/Publii/issues/341

How do I retrieve my text??

**Comment by dziudek** [comment]
Hi,

How you have lost your articles? Are you sure that it is a new publii release related?
Could you share one of your backup files?

**Comment by Swuap1** [comment]
My Gitlab site crashed and my articles are not found there anymore. This problem started with the first February release.

I updated to version 0.33.3 11538 on windows and this problem still happens.

http://s000.tinyupload.com/index.php?file_id=18467376393635039392

Can't upload here, "We don't support that file type"

**Comment by dziudek** [comment]
Did you send me a proper backup of your website? The date suggest that you have did it 2 days ago, but I see posts from 2 hours ago - test1/2/3 on the posts listing after unpacking it.

**Comment by Swuap1** [comment]
It's that one. I sent you that because even that one I can't restore, the simplest backup. I have been testing various methods to see why it's not restoring, thinking due to size or corruption from the February Publii update.

**Comment by dziudek** [comment]
Please check if the following procedure helps you to restore your website:

1. Please rename your current website directory to e.g. myblog-backup and move it to your desktop
2. Unpack the backup which you want to restore and rename the unpacked catalog to your website directory name (in my examples - myblog).
3. Move the unpacked and renamed folder to the sites directory

**Comment by Swuap1** [comment]
Yes, it worked! Thank you very much!
