### ISSUE TITLE
Problem on AMP pages

### ISSUE THREAD

**Issue by FachrulCH** [GetPublii/Publii#360]
Hi, I've problem with AMP page, get email from google said:

> Search Console has identified that your site is affected by 2 new issues of type AMP.
> 
> Top Errors (5 maximum)
> 
> Errors can prevent your page or feature from appearing in Search results. The following errors were found on your site:
> 
> 1. AMP HTML Tag has an invalid layout specified by its attributes.
> 2. Disallowed tag present.
> We recommend that you learn more about these issues and fix them when possible to enable your site to have the best possible experience and coverage in Google Search.

Publii Configuration:
Version: macOS Mojave, Publii Version 0.33.3 
Theme: Simple (v.1.6.1.0)
Published on: Github Pages

**Comment by bobmitro** [comment]
Hi,
Try to use this tool https://validator.ampproject.org/ , it helps you identify any issue with your AMP pages. By default, the Simple theme passes the validation in the Structured Data Testing Tool very well.

**Comment by dziudek** [comment]
I am closing this issue due inactivity. Feel free to reopen it, if any new details will be available.
