### ISSUE TITLE
Add a global media gallery/source

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#364]
It would be nice to have a place where every used image/media is stored/accessible in the client. To make this useful, you should be able to select an image/media object from a global gallery. Thus you can easily reuse images or videos which are useful in different posts/sources.

This will save disk space and make it easier to post in certain situations.

**Comment by bobmitro** [comment]
HI,
We are working now on the brand new feature: file manager https://getpublii.com/roadmap/  
It will allow you to manage the pictures, files (e.g., pdf) or gallery from one place and share resources between different posts.
I hope it will be ready in April.

**Comment by GiantCrocodile** [comment]
Hello @bobmitro,

is it right that the feature does nothing yet? At least it shows media/files and root dir as empty. Will the file manager be somehow integrated in specific features of the editor?

**Comment by bobmitro** [comment]
All resources will be available and integrated with the post the editor, so you will be able to upload and insert any file into WYSIWYG editor.

**Comment by RLO1729** [comment]
I have some images that appear on many pages, sometimes individually and sometimes in galleries. If I update one of these images I need to reload it to each page. Could there be a file manager setting that allowed all uses of the image on a site to be updated when the image in file manager is updated? Or is there another way to do this more easily?
