### ISSUE TITLE
Vue JS directives support

### ISSUE THREAD

**Issue by tigrankhachikyan** [GetPublii/Publii#367]
I've tried to implement some basic VueJS functionality and it is worked very well. 

For example, according to Vue's documentation (https://vuejs.org/v2/guide/index.html), I've added the below script into Tools->Custom HTML->Head section. 
```
<script src="https://cdn.jsdelivr.net/npm/vue"></script>
```
And put this simple Vue logic into my post.
```
<div id="app">
  {{ message }}
</div>
<script>
var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!'
  }
})
</script>
```
After saving, this piece of code automatically converted to:
```
<div id="app">{{ message }}</div>
<script>// <![CDATA[
var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!'
  }
})
// ]]></script>
```

After rendering, the message was successfully rendered inside `{{ message }}`, so I was able to see the message 'Hello Vue!' in my post page. 

Now going forward, I've tried to add more advanced Vue' directives, like `v-if`, here it looks like we loose that directives during save. 
example: 
```
<div id="app">
  {{ message }}
  <p v-if="seen">Now you see me</p>
</div>
<script>
var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!',
    seen: true
  }
})
</script>
```
After saving, when I opened the editor again, my code become:
```
<div id="app">{{ message }}
<p>Now you see me</p>
</div>
<script>// <![CDATA[
var app = new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue!',
    seen: true
  }
})
// ]]></script>
```

So as you can see the `v-if` directive disappeared from the `<p>` tag. 

Wander if you can add the support for the Vue directives, as it can power a lot the way we can manipulate the post content. 

Thanks in advance!

**Comment by dziudek** [comment]
Hi @tigrankhachikyan,

This is a very specific use case and I am not sure if it is required to implement in Publii at this moment, but I have a solution for you - under `My Documents/Publii/config/` catalog you can create file `tinymce.override.json` and in this file you can put something like below:

```json
{
extended_valid_elements: "a[*],altGlyph[*],altGlyphDef[*],altGlyphItem[*],animate[*],animateColor[*],animateMotion[*],animateTransform[*],circle[*],clipPath[*],color-profile[*],cursor[*],defs[*],desc[*],discard[*],ellipse[*],feBlend[*],feColorMatrix[*],feComponentTransfer[*],feComposite[*],feConvolveMatrix[*],feDiffuseLighting[*],feDisplacementMap[*],feDistantLight[*],feDropShadow[*],feFlood[*],feFuncA[*],feFuncB[*],feFuncG[*],feFuncR[*],feGaussianBlur[*],feImage[*],feMerge[*],feMergeNode[*],feMorphology[*],feOffset[*],fePointLight[*],feSpecularLighting[*],feSpotLight[*],feTile[*],feTurbulence[*],filter[*],font[*],font-face[*],font-face-format[*],font-face-name[*],font-face-src[*],font-face-uri[*],foreignObject[*],g[*],glyph[*],glyphRef[*],hatch[*],hatchpath[*],hkern[*],iframe[*],image[*],line[*],linearGradient[*],marker[*],mask[*],mesh[*],meshgradient[*],meshpatch[*],meshrow[*],metadata[*],missing-glyph[*],mpath[*],path[*],pattern[*],polygon[*],polyline[*],radialGradient[*],rect[*],set[*],solidcolor[*],stop[*],style[*],svg[*],switch[*],symbol[*],text[*],textPath[*],title[*],tref[*],tspan[*],unknown[*],use[*],view[*],vkern[*],publii-amp,publii-non-amp,script[*],i[*],video[*],audio[*],source[*],stream[*],*[v-if],*[v-for],*[@click],*[v-bind],template"
}
```

As you can see I have added few Vue.js-related rules (for attributes and for the `<template>` tag), you should add all possible attributes.

Alternatively you can use:

```json
{
extended_valid_elements: "*[*]"
}
```

Then TinyMCE should won't modify your output (despite adding CDATA sections for scripts).

**Comment by tigrankhachikyan** [comment]
I see. Thank you very much for the workaround!

**Comment by 729902288** [comment]
config is noused for  Vue JS directives 
![image](https://github.com/user-attachments/assets/9968314f-7750-4bbb-94d3-39faab0de7f3)
