### ISSUE TITLE
[feature request] - Fullscreen editor

### ISSUE THREAD

**Issue by 6uhrmittag** [GetPublii/Publii#370]
What
It would be great to have either a fullscreen/distraction free view for the editor or at minimum a option to disable the sidebar.

Why
Unless I missed it, the current app doesn't provide a fullscreen editor. The "Post settings" sidebar can't be disabled. 
When I'm not at my desk, I only have a 12,5" 1366x768 - the "post settings" sidebar blocks almost 1/4 horizontally of the screen and the editor menu another 1/4 vertically... both are not needed for writing a post.
This makes it really hard to get the big picture of a post.

How
A fullscreen/distraction free view for the editor like the HTML-view or at minimum a option to disable/shrink the sidebar.

**Comment by dziudek** [comment]
Hi,

Thank you for the feedback. In fact on smaller screens the sidebar takes a lot of space of the post editor.

We will try to address this issue in the nearest releases.

**Comment by bobmitro** [comment]
Implemented. Now all the sidebars can be enabled/disabled.
