### ISSUE TITLE
Syncing with Amazon seems to not detect not changed files

### ISSUE THREAD

**Issue by c3s4** [GetPublii/Publii#377]
I configured the server section to allow Publii to upload website to Amazon S3 bucket, everything goes well but when I tried to sync again without any change, Publii uploaded every built file again.

I'm using the 0.33.4 version on a MacOS 10.14.1. If I can help with additional information please let me know.

**Comment by dziudek** [comment]
Hi,

Could you provide more details? What do you get during deployment? Are you sure that you did not applied any change? E.g. simple change of the footer text can affect all subpages.

**Comment by c3s4** [comment]
Hi, yes for sure!!
During the deployment simply I see the popup indicating the upload running (see screenshot).

![Schermata 2019-03-14 alle 11 27 28](https://user-images.githubusercontent.com/7916898/54350103-e8e08d80-464c-11e9-8dac-ae5897a5dda1.png)

I'm sure I did not change anything because I only clicked on the _Sync_ button just after previous sync proceses was finished.

If you need more information just ask, at the moment I'm not figuring out what kind of info I can give to help.

**Comment by dziudek** [comment]
Could you check if the files.publii.json file is on your destination bucket? This file is used to detect which files should be synced, and maybe due some problem this file hasn't been uploaded.

**Comment by c3s4** [comment]
You're right, this file is not present!
I also tryed to build the site locally but in the output directory the `files.publii.json` is absent.

**Comment by dziudek** [comment]
After resync the file is still absent?

**Comment by c3s4** [comment]
Yes, I synced many times to be sure but the `files.publii.json` is never uploaded and, I think, never generated.

**Comment by dziudek** [comment]
@c3s4 - thank you for your deeper investigation of this issue.

I suppose that the problem is related to the fact that the files.publii.json have other permissions than other files - it is set to `authenticated-read`: https://github.com/GetPublii/Publii/issues/62

I will check it and if it is a reason, I will provide a fix in the next release.

**Comment by c3s4** [comment]
Thank you

**Comment by dziudek** [comment]
Hi again,

I have checked this issue but for me the upload to s3 works correctly, the `files.publii.json` file is visible on the bucket and after resync I have only 2 operations to do (what is ok, as the timestamp is changed in RSS/JSON feeds during sync).

**Comment by c3s4** [comment]
Hi,

maybe is there something wrong in my bucket configuration? But every other file is uploaded correctly.
I'll check again everything.

**Comment by dziudek** [comment]
I have used a default bucket configuration.
The only thing which I have changed is the following flags:

<img width="762" alt="Screenshot 2019-03-22 at 11 22 10" src="https://user-images.githubusercontent.com/22004/54816591-f1604600-4c94-11e9-9aba-ee006d5c2278.png">

Maybe you have a policy which blocks access to the files with the ACL = `authenticated-read`?

**Comment by c3s4** [comment]
Hi,
yes my s3 bucket configuration is a little different specially concerning the ACL part. I'll try after a better understanding of what this implies regarding the bucket access.

I'm wondering about why the only file with access denied is the `files.publii.json`, every other file is uploaded with no problems

**Comment by dziudek** [comment]
I have explained it here: https://github.com/GetPublii/Publii/issues/377#issuecomment-474730444

**Comment by c3s4** [comment]
Hi, sorry for never giving you a feedback, I triied something just in these days.
I'm facing with the same problem. I changed permissions as in your screenshot, although the configuration in the bottom right is wrong to make your site publicly available, but nothing changed same error, again.

So I read again your documentation about S3 configuration and noticed that there are many things missing: nothing about your screenshot here and noting about Bucket Policy, needed to make your site publicly available. So I don't have any reference point to compare with and understand if there's something strange in my configuration.

Thanks

**Comment by dziudek** [comment]
@c3s4 - configuration used in documentation is just default S3 configuration, that's why it mentions only changes which are required to be done before publishing a website. In my free time I will review the documentation and bucket creation process as S3 changes their UI often and maybe some additional steps are required to be included in the docs.

**Comment by c3s4** [comment]
Thank you for your answer.
I tried everything again creating a new bucket following your guide step by step (when was possible because some steps at the moment are very very different) and now I figured out what's happing and I am bit scared of it.

In the step where you talk about how to create security credentials you are suggesting to create a root credentials pair that is very very dangerous and discourage by amazon itself. So I think there is some configuration needed to upload using IAM role (the aws suggested way) instead of root credentials.

Btw using root credentials the `files.publii.json` is uploaded as expected.

**Comment by dziudek** [comment]
The updated tutorial will be for sure based on the IAM roles - I had also problems to properly configure them, but I know good dev ops who should be able to solve this problem :) I will let you know when the updated tutorial will be ready - I do hope that it will be ready soon :)

**Comment by dziudek** [comment]
FYI - I have created an IAM group with `AmazonS3FullAccess`, policy:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": "*"
    }
  ]
}
```

I have also set permissions to the bucket as I mentioned in my comment: https://github.com/GetPublii/Publii/issues/377#issuecomment-475567334 and it seems that it is working and during second upload I got only 2 files to update instead of 47.
