### ISSUE TITLE
Technews theme broken regarding tags

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#379]
I'm using latest Publii version and theme version. This happens in Firefox.

![grafik](https://user-images.githubusercontent.com/6271057/54490455-2f84f080-48b6-11e9-9d9f-9ce754d1532d.png)

**Comment by bobmitro** [comment]
This theme requires featured images to have a great looking layout. If you do not want to use them, just disable tag on the front page or play with CSS to change its position.

**PS: this repo is dedicated to Publii app; to report any issue or get support for themes, please use https://publii.ticksy.com/**

**Comment by dziudek** [comment]
I am closing this issue due inactivity and due fact that it is not strictly related with Publii but with its theme.

**Comment by AlexHCC** [comment]
> **PS: this repo is dedicated to Publii app; to report any issue or get support for themes, please use https://publii.ticksy.com/**

Obviously the link is not working anymore. Where can I find the technews theme repo?

**Comment by bobmitro** [comment]
You can get a help on the community forum https://forum.getpublii.com/
