### ISSUE TITLE
Do not put blog on the main page, use a fixed post

### ISSUE THREAD

**Issue by wuniversales** [GetPublii/Publii#383]
I would like to have a hidden fixed post for my home website, and it is not possible for me, I do not know if it is an error.

**Comment by dziudek** [comment]
You can achieve it by custom modifications of the theme at this moment thanks to the use of the [{{getPost}} helper](https://getpublii.com/dev/getpost-helper/). Maybe in the future we will add a built-in option for that in our themes, but currently we have no ETA for that.
