### ISSUE TITLE
Add best support using "//"

### ISSUE THREAD

**Issue by wuniversales** [GetPublii/Publii#386]
Hello,
The idea is to add a new option that supports that type of url.
For example, if you are with my websites:
http://example.com/
https://example.com/
dat: //example.com/

Delete the absolute path so that it stays that way
//example.com/

This would add a lot of compatibility to publii

**Comment by wuniversales** [comment]
Now, apart from adding the option "//" you can also add the protocol "dat://" at the start of the url.

**Comment by dziudek** [comment]
Hi,

I have added dat://, ipfs:// and // as additional protocols.
