### ISSUE TITLE
Verification failed while extracting electron

### ISSUE THREAD

**Issue by juranki** [GetPublii/Publii#390]
Hi,

`npm install` on clean git clone gives this error

```
npm ERR! Verification failed while extracting electron@3.1.6:
npm ERR! sha512-Y1TbV5py2O0br0JVYh+ew1cW4cIOOgRNRMzwTwWuZNMZ9fK/XLlqsbZr1GpYHdiN2yIU1koO+g4Cw8VuW86NXQ== integrity checksum failed when using sha512: wanted sha512-Y1TbV5py2O0br0JVYh+ew1cW4cIOOgRNRMzwTwWuZNMZ9fK/XLlqsbZr1GpYHdiN2yIU1koO+g4Cw8VuW86NXQ== but got sha512-elEKKlFMnR0bhR/Uttk0TI496ZadxYsecyKgj2tZgrWx/F/anzfxbEYNcv134vT+qMFC/BXvoaeaIIj2YYdVuA==. (73284 bytes)

```

Looks like checksum was not updated when bumping electron to 3.1.6:
https://github.com/GetPublii/Publii/commit/a72b045b1c1e1570d7ef67d09e68f0f5899b0d91#diff-32607347f8126e6534ebc7ebaec4853dR2832

Removed invalid checksum from package-lock.json, ran `npm install` again.
Afterwards `git diff` looked like this

```
diff --git a/package-lock.json b/package-lock.json
index 16d5566..d49981f 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -2829,7 +2829,7 @@
     "electron": {
       "version": "3.1.6",
       "resolved": "https://registry.npmjs.org/electron/-/electron-3.1.6.tgz",
-      "integrity": "sha512-Y1TbV5py2O0br0JVYh+ew1cW4cIOOgRNRMzwTwWuZNMZ9fK/XLlqsbZr1GpYHdiN2yIU1koO+g4Cw8VuW86NXQ==",
+      "integrity": "sha512-elEKKlFMnR0bhR/Uttk0TI496ZadxYsecyKgj2tZgrWx/F/anzfxbEYNcv134vT+qMFC/BXvoaeaIIj2YYdVuA==",
       "requires": {
         "@types/node": "^8.0.24",
         "electron-download": "^4.1.0",
```

**Comment by dziudek** [comment]
Hi,

Thank you for your feedback - in the meantime I have updated electron to 3.1.7 so this issue will be solved: https://github.com/GetPublii/Publii/issues/392 :)

**Comment by lesatdgl** [comment]
Just cloned Publii; ran npm install - got failure as above on electron3.1.6 ; updated package.json - changed 4 occurences of 3.1.6 to 3.1.7 - ran OK
