### ISSUE TITLE
Relative URL not working, where is renderer.js?

### ISSUE THREAD

**Issue by sciita** [GetPublii/Publii#393]
I have to use relative path.

I followed this issue page: https://github.com/GetPublii/Publii/issues/141 and found the suggestion : https://github.com/GetPublii/Publii/commit/1dc2efb3344f090d87cc74b6906628e456e34b37#diff-d9881c828b537e8b79fb7f38c3f8570e

But after PUBLII update I noticed that there was no renderer.js in the installation dir.

So, where is this renderer.js or which file do I need to edit?

Best Regards.

**Comment by dziudek** [comment]
Hi,

Unfortunately at this moment all files are packed into *.asar file due performance reasons. Additionally the mentioned solution as I remember wasn't complete and there was problems/conflicts with it, that's why it is not implemented in Publii.

**Comment by dziudek** [comment]
Hi again @sciita,

What is your use case for the relative URLs?

I am asking, because as I see it is possible to do in Publii, but it will affect some elements like Open Graph, social sharing etc.

**Comment by sciita** [comment]
I don't care for open graph and social sharing.

I need relative URLs for CDN integration.

Without cdn my site takes 1.2 sec to load. With (warmed) cdn, 0.6 to 0.8 sec ( I don't like using lazy load ).

Anyhow, I unzipped the app.asar ( https://www.npmjs.com/package/asar ), made the changes to the renderer.js, packed it again and now things are working fine for me.

**Comment by dziudek** [comment]
@sciita  - are you using CDN for images/css/js assets or for the whole page?

For assets we have an issue: https://github.com/GetPublii/Publii/issues/274 and then issue with Open Graph and social sharing won't exist.
