### ISSUE TITLE
No "Share This:" on posts if zero Share Buttons active

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#395]
see title

**Comment by bobmitro** [comment]
Exactly,  it works this way. You did not provide a theme name, so I can not check any potential bug.
**PS: this repo is dedicated to Publii app; to report any issue or get support for themes, please use https://publii.ticksy.com/**

**Comment by GiantCrocodile** [comment]
This happens with QF (v.1.3.0.0) theme. Thanks for the hint regarding no support/bug report for themes via this repository. This wasn't obvious to me.
