### ISSUE TITLE
Allowing select the default post template

### ISSUE THREAD

**Issue by bobmitro** [GetPublii/Publii#396]
As in title; this option should be placed on the  **Post options** page.

**Comment by bobmitro** [comment]
This option does not work; it should affect and change the default template in a post.

<img width="496" alt="screenshot 2019-03-29 o 07 16 51" src="https://user-images.githubusercontent.com/1391007/55213125-a8f3db80-51f2-11e9-8a55-7822a5958480.png">

**Comment by dziudek** [comment]
I have tested it yesterday with Portfolio theme and it affects post template setting, but it can affect only new posts. Old posts will have their original settings - otherwise it would be impossible to override this settings per post.
