### ISSUE TITLE
HTML DOM Events not work

### ISSUE THREAD

**Issue by wuniversales** [GetPublii/Publii#399]
For example, the code does not work like that.
&#60;input onclick="myFunction()" type="button" value="Test">
The code disappears when saving the post.
It forces me to do this....
&#60;input id="demo" type="button" value="Test">
<script>
document.getElementById("demo").onclick = function() {myFunction();};
</script>

**Comment by dziudek** [comment]
Hi,

Please use this workaround: https://github.com/GetPublii/Publii/issues/367#issuecomment-471542079

At this moment I do not see a reason of allowing `on*` attributes globally, but if more people will request it - we will add it. So I will left this issue open.

**Comment by janiosarmento** [comment]
+1

`on*` events are particularly useful for me.

**Comment by dziudek** [comment]
As Publii has an option to specify additional valid elements under settings I do not see any additional reason to add more changes related to this issue.
