### ISSUE TITLE
Embedd images and videos from online source - free to use sources

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#400]
I would love to be able to press a button in the post editor, for featured image and the post itself, and be able to insert a image or video with a few clicks. The source of the images should be public image, gif and video sources which provide such resources with appropriate licenses.

Example sites:
- https://pixabay.com/
- https://unsplash.com/
- https://www.flickr.com/creativecommons/

Things to keep in mind:
- some sites have to be filtered because there are resources under different licenses
- this feature can be extended in the future to be customizable by the Publii user (like adding your own sources by providing basic information like URL/API structures, etc.)

This would be wonderful as a author because it makes adding resources way easier and more integrated. I'm sorry for this somehow bad description. I hope it's clear what I talk about.

**Comment by dziudek** [comment]
It is impossible to add this kind of feature, because these services APIs are too limited for wider use. Also it is a topic for plugin not a core app feature.

**Comment by GiantCrocodile** [comment]
What do you lack with their APIs @dziudek? I suspect there's some way because I've seen this with some messengers and one or two more advanced CMS'.

**Comment by dziudek** [comment]
Pixabay API rate limitation is a big issue - we cannot require users to get their own API key, because it is a problematic for non-tech users. And even if we get higher API rate limit - who will promise that it will be always free? 

Unsplash API have other big issue:

```
Your application’s Access Key  and Secret Key  must remain confidential. This means that they cannot be included in the client or made public. In most cases, this will require proxying the API through your own endpoint to sign the request with your keys.
```

It is impossible to hide access key and secret key in the Electron App, and we have no plans to provide additional endpoints for that case (additional maintenance work, privacy policy etc.).

**Comment by GiantCrocodile** [comment]
Hm ... you are right regarding the API limits if you share an API key, which is obviously disallowed by the services ToS. I've suspected that this could be some field in the publii client.

Maybe I will find a different way, how I can make this more comfortable for myself/others.
