### ISSUE TITLE
Publii starts with wrong window position

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#401]
Every time I open Publii, it's size is correct but the window is not maximized but has some centimeters offset. Thus I have to maximize the window all time to use Publii properly. I found the `window-config.json` and it contains this values after closing the maximized window:

`{"x":-8,"y":-8,"width":1936,"height":1056}`

I think this is a bug. I'm working with a resolution of 1920x1080 on Win 10. Is this a known bug or do I miss something? Also, I think the window position should be saved in relative values and not fixed positions.

**Comment by dziudek** [comment]
Thanks for the feedback - I see that I am not alone with that issue on Windows :)

**Comment by dziudek** [comment]
It seems to be an Electron issue on Win10: https://github.com/electron/electron/issues/4045

I have applied some fix which help me to avoid the left offset in this situation.

**Comment by tushev** [comment]
@dziudek I'm still having this issue with Publii `0.38.3`. Is it possible to fix it somehow? :)
