### ISSUE TITLE
Hero minimum and maximum height settings

### ISSUE THREAD

**Issue by SebastianSolidwork** [GetPublii/Publii#405]
It looks like there once were more options for the hero section. Was this a dummy ui? Or are they really gone? 
https://getpublii.com/docs/theme-settings.html#js-header
![image](https://user-images.githubusercontent.com/22794134/55632680-0ff92d80-57bb-11e9-8cd3-21b69bd31ab0.png)

Version: 0.33.4
OS: Window 10
Theme: theme-starter and simple

**Comment by bobmitro** [comment]
Hi Sebastian,
Different themes contain different options. 

PS: this repo is dedicated to Publii app; to report any issue or get support for themes, please use https://publii.ticksy.com/

**Comment by SebastianSolidwork** [comment]
@bobmitro Thanks. I have created this ticket related to the theme too. Should I recreate it at you side?
https://github.com/GetPublii/theme-Starter/issues/10
