### ISSUE TITLE
Requesting sync then cancel, I got this message systematically 

### ISSUE THREAD

**Issue by Grenoblois** [GetPublii/Publii#412]
Requesting sync then cancel, I got this message systematically.

![Screen Shot 2019-04-07 at 1 34 52 PM](https://user-images.githubusercontent.com/14146914/55793978-0bcf5780-5abc-11e9-8fe5-23e9c0174e63.png)

**Comment by Grenoblois** [comment]
Problem solved probably sinced I upgraded node from 8 to the latest 10.15.3
Just a guess.

**Comment by dziudek** [comment]
Hi, this issue occurs anyway in some cases. I have to deeply debug this issue as my previous fixed does not solved it. Fortunately it is not a critical issue as it does not block anything.
