### ISSUE TITLE
Add support for file uploaders

### ISSUE THREAD

**Issue by GasmoN** [GetPublii/Publii#416]
I think that it would be great if you add file upload support in pages.
For example, I create a post and click on "Add uploader" button, than when publii render and publish my page, it will have "Choose file" to upload files.
I think that this can be done with dropbox, mediafire or any other API using javascript. (Not sure)

**Comment by GiantCrocodile** [comment]
Do you mean that website visitors can upload files? If yes, I have doubts that this is a good idea regarding server security, legal reasons (what if criminals upload bad stuff?), etc.

**Comment by GasmoN** [comment]
Well, every site that has upload form can be used in for illegal puposes, I think that shouldn't be the reason not to include this feature.

**Comment by dziudek** [comment]
@GasmoN - as far as I know - there is no way to handle file uploads on the static websites without server-side solutions and at this moment we have no plans to implement any features for websites which requires server-side.

**Comment by dziudek** [comment]
I am closing this ticket due inactivity and due lack of ideas how to implement this.
