### ISSUE TITLE
No color chooser in text editor

### ISSUE THREAD

**Issue by GasmoN** [GetPublii/Publii#421]
I think you should add color chooser in the text editor. 
It's a must have feature tha almost everyone use.

**Comment by dziudek** [comment]
Hi @GasmoN,

If I correctly remember it is a first or maybe second request of this feature, so I am not sure if it is as you wrote:

> It's a must have feature tha almost everyone use.

I will leave this issue open for further consideration.

In the meantime - if it is so important feature for you - please remember that you can customize editor toolbars for your Publii instance:

1) Create file `My Documents/Publii/config/tinymce.override.json`

2) Put the following content to this file:

```json
{
	"plugins": "advlist autolink autosave link image lists hr pagebreak searchreplace media table textcolor paste autoresize autosave textpattern toc",
	"toolbar2": "styleselect formatselect forecolor backcolor searchreplace hr readmore undo redo restoredraft removeformat sourcecode"
}
```

The color pickers for the text and background color will appear in your editor in the second toolbar.

**Comment by GiantCrocodile** [comment]
I agree with @GasmoN that this is a common feature for different types of websites. On the other hand, I think this issue should be treated more general: Why are some features removed or added to the toolbars? It's hard to decide what is common or not, especially without a clear opinion from the community. Is it possible to have some kind of setting/option to add/remove all possible options via the GUI? This is helpful for anybody who has no clue what is/is not provided by the editor. For example I did expect that the color chooser isn't a standard feature of it and thus I didn't expect to enable/disable it so easily.

A more general approach to this will prevent different tickets/issues for this kind of issues and thus increase the usability/help yourself level.

**Comment by dziudek** [comment]
> Why are some features removed or added to the toolbars?

We analyze other tools and we decide what is important and what's not

> It's hard to decide what is common or not, especially without a clear opinion from the community.

The active part of the community is too small to provide proper feedback on this. Also community often is not best source of good ideas as Henry Ford said “If I had asked people what they wanted, they would have said faster horses.”. 

>  Is it possible to have some kind of setting/option to add/remove all possible options via the GUI?

We have a very long list of things which are much more important than this. And at this moment it won't be important as everybody who really needs to customize the toolbar can edit the editor configuration via override. It is absolutely enough at this moment.

**Comment by bobmitro** [comment]
Added in the WYSIWYG editor.
