### ISSUE TITLE
Generate robots.txt for the websites

### ISSUE THREAD

**Issue by wuniversales** [GetPublii/Publii#432]
I have noticed by checking the SEO of my website, that the robots.txt file is not automatically generated
I think it is necessary at least the "basic"

User-agent: *
Allow: /
Sitemap: example.com/sitemap.xml

regards

**Comment by YoavRheims** [comment]
Well, good idea! But drop the "Allow: /" because it's not really valid.
http://www.robotstxt.org/robotstxt.html

Must be:

User-agent: *
Disallow:
Sitemap: example.com/sitemap.xml
