### ISSUE TITLE
add ENTER to confirm dialog

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#436]
I would like to see more keyboard support: If I create a site, I type in the name of the site and the author name. Afterwards I should be able to press ENTER to confirm my input so I can avoid using mouse cursor to press the button.

Maybe this can be implemented at other spots too, if applicable.

**Comment by dziudek** [comment]
Thanks - it is a good point - I will try to improve it in the next release :)

**Comment by dziudek** [comment]
I have added the enter key handler for:
- alert popup
- confirm popup
- regenerate thumbnails popup
- site add form
- sync popup
