### ISSUE TITLE
How can I create sub-pages?

### ISSUE THREAD

**Issue by wuniversales** [GetPublii/Publii#437]
I'm trying to create a sub-page, but I think it's not possible, would it be possible to add it?
https://example.com/example1/example2

**Comment by dziudek** [comment]
Hi,

At this moment we have no plans for the sub-pages support. Maybe in the future, but currently it is not in our roadmap.

**Comment by wuniversales** [comment]
At least add the idea tag, right?

**Comment by dziudek** [comment]
I am closing it as this feature will be part of #656 in v.1.0.0 :)
