### ISSUE TITLE
Images additional optimisation

### ISSUE THREAD

**Issue by dziudek** [GetPublii/Publii#442]
Consider adding pngquant and mozjpeg to the images creation/regeneration workflows.

**Comment by dziudek** [comment]
There is a big issue with ASAR and pngquant/mozjpeg libraries. At this moment there is no way to implement these solutions while ASAR is enabled.

**Comment by pavelloz** [comment]
I dont know if that changes anything, but i have found sharp to be better (much faster and one API to rule them all).

It was orders of magnitude faster than everything else i tried + has webp support and some basic, and not so basic transformations if needed.

Read more: https://sharp.dimens.io/en/stable/

**Comment by dziudek** [comment]
@pavelloz - Publii uses Jimp and Sharp at this moment. Unfortunately Sharp is not so good at PNG/JPG optimisation. I have tried to use external libraries, but they are incompatible with ASAR. In the future we will come back to this topic and we will try to develop additional optimisation as external plugins where ASAR won't be a problem.

**Comment by pavelloz** [comment]
Hmm, i find sharp very good at jpeg/png optimization - maybe its a matter of settings?

**Comment by dziudek** [comment]
Sharp is not bad, but mozjpeg and pngquant are much better (they can produce sometime 2-3 times lighter images)

**Comment by dziudek** [comment]
I am closing this issue as we have discovered that most of the issues were caused by unnecessary upscaling: https://github.com/GetPublii/Publii/issues/503

Maybe the images can be a little bit more optimized, but it is not so critical as earlier, before fixing #503
