### ISSUE TITLE
No author page generated if zero posts exist

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#446]
`<site>/preview/authors/<author name>/index.html` leads to a non existing file with Simple theme if there are no posts yet. I don't know if this is a theme or client issue.

**Comment by dziudek** [comment]
Hi,

Please make sure that you have enabled option Settings > SEO > Display authors w/o posts

If it is disabled then author pages are not generated.

**Comment by GiantCrocodile** [comment]
Hi @dziudek! Then it must be an issue related to the theme because on the home page there is a link generated to the missing file.

**Comment by dziudek** [comment]
Hi again,

Which theme are you using? It is one of the default ones or the custom one?

**Comment by GiantCrocodile** [comment]
Hi @dziudek! It happens with the `Simple` theme which is a standard, non-custom one.

**Comment by dziudek** [comment]
I have made a deeper analyze of this issue and we won't fix it.

In fact it is an edge case when someone will create a website without posts. Also the option of showing site owner is available, so user can fix it. Additional solution is to use option mentioned in one of my previous comments.

There is no sense to add additional condition and code which will make a check if author have a post or not, especially if it will be useful only for such edge-cases.
