### ISSUE TITLE
Building on Windows (10)

### ISSUE THREAD

**Issue by oleteacher** [GetPublii/Publii#453]
Greetings! We were trying to build Publii in a classroom project yesterday following your instructions.

We cannot get past this point:

![image](https://user-images.githubusercontent.com/26278259/57971561-637f9f00-7955-11e9-9645-b2a2dbd918aa.png)

Two hours later and nothing changes?

Would it be possible to give me some pointers so could try again on Monday morning class?

Thank you!

**Comment by dziudek** [comment]
Hi @oleteacher ,

I think that much easier will be just downloading installer from: https://getpublii.com/download/ for Windows.

Building the app is useful only for developers who wants to contribute in the project or needs the newest (and usually unstable version of Publii) :)

**Comment by oleteacher** [comment]
Ok. sorry to have bothered you. We were trying to "dev" in a classroom enviroment.

**Comment by dziudek** [comment]
I suppose that the information about the installers availability is not enough visible in the Readme so we will change it a little bit :)

**Comment by oleteacher** [comment]
Did not need a installer. We have been using Publii in the classroom for about a year. We were experimenting with building it from source.

Not to worry though, a fellow user saw this issue and came to rescue on solving issue.

Cheers!

**Comment by dziudek** [comment]
Ah, ok :) So when the files are compiled just click Ctrl+C to terminate the process and then continue rest of the commands.
