### ISSUE TITLE
WP Import assigns tags only when more then one category

### ISSUE THREAD

**Issue by jozwikp** [GetPublii/Publii#456]
We have an issue with WP Import.

We have a large feed with more than 2000 posts. We use wp categories as Publii tags. After import, I noticed that posts which were assigned to more than one category have assigned Publii tags. Other do not. So we have about 1000 posts with no Publii tags and 1000 with 2 or more Publii tags.

Can you help?

**Comment by jozwikp** [comment]
What's funny if you add blank element <category domain="" nicename=""></category> to each <item> it solves the problem. It's looks as an coma "," related issue.

**Comment by dziudek** [comment]
Hi,

Thank you for your feedback - I will try to fix this issue in the nearest release.

**Comment by dziudek** [comment]
@jozwikp - could you provide me an example of posts in the WXR format which have this issue? I have just imported the WXR from one of my test WP and the import is correct - regardless of the categories amount.

**Comment by jozwikp** [comment]
<item>
		<title>
				2,2 miliarda internautów w 2013 roku!		</title>
		<link>http://futureblog.pl/22-miliarda-internautow-w-2013-roku/</link>
		<pubDate>Sun, 16 Aug 2009 08:13:09 +0000</pubDate>
		<dc:creator><![CDATA[admintt]]></dc:creator>
		<guid isPermaLink="false">http://futureblog.pl/?p=6669</guid>
		<description></description>
		<content:encoded>
				</content:encoded>
		<excerpt:encoded>
				<![CDATA[]]>		</excerpt:encoded>
		<wp:post_id>6669</wp:post_id>
		<wp:post_date><![CDATA[2009-08-16 10:13:09]]></wp:post_date>
		<wp:post_date_gmt><![CDATA[2009-08-16 08:13:09]]></wp:post_date_gmt>
		<wp:comment_status><![CDATA[open]]></wp:comment_status>
		<wp:ping_status><![CDATA[closed]]></wp:ping_status>
		<wp:post_name><![CDATA[22-miliarda-internautow-w-2013-roku]]></wp:post_name>
		<wp:status><![CDATA[publish]]></wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>0</wp:menu_order>
		<wp:post_type><![CDATA[post]]></wp:post_type>
		<wp:post_password><![CDATA[]]></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
										<category domain="category" nicename="internet-2"><![CDATA[Internet]]></category>
		<category domain="category" nicename="swiat-przyszlosci"><![CDATA[Świat przyszłości]]></category>
		<category domain="category" nicename="technologie-2"><![CDATA[Technologie]]></category>
						<wp:postmeta>
		<wp:meta_key><![CDATA[_edit_last]]></wp:meta_key>
		<wp:meta_value><![CDATA[39]]></wp:meta_value>
		</wp:postmeta>
							<wp:postmeta>
		<wp:meta_key><![CDATA[hpbottom]]></wp:meta_key>
		<wp:meta_value><![CDATA[http://futureblog.pl/wp-content/uploads/2009/08/381.jpg]]></wp:meta_value>
		</wp:postmeta>
							<wp:postmeta>
		<wp:meta_key><![CDATA[thumbnail]]></wp:meta_key>
		<wp:meta_value><![CDATA[http://futureblog.pl/wp-content/uploads/2009/08/382.jpg]]></wp:meta_value>
		</wp:postmeta>
							<wp:postmeta>
		<wp:meta_key><![CDATA[_thumbnail_id]]></wp:meta_key>
		<wp:meta_value><![CDATA[6670]]></wp:meta_value>
		</wp:postmeta>
							</item>

**Comment by dziudek** [comment]
@jozwikp  - this post have 3 categories assigned and no tags - maybe you have set the import to use post tags instead of categories? But also when I have used tags as a taxonomy I got properly assigned tags in my test WXR file.

**Comment by jozwikp** [comment]
We tried every combination. But I'm sure about this issue.
When there is only one category in <item> there is no assignment.

**Comment by dziudek** [comment]
Could you send me an example WXR file? Then I will try to reproduce your issue on my Publii installation. You can send it via e-mail.
