### ISSUE TITLE
Desktop: Minimum application geometry larger than display

### ISSUE THREAD

**Issue by iam-TJ** [GetPublii/Publii#458]
I've just installed 0.34.1 on Xubuntu 18.04 amd64 from the Debian package.

On initial launch the application window will not maximise on the secondary (left-most) monitor. The monitor layout is:

```
  [1920x1080] [2560x1440]
  [         ] [ primary ]
```

The application starts on the primary monitor. I drag it to the secondary (left-most) monitor and double-click the title bar expecting it to maximise but it doesn't, and won't via the System menu either. It will maximise on the primary monitor.

On the primary display I manually resized the window to its minimum which turns out to be larger that the secondary display which is presumably why the window will not maximise on the smaller display:

```
xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x4400001 "Publii"

  Absolute upper-left X:  2384
  Absolute upper-left Y:  63
  Relative upper-left X:  6
  Relative upper-left Y:  43
  Width: 2040
  Height: 1190
  Depth: 24
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOutput
  Colormap: 0x20 (installed)
  Bit Gravity State: NorthWestGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: no
  Corners:  +2384+63  -56+63  -56-187  +2384-187
  -geometry 2040x1190-50+20
```

**Comment by iam-TJ** [comment]
This is looking more like a problem with the minimum size of the application window hard-coded. I used a devilspie2 script to (try to) force the window geometry on open.
```
$ cat .config/devilspie2/Publii.lua 
if (get_window_name() == "Publii") then
           -- x,y, xsize, ysize
           set_window_geometry(30, 30, 900, 700);
end
```
The window moves to the left-most display correctly but it does not use the new size of 900x700.

On each test I delete the existing Publii config in case the size was saved:

```
$ rm -r ~/.config/Publii
```
Therefore I'm re-titling this issue to reflect the apparent problem with the minimum size.

**Comment by iam-TJ** [comment]
Looking at the source-code I found in `app/back-end/app.js::loadConfig()`:

```
        if (!this.windowBounds) {
            const {width, height} = electron.screen.getPrimaryDisplay().workAreaSize;

            this.windowBounds = {
                width: width,
                height: height
            };
        }
```
there might be an additional issue here - relying on `getPrimaryDisplay()` rather than iterating all displays and using the smallest as the bounds to use for the initial size.

That doesn't seem to affect the `minWidth` and `minHeight` values though, which are set in  `initWindow()`:
```
        let windowParams = this.windowBounds;
        windowParams.minWidth = 1200;
        windowParams.minHeight = 700;
```
However, the application is not using these values. This appears to be called after  `loadConfig()` from the constructor and I cannot find any code affecting window size after `initWindow()` is called.

Hopefully someone familiar with the code can make more sense of it.

**Comment by dziudek** [comment]
Hi,

I have added a code which will find the smallest possible dimensions according to available screens. But the screens must have at least 1200x700 workarea - smaller screens are not supported and can cause issues.
