### ISSUE TITLE
Serve Images in Next-Gen Formats

### ISSUE THREAD

**Issue by YoavRheims** [GetPublii/Publii#459]
Could be a useful feature to add in the future for the more photo heavy themes in particular: https://developers.google.com/web/tools/lighthouse/audits/webp

**Comment by YoavRheims** [comment]
Oh, seems like Bob had the same idea: https://github.com/GetPublii/Publii/issues/442 

Would love to see webp integrated :)

**Comment by bobmitro** [comment]
The additional image format will extend the rendering website time, and will definitely increase the number of generated image files. I think, there is still not enough support for WEBP format.
But... we got a plan in the next release to add the new two image compressor: for PNG: https://pngquant.org/  and for JPG: https://github.com/mozilla/mozjpeg
I'm pretty sure this will do the trick.

**Comment by YoavRheims** [comment]
That'd be already amazing indeed! Will be there to try it out.

**Comment by eclipsesrl** [comment]
@bobmitro picture element can be an idea? it's supported by all major browsers and auto fallbacks to img tags, you can set multiple sources. Chrome, Firefox and Edge will render the webp format and safari will use the png/jpg one

**Comment by bobmitro** [comment]
Yeap, this is a solution, especially that it actually has good browser support https://caniuse.com/#feat=picture

**Comment by YoavRheims** [comment]
Oh, that'd be great if it is not too much of a hassle to implement :)

**Comment by bobmitro** [comment]
I'm afraid you have to wait a bit for that; at this moment we have the plan to add the new image compressors only and have not enough time to implement <picture>.

**Comment by YoavRheims** [comment]
> I'm afraid you have to wait a bit for that; at this moment we have the plan to add the new image compressors only and have not enough time to implement "picture".

No worries :)

**Comment by dziudek** [comment]
WebP will be supported in v.0.38 on mac OS and Windows (on Linux due big issues with sharp library we cannot support it). Implementation of `<picture>` tag needs a lot of of work and in my opinion it is not worth of it as WebP will be soon largely supported.
