### ISSUE TITLE
Google Fonts and font-display improvements

### ISSUE THREAD

**Issue by YoavRheims** [GetPublii/Publii#460]
You can read more about it: https://www.zachleat.com/web/google-fonts-display/

I know it's easy to fix by ourselves but still worth native support imo.

**Comment by bobmitro** [comment]
Hi Yoav,
I have noticed this recently, and I will add to all themes the next Publii release.

**Comment by YoavRheims** [comment]
Great :)

**Comment by bobmitro** [comment]
Implemented.

**Comment by YoavRheims** [comment]
Great!
