### ISSUE TITLE
.htaccess and other dot-files not synced to Github pages

### ISSUE THREAD

**Issue by perifer** [GetPublii/Publii#461]
Files starting with a dot added to root directory in the Files Manager are not synced to Github Pages. E.g `.htaccess` or `.travis.yml`.

Tested with Publii 0.34.1 on a Mac.

**Comment by dziudek** [comment]
It will be fixed in the next release - only `.DS_Store` and `thumbs.db` files will be ignored. 

BTW `.htaccess` won't work on Github Pages - it is an Apache config file.

**Comment by perifer** [comment]
Excellent! Thanks 🙏!
