### ISSUE TITLE
Add a virtual pages system like in Kirby 3

### ISSUE THREAD

**Issue by GiantCrocodile** [GetPublii/Publii#462]
It would be so powerful and offer a lot of new possibilities to have a virtual page system like Kirby 3 has: https://getkirby.com/docs/guide/virtual-pages

Most likely this feature is less powerful in Publii than in Kirby 3 because of the technical limitations but the basics should be possible.

**Comment by internettips** [comment]
At first glance, Kirby virtual pages sound interesting. Though I wonder if for a "speed demon" like Publii, that also already does a superb job of addressing the glaring weaknesses in most other content management systems, perhaps the added complexity and approach like that shown at Kirby virtual pages, could introduce more security risks, SEO risks (ranking confusion, etc), additional speed hurdles, etc. It might feel like a backward step.

**Comment by GiantCrocodile** [comment]
The feature could be implemented so the data is downloaded, preprocessed and stored like ordinary articles/pages. This will mean that no addition runtime is required due to using this feature. Of course this would result in no realtime data but data from a specific date or updated like in a regular schedule on publishing the site.

**Comment by dziudek** [comment]
(clearing the backlog)
