### ISSUE TITLE
FTP transfer stops after 12000 files

### ISSUE THREAD

**Issue by jozwikp** [GetPublii/Publii#465]
We have an issue with a large site. FTP transfer always stops in the middle

![2019-05-27](https://user-images.githubusercontent.com/5263329/58411930-b8b66180-8075-11e9-8c27-0a4fc3b8a036.png)

**Comment by dziudek** [comment]
Hi,

Can you provide logs for this case (especially deployment-process.log and deployment-errors.log)? You can upload them as private ticket on Ticksy: https://publii.ticksy.com

I suppose that process stopped due some network issue and the upload process crashed. To be honest - it is probably the biggest website on Publii which I have ever seen ;) 

BTW I will fix other issue - at this moment as I see the manual deployment method (what would be good for an initial sync for such big sites) won't generate publii.files.json - I will add it so you will be able to make a manual deployment to shorten the deployment process and then you will be able to sync only modified files.

**Comment by dziudek** [comment]
Also all connection*.log files would be useful to diagnose the issue.

**Comment by ajeet001** [comment]
Just want to highlight this ( though not related to this but similar), when I use SFTP with pasword, and start upload, i sometimes see the same view - transfer stops in the middle and when you cancel you see some error. The strange thing is that when i open my site and refresh it, i see the updated view. This has happened many times, but I think this is relate to server-network issue.

**Comment by internettips** [comment]
@jozwikp

For now, instead of FTP, SFTP, etc., the following method might work for you: 

1. Choose the "Manual upload" option.

2. Upload the .zip file to your desired web hosting location. 

3. In your web hosting cPanel, open "File Manager".

4. Delete all existing files in the desired location except your new .zip file (and any other files you want to keep).

5. Select your .zip file, then choose the "Extract" command.

For a website of about 650 items, website downtime is about 4 seconds.

**Comment by dziudek** [comment]
@ajeet001 - i will try to debug these issues too.

@internettips - yes, it is a good solution, but the only disadvantage is a fact that I have to fix https://github.com/GetPublii/Publii/issues/466 to get a real advance of the manual upload as during sync Publii won't see the manually uploaded files.

**Comment by jozwikp** [comment]
[hard-upload-errors-log.txt](https://github.com/GetPublii/Publii/files/3223660/hard-upload-errors-log.txt)
[deployment-errors.log](https://github.com/GetPublii/Publii/files/3223661/deployment-errors.log)
[deployment-process.log](https://github.com/GetPublii/Publii/files/3223662/deployment-process.log)

**Comment by dziudek** [comment]
The issue mainly appeared when there was a lot of files to remove. Due invalid calculation of progress the progress bar stops but in background Publii still sends the files.
