### ISSUE TITLE
Preview error, deleting website config folder.

### ISSUE THREAD

**Issue by Azenha** [GetPublii/Publii#469]
![image](https://user-images.githubusercontent.com/8021442/58742022-1d1b4d00-83f7-11e9-8459-62a845e41b64.png)

When I try to Preview, or Save & Preview, I get this error.

If I create a new website and save the settings, all are stored on config folder, but when building the preview/website the config folder is gone.

Using Win10 64bits and Publii 0.34.1 (build 11733) Beta.

**Comment by dziudek** [comment]
Hi,

On which application screen do you get this error? On the site settings or theme settings?

**Comment by Azenha** [comment]
Site settings, but it occurs on any preview, including post preview.

**Comment by Azenha** [comment]
Now I don't get the error, but the config folder is gone.

https://gfycat.com/flatmasculinegibbon

**Comment by dziudek** [comment]
As I see only the theme.config.json file is deleted, not the whole folder.

Could you try to save theme settings before rendering a website?

**Comment by Azenha** [comment]
Sorry, the video ended before, but the config folder is deleted.

I will backup the config folder and give another try.

**Comment by Azenha** [comment]
Solved, I deleted a old config file inside "Documents" folder, and deleted publii Appdata folder.
