### ISSUE TITLE
Page homepage not rendered into AMP format

### ISSUE THREAD

**Issue by YoavRheims** [GetPublii/Publii#473]
Hi,

It seems like when you decide to set up a page as the homepage, AMP will still render the old way, ignoring the dedicated chosen page.

Has anyone have seen this happening too?

**Comment by bobmitro** [comment]
UPSSS .. I forgot to implement it for AMP pages.

**Comment by YoavRheims** [comment]
Seen that happening only yesterday.

:)

**Comment by bobmitro** [comment]
Implemented.
