### ISSUE TITLE
 Preloading Strategy using Guess.js - Plugin Suggestion

### ISSUE THREAD

**Issue by ajeet001** [GetPublii/Publii#478]
Not sure if this can be implemented with Publii but Gatsby has a plugin. 
More info: 
https://blog.mgechev.com/2018/12/24/quicklink-angular-prefetching-preloading-strategy/
https://blog.mgechev.com/2018/05/09/introducing-guess-js-data-driven-user-experiences-web/

**Comment by YoavRheims** [comment]
Yeah, I suggested the same in March: https://publii.ticksy.com/ticket/1945268/

**Comment by ajeet001** [comment]
Extremely sorry for posting this here. Will make sure I search issues/suggestions at the forum first. Coming back to Guess js, his responses at the forum were:
1. "Do you really think that adding support for something in ALPHA version is a good idea?"
- I agree with him that it should not (or must not) be added as it is in alpha version.
2. "Do you really think that for a typical user this will change anything in the feeling of super-fast websites generated by Publii?"
- What he talks here about a TYPICAL user. It's userbase is limited in numbers. The Publii has limited features and integrations, and comes with unnecessary plugins, that's why one of the reasons it's fast. Even they have not added support for most of the popular google fonts.Since the app has limited features, for now, users might not feel the difference.
3. "It is a very bad idea (and in fact it closes this topic)......And you suggest to load another JS library to get 10-50ms? "
- It not a bad idea. It is bad for simple websites in Publii ( as he said in the forum) but again as I said, Publii is simple for now and has it's limitations. Quicklink by Google only injects & prefetch data when browser is idle and if the user is on a fast connection.  JS code in less than 1KB. You may not see score improvement in GTmetrix/Pagespeed insights. but aim is to improve inner pages navigation. When you click through the links, you will feel difference. See the demo here: 
https://www.webpagetest.org/video/view.php?id=181212_4c294265117680f2636676721cc886613fe2eede&data=1

Gatsby uses aggressive prefetching. More here: https://www.gatsbyjs.org/docs/how-code-splitting-works/#prefetching-chunks

4. "That solution is an overkill for simple websites. It can have (just maybe) a sense for big websites or SPAs with big JS bundles and different libraries loaded on the different subpages."
- As I said, Publii is foucssing on simple websites for now, and for now, it's not good . Developers have already several priorities. But that does not mean it's a bad idea. Several devs are working on gatsby js, and I believe this will soon takeover other frameworks.

**Comment by YoavRheims** [comment]
It looks like Publii's team added a similar prefetching mechanism in the latest developed theme (released today!): https://marketplace.getpublii.com/products/prodocs/

Is this something that will be implemented to previous themes?
