### ISSUE TITLE
Add Zeit.co and Render.com as hosting options

### ISSUE THREAD

**Issue by pagelab** [GetPublii/Publii#486]
Both [Zeit](https://zeit.co/pricing) and [Render](https://render.com/pricing) have awesome free plans for static sites.

**Comment by ajeet001** [comment]
Zeit Now 2.0 is fairly new. i have used it and abandoned it as I was having hard time setting up zeit with Cloudflare. They strictly do not recommend CF CDN as they have their own. That's why their CF doc is not updated. Several users have complained about CF issue with Zeit ( Even I had also written a few days back on their Spectrum community)  but again it's pain to manage CF with zeit.
Their free community support is not great, but in case of Netlify their support is excellent.

**Comment by pagelab** [comment]
My experience with them has been very nice so far, but I haven't use CF with Now. So, I can't make an informed opinion on this specific case.

**Comment by anurag** [comment]
@ajeet001 what do you need from us to enable support for Render.com? Should I submit a PR?

**Comment by dziudek** [comment]
@anurag - I think that no PR is required to support Render.com. As your documentation states: https://render.com/docs/static-sites - just link Github repository. In this case @pagelab can create private repository, sync it with Render.com and then use Github to deploy to Render.com :)

**Comment by dziudek** [comment]
@pagelab - the same thing can be done with Zeit: https://zeit.co/docs/v2/deployments/basics/ - they have a Github integration.

So in my opinion there is no need for a dedicated deployment method. We can consider to add some tutorials for both hosting options with use of our Github integration.

**Comment by anurag** [comment]
@dziudek good to know. Would it make sense to create a guide for [server configuration](https://getpublii.com/docs/server-configuration.html) section so Publii users know it's supported out of the box? We have similar official guides for [CRA](https://facebook.github.io/create-react-app/docs/deployment#render-https-rendercom), [Gatsby](https://www.gatsbyjs.org/docs/deploying-to-render/) and [Vue](https://cli.vuejs.org/guide/deployment.html#render).

**Comment by dziudek** [comment]
@anurag - it is a good idea - we will consider to do it in our documentation for users and then we will also add some indication in the UI :)

**Comment by anurag** [comment]
Thank you! Again, let me know if we can help with anything.

**Comment by pagelab** [comment]
@dziudek Agreed, closing this one.
