### ISSUE TITLE
Add Post as Frontpage to Starter theme

### ISSUE THREAD

**Issue by kousu** [GetPublii/Publii#489]
I downloaded [Starter 1.0.6.0](https://marketplace.getpublii.com/products/starter/) and built an initial site around it. I learned today ([1](https://publii.ticksy.com/ticket/2046425/) [2](https://publii.ticksy.com/ticket/2024914/) [3](https://publii.ticksy.com//ticket/2019944/)) that some themes support using a post as a homepage. This seems like a pretty essential feature, so I would like to request it get added to the Starter theme --- I spent all yesterday manually editing starter/index.hbs to get my frontpage the way I wanted, not realizing I could just get it to render a WYSIWYG page.

**Comment by bobmitro** [comment]
This repository is dedicated to Publii PAP, Starter theme has its own https://github.com/GetPublii/theme-Starter
