### ISSUE TITLE
Responsive image generation

### ISSUE THREAD

**Issue by kousu** [GetPublii/Publii#491]
If I use the HTML Source tab in the Post Editor to write in

```
<img src="assets/png/infographic.png">
```

then, when rendered, Publii generates

```
<img src="assets/png/infographic.png" sizes="(max-width: 48em) 100vw, 768px" srcset="assets/png/responsive/infographic-xs.png 300w, assets/png/responsive/infographic-sm.png 480w, assets/png/responsive/infographic-md.png 768w">
```

This appears to be fine on my laptop, but on mobile (or on mobile faked via responsive design testing mode) suddenly the image disappears mysteriously. What's going on is that on my laptop, the screen is large enough that the `src=` takes precedence. But on mobile, the `srcset=` kicks in.

Once I realized the problem I deleted my image and re-added it using the GUI, and that fixed it.

I would like Publii to either
1. Not mangle `<img>` tags at all; it should probably generate the `srcset=` part when an image is inserted from the editor GUI, and then never again touch the structure of an <img> tag.
2. or, on "Apply changes" in the HTML editor, to drop back to the GUI editor, detect when an `<img>` doesn't have its responsive images existing or up to date and do the image generation then.

**Comment by dziudek** [comment]
Hi,

I think that solution for this case will be easier - skip adding srcset/sizes attributes form images which are outside media/posts and media/website directories, as only these images are parsed by regenerate thumbnails feature.

I will try to implement a fix in the 0.35.1 release. Thank you for your feedback :)
