### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by theflossinformation** [GetPublii/Publii#492]
Note: I am not an expert.

You have written that the software is licensed under GPLv3. I think the code is on the site.

Does GPLv3 have no restrictions on compatible licenses? Disqus and Google Custom Search are not proprietary software? Then what can be done?

**Comment by dziudek** [comment]
Hi,

Disqus and Google Custom Search are external services and can be used with any software regardless of the license.

**Comment by theflossinformation** [comment]
> Hi,
> 
> Disqus and Google Custom Search are external services and can be used with any software regardless of the license.

Although I didn't think it was an important detail, I think I could license the repository with GNU AGPLv3: [https://gitlab.com/theflossinformation/theflossinformation.gitlab.io](The repository)
I was confused by Disqus and Google Custom Search. Thank you.
