### ISSUE TITLE
Update question about the ".rpm" package

### ISSUE THREAD

**Issue by theflossinformation** [GetPublii/Publii#493]
I'm using Fedora GNU/Linux. There is a repository system of GNU/Linux updates. The software is downloaded and updated by means of repositories or mirrors. From what I can see, Publii's repository didn't exist in my operating system. Should GNU/Linux users manually follow updates?

**Comment by dziudek** [comment]
Hi,

At this moment we have no plans to maintain other update ways as our website download due lack of time. Also linux users are a niche as far as we know and see. Maybe in the future we will consider support for popular distributions repositories.

**Comment by theflossinformation** [comment]
> Hi,
> 
> At this moment we have no plans to maintain other update ways as our website download due lack of time. Also linux users are a niche as far as we know and see. Maybe in the future we will consider support for popular distributions repositories.

I admit that there is a bit of variety in GNU/Linux. I'm not quite sure, but maybe you can add the package to the official repositories of popular distributions.

**Comment by dziudek** [comment]
(clearing the backlog)
