### ISSUE TITLE
Important issues

### ISSUE THREAD

**Issue by theflossinformation** [GetPublii/Publii#494]
# Important issues
I think I noticed that they had important problems when using Publii. I will try to explain the problems that I have noticed.
## List of important issues that I noticed
- Search engines did not detect favicon. I think that's a big problem. In addition, sometimes favicon may not appear on desktop browsers.
- From what I see, Google Analytics isn't working.
- No picture appears on Twitter Cards.
These are the problems I found important in the first stage. I hope it can be solved.

**Comment by GetPublii** [comment]
# Important answers:
All your potential issues are related to themes, not Publii app, so the next time please use the free support here: https://publii.ticksy.com/ ; despite this:

1. I can not agree with you, the search engines display favicon uploaded by all Publii theme
2. GA does not work only if you implement it badly.
3. You are right TC does not display picture.

**Comment by theflossinformation** [comment]
> # Important answers:
> All your potential issues are related to themes, not Publii app, so the next time please use the free support here: https://publii.ticksy.com/ ; despite this:
> 
> 1. I can not agree with you, the search engines display favicon uploaded by all Publii theme
> 2. GA does not work only if you implement it badly.
> 3. You are right TC does not display picture.

I would appreciate it if you solved the picture problem on Twitter Cards. I will talk about the problems I have mentioned here.

**Comment by theflossinformation** [comment]
Can you look at this?

[https://publii.ticksy.com/ticket/2075270/](Important issues)

Thank you.

**Comment by theflossinformation** [comment]
Can you look at this?

[Important issues](https://publii.ticksy.com/ticket/2075270/)

Thank you.
