### ISSUE TITLE
Password protected posts

### ISSUE THREAD

**Issue by dziudek** [GetPublii/Publii#5]
Needs deeper analyze.

ref. https://github.com/matteobrusa/Password-protection-for-static-pages
ref. https://publii.ticksy.com/ticket/1591753#comment-7951141

It should works everywhere exceptin Github Pages. But users should be informed about necessary configuration (disable directory listings etc.).

**Comment by strelok899** [comment]
i would like to have this option too. 
i am hosting photography website and delivering client galleries through publii post and galleries . for now i am using long slug.
but password per post would be better . and will have the ability to put the client galleries to the menu or page .

**Comment by internettips** [comment]
Perhaps at some point, we can jump to passwordless login using something like WebAuthn ([https://webauthn.guide](url), FIDO2 framework: [https://duo.com/blog/developments-to-webauthn-and-the-fido2-framework](url)?

**Comment by dziudek** [comment]
We won't add support for such feature directly in Publii. Maybe on the future we will prepare articles how to add such functionality on particular hosting services like Netlify: https://docs.netlify.com/visitor-access/password-protection/
