### ISSUE TITLE
Block-based editor

### ISSUE THREAD

**Issue by dziudek** [GetPublii/Publii#500]
Totally new writing experience in Publii :)

**Comment by YoavRheims** [comment]
Question: is this add a sidebar to the content?

**Comment by pavelloz** [comment]
Any sneak peeks? :P

**Comment by cristian-milea** [comment]
is it possible to open or convert an existing post written in WYSIWYG with the new Blocks Editor?

**Comment by candideu** [comment]
Are there any plans to implement an "Undo" for format changes?
