### ISSUE TITLE
0.35 Windows Installer gives error

### ISSUE THREAD

**Issue by gokceozan** [GetPublii/Publii#506]
Hi. I am getting below error on Windows Install:
![Publii-0 35_1 tmp_7mQfheeqx0](https://user-images.githubusercontent.com/1352027/60966401-d0456300-a320-11e9-9cef-f7d27679ed9b.png)
Tried with 2 different downloads. The same thing happened each time.

**Comment by YoavRheims** [comment]
Had the same issue.
Try the Alternative download from https://getpublii.com/download/
It worked perfectly for me.

**Comment by gokceozan** [comment]
Yup, alternative one works. Thanks!

**Comment by ajeet001** [comment]
The alternative download did not work for me when I installed for the first time without Running as Admin. 
![error1](https://user-images.githubusercontent.com/30115193/60972800-98501700-a344-11e9-81b4-ac97bc5ec401.PNG)

But running as Admin worked for me.

**Comment by dziudek** [comment]
We have fixed the package on CDN but it seems that the cache clear won't work and the old file has been served.

**Comment by dziudek** [comment]
I am closing this issue as I suppose that with updated packages it is fixed. If anyone else have this problem - feel free to reopen it.
