### ISSUE TITLE
Can you look at this?

### ISSUE THREAD

**Issue by theflossinformation** [GetPublii/Publii#511]
Can you look at this?

[Important issues](https://publii.ticksy.com/ticket/2075270/)

Thank you.

_Originally posted by @theflossinformation in https://github.com/GetPublii/Publii/issues/494#issuecomment-510439311_

**Comment by dziudek** [comment]
Please do not spam the issues section. It is an open source project and we does not provide 24/7 support. The reply time depends of the priority and the mentioned issues are not important as your issue name suggest.

**Comment by theflossinformation** [comment]
Bu ileti The FLOSS Information'a gönderdiğiniz ileti sonucunda otomatik olarak oluşturuldu.

Bu iletiye yanıt vermenize gerek yoktur.

Bu iletiyi gönderdiğiniz için teşekkür ederiz. 4 gün içerisinde yanıtlamaya çalışacağız. Eğer 4 gün içinde yanıt gelmezse tekrar ileti gönderebilirsiniz.

Sık Sorulabilecek Sorular: https://theflossinformation.gitlab.io/sik-sorulabilecek-sorular.html
Hakkımızda: https://theflossinformation.gitlab.io/hakkimizda.html
Bize Ulaşın: https://theflossinformation.gitlab.io/bize-ulasin.html

Saygılarımızla,
The FLOSS Information
https://theflossinformation.gitlab.io/
