### ISSUE TITLE
Missing index.html from tags url even when "Always add index.html in URLs" option is enabled

### ISSUE THREAD

**Issue by anggras** [GetPublii/Publii#512]
Found that line 29 of app/back-end/modules/render-html/items/tag.js https://github.com/GetPublii/Publii/blob/4580cca8b35cc2709f9fed47f87d348ce8764101/app/back-end/modules/render-html/items/tag.js#L29 is missing 
```javascript
|| this.siteConfig.advanced.urls.addIndex
```
statement.

It should be similar with line 182 of app/back-end/modules/render-html/renderer-context.js https://github.com/GetPublii/Publii/blob/336cd020cb2fc3a98741440e0ed06e38c15cb728/app/back-end/modules/render-html/renderer-context.js#L182

**Comment by dziudek** [comment]
Hi,

Thanks for the feedback :) I will check and fix this issue in 0.35.1 :)
