### ISSUE TITLE
Open Graph need image size

### ISSUE THREAD

**Issue by jeckyl** [GetPublii/Publii#538]
Hi,

Open Graph need to have og :image :width and og :image :height to share perfectly links.

**Comment by dziudek** [comment]
Hi,

Thanks for the feedback, we will include this feature in the next big release as we are unable to add it in v.0.35.1, which is feature-frozen currently and we adds only bug fixes now.

--------------------

Tags to add:

```
<meta property="og:image:type" content="image/jpeg" />
<meta property="og:image:width" content="400" />
<meta property="og:image:height" content="300" />
<meta property="og:image:alt" content="Lorem ipsum dolor sit amet" />
```

**Comment by kmanadkat** [comment]
Hi @dziudek 
I am facing problem with OG tags. I see preview image of my Post in Instagram & Twitter. In whatsapp however it shows only Text, no preview image. Please find examples before:

**Twitter**
![IMG_2869](https://github.com/GetPublii/Publii/assets/25281055/65adf86f-7da5-472c-8ba4-eb0343186e8f)

**Instagram**
![IMG_2870](https://github.com/GetPublii/Publii/assets/25281055/4257cf55-07a3-4a61-a945-ebfa54af452f)

**Whatsapp**
![IMG_2868](https://github.com/GetPublii/Publii/assets/25281055/4dc0ce05-7c04-40c2-951f-a3699d145b74)

After searching a bit I found that whatsapp ignores `og:image` url if `og:image:width` or `og:image:height` is more than 300.

I am not finding any option to set those tag values myself. I checked the blog theme source code too, it seems it is just populating value what is passed in handlebar variables by Publii.

<img width="1212" alt="Screenshot 2023-07-22 at 10 50 52 PM" src="https://github.com/GetPublii/Publii/assets/25281055/72e18c56-ca58-4ecb-9b54-29027649d774">

> Also, how do i remove this <meta name="generator" content="Publii Open-Source CMS for Static Site"> from all my site pages?

Thanks
