### ISSUE TITLE
Updater

### ISSUE THREAD

**Issue by GasmoN** [GetPublii/Publii#540]
I think that "Check for updates" buttin will be good to add as soon as possible, at least when it's still in beta, so new versions are more often released. 
So when we click "Check for updates" button and if there is new update, we can choose to update the software or not. 
The reason for this is that we don't need to uninstall old and download and install new version every time it's released.

**Comment by dziudek** [comment]
Hi,

We will add this feature along with: https://github.com/GetPublii/Publii/issues/536

I will leave it as a separate issue as #536 is about theme updates.

**Comment by dziudek** [comment]
The idea has been changed and updates center from https://github.com/GetPublii/Publii/issues/536 will also cover Publii updates so this issue can be closed.
