### ISSUE TITLE
Export modified themes

### ISSUE THREAD

**Issue by GasmoN** [GetPublii/Publii#541]
Let's say that we are using TechNews theme, but have done some modifications (CSS for example, etc.) to that theme so it is now Dark insted of white. I think it would be good to add option "Export this theme" so we can export all custom files we added or all existing files we changed into one .zip archive as a seperate theme.

**Comment by dziudek** [comment]
It is unnecessary as theme overrides mechanism exists: https://getpublii.com/dev/theme-overrides/ 

It is a developer task to do zip from these files, so it is not necessary for casual users.
