### ISSUE TITLE
svg-fix.js

### ISSUE THREAD

**Issue by kousu** [GetPublii/Publii#546]
I'm using the [Starter Theme](https://github.com/GetPublii/theme-Starter) (with some modifications, of course) and I noticed that running [uMatrix](https://github.com/gorhill/uMatrix) would break my site's Social Icons. I dug into it and found the same issue in most themes. The social media icons are supposed to be rendered using SVG's import feature, [`<svg><use/></svg>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use):

https://github.com/GetPublii/Publii/blob/7b01f07b1afef57be5fa007215075ad129853073/app/default-files/default-themes/simple/partials/footer.hbs#L4-L17

So it's supposed to be downloading [svg-map.svg](https://github.com/GetPublii/Publii/blob/7b01f07b1afef57be5fa007215075ad129853073/app/default-files/default-themes/simple/assets/svg/svg-map.svg) once and then using pieces of that all over. I assume this is to save a few bytes of HTTP header by only doing one download for all the small icons. But it doesn't work as advertised.

For some reason the `<use>` link doesn't behave itself. I thought it was because it was written using the [older](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href) SVG1.1 `xlink:href="..."` property but even changing that to `href=` doesn't seem to make it work for me.

Perhaps this is why there is also `svg-fix.js` + `svg2js.js`. These two literally duplicate and hardcode the contents of the `svg-map.svg` into a js array and then find all the `<use>`s and fill in the contents from the array instead of from the svg:

https://github.com/GetPublii/Publii/blob/7b01f07b1afef57be5fa007215075ad129853073/app/default-files/default-themes/simple/assets/js/svg-fix.js#L1

https://github.com/GetPublii/Publii/blob/7b01f07b1afef57be5fa007215075ad129853073/app/default-files/default-themes/simple/assets/js/svg2js.js#L1-L17

This is annoying because it makes my site depend on code.jquery.com. It slows down loading, breaks if my ad-blocker is on, exposes my users to surveillance, and breaks if I'm working without WiFi. Recently, the default theme has [been updated](https://github.com/GetPublii/Publii/blob/84e90cd26f00a5fde6e0e97e3ca1431fab501867/app/default-files/default-themes/simple/assets/js/svg-fix.js) to use `document.querySelectorAll` instead of depending on jQuery, but the starter theme [hasn't yet](https://github.com/GetPublii/theme-Starter/blob/master/assets/js/svg-fix.js).

I also want my site to work js-free, so even though I could include jQuery as in `assets/js/`, I don't want to.

Why is `svg-fix.js` necessary?

If it's to work around poor browser support for `<svg><use>` would you be open to just splitting up `svg-map.svg` into separate files and using `<img src=>` instead?

Even if you're not open to going that far, please update the Starter Theme and any other theme still suffering with the fix that removes third-party Javascript.

Thank you for all your hard work on Publii and I hope this finds you well.

**Comment by dziudek** [comment]
Hi,

The svg-fix.js is dedicated only for the preview pages. It is not used on the production sites. svg-fix.js is necessary, because while previewing websites on local filesystems, the SVG map parts are not loaded due CORS, and this issue cannot be overrided in any other way. SVG maps are necessary to avoid a lot of small HTTP requests which can really affect website performance.

**Comment by kousu** [comment]
Oh I see. It's too bad that `<img src=>` and `<script src=>` work with `file://` but the rules are different for svgs. I guess there's no fix short of running a local/staging webserver for development -- which is what you have to do for any moderately-sized web project and up anyway exactly because of issues like this.

I'm going to port the jQuery-less fix into my theme, and I assume it'll make its way to the Starter theme as time permits.

It would be less confusing, and less redundant, if, if this is really a preview-only workaround, it was injected *by the generator* at preview-time, and just operated as a polyfill; `window.publiiSvgFix` can be generated from the svg files at preview time instead of making it a part of each theme.

**Comment by kousu** [comment]
For future reference, here is a long thread of web developers complaining about Chrome's decision to treat each file:// URIs as a distinct Origin: https://bugs.chromium.org/p/chromium/issues/detail?id=47416
They wontfixed it.

Firefox claims on their wiki (https://developer.mozilla.org/en-US/docs/Archive/Misc_top_level/Same-origin_policy_for_file:_URIs) to have a slightly looser policy:
> a file can read another file only if the parent directory of the originating file is an ancestor directory of the target file.

so keeping everything in the `preview/` folder should work, but I'm using Firefox 68.0.1 and experimentally it is behaving like Chrome. Maybe they gave in and synced their security with Chrome and forgot to update the wiki.
