### ISSUE TITLE
Not able to open it.

### ISSUE THREAD

**Issue by tiotrom** [GetPublii/Publii#549]
I am trying it in Manjaro Gnome from AUR and AppImage. None can open the program. For the appimage I see this error

```
[tio@tio-pc ~]$ '/home/tio/Applications/Publii-0.35.1_9e7fdf86af4aefd9f6a05f9bc2d0d1ea.AppImage' 
qt5ct: using qt5ct plugin
The setuid sandbox is not running as root. Common causes:
  * An unprivileged process using ptrace on it, like a debugger.
  * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Trace/breakpoint trap (core dumped)

```

**Comment by dziudek** [comment]
Hi,

The only way to run AppImage version of Publii on some Linux distributions is using ` --no-sandbox` switcher. It is an Electron issue: https://github.com/electron/electron/issues/17972

**Comment by tiotrom** [comment]
I see. What about the AUR version?

**Comment by dziudek** [comment]
Electron packager as I see does not support this kind of package.

**Comment by tiotrom** [comment]
I reported it here https://aur.archlinux.org/packages/publii - is it not maintained by you guys?

**Comment by dziudek** [comment]
We do not manage this one :)

**Comment by tiotrom** [comment]
I was thinking since is using "https://cdn.getpublii.com/Publii-$pkgver.rpm" and still presents itself with a similar issue like nor being able to open it, is this not a general problem and not only an appimage issue?

**Comment by dziudek** [comment]
This issue as far as I know is connected with AppImage and only some linux distributions - more details are available in the mentioned issue on the Electron repository :)

**Comment by tiotrom** [comment]
As I mentioned the rpm doesn't work either - I reported here https://aur.archlinux.org/packages/publii/

**Comment by julianxhokaxhiu** [comment]
@dziudek Hi I am the maintained of the AUR package and all I do is convert the RPM to a tar.xz and install it, the exact way it comes within the RPM. To be honest I didn't had time to test it on a Linux Desktop recently, but it used to work. Did you do any change recently in the RPM? Maybe some dependencies? I'll try to find some time to test it and see if some packages as dependencies are missing. In case just let me know, thanks.

**Comment by dziudek** [comment]
Hi @julianxhokaxhiu,

v.0.35.1 updated some dependencies e.g. sharp which now is available also for linux. It could break the package as sharp needs manual changes inside before packaging - ASAR packager have a problem with symlinks which are used in the sharp build files.

**Comment by julianxhokaxhiu** [comment]
Is there a place where I can see which dependencies pulls the RPM? So I can reflect those in the AUR package. Thank you in advance.

**Comment by dziudek** [comment]
@julianxhokaxhiu - the only place with dependencies for the app is `app/package.json`, but as I suppose dependencies are also related to the process used by `electron-packager` and I have no idea which additional dependencies it uses :/

**Comment by julianxhokaxhiu** [comment]
Can I please ask if you can assign this to me, so I have it as a reminder to get it fixed? Thank you in advance.

**Comment by tiotrom** [comment]
Update: it works now! Manjaro got a big system update and apaprently several appimages that didn't work, work now. Appimage launcher and electron got update in the process. Maybe that fixed it?

**Comment by mxmilkb** [comment]
Currently getting;

```
curl: (60) SSL: no alternative certificate subject name matches target host name 'cdn.getpublii.com'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
==> ERROR: Failure while downloading https://cdn.getpublii.com/Publii-0.35.2.rpm
    Aborting...
Error downloading sources: publii
```
