### ISSUE TITLE
Menu Bar is not hidden in linux

### ISSUE THREAD

**Issue by mx666pl** [GetPublii/Publii#551]
Hi,
In 0.35.1 (build 11963) Beta Menu bar is not hidden.
After clicking one of the menu bar options Publii crash (without saving).

OS checked: Fedora 30, Linux Mint 19.2

**Comment by dziudek** [comment]
Hi,

Could you provide a screenshot of this issue? I am not having these distributions, and it will be faster than creating a VM with them :)

**Comment by mx666pl** [comment]
![publi_f30](https://user-images.githubusercontent.com/24990575/63618050-5a087180-c5eb-11e9-81e9-cae42fc9d3d3.jpg)
It's from Fedora 30.

**Comment by dziudek** [comment]
Hi,

Thank you for the screenshot - I suppose that the latest build could be created with the wrong flag or the menu appears anyway on some distributions. During tests I was unable to see it, but I have tested it on Ubuntu.

I will try to fix it in v.0.35.2

**Comment by dziudek** [comment]
Fixed by changes in #575
