### ISSUE TITLE
[Feature Request] Payment System with PayPal

### ISSUE THREAD

**Issue by VladimirCores** [GetPublii/Publii#557]
As a user of Publii CMS I would like to have an option to provide products for visitors of my site backed by Publii CMS and checkout mechanism with PayPal. 
The payment system contains:
- User account page
- Products page with catalog divided into sections with filter
- "Basket" button
- Shopping cart page
- Checkout page
- Confirmation page
- Tracking page

**Comment by DQvsRA** [comment]
For example, integrate with https://www.braintreepayments.com

**Comment by sunk818** [comment]
@DQvsRA there are services like Shopify or WordPress with ecommerce plugins that are already developed and ready to go. I feel Publii is for publishing blogs in a static format. It'd be a long and hard road to do what you ask for Publii. I don't really see the benefit.

Years ago, I used AmeriCart (now AmeriCommerce https://www.americommerce.com/examples) for a static site to have "shopping cart" feature/service. PayPal also has integration... there are so many options already.

**Comment by dziudek** [comment]
Hi,

We have plans to add some basic ecommerce features for Publii, but it will be most probably implemented after other two big milestones: block editor and multilanguage support. So I suppose that ETA is in 2020 for that.

**Comment by YoavRheims** [comment]
Perhaps include Snipcart.com too? Version 3 is coming soon (that's what they said) and it looks super promising. I know you can do it easily already.

**Comment by YoavRheims** [comment]
Or, another open source project such as https://www.vendure.io/

**Comment by DQvsRA** [comment]
@YoavRheims the tool you proposed looks interesting, thanks.

**Comment by YoavRheims** [comment]
And, maybe, Shoprocket which is very similar service to Snipcart. Their next version might be even better than Snipcart imo.

**Comment by DQvsRA** [comment]
@YoavRheims thanks for your suggestion, I think I saw this product from VueJs facebook page, it looks very useful with a lot of options like taxes and shipping.

**Comment by SecondLife365** [comment]
I second to that Paypal integration, and it would be nice to see some support for cryptocurrency payments too.

**Comment by dziudek** [comment]
Such features will be developed as a plugins so I am closing this issue as it won't be a core Publii feature.
