### ISSUE TITLE
Publii 0.35.1 execution problem

### ISSUE THREAD

**Issue by erotavlas85** [GetPublii/Publii#565]
Hi,
I just updated Publii from 0.35 to 0.35.1 and now it does not start. I'm using ubuntu 16.04 64 bit and I get this error.
```
Something went wrong installing the "sharp" module

/lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /opt/Publii/resources/app.asar.unpacked/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
```
I made a symlink as described [here](https://stackoverflow.com/questions/48306849/lib-x86-64-linux-gnu-libz-so-1-version-zlib-1-2-9-not-found). Moreover, I tried to remove sharp folder without success.
Any idea?

**Comment by dziudek** [comment]
Hi,

The deb package for Publii v.0.35 is here: https://send.firefox.com/download/59bfddfa1d3706ad/#8lHTtW31YGgGrMlgozls5Q

**Comment by erotavlas85** [comment]
Thank you, I think you should mention this fact on download web page.

**Comment by dziudek** [comment]
To be honest - linux distributions have so many quirks and listing them all would generate very long list on the download page - and as long text it won't be read by anyone ;) Also Ubuntu 16.04 is a quite old release.

**Comment by erotavlas85** [comment]
> To be honest - linux distributions have so many quirks and listing them all would generate very long list on the download page - and as long text it won't be read by anyone ;) Also Ubuntu 16.04 is a quite old release.

Ubuntu 16.04 is still supported up to 2021. However, it would be enough to state OS requirements on the download page.
