### ISSUE TITLE
Failed to get index.html.zip from CDN

### ISSUE THREAD

**Issue by greytear** [GetPublii/Publii#566]
Following documentation about creating a website on Netlify, on point 3, the link to "our CDN" leads to a SSL error
![Captura de ecrã de 2019-09-16 17-59-03](https://user-images.githubusercontent.com/9157356/64977804-03b9e600-d8ac-11e9-871a-93d7b780af6a.png)

**Comment by YoavRheims** [comment]
I corrobre, looks like the subdomain was not included in the certificate. Example: https://cdn.getpublii.com/themes/qf_1.4.1.0.zip

**Comment by greytear** [comment]
Seems to be working now. This issue can be closed.

**Comment by YoavRheims** [comment]
Yup! Fixed.
