### ISSUE TITLE
Make possible to store site sources not only on local disk

### ISSUE THREAD

**Issue by cstamas** [GetPublii/Publii#582]
Idea is basically to enable teamwork (or even just "time share" on same site, if not true concurrent work) for n00bs, while still enjoying benefits of distributed storage.

Some ideas:
* keep sources in some git repo (github/bitlab/whatever) -- a transparent operation could transparently clone, edit locally and commit+push on save (or publish?)
* keep sources in S3 bucket? This could basically mimic local file access, no need for commit, sync
* FTP/sftp/etc. So maybe like some VFS?

**Comment by cstamas** [comment]
Just spotted this: https://github.com/GetPublii/Publii/issues/199

Fair arguments, but then please let some tech-savvy user set up some non-tech person Publii in way to achieve this. Ie. by adding some "hooks" (ie. batch/scripts) to execute after some actions?

**Comment by dziudek** [comment]
Any custom operations after rendering a website will be probably possible in the future as a plugin. We have no plans to add such features as a part of the core.
