### ISSUE TITLE
Mobile style apparently broken

### ISSUE THREAD

**Issue by ea1het** [GetPublii/Publii#583]
Hi there, 

I've been using Publii for a while like, always working like a charm. In the last 50 days I didn't publish anything new but today I did a new publication and found the mobile version was not showing as expected. Looks like the new publications don't respect CSS blocks sizes. 

I've tried typing simple text and apparently something gets broken IMHO when we start including bullet points and more text blocks. I've captured couple of screenshot from my mobile phone to explain what I'm seeing, but, if you just surf the web to my website ([https://0x30.io](https://0x30.io), hosted in GitHub Pages) you s obtain should same results. 

In addition to the above, i thought the mobile version broken could be only related to a single template, so I changed the template. Unfortunately, that didn't solve the problem. 

Note: all older publications are shown perfectly. 

---

In this picture you see the CSS blocks are respected:

![photo_2019-10-07_20-15-33](https://user-images.githubusercontent.com/30727873/66337341-3e5cee80-e93f-11e9-95e9-bd05cadc1bae.jpg)

---
In the post page, you see the CSS blocks are not respected and width expands the size of the mobile screen (the windows):

![photo_2019-10-07_20-15-30](https://user-images.githubusercontent.com/30727873/66337339-3e5cee80-e93f-11e9-84f2-e35e25aecd1d.jpg)

**Comment by bobmitro** [comment]
Hi,
To report any issue related to the themes please use our forum. This Github repo is more application-oriented than the addons. Thank you in advance.
https://getpublii.com/forum/
