### ISSUE TITLE
Upload the website to Infura IPFS 

### ISSUE THREAD

**Issue by wuniversales** [GetPublii/Publii#585]
The truth, this would be great, I hope it is added to the project, I leave the api here ...

https://infura.io/docs/ipfs/post/add

When uploading the website to infura ipfs, which publii shows the hash of the website, it would be great and very useful.

Thanks for the good work, regards.

**Comment by dziudek** [comment]
Hi,

I have note this deployment method as a possible plugin in the future. As we want to release plugin support later this year, we won't add any new deployment methods to the Publii core - all new deployment methods will be developed as plugins.
