### ISSUE TITLE
Unable to save global settings

### ISSUE THREAD

**Issue by adrian5** [GetPublii/Publii#589]
When going to **Global settings** (e.g. to set time format to 24h) and clicking Save Settings, nothing happens. When I leave the settings page and then reopen it, the time is still 12h.

* Publii: v.0.35.2 (build 12011) AppImage
* OS: (X)ubuntu 18.04

**Comment by joegasper** [comment]
Same issue, can't save any global settings.
Publii: 0.35.2 (build 12011) Beta
OS: Windows 10 Enterprise 1903 (18362.418)

**Comment by atomGit** [comment]
same here on Publii 0.35.3-1, manjaro

for me, creating a site wasn't enough - i had to change site settings and not just any settings, though i don't which site setting enabled saving global settings

**Comment by kuranai** [comment]
Thanks @atomGit for the tip. I had to go the the site settings and hit the blue button "save settings". After that, I was able to save the global settings. The green "save & preview" button in the site settings  seems to not help with this behaviour.

**Comment by dziudek** [comment]
I have discovered today that this problem occurs only when there is no selected website and user opens global settings. Fix will be applied in v.1.0.0

**Comment by cristian-milea** [comment]
Save settings problem still happening.

- publii/now 0.36.1 amd64 [installed,local]
- OS: Ubuntu 20.04 LTS / kernel-release 5.4.0-37-generic

I tried to follow the tutorial for dropbox collaboration and can't seem to save the **Sites location** or any other setting there. I click save, I get the warning about the folder but nothing happens. If I close and reopen App Settings, the folder path is the old one.

Once I accept the license agreement on the first screen, a "Publii" folder is created in /home/Documents/ and nothing happens there when trying to save any settings. Also tried with a "/home/Documents/test" folder and still doesn't work.

**Comment by cristian-milea** [comment]
Update on this. 

I downloaded the AppImage version and ran that with sudo and now the App Settings page works.
