### ISSUE TITLE
Improve SVG Accessibility

### ISSUE THREAD

**Issue by YoavRheims** [GetPublii/Publii#591]
Accessibility for SVG images can be improved. Check this out: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Role_Img#SVG_and_roleimg

**Comment by bobmitro** [comment]
Where exactly?

**Comment by YoavRheims** [comment]
The share buttons for example. I can create a pull request and do it myself.

**Comment by bobmitro** [comment]
This is related to the themes, not the app, so to report any issue/feature connected with Publii theme please use our forum https://getpublii.com/forum/

Ps:  What theme for example?

**Comment by YoavRheims** [comment]
Oh, sorry about that.

Technews for example, didn't checked the other yet. Opening a pull request
there are few other improvements.

**Comment by bobmitro** [comment]
This is an old theme and requires an update similar to the Simple or Tattoo theme. I'm afraid,  due to lack of time it has to wait.

**Comment by YoavRheims** [comment]
I understand. I can do it myself if the themes located in this repository are also used for the themes.

**Comment by bobmitro** [comment]
They are not.

**Comment by YoavRheims** [comment]
I see. Is there a public repository for them?

**Comment by bobmitro** [comment]
Unfortunately not.

**Comment by dziudek** [comment]
I am closing this issue as it is not strictly related to the app. You can continue discussion on https://getpublii.com/forum if necessary.
