### ISSUE TITLE
Can not open publii after configuration missing

### ISSUE THREAD

**Issue by FachrulCH** [GetPublii/Publii#592]
# Problems
When I open publii.app it throw error:
![image](https://user-images.githubusercontent.com/10245158/66850146-692fee00-efa2-11e9-95b7-910e6c206bbf.png)
I try to delete the app and re-install from .dmg but result remain same, can't open publii

# Context
I have wrong configured publii in some directory, then i delete all inside the folder, now when ever i open publii it give me error (as above screenshoot) it said missing configuration `Publii/config/app-config.json`
My question is, how to generate this file again? i try reinstall publii but it keep throw me same error

# Step to reproduce
As far as i remember:
- Fresh Install publii (at first i can open)
- Delete configuration directory publii (default /Documents/Publii/)
- Close publii, and reopen
- Throw error

# Configuration
- MacOS mojave 10.14.6
- App Publii-0.35.2

**Comment by dziudek** [comment]
Hi,

Are you sure that you have removed the whole /Documents/Publii catalog? For me after such operation Publii starts like a fresh install. Maybe you have removed only config catalog? If yes - please rename your Publii catalog to e.g. __Publii and then please try to run app again. For me it works fine. Then you can move necessary files to the newly created Publii directory.

**Comment by FachrulCH** [comment]
Ah yeah, got it solved after renamed the Publii directory

My observation, it got error when i had /Documents/Publii with empty files, only log directory inside

![image](https://user-images.githubusercontent.com/10245158/66987814-a05de680-f0eb-11e9-9fab-47c2b4a6641e.png)

It solved after i deleted the folder then open publii.app again as fresh install

Thank you :)
