### ISSUE TITLE
Provide way to specify alternative S3 endpoint 

### ISSUE THREAD

**Issue by arthurlogilab** [GetPublii/Publii#596]
AWS is not the only entity providing S3 bucket compatible hosting, a number of other compatible endpoints can be used. It would be nice to be able to use them directly from Publii by having an option to override the s3 endpoint.

**Comment by aadrian** [comment]
> .. by having an option to override the s3 endpoint...

Many also have custom URL for the AWS buckets too.

This seems to be a general issue with the other Server "urls" too, not just S3 (e.g. #605 )

It's good that there are defaults, but it would be much more helpful if all these URLs would be an input field (with the default current value in it). This way it wold work out of the box, but it would be still modifiable.

**Comment by pandel** [comment]
+1 - I also opt for Minio S3 as endpoint!
