### ISSUE TITLE
Can't upload to Google Cloud

### ISSUE THREAD

**Issue by jmcoelloidonia** [GetPublii/Publii#597]
When uploading to Google Cloud it shows a progress bar with multiple elements however only "files.publii.json" is created, any other file is completely missing.

Deleting files.publii.json and trying again does not solve the issue. Setting a prefix does not fix the issue.

"Test connection" button in Server section shows a success message.

- connection-debug-log.txt is empty.
- hard-upload-errors-log.txt contains an array of (apparently) every file but files.publii.json itself.

No error is shown while uploading.

Publii: v.0.35.2 (build 12011) Beta .deb
OS: Lubuntu 19.04

**Comment by dziudek** [comment]
Hi,

Do you have anything in the `connection-log.txt` file? There should be more details about the hard upload errors.

**Comment by jmcoelloidonia** [comment]
Ok, I didn't check this file and the error is clear:

> ApiError: Cannot use ACL API to set object policy when object policies are disabled.

I'm using per-bucket ACL but I can make the change to per-object ACL. Any chance per-bucket ACL will be supported?

Thank you!

**Comment by dziudek** [comment]
Hi,

If I correctly understand, the issue is caused by fact that during uploading files I set:

```
public: true
```

?

I am using the per-object ACL, because the files.publii.json can be non-public (it contains a list of all website files and is used only for the sync purpose). With per-bucket ACL it won't be possible.

**Comment by jmcoelloidonia** [comment]
Makes sense to me, thank you!

**Comment by krissydymaxiongroove** [comment]
So what was the resolution here? I'm unable to sync to google cloud and I'm receiving no error message. Files just won't upload.

**Comment by krissydymaxiongroove** [comment]
Actually, scratch that. It does upload a single file - files.publii.json 
Not sure what that's about.
