### ISSUE TITLE
Feature: add possibility to fetch data into templates from several sources

### ISSUE THREAD

**Issue by supersexy** [GetPublii/Publii#601]
It would be a killer feature if Publii was able to fetch data from several sources and generate pages from templates with that data, similar to [Hugo data templates](https://gohugo.io/templates/data-templates/). This is the only feature that is missing to make Publii dominate world :)

**Comment by Viteok** [comment]
Very good idea👍

**Comment by devopstoday11** [comment]
Hi, any plans on supporting Hugo themes soon in Publii?  Especially Hugo Documentation themes.

**Comment by dziudek** [comment]
I am closing this issue, because at this moment we have no plans to implement such feature.
