### ISSUE TITLE
Related post selection based only on tags

### ISSUE THREAD

**Issue by drm-wntd** [GetPublii/Publii#603]
Hi!

It seems to me the related posts selection is based on post titles and on tags.

Is there a way to select the related posts based only on tags? because with very different titles, even if they all have the same tags, no related post is currently showing.

Currently using version 0.35.2 on windows 10

**Comment by drm-wntd** [comment]
On version 0.33 (linux appimage) even if the titles didn't have any matching words, the related post were selected by the tags and were showing fine.

**Comment by dziudek** [comment]
Hi,

Good idea - I will add an option to specify if the releated post should use titles, tags or both of them in v.0.35.3 :)
