### ISSUE TITLE
Using a different theme than 'simiple' copies the .git directory too.

### ISSUE THREAD

**Issue by aadrian** [GetPublii/Publii#604]
Using a different theme than 'simiple' theme copies the .git directory too :(.

This breaks Git if one wants to use and sync with GIT the `Publii\sites\mysite` since `Publii\sites\mysite\input\themes\mercury` (or some other theme) is also a different git repo.

Thank you.

**Comment by dziudek** [comment]
@bobmitro - please check if the theme packages contains unnecessary .git directories (please remember that it is a hidden catalog due dot at the beginning of the name).
