### ISSUE TITLE
GitHub Enterprise, and others Git Servers.

### ISSUE THREAD

**Issue by aadrian** [GetPublii/Publii#605]
At the moment the 'server' url for GitHub seems to be hardcoded :( .

Please make it an input field, so that users can configure it.

This would be important if one is using the "Enterprise" version of GitHub or some other API compatible Git Server (e.g. like [GitBucket](https://gitbucket.github.io/)  ), since the URL won't be in this cased https://github.com , but something else.

Thank you.

**Comment by dziudek** [comment]
Hi,

I will add an option to specify API server address in the upcoming 0.35.3 release :)
