### ISSUE TITLE
Package managers for Windows  and OSX too.

### ISSUE THREAD

**Issue by aadrian** [GetPublii/Publii#606]
Please add "package manager" support for Windows and OSX too.

E.g. https://chocolatey.org/  for Windows would allow to just do `choco install publii` , and https://brew.sh/ for OSX would allow just `brew cask install publii`.

The main advantage would not be that much in the initial installation, but keeping the machines up to date. E.g. with `choco upgrade all` makes sure a machine gets the **all** software to the latest update :) .

Thank you.

**Comment by dziudek** [comment]
Hi,

I will leave this issue for the future, at this moment it seems like a very niche feature ;)

**Comment by dziudek** [comment]
Closing this issue as it is still very niche feature, so we have no plans to handle such features at this moment.

**Comment by joegasper** [comment]
This may still be niche feature, but just want to show the process for updating Windows winget package manager to enable installing Publii ("winget install publii"). These are [my notes on how I do it](https://gist.github.com/joegasper/5fa53706510253ceb3a09be28c5f323d), and it can be automated with a GitHub Action (at the bottom of my gist). Thank you for your consideration.
