### ISSUE TITLE
[Payments] Stripe Integration

### ISSUE THREAD

**Issue by VladimirCores** [GetPublii/Publii#607]
Is it possible to integrate Stripe payments?
https://stripe.com/docs/web

**Comment by dziudek** [comment]
Hi,

At this moment you have to implement all scripts and mechanism on your own through theme customizations. In the next releases - 1.1.0 or 1.2.0 we will focus on the ecommerce functionality for Publii.

**Comment by DQvsRA** [comment]
Could I participate somehow in the development process?

**Comment by dziudek** [comment]
This feature will be implemented probably in the future as a plugin not a core feature, so I am closing this issue.
