### ISSUE TITLE
Missing post_image class

### ISSUE THREAD

**Issue by bobmitro** [GetPublii/Publii#608]
When te image does not have a caption the ` post__image ` class is added and it's supposed to be like that. 
The situation looks different when the image still does not have the caption but has alignment class applied like `post__image-centered`, then the `post__image` class is missing.

In short, the `post__image` class should always be added to the image in the post content.

**Comment by dziudek** [comment]
The editor can temporary generate wrong CSS classes (duplicated `post__image`) but after save it will be removed. There is no other performant way to fix this issue in other way.
