### ISSUE TITLE
JSON config files need formating with pretty print!

### ISSUE THREAD

**Issue by aadrian** [GetPublii/Publii#609]
The current JSON files (e.g. in /config) are not formatted with pretty print (in fact they lack formatting completely :( )

Because of this, **diffing for changes** in a site (with a VCS like Git, svn or just by directories) is quite hard/useless, since everything is on one line in those files :( .

Since every non-trivial JSON library can pretty print, please use this functionality when serializing the files to disk.

Thank you.

**Comment by dziudek** [comment]
Good idea - I will add this feature in v.0.35.3 as it needs small code changes.
