### ISSUE TITLE
Usability - Menu Item Editor for Pages

### ISSUE THREAD

**Issue by aadrian** [GetPublii/Publii#611]
When using the Menu Editor to add Menu Items of type Post (Page):
 - the "Label" field is a mandatory field - it's not marked with '*' but there's a validation when saving
 - the user has to type the name for the Post (Page) - instead of **just being prefilled** by the selection of the page.

Thank you.

**Comment by dziudek** [comment]
I have reviewed this issue and at this moment I do not see any additional action required so I am closing this issue:

* required fields are not marked with "*" anywhere in Publii UI and it is first request for it
* dropdown with posts list contains list of pages (it appears when you click on the post selection field)
