### ISSUE TITLE
Option to turn off "blog mode", or activate "simple site mode".

### ISSUE THREAD

**Issue by aadrian** [GetPublii/Publii#612]
It would be very useful and user friendly if there were a simple switch to turn off the "blog mode", since many sites are not blogs, just simple sites with pages (not really "posts"). 

To achieve the "simple site mode" (or "non-blog" mode), at the moment for each site the user has to change way to many options:
 - Theme/Post Options/Display category name -> Disabled
 - Theme/Post Options/Display author name -> Disabled
 - Theme/Post Options/Display date -> Disabled
 - Theme/Post Options/Display author bio -> Disabled
 - Theme/Post Options/Display comments -> Disabled

and I'm sure I forgot a few of the granular settings :( .

Thank you.

**Comment by bobmitro** [comment]
Hi Aadrian,

Thank you for your suggestion. Publii was designed as a blogging tool and in my opinion, it should works as it works now. This will probably change when we add support for Pages, what will happen next year (I do hope).

**Comment by dziudek** [comment]
I am closing it as we will implement Pages feature in v.1.0.0 so there will be a separate issue for that.
