### ISSUE TITLE
Should not export media for draft or trashed posts

### ISSUE THREAD

**Issue by drm-wntd** [GetPublii/Publii#614]
Hi!

When I put some post in the trash or set them as draft, the post themselves (html pages) are not exported in the final output but the media files contained in these posts are exported. The media files (pictures) from the post should not be exported in the preview or output directory if the post they are in is trashed or saved as draft.

**Comment by dziudek** [comment]
Hi,

You're right - at this moment media directory is not filtered for the draft or trashed posts - we will fix it in v.0.35.3.

Thank you for finding this bug :)
