### ISSUE TITLE
Share using "addtoany"

### ISSUE THREAD

**Issue by wuniversales** [GetPublii/Publii#617]
I think it would be good to use "addtoany" to share the post, or the web.
https://www.addtoany.com/buttons/for/website
I leave an example working with publii
https://buscatope.runkodapps.com/
The option to share can be displayed below on the left.
Regards

**Comment by dziudek** [comment]
It can be easily added by theme modification or thanks to custom HTML feature so there is no need to add it by default. For basic needs the sharing buttons available in themes are enough and do not uses third party scripts.
