### ISSUE TITLE
SFTP initial upload problem

### ISSUE THREAD

**Issue by alexandrpaliy** [GetPublii/Publii#618]
Hello.

publii-0.35.2 . Latest available release atm.

**Prequisites:**  
I've made local publii project, and I try to upload it to my web-server via SFTP (with key).  
At webserver, website directory is empty. User, which I will use to connect via SFTP, have all needed rights for writing into target directory.  
In publii, if I go to "Server" settings, and press "Test connection" - it says that everything is fine.

**Expected behavior:**  
I press "Sync your website", and all needed files are successfully transferred to the server.

**Real behavior (problem):**
First (upper) progressbar successfully finishes with 100% (green light).  
Second - hangs at ~ 5%. Like this:  
![image](https://user-images.githubusercontent.com/5554048/69245193-0e943e00-0baf-11ea-86d0-eabd0df26dc1.png)
I tried to wait for ~ 30 minutes (expected to see something about timeout issue) - no, it just stays the same.  

connection-log.txt:  
```
ERR (2): Error: Failed to get myproject123/files.publii.json: No such file [<- files.publii.json]
Founded 85 operations to do
```

-------------------  

For me, I solved this by manually uploading files to server (not via publii) - after this publii starts to upload files via SFTP correctly.

**Comment by dziudek** [comment]
Hi,

Do you have any errors under `connection-error-log.txt`, `connection-debug-log.txt` or inside `deployment-errors.log` and `deployment-process.log` files?

**Comment by alexandrpaliy** [comment]
Sorry for waiting.

deployment-errors.log - empty  
deployment-process.log - empty  

connection-error-log.txt, connection-debug-log.txt - I do not have such files.  
![image](https://user-images.githubusercontent.com/5554048/70160178-bdae3a80-16c2-11ea-99af-656f7a9054ec.png)

**Comment by alexandrpaliy** [comment]
Still facing this issue. Still using workaround, which I mentioned before: performing initial upload manually.

The only log-file, which (at my opinion) has useful information, is still connection-log.txt
As far is I understand what's going on, publii refuses to make initial upload because remote directory is empty - so publii can't even check "what's already there" (no remote file files.publii.json available)

**Comment by dziudek** [comment]
Hi @alexandrpaliy,

In the nearest Publii prerelease 4  (the current prerelease 3 is here: https://getpublii.com/forum/topic/publii-0-36-prerelease-3-come-help-us-make-it-better/ ) I will fix few bugs in the SFTP implementation - I do hope that it will also fix your issue :)

**Comment by dziudek** [comment]
Hi @alexandrpaliy - please check prerelease 4 - I have probably fixed a reason of your problem during SFTP connection: https://getpublii.com/forum/topic/publii-0-36-prerelease-4/ :)

**Comment by ivorgri** [comment]
I had the same problem, but using the 0.36 prerelease 4 fixed this for me. Thanks for the fix @dziudek!
