### ISSUE TITLE
Deploying output folder has paths to the preview folder

### ISSUE THREAD

**Issue by theasteve** [GetPublii/Publii#619]
When I deploy the `output` folder to github pages I see the paths for the source files linking to the `preview` folder. For example, when I deploy the `output` folder I see the following in some of the files links:

`<a href="../preview/jobs-2.html">`

Why is the `../preview` attached to the file path? it should be `../jobs-2.html`. 

How can I go about fixing this?

**Comment by dziudek** [comment]
Hi,

Could you specify which types of links are wrongly generated - if you can - please also provide a link to the repository where is a problem.
