### ISSUE TITLE
Preparation error

### ISSUE THREAD

**Issue by Pilvinen** [GetPublii/Publii#624]
I got this very verbose and helpful error after updating to 0.35.3 (build 12094) Linux version, and trying to synch with my website:

![](https://i.imgur.com/PXA2biV.png)

**Comment by Pilvinen** [comment]
After trying out "Preview your changes" I got this error which seems a bit more helpful:

`An error (1002) occurred during parsing index.hbs file. rendererInstance is not defined`

**Comment by popken** [comment]
similar problem on a mac 
https://github.com/GetPublii/Publii/issues/625

**Comment by dziudek** [comment]
Hi,

We will fix it in a few minutes.

**Comment by dziudek** [comment]
The fix will be available soon - we have prepared a hotfix release

**Comment by Pilvinen** [comment]
Tried to download the hotfix. The download page has the new build number. But when I download and install the actual installation package and then run it I'm still on build 12094.

**Comment by bobmitro** [comment]
@Pilvinen What Publii version (windows?) do you use?

**Comment by Pilvinen** [comment]
Still on Linux. Downloaded the .deb package. Also tried the "alternative source", but the same thing happened.

**Comment by Pilvinen** [comment]
My working assumption is that the installation package accidentally wasn't updated to the new build.

**Comment by bobmitro** [comment]
I think our CDN has not yet refreshed the files, try with the "alternative source" - it should work now.

**Comment by Pilvinen** [comment]
That does not seem to be the case. But I will try again a bit later.

**Comment by Pilvinen** [comment]
One possible reason for it failing to update on your servers might be because the new build has an identical filename. That can sometimes cause issues with caching. Other than that I'm out of ideas.

**Comment by Pilvinen** [comment]
Seems to work now.

Because the package had **identical name** across builds it seems Ubuntu was using a cached version when installed through the graphical desktop. I got around this by forcing an install with dpkg from the command line.

For the future - if it's not terribly inconvenient, I would recommend that you consider using filenames which change across builds, even if the change is a minor one.

This ticket got a bit sidetracked. But the original issue is, indeed, fixed by this quickfix. Thank you for the fast response. Your support is, as always, excellent.

**Comment by dziudek** [comment]
@Pilvinen - yes I know, but npm run build won't work with 0.35.3.1, that's why I have decided to not change the package name in this case. For the future cases we will use the build in the name for such situations.
