### ISSUE TITLE
Reendering Error after update to Publii 0.35.3

### ISSUE THREAD

**Issue by popken** [GetPublii/Publii#625]
Hi, 
I just updated to 035.3. I can't reender any sites, I get the error message:

An error (1002) occurred during parsing post.hbs file.
rendererInstance is not defined

**Comment by dziudek** [comment]
Hi,

We will fix it in a few minutes.

**Comment by popken** [comment]
sorry, it was an issue with my themes. I updated my themes and now it's working. I feel stupid.

**Comment by dziudek** [comment]
@popken - no, it is also an issue in Publii - just new themes have no problem with new version, but 0.35.3 breaks backward compatibility. Unfortunately the issue appears on my development machine randomly so it was hard to detect before the release. 

Now I am packaging fixed version.

**Comment by popken** [comment]
updated, all themes, even the older ones, are working fine. Thanks.
