### ISSUE TITLE
Page title suffix with pagination page number

### ISSUE THREAD

**Issue by dziudek** [GetPublii/Publii#634]
For adding custom titles for every pagination page, when pagination indexation is enabled.

So we need to add option like "Pagination title suffix", where by default we add value `- page %page_number%`.

**Comment by HippieSmack** [comment]
Did this ever get implemented?  It was targeted for 0.35.4 which doesn't look like it was ever released and I don't see it in 0.36.0 or 0.36.1

**Comment by garthkoyle** [comment]
Is there an update to this, or a workaround?

**Comment by dziudek** [comment]
@garthkoyle - you can consider using the `@pagination` global variable to generate additional text in the page title: https://getpublii.com/dev/pagination-global-variable/
