### ISSUE TITLE
Javascript bug when generating image

### ISSUE THREAD

**Issue by wuniversales** [GetPublii/Publii#640]
This is the real code:
`document.getElementById("prevista").innerHTML = '<br><strong>Vista previa</strong><br><img src="'+document.getElementById("httpimagen").value+'" alt="Generando vista previa... (Si es posible)" style="text-align: center;">';`
This is the generated code:
`document.getElementById("prevista").innerHTML = '<br><strong>Vista previa</strong><br><img src="'+document.getElementById(" data-is-external-image="true" httpimagen").value+'" alt="Generando vista previa... (Si es posible)" style="text-align: center;">';`

Using Publii v.0.35.3 (build 12104) Beta

**Comment by dziudek** [comment]
It seems to be an edge-case when code used in the post content interferes with post content code modifications. As it can be solved by scripts added in the footer/theme I think that it is not necessary to handle such case at this moment on the content modification scripts.
