### ISSUE TITLE
Trailing slash in @website.url

### ISSUE THREAD

**Issue by perifer** [GetPublii/Publii#641]
@website.url outputs `example.com/` instead of `example.com`. While this is consistent with other url:s it creates issues when concenating urls in a theme:

- `{{@website.url}}about` is a lot less readable than `{{@website.url}}/about`
- `{{@website.url}}about` will break when previewing since the the preview-url does not contain a trailing slash. Leaving out `{{@website.url}}` and just use `/about` will also not work when previewing since the url will be interpreted as "file:///about".

Can the trailing slash be removed?

**Comment by dziudek** [comment]
Due breaking API changes we won't implement this change.
