### ISSUE TITLE
Exporting all articles to markdown ?

### ISSUE THREAD

**Issue by shantee** [GetPublii/Publii#642]
Hello
I wonder if there is a way to export all posts to markdown files.
For exemple if I have 10 articles I would like to get 10 folders with my articles and its media if there are some linked to it.

**Comment by dziudek** [comment]
Hi,

There is no way to do it in Publii and we have currently no plans for such feature.

**Comment by ajeet001** [comment]
I have found a solution

https://getpublii.com/forum/topic/export-your-content-to-markdown/
