### ISSUE TITLE
Integration with commento.io

### ISSUE THREAD

**Issue by antoninadert** [GetPublii/Publii#648]
Integration with Disqus is cool but it doesn't respect user privacy. 
Commento.io has a nice interface and protects privacy.

Is it possible to integrate Publii with commento.io ?

**Comment by bobmitro** [comment]
It's more related to the theme, not to the app.

**Comment by wuniversales** [comment]
And an option in the themes to choose the comments server?

**Comment by gpsblues** [comment]
Hi,
I think you can edit **post.hbs** file and **partials/disqus.hbs** file:
```
    {{#if @config.post.displayComments}}
         <div class="post__comments">
            <div class="wrapper">
               <h2 class="h5">
                  {{ translate 'post.comments' }}
               </h2>
               **{{> disqus}}**
            </div>
         </div>
      {{/if}}
```
You can change disqus.hbs with another comments server code.
