### ISSUE TITLE
vscode theme setup?

### ISSUE THREAD

**Issue by labsforge** [GetPublii/Publii#654]
Hi,

First, this is awesome.
Second, this is super awesome.
Third, I need to setup a website theme, I already know handlebars and use it for our email templates, and on vscode I have an extension that loads a sample-data.json and generates the preview of the *.hbs file (never used partials, but some extensions can look for partials on the project), so I have both worlds "hot-reload" and a nice ide, but unfortunately I can't make it work.. 

So my question is: how to setup the environment for create/edit themes?

Kind regards & congratulations!

**Comment by bobmitro** [comment]
Hi, have a look at  https://github.com/GetPublii/Publii/issues/496

**Comment by labsforge** [comment]
Hi @bobmitro, I actually opened on vscode the root folder of the simple theme to get an overall idea of the structure, my question was more about on how to edit files and get an instant preview of the changes while editing the code.

**Comment by labsforge** [comment]
No secret sauce?

**Comment by JOduMonT** [comment]
@labsforge 
For the secret sauce, I would say; it's the core business of [TidyCustoms](https://tidycustoms.net) which is based on experience, so build your own experience and share it with us :p

This is how I started

1. VSCode and VSCodium have extensions for everything but also one which called: **[Handlebars Preview](https://github.com/chaliy/vscode-handlebars-preview)**

2. By [overriding a theme](https://getpublii.com/dev/theme-overrides/#js-header) (simple is a good base, Publii team maintain it and based few others themes on it)

3. By [creating custom templates](https://getpublii.com/dev/how-to-create-custom-templates/)

4. ToBeContinue hopefully with You

**Comment by labsforge** [comment]
Hi @JOduMonT, points 1 and 2 was what I did first, the only problem I have is to provide data to handlebars preview, if you could help me with that, I think I can move on to build the theme and add custom templates too.

**Comment by dziudek** [comment]
I am closing this issue as the issues section is not a perfect place to talk about things which are not strictly releated to the Publii app features/bugs. Feel free to continue the discussion on the forum: https://getpublii.com/forum/
