### ISSUE TITLE
Support for non x64 architectures

### ISSUE THREAD

**Issue by awafaa** [GetPublii/Publii#655]
Could we get binary builds for non Intel/AMD x86_64 architectures, primarily ARM64? There are several Windows based platforms available and more re coming, the same goes for Linux (especially chromebooks).

**Comment by dziudek** [comment]
Hi,

After 1.0.0 release we will consider this, but it will be strictly depended from the ARM64 support for our native dependencies.

**Comment by dziudek** [comment]
I am closing this issue due lack of bigger interest (also it seems that Windows ARM build have support for x86 apps) so creating additional build can be unnecessary and time consuming (additional build, additional tests on new platforms).

**Comment by alfredonodo** [comment]
Hi,
do you have any update?
Thank you

**Comment by alfredonodo** [comment]
Hi,
do you have any updates on this? Especially on GNU/Linux, as windows since version 11 can [emulate any amd64 application](https://learn.microsoft.com/en-us/windows/arm/arm64ec).
Thanks
