### ISSUE TITLE
Insecure mixed content detected

### ISSUE THREAD

**Issue by soulstamina** [GetPublii/Publii#658]
I have the following message from netlify after publishing a website using the mercury theme from Publii v.0.36.0 (build 12631) Prerelease 3

'Insecure mixed content detected  Although you have enabled HTTPS on your site, we’ve detected some content that’s still being served over an HTTP connection. Learn more about mixed content.'

In addition to this, the website displays inccorectly.

**Comment by YoavRheims** [comment]
Actually, Netlify's logs show which files are involved.

**Comment by soulstamina** [comment]
Forgive me but I am a novice, I have never built a website let alone deploy one.

The list includes: insecure link urls :insecure script urls: insecure img urls:

**Comment by YoavRheims** [comment]
You should use the Publii forum instead of Github then add the link of the
website.

**Comment by soulstamina** [comment]
ok. thank you
