### ISSUE TITLE
getPostsByTags returning wrong results

### ISSUE THREAD

**Issue by theasteve** [GetPublii/Publii#660]
I'm currently trying to return post by the following tag ids. `2,3,4,5,6,7,8,11` however what I get is the posts from tag ID 13. 
```
{{#getPostsByTags 9 [2,3,4,5,6,7,8,11] ""}}
    <h4 class="h3">{{ mainTag.name }}</h4>
        <ul class="list-none p-0 color-mid-background" id="jobs-list">
          <li class="py-1 px-2">
            <a href="{{url}}">
            {{title}}
            </a>
          </li>
        </ul>
{{/getPostsByTags}}

```
How is it that I'm getting the results for tag id 13? Is the array not the proper way to pass the tag ids?

**Comment by dziudek** [comment]
Hi,

Arrays are not allowed - please use string with IDs separated by comma:

```
{{#getPostsByTags 9 "2,3,4,5,6,7,8,11" ""}}
```
