### ISSUE TITLE
getPostByTags new syntax 0.34 not working 

### ISSUE THREAD

**Issue by theasteve** [GetPublii/Publii#661]
Publii version. 0.35.2
I'm currently unable to fetch posts using getPostByTags new sytax in version 0.34.
`{{#getPostsByTags "count=5&allowed=hidden,featured&tag_as=id&tags=1,2,3&excluded=1,2&offset=10&orderby=modified_At&ordering=asc"}`

The above snippet is from the documentation. However, when I use it I don't get any posts return. I do get posts return when I use the previous syntax.

```
{{#getPostsByTags 5 [2,3,4,5,6,7,8,11] ""}}
      <div>maintag: {{{mainTag.name}}}</div>
      <h4 class="h3">{{ tag.name }}</h4>

  <li>
      <h2>{{ title }}</h2>
      <div>{{{ excerpt }}}</div>
      <div>url: {{url}}</div>
  </li>
{{/getPostsByTags}}
```

Not sure what the issue is.

**Comment by dziudek** [comment]
Hi,

Please try to use:

```
{{#getPostsByTags "count=5&allowed=hidden,featured&tag_as=id&tags=1,2,3&excluded=1,2&offset=10&orderby=modifiedAt&ordering=asc"}
```

Seems that in the documentation there is a bug and there is `modified_At` instead of `modifiedAt`
