### ISSUE TITLE
Custom Helper documentation, creating a helper function not working

### ISSUE THREAD

**Issue by theasteve** [GetPublii/Publii#662]
Currently I'm getting a `Missing Helper` method when trying to launch the theme preview. 
```
module.exports = function (Handlebars) {
	return {
    verifyTagName: function(tagName) {
      let tagNamesNotToUse = ['Full Time', 'Apprenticeship', 'Temp']
      tagNamesNotToUse.forEach(tag => {
        if(tag === tagName){
          return false;
        }
      })
      return true;
    }
	};
};

```
I have the above code in `/themes/starter/helper.js` file. I also change the configuration to the following.
`    "includeHandlebarsInHelpers": true,`

As per the documentation shown here https://getpublii.com/dev/how-to-create-custom-handlebars-helpers/

However I get the error from this code.
```

    {{#each @website.contentStructure.tags as |tag|}}
      {{#verifyTagName tag.name}}
        {{#if tag.postsNumber}}
          <h4 class="h3">{{ tag.name }}</h4>
        {{/if}}
        <ul class="list-none p-0 color-mid-background" id="jobs-list">
          {{#each this.posts}}
          <li class="py-1 px-2">
            <a href="{{url}}">
            {{title}}
            </a>
          </li>
          {{/each}}
        </ul>
      {{/verifyTagName}}
    {{/each}}

```
The error is `MIssing: Helper`.  How can I go about solving this?

**Comment by dziudek** [comment]
> It is also possible to use Handlebars object instance - This scenario will require field includeHandlebarsInHelpers set to true under renderer section in the theme settings.

That's for 99.9% reason of your issue.

Please post your future problems as a post on our forum not here, because they are not a bugs but development questions.
