### ISSUE TITLE
'Responsive images mechanism' is creating unnecessary amount of files

### ISSUE THREAD

**Issue by fatmanm** [GetPublii/Publii#666]
Is there a way to disable 'Responsive images mechanism' completely? Or can we delete all images on responsive folder? Site will work fine?

The problem is it creates too many number of files. Putting pressure on server, build times etc. 

Let's say I have a post with 15 images, Responsive images mechanism creates 90 more images/files, totaling 105 images/files for a single post.

Thanks in advance.

**Comment by bobmitro** [comment]
Hi,
Your issue is more related to the theme settings than to the app. Check the config.json file; the next time, to get help with this kind of things please use our forum https://getpublii.com/forum/

**Comment by fatmanm** [comment]
Thanks for your very kind and explanatory reply.
