### ISSUE TITLE
Publii AppImage not running on Debian 9

### ISSUE THREAD

**Issue by SparkyCW** [GetPublii/Publii#671]
Hi!

I downloaded 2 AppImages:
Publii__0.35.3.AppImage and Publii-0.36.0-prerelease-3.AppImage
Tried to run each one on Debian 9 64-bit as shown below getting the same error message.
Please, can anyone help me with this?

luis@debian9:~/Programas/Publii$ ./**Publii__0.35.3.AppImage**

Something went wrong installing the "sharp" module

/tmp/.mount_Publii5mvkGA/resources/app.asar.unpacked/node_modules/sharp/build/Release/../../vendor/lib/librsvg-2.so.2: undefined symbol: cairo_tag_end

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues

------------------------
luis@debian9:~/Programas/Publii$ ./**Publii-0.36.0-prerelease-3.AppImage**

Something went wrong installing the "sharp" module

/tmp/.mount_PubliiqDfY9z/resources/app.asar.unpacked/node_modules/sharp/build/Release/../../vendor/lib/librsvg-2.so.2: undefined symbol: cairo_tag_end

- Remove the "node_modules/sharp" directory, run "npm install" and look for errors
- Consult the installation documentation at https://sharp.pixelplumbing.com/en/stable/install/
- Search for this error at https://github.com/lovell/sharp/issues
---------------
Many thanks

**Comment by dziudek** [comment]
Hi,

In the next prerelease planned for the upcoming week I will upgrade sharp to newest release 0.23.4 -> 0.24.1 - maybe it will help as there are some electron-related issues with sharp as I see on them issues list

**Comment by SparkyCW** [comment]
Hi!

Thanks for your reply, and thanks for your work!,

**Comment by dziudek** [comment]
Hi @SparkyCW ,

Due a lot of native bindings issues, we have disabled sharp on linux platform. So you should be able to run Publii prerelease 4 without problems: https://getpublii.com/forum/topic/publii-0-36-prerelease-4/

**Comment by SparkyCW** [comment]
> Hi @SparkyCW ,
> 
> Due a lot of native bindings issues, we have disabled sharp on linux platform. So you should be able to run Publii prerelease 4 without problems: https://getpublii.com/forum/topic/publii-0-36-prerelease-4/

Thank you, you are rigth!
Now I can run Publii

Kind regards
