### ISSUE TITLE
WP Importer An error occurred during parsing selected WXR file

### ISSUE THREAD

**Issue by jpu4** [GetPublii/Publii#675]
Using v.0.36.0 (build 12889) Prerelease 4
Windows 10

Exported XML file from wordpress site
Shows wp:wxr_version is 1.2

Select exported XML file in Tools > WP Importer 
Received error "An error occurred during parsing selected WXR file"

**Comment by dziudek** [comment]
Hi,

Please validate your WXR file with XML validator -> fix problems and try to upload again. WordPress sometimes outputs invalid XML files.

**Comment by jpu4** [comment]
Ah ok. Thanks. Will do!

**Comment by rhuddlestone** [comment]
Hi.  I am having the same problem when trying to import a WordPress file.   Where can I find the XML validator to fix the file?  Thanks
