### ISSUE TITLE
Regenerate Thumbnails does not start

### ISSUE THREAD

**Issue by kauron** [GetPublii/Publii#678]
I have a simple site with a single image, and when I try to regenerate the thumbnails to have the different sizes for responsive themes, the program seems to start but doesn't progress.

If launched from a console, there is nothing printed there, or in the logs.

I'm using version 0.35.3 (build 12104).

**Comment by kauron** [comment]
I've realized that the image file I had included had no extension (it was called just `background`), so maybe that was the cause of the error. Still, I'd have expected an error or for the image to be skipped, not an infinite wait.

**Comment by dziudek** [comment]
Hi,

I will handle this edge-case. Also I will check how to fix such problems for other situations to avoid infinite wait for the process end :)
