### ISSUE TITLE
Unable to access individual article in Sub-directory

### ISSUE THREAD

**Issue by surya304** [GetPublii/Publii#681]
1) I want to post a blog on my website using Amazon s3 in a sub Directory using prefix url /blog ( https://tribeloop.net ) 
![Image Pasted at 2020-3-4 12-27](https://user-images.githubusercontent.com/29607438/75889264-a3ffc900-5e52-11ea-9fda-dfe0f24af442.png)

2) I created the Main blog Listing page in  the subdirectory of my website ( https://tribeloop.net/blog ) 
3) But the Individual article is not getting linked from sub directory (https://tribeloop.net/blog )
4) Instead of accessing  this (https://tribeloop.net/blog/testingpost/ ) it is accessing this ( https://tribeloop.net/testingpost ) so the page is not loading  Refer Image 2 and 3 
![Image Pasted at 2020-3-4 12-53](https://user-images.githubusercontent.com/29607438/75889305-b67a0280-5e52-11ea-88d0-7f45ff93c80e.png)
**ON Clicking the link it Redirects to this page with no subdirectory which is /blog** 
![Annotation 2020-03-04 125958](https://user-images.githubusercontent.com/29607438/75889309-ba0d8980-5e52-11ea-953f-dccde6deff3e.png)

5) Please can anyone help me with this

**Comment by dziudek** [comment]
Hi,

You should set your domain name to  https://tribeloop.net/blog  not  https://tribeloop.net

**Comment by surya304** [comment]
It Works.
ThanYou @dziudek  For the reply really appreciate Your help
