### ISSUE TITLE
Flatpak Support

### ISSUE THREAD

**Issue by cwmke** [GetPublii/Publii#684]
Any chance of adding [Flatpak support](https://www.flatpak.org/)? I'm currently using the rpm package but Flatpak allows for cross-distro support on Linux with automatic updates through the OS for users instead of manual downloading and install. Thanks for developing this amazing tool!

[Flatpak Getting Started](https://docs.flatpak.org/en/latest/getting-started.html)
[Flatpak Electron Docs](https://docs.flatpak.org/en/latest/electron.html)
[Flathub](https://flathub.org/) - very popular flatpak app store

**Comment by dziudek** [comment]
Hi,

Electron builder used to build Publii does not seem to support Flatpak. What do you think about Snap? It seems to be supported: https://www.electron.build/

**Comment by cwmke** [comment]
Hey, I don't have anything against snap as it's pretty similar but it's tied to Ubuntu and requires a contributor license agreement whereas flatpak is decentralized and doesn't.

I stumbled onto [electron-installer-flatpak](https://github.com/endlessm/electron-installer-flatpak) while looking around. Maybe that could work? I think someday they may add support to electron-builder but no clue when that would be. electron-userland/electron-builder#512

**Comment by dziudek** [comment]
We have no plans to support anything what is not compatible with electron-builder as we do not want to complicate the app build process. To be honest - these packages are a total niche and at this moment we have more important tasks to do. If electron-builder has no official support for it - we won't support this format.

**Comment by cwmke** [comment]
That makes sense. I'll keep an eye on electron-builder support and bring it up again when they officially support it. I don't want to take away your attention from more pressing issues. :smiley:
Thanks!

**Comment by dziudek** [comment]
I am closing this issue as it seems that electron-builder won't support flatpak in the near future: https://github.com/electron-userland/electron-builder/issues/512 :/

**Comment by fungs** [comment]
Too bad, Flatpak is the only almost universal way to distribute software for Linux with an update channel built-in.

As of today, at least it seems that electron-builder supports creating flatpak bundles.
Also of relevance: https://docs.flatpak.org/en/latest/electron.html

**Comment by jgonzales20** [comment]
Maybe this can be reopened? There are many Flatpak only distro out there and electron support is now available
