### ISSUE TITLE
RSS/Atom Follow Button

### ISSUE THREAD

**Issue by cwmke** [GetPublii/Publii#685]
Many feeds have a RSS follow link or button that looks like the below image. Often they'll have the standard list with Twitter, Facebook, LinkedIn and then use "Feed" or "RSS Feed."

![download](https://user-images.githubusercontent.com/1923967/76672598-01d79380-656c-11ea-9dbc-e56e016ff9b9.jpeg)

**Comment by jeckyl** [comment]
Hi,

It's a very good idea to add an RSS feed on a site advocating resource saving.

**Comment by masvil** [comment]
Yup, it should be great.

**Comment by bobmitro** [comment]
Closed as this is for an implementation in a theme not in an app.
