### ISSUE TITLE
iframe wrapper clips content

### ISSUE THREAD

**Issue by anghelos** [GetPublii/Publii#686]
v.0.36.0 (build 12889) Prerelease 4
When embedding a Bandcamp album with tracklist (non-responsive, 350px by 588px), the post__iframe wrapper hides the lower part of the embed. 

Also, the preview generated directly from the post editor doesn't include the wrapper.

**Comment by dziudek** [comment]
Hi,

In the next prerelease planned for the next week, if you will add attribute `data-responsive="false"` to your iframe, then the post__iframe wrapper won't be added.
