### ISSUE TITLE
Writing the post excerpt?

### ISSUE THREAD

**Issue by ciokan** [GetPublii/Publii#689]
The generated excerpts are horrendous. They pull in h2 or h1 tags (whatever I have in the first paragraphs), they are inconsistent and they make the cards ambiguous (because the cards have variable heights)

I searched for a way to write my own excerpts but I didn't find a way to do it. Is there such a possibility?

**Comment by ciokan** [comment]
![Screenshot from 2020-03-24 20-13-12](https://user-images.githubusercontent.com/474948/77461898-f574f580-6e0b-11ea-9346-4b92d98de465.png)

**Comment by dziudek** [comment]
Hi,

Please check option **Hide custom excerpts on post pages**: https://getpublii.com/docs/website-settings.html

You will be able to write custom excerpts before readmore separator then.
