### ISSUE TITLE
My files are missing in my "Preview Location" folder???

### ISSUE THREAD

**Issue by jarredmoore** [GetPublii/Publii#691]
I set my preview loacation inside my /dev folder which contained all of my "local host" development files. When I "preview my site" does it wipe out the rest of my files that are in that folder?? 
![Annotation 2020-03-27 161538](https://user-images.githubusercontent.com/7459434/77801456-e3cb6200-7046-11ea-9e23-5fdf28c4c750.jpg)

**Comment by dziudek** [comment]
Hi,

By default Publii outputs preview files in a preview directory inside site files. If this option is set Publii will output the preview files to the specified directory. The preview process always removes all files not-related to the site, so for such case - yes - it will wipe out the content of the /dev folder. In your case you should create catalog folder like "/dev/publii-preview" - then preview output will be generated inside this catalog and will wipe out only content of the publii-preview directory.

**Comment by superboum** [comment]
Just to mention that this "feature" has just bitten again.
An acquaintance assumed that Publii would create an output in the pointed folder.
Instead, at the moment he previewed his website... he lost 140Gio of data!

I really recommend putting a warning when someone changes the "Preview location".
Or maybe even better, check if the folder is empty before setting the path.
If it is not, create a "Publii" folder inside the pointed folder and set the preview location to this folder.

**Comment by dziudek** [comment]
Hi,

I will address this issue in the upcoming v.0.38 release - I will add an additional notification after changing the preview directory

**Comment by Adrien-Luxey** [comment]
Good luck with that! I hope Publii gets the praise it deserves. You're doing a very good job at making static site creation delightful and conceptually simple. 
I'll stop spamming now, bye!
