### ISSUE TITLE
gitlab token replaced by string after making posts

### ISSUE THREAD

**Issue by Joseph-Smith** [GetPublii/Publii#693]
The string is name of variable like gitlabtoken-name of website.
I just keep pasting the token in and then delete the repo files on gitlab and then it works

v.0.36.0 (build 13098) Prerelease 5
win 7

**Comment by mrlinnth** [comment]
Having same issue with github pages.
Gitlab pages has an issue #692 and tried Github pages. Have this issue.
At least I can solve it by just copying the token again.

**Comment by dziudek** [comment]
Hi,

Did you changed your website name before the token values were replaced?

**Comment by mrlinnth** [comment]
Nope. 
And I faced this error only on the second sync.
So far I don't have to update token anymore.

**Comment by dziudek** [comment]
I have found a reason of this issue - it will be fixed in the next release: https://github.com/GetPublii/Publii/commit/101fad5fe68da5276cb38b5c682c41e6b11f10da
