### ISSUE TITLE
Disqus specification

### ISSUE THREAD

**Issue by Daudre-Vignier-Charles** [GetPublii/Publii#696]
Hi,

Disqus does not allow non-ascii characters in `this.page.title` but Publii allows it.
In other language than english, if `this.page.title` contain non-ascii characters, this lead to a bug.

Best regards,

Thank for your nice software :)

**Comment by dziudek** [comment]
Hi, 

We will remove the title param as it can be generated automatically by Disqus:

> Tells the Disqus service the title of the current page. This is used when creating the thread on Disqus for the first time. If undefined, Disqus will use the <title> attribute of the page. If that attribute could not be used, Disqus will use the URL of the page.
