### ISSUE TITLE
Gitlab Sync Fail when connecting to a project within a Group (with a custom domain)

### ISSUE THREAD

**Issue by noelnuguid** [GetPublii/Publii#697]
Publii: v.0.35.3 (build 12104) and Publii-0.36.0-prerelease-5
Server: Gitlab Pages

Hi, I am working on getting Publii to connect to a Gitlab Project with Pages. 

For example i have a gitlab project called `https://gitlab.com/projectname/blog` (note that its inside a group) and when I use it directly using the domain `projectname.gitlab.io/blog` it works pretty well and sync properly.

But if I use a custom domain such as `projectname.com`, I' no longer sure what to put in the Repository field. When i put there `projectname/blog`, I get this error during syncing:

<img width="611" alt="image" src="https://user-images.githubusercontent.com/16016730/78541285-fc4a3200-7827-11ea-8783-21c800a1e850.png">

Here are some of the log files.

Deployment Errors:

```
TypeError: Cannot read property 'id' of undefined
    at /Applications/Publii.app/Contents/Resources/app.asar/back-end/modules/deploy/gitlab-pages.js:169:42
```

Deployment Process

```
(!) CLIENT CREATED
downloadFilesList:  undefined
```

**Comment by dziudek** [comment]
Hi,

The issue is caused by fact that our current implementation of Gitlab does not support groups at all. I will see what we can do with that.

**Comment by noelnuguid** [comment]
> Hi,
> 
> The issue is caused by fact that our current implementation of Gitlab does not support groups at all. I will see what we can do with that.

Thanks for this sir. Looking forward to have this feature in place.

**Comment by straight-shoota** [comment]
I've managed to sync to a gitlab repository belonging to a group instead of my own account. It only works when you are an owner of the group (owner of only the repo might work as well). Repository name is the name of the repository (without the group).
Maybe this helps as a workaround for others facing this problem. But it should really be fixed that groups are properly supported.

**Comment by noelnuguid** [comment]
> I've managed to sync to a gitlab repository belonging to a group instead of my own account. It only works when you are an owner of the group (owner of only the repo might work as well). Repository name is the name of the repository (without the group).
> Maybe this helps as a workaround for others facing this problem. But it should really be fixed that groups are properly supported.

Thanks for effort on getting this done. Is this part of the latest release? 0.37.x?

**Comment by mtrimolet** [comment]
```patch
diff --git a/app/back-end/modules/deploy/gitlab-pages.js b/app/back-end/modules/deploy/gitlab-pages.js
index 1a4b72f9..f8d4454e 100644
--- a/app/back-end/modules/deploy/gitlab-pages.js
+++ b/app/back-end/modules/deploy/gitlab-pages.js
@@ -66,7 +66,7 @@ class GitlabPages {
                 let projectID = projects[0].id;
 
                 // Detect a case when repository name is only similar to the provided repository name (not equal)
-                if (projects[0].name !== repository) {
+                if (projects[0].name !== repository && projects[0].path !== repository) {
                     this.waitForTimeout = false;
                     app.mainWindow.webContents.send('app-deploy-test-error', {
                         message: {
```
