### ISSUE TITLE
Error loading external images 

### ISSUE THREAD

**Issue by yangjchen** [GetPublii/Publii#698]
I insert the external img links in the post , but in the preview ,image url is modified, the picture can't show, how do I use external img now?

eg：
The real link is:
[https://i.loli.net/2020/04/05/VdJODFPTzxUnmYA.jpg](url)
But when generating the page it appears this: [https://i.loli.net/2020/04/05/responsive/VdJODFPTzxUnmYA-lg.jpg](url)

**Comment by dziudek** [comment]
Hi,

Are you using the newest version of your theme? I remember that we have fixed similar issue

**Comment by dziudek** [comment]
I am closing this issue due inactivity. @yangjchen feel free to reopen it, when you will be able to come back with more details.
