### ISSUE TITLE
WYSIWYG editor: “Add post title” field changes position unexpectedly after editing the text.

### ISSUE THREAD

**Issue by pagelab** [GetPublii/Publii#700]
Steps to reproduce the issue:

1. Create a new post with the WYSIWYG editor.
2. Paste some boilerplate text in the editor (at least 4,000 characters). 
3. Scroll up to the first paragraph.
4. Click inside any part the content and hit “Enter” to open a new paragraph.
5. The “Add post title” field shifts up and becomes unavailable to editing.

Notes: 
* This issue does not occur in the other editors (Markdown and Block Editor).
* The amount of text needed to make the bug appear varies depending on the height of the app window.
* MacOS.
* Publii version 0.36 (prerelease 5).

![2020-04-15 13 01 12](https://user-images.githubusercontent.com/1451087/79362114-9131e700-7f1c-11ea-9829-8f4639625027.gif)

**Comment by dziudek** [comment]
@pagelab - I cannot reproduce this issue in the v.0.36.0 - can you check if you are able to reproduce this problem?

**Comment by pagelab** [comment]
Yes, the issue still exists on build v.0.36.0 (build 13213) beta.
I'm on Mac OS 1.14 Mojave. 

![2020-06-11 14 41 25](https://user-images.githubusercontent.com/1451087/84421374-dc513900-abf1-11ea-9c20-772590cf469f.gif)

**Comment by internettips** [comment]
@pagelab 

I can't reproduce the problem on macOS Catalina v10.15.5, using Publii v.0.36.0 (build 13213) beta.

Performs perfectly.

**Comment by pagelab** [comment]
So probably it's specific to Mojave then.

**Comment by internettips** [comment]
Looks that way. Maybe an Apple bug that was quietly fixed in Catalina. Perhaps @dziudek can confirm.

**Comment by dziudek** [comment]
Yes - it looks like this. I am using Catalina and I does not have this issue. Unfortunately I have no mac with Mojave. In this case I am unable to reproduce and fix this problem :/

**Comment by pagelab** [comment]
@dziudek I see. So the Wysiwyg editor is not completely compatible with Mojave.

Not a big deal, though. I just need to remember to create the title before creating the content.

Closing this one, thank you for investigating!
