### ISSUE TITLE
Date for footer

### ISSUE THREAD

**Issue by SecondLife365** [GetPublii/Publii#701]
For particular webpages it would be nice to have built in the footer this simple feature: When synchronizing the webpage, if set for a footer in settings, there could be some current info about dates generated. It would be useful for copyright or for providing of the information when the webpbage was updated. That would avoid the need to manualy update such data when the webpage is static. User could insert some text and/or graphics plus date/time in pre-defined format. Example: %Logo.png © %YYYY MyCompany, Inc

**Comment by internettips** [comment]
These areas can be dealt with in the Publii theme designs: https://marketplace.getpublii.com. Including, date of publication, date of update, and automatic copyright update on the first day of every year.

**Comment by SecondLife365** [comment]
In my Theme I see that option for posts only, not for footers.

**Comment by internettips** [comment]
Which theme?

**Comment by SecondLife365** [comment]
Taste (v.1.8.1.0)

**Comment by internettips** [comment]
Sure, can be done there too. Probably best to ask for the precise details at: https://getpublii.com/forum/

**Comment by dziudek** [comment]
It is a thing which can be solved on a theme level with this `@utils` variable: https://getpublii.com/dev/utils-global-variable/
