### ISSUE TITLE
Feature suggestion: Get posts by main tag

### ISSUE THREAD

**Issue by RicardoJCP** [GetPublii/Publii#704]
Forum suggestion ticket: [Get posts by main tag
](https://getpublii.com/forum/topic/get-posts-by-main-tag/)

I've some sections in the homepage, each one has a number of posts by tags, but if one post have more than one tag, it appears on several sections.

In order to avoid add an additional argument **exclude_tags** or **main_tag** on [{{#getPostsByTags}}](https://getpublii.com/dev/getpostsbytags-helper/) helper, i suggest create an **{{#getPostsByMainTag}}** helper.

I think that if the pages-feature came to reality, this is no longer necessary.

**Comment by RicardoJCP** [comment]
```javascript
let themeHelpers = {
    getPostsByMainTag: function(mainTag, content) {

        const postsData = JSON.parse(JSON.stringify(content.data.website.contentStructure.posts));

        let filteredPosts = [];

        postsData.forEach(function(post) {

            post.mainTag.slug == mainTag && filteredPosts.push(content.fn(post));
        });

        return filteredPosts.join();
    }
};
module.exports = themeHelpers;
```

**Comment by candidexmedia** [comment]
Hi @rjcpereira ! Would you happen to know how to create a helper that can get all the mainTags (similar to `{{#each tags}}` )?
