### ISSUE TITLE
Option for leaving "Domain" blank / ZeroNet

### ISSUE THREAD

**Issue by DJSAKUGA** [GetPublii/Publii#709]
Hi, there's the chance to export the site leaving the "Domain" field blank?
I want to open the site localy, and with many "/" inside the index.html, CSS or JS won't be loaded.
If I remove the "/" inside the index.html or other pages, than the site works fine.

I want to upload my site in ZeroNet, for example.

Many thanks.

**Comment by dziudek** [comment]
Hi, 

I have tested many options but as I see the relative URLs must start with "./" to work, so I have added it in v.0.37 planned to release in the upcoming days.

If you will see any issues - please let me know.
