### ISSUE TITLE
sftp sync issues

### ISSUE THREAD

**Issue by trocster** [GetPublii/Publii#710]
Hi,

Versions : 0.36.5 and 0.36.3 on OS X 
Sync method: password and key based sftp (and manual publish).

The test connection works: 

`May  4 14:57:58 websrv sshd[31112]: Accepted password for publiist from 10.170.192.65 port 57164 ssh2`
`May  4 14:57:58 websrv sshd[31112]: pam_unix(sshd:session): session opened for user publiist by (uid=0)`
`May  4 14:57:59 websrv sshd[31116]: subsystem request for sftp`
`May  4 14:57:59 websrv sftp-server[31117]: open "public_html/publii.test" flags WRITE,CREATE,TRUNCATE mode 0666`
`May  4 14:57:59 websrv sftp-server[31117]: sent status Success`
`May  4 14:57:59 websrv sftp-server[31117]: close "public_html/publii.test" bytes read 0 written 37`
`May  4 14:57:59 websrv sftp-server[31117]: sent status Success`
`May  4 14:57:59 websrv sftp-server[31117]: remove name "public_html/publii.test"`
`May  4 14:57:59 websrv sftp-server[31117]: sent status Success`
`May  4 14:57:59 websrv sftp-server[31117]: session closed for local user publiist from [10.170.192.65]`
`May  4 14:57:59 websrv sshd[31116]: Received disconnect from 10.170.192.65: 11:`
`May  4 14:57:59 websrv sshd[31112]: pam_unix(sshd:session): session closed for user publiist`

however a sync fails (there is little useful info in the connection / error logs).

This fails for both password based and (encrypted and un-encrypted) key based sftp authentication. SFTP using an sftp client works for all three methods.

Issue is not the same as "https://getpublii.com/forum/topic/sftp-stuck/" as setting a non-relative path makes no difference.

After deleting "files.publii.json" on the server the file count went up; but still is stuck on syncing. 

When using the connection to sync the site the following is observed in the sftp server logs:

`May  4 15:53:47 websrv sshd[5678]: Accepted password for publiist from 10.170.192.65 port 57463 ssh2`
`May  4 15:53:48 websrv sftp-server[5683]: session opened for local user publiist from [10.170.192.65]`
`May  4 15:53:48 websrv sftp-server[5683]: received client version 3`
`May  4 15:53:58 websrv sftp-server[5683]: session closed for local user publiist from [10.170.192.65]`
`May  4 15:53:47 odessa sshd[5678]: pam_unix(sshd:session): session opened for user publiist by (uid=0)`
`May  4 15:53:48 websrv sshd[5682]: subsystem request for sftp`
`May  4 15:53:58 websrv sshd[5678]: pam_unix(sshd:session): session closed for user publiist`

Nothing notable in connection-error-log.txt

Also output directory has been copied manually, but even after there is a full copy on the server the above connect disconnect is observed. This used to work fine, as far as we can tell all the permissions on the sftp target are unchanged and correct. 

Finally the server type was changed to manual. The target was specified as a newly created local and uncompressed directory/target, but this also hangs. The preview however, which I suspect creates the sites/name/output directory, seems to work fine when new content is made.

**Comment by trocster** [comment]
The upload failures were due to the sftp library/app not being able to handle large (500 MiB) files.

Once the file size was reduced the upload resumed normally.  The logs seem to be split in two places, it is worth finding the other set of logs which aren't reported in app. The additional logs indicated there was an out of memory issue, which helped track down the 'large' file.

**Comment by dziudek** [comment]
@trocster - where did you find the additional logs?

**Comment by dziudek** [comment]
I am closing this issue due lack of response.

**Comment by TCC-UK** [comment]
I'd like to reopen this. I'm a noob but I really like this platform. I'm trying to push my files up hosting via SFTP and getting this
![Screen Shot 2020-06-13 at 11 25 31 AM](https://user-images.githubusercontent.com/59293208/84576330-c9ad4000-ad68-11ea-995d-48fe566ed083.png)
My permissions are 755. 
Can't seem to find the logs.
Any ideas as to the problem?
Cheers - Simon

**Comment by dziudek** [comment]
@TCC-UK - your "remote path" is wrong - it should be a path on the server without domain name etc.
