### ISSUE TITLE
Upload the website to Runkod using API

### ISSUE THREAD

**Issue by wuniversales** [GetPublii/Publii#717]
Website: https://runkod.com
Website API: https://runkod-api.runkodapps.com
It is currently the hosting that I use together with Publii.
Please add the "IDEA" label.
Thanks

**Comment by YoavRheims** [comment]
Interesting, never heard of them before.

**Comment by pagelab** [comment]
@wuniversales It seems like a really nice hosting option, thanks for sharing. Have you had any downtimes or performance issues using it?

**Comment by wuniversales** [comment]
No, everything is fine, the truth works great.

**Comment by dziudek** [comment]
Well, if hosting service cannot manage update SSL certificates: https://runkod-api.runkodapps.com/ then it is not a good sign ;) 

Looks like very niche hosting alternative. Maybe with the plugins support we will consider adding support for them, but to be honest our current plugins list for deployment is quite long :)
