### ISSUE TITLE
Custom canonical URLs

### ISSUE THREAD

**Issue by dziudek** [GetPublii/Publii#72]
ref: https://publii.ticksy.com/ticket/1434432/

With use of the advanced options buttons to hide more advanced SEO options.

<img width="513" alt="35029099-8889f014-fb59-11e7-839e-0708ef54e9ca" src="https://user-images.githubusercontent.com/22004/42259708-e0ccad98-7f61-11e8-9d00-a2584e113a2e.png">

**Comment by dziudek** [comment]
For the documentation purpose - the canonical URL will be available in the post item.

**Comment by theasteve** [comment]
I'm trying to link to a post. I created a post override as `post-jobs.hbs` Now I have a menu nav bar where I have a `href` tag pointing to this file. `href=post-jobs`. The documentation around linking to a post is confusing. 

How can I link to a post ?
