### ISSUE TITLE
Highlight code issue with classe

### ISSUE THREAD

**Issue by jeckyl** [GetPublii/Publii#723]
Hi,
with the latest version of Publii 0.36.0 I encounter a concern and misunderstanding.
I tested the new Post creation system using Block and especially the one that allows to put code that is superb in the backoffice.
On the other hand, it is impossible to display it properly in the frontoffice because the classes are on the PRE tag and not on the CODE tag as it is commonly applied by scripts like prism.js or highlightjs.
Moreover, I wanted to simply add a class and it ended up pasted to the other automatically inserted classes.

![Capture d'écran 2020-05-29 11 59 35](https://user-images.githubusercontent.com/595633/83247498-e90e6f80-a1a3-11ea-9491-2ea51fd2ef46.jpg)

result :

`<pre class="line-numbers language-phplanguage-php"><code></code></pre>`

in my opinion, the code should simply be:

`<pre><code class="line-numbers language-php"></code></pre>`

But maybe I didn't understand how to implant it and use it on my site.

**Comment by bobmitro** [comment]
Hi Jeckyl,

The markup of source code served by Block editor looks:
`<pre> <code> your code </code></pre>`

To change the syntax highlighting language, use the drop-down menu:

![block-editor-2](https://user-images.githubusercontent.com/1391007/83248381-42c36980-a1a5-11ea-97b5-8d6d8b844765.png)

**Comment by jeckyl** [comment]
> Hi Jeckyl,
> 
> The markup of source code served by Block editor looks:
> `<pre> <code> your code </code></pre>`
> 
> To change the syntax highlighting language, use the drop-down menu:
> 
> ![block-editor-2](https://user-images.githubusercontent.com/1391007/83248381-42c36980-a1a5-11ea-97b5-8d6d8b844765.png)

Thank you but my concern is not on the use within the management space of my site since I know very well how to change the display and frankly it is perfect at the level of the backoffice, on the other hand how to obtain the same display in front on my site for the readers because prism and the other scripts is based on classes defined on CODE and not on PRE.

**Comment by bobmitro** [comment]
I think all you have to do is add the prism to your theme. Have a look at https://getpublii.com/docs/highlight-your-code-syntax-with-prism-js.html

**Comment by jeckyl** [comment]
Thank you, the integration of Prism worked very well on my theme.

However, it still doesn't correct the lack of space between the added classes and the class I wanted to define for this space.

I hope that I am making myself understood.

`class="line-numbers language-phplanguage-php"`

**Comment by dziudek** [comment]
Hi, the problem with the missing space will be solved in v.0.36.1 - thanks for your feedback :)
