### ISSUE TITLE
Add list of tags when only tag prefix is opened

### ISSUE THREAD

**Issue by GasmoN** [GetPublii/Publii#725]
Okay so let's say that "Pretty URLs" is activated and my tag prefix is "downloads". 
Also, let's say that I have "Games" and "Videos" tags. So when I add in menu "Downloads" button it would be great when user clicks on that button which leads to mysite.com**/downloads** to display all available tags. I hope you are getting the point what I am trying to say, like categories and subcategories, but this is limited to only one "main" category and that is that tag prefix.

**Comment by dziudek** [comment]
@bobmitro - we need to add before release:

- [ ] Documentation for the `tags.hbs` / `amp-tags.hbs` files
- [ ] `tagsList` to the `supportedFeatures`
- [ ] User documentation for the new options
- [ ] Styling for the alert about lack of support for the `tagsList` feature (it is the same structure as the alert about luck of the `supportedFeatures` in the theme JSON file)

**Comment by dziudek** [comment]
@bobmitro - in supported features there is an option `"tagsList": true` and under renderer section you should put `"createTagsList": true`
