### ISSUE TITLE
Codeberg support

### ISSUE THREAD

**Issue by zsoltsandor** [GetPublii/Publii#726]
Codeberg is an open-source focused Git provider based in Germany, and as a European service, might be more preferable to some. Just like the major Git providers, they have introduced a Pages option for static content, as briefly described on https://pages.codeberg.org/.
Codeberg uses Gitea for its infrastructure.

It would be nice to have an option to use Codeberg - or Gitea in general - with Publii, if it's not added yet, at least not according to the documentation.

**Comment by dziudek** [comment]
Hi,

I have note this deployment method as a possible plugin in the future. As we want to release plugin support later this year, we won't add any new deployment methods to the Publii core - all new deployment methods will be developed as plugins.
