### ISSUE TITLE
Warn of unsaved changes on Quit or add autosave

### ISSUE THREAD

**Issue by Swader** [GetPublii/Publii#728]
Right now if the app closes mid-writing, all unsaved work is lost. This should be mitigated with autosave every X seconds, or with a warning on quit (i.e. accidental press of CTRL+Q which, [per docs](https://getpublii.com/docs/the-markdown-editor.html), is "blockquote").

Preferably, the solution would be autosave as it also protects against power outages and other system crashes.

**Comment by renanlecaro** [comment]
Related issue : https://github.com/GetPublii/Publii/issues/734

The ctrl+Q shortcut seems to be a pain for multiple users.
