### ISSUE TITLE
Editorial theme does not load changes from theme files

### ISSUE THREAD

**Issue by Swader** [GetPublii/Publii#729]
Following [this](https://getpublii.com/docs/highlight-your-code-syntax-with-prism-js.html) to add syntax highlight to my posts, I have modified the head and footer files as described, but when previewing the rendered file still does not contain those lines. My code fragment does have the class required (language-x) but the prism files are not being included, as if there's some partials caching going on.

**Comment by bobmitro** [comment]
This repo is related to the app only; to get help especially with the commercial products use a  dedicated Premium Support https://marketplace.getpublii.com/log-in/​
