### ISSUE TITLE
Page render generation hangs on 75%

### ISSUE THREAD

**Issue by Swader** [GetPublii/Publii#730]
Restarting does not help.

![image](https://user-images.githubusercontent.com/1430603/83757778-48232700-a671-11ea-9610-bbd872b577c3.png)

Also happens when trying to sync.

Does not happen on individual posts, only on whole site preview.

There is nothing in the logs, they do not update.

Theme: editorial, customized for Prism.js by @bobmitro 

How do I get some log output to see what's wrong?

**Comment by bobmitro** [comment]
I just tested your site and it works for me without any problems. Did you make any changes in the theme core files after installing the backup I sent you?

**Comment by Swader** [comment]
No changes other than finishing the post I was working on.
I just saved the draft of a new post I'm working on to try again, and got this now:

![image](https://user-images.githubusercontent.com/1430603/83759476-e0221000-a673-11ea-9a56-a828fba4ae4d.png)

**Comment by Swader** [comment]
Is there a way to open dev tools so I can debug?

**Comment by Swader** [comment]
Ah, wait, I did make changes. I changed the prism color to beige, and I changed the code snippet font with custom CSS:

```css
/*
 * Put your custom CSS code here
 */
code[class*="language-"], pre[class*="language-"] {font-size: 18px !important;}
```

**Comment by Swader** [comment]
Tried deleting `sites/dotleap/preview` folder, no change.

**Comment by bobmitro** [comment]
Send me your site back up once again, via the Premium support board.

**Comment by Swader** [comment]
I figured out what it is.
It seems markdown files share the ID - the ID for both my posts is 2 for some reason. That's the reason for the error, and for the halt (the halt does not show the error, but that's what stops it). If I make one of my published MD posts a draft and leave just one published, then the preview works again.

**Comment by Swader** [comment]
Strange because IDs in the UI are different, so must be a bug during rendering.
![image](https://user-images.githubusercontent.com/1430603/83761424-94bd3100-a676-11ea-8fdc-b1f88367b8d1.png)

**Comment by Swader** [comment]
@bobmitro anything I can hack on here to fix this? Really eager to publish these posts tonight.

**Comment by bobmitro** [comment]
I think I won't help much here, Tomasz (programmer) has to look at it, probably this is app bug. Anyway, send me your website backup.

**Comment by Swader** [comment]
Sending in an hour or so, as soon as I finish this post.

**Comment by Swader** [comment]
Sent

**Comment by Swader** [comment]
I was able to temporarily work around this by converting my MD posts to HTML and importing them into WYSIWYG's source mode. Let me know if I can help test any solutions to this problem.

**Comment by bobmitro** [comment]
I've checked your site and it seems that there is a problem with parsing of javascript ('''js) code. After removing all the javascript blocks in your post the site back to life. 
We will try to fix it in the next app release.

**Comment by dziudek** [comment]
@Swader 

It seems that on v.0.36.1 the issue is fixed somehow. We will release it tommorow - if the problem will still occurs, please reopen this issue :)
