### ISSUE TITLE
Typing ctrl+a (select all) on a french keyboard exits the app.

### ISSUE THREAD

**Issue by renanlecaro** [GetPublii/Publii#734]
Thanks for creating this excellent, very usefull software. Here's an annoyance that's a bit frustrating, i think it would happen on any french system but i'm not 100% sure. 

Steps to reproduce :
-open publii on ubuntu with a german keyboard set to azerty (french) layout
- click a text field
- press ctrl + A (A is on located in place of the Q in an AZERTY layout) 

Expected result : full content of text input is selected (that's the behavior of any other app on the system)

Actual result : the software immediately quits without warning and without saving the progress of the user

Suggested fix : don't use keycodes to determine the key being pressed. 

I tried to clone the repo to offer a fix as a PR but had some trouble getting the dev environment running.

**Comment by dziudek** [comment]
@renanlecaro - thanks for the feedback :) To be honest - I did not think about such case :) 
In the upcoming 0.36.1 release it will be fixed :)

**Comment by renanlecaro** [comment]
@dziudek the fix in the commit referenced here actually makes this behaviour apply to all users, it should be =="q" not =="a"
