### ISSUE TITLE
Feature Request: Cloudflare Workers / Wrangler

### ISSUE THREAD

**Issue by JOduMonT** [GetPublii/Publii#738]
### a Mini Why

While I deploy the same site in Netlify vs Cloudflare worker
based on gtMetrix from HongKong
at Netlify, even with all the tweak take 2.1sec to load 
with Cloudflare Worker, it take 0.8sec to load

### For now I know two ways to make it happen

1. [installing wrangler via npm](https://developers.cloudflare.com/workers/tooling/wrangler/install/) than pushing the site 
2. through an [github action](https://github.com/cloudflare/wrangler)

in a case of a team/collaboration, I believe the second way is better.

**Comment by dziudek** [comment]
Hi I suppose that currently the better solution is using Cloudflare Pages - we will publish in the next week an article how it can be achieved.
