### ISSUE TITLE
Linux - when there is no libsecret library, server settings storage is silently failing

### ISSUE THREAD

**Issue by dziudek** [GetPublii/Publii#739]
We need to detect such cases and show apropriate error message.

**Comment by Spacesurfer** [comment]
Would it be possible to just force/fallback to `Require the FTP password on every time you sync your site`?

**Comment by Spacesurfer** [comment]
I use the .appimage on Manjaro Plasma and have this issue there but no issue on Fedora GNOME 33. Does that mean https://github.com/atom/node-keytar/ will be included with the .appimage going forward or will node-key still need to be installed separately?

**Comment by dziudek** [comment]
@Spacesurfer - you must install libsecret manually if you are using appImage - it is a standalone app so it cannot install such dependencies. 

Publii in the next release will display a proper message when it fails during using secure password storage, so we will avoid case of quiet fails during settings save.
