### ISSUE TITLE
When using WYSIWIG it's Impossible to add a title after starting writing

### ISSUE THREAD

**Issue by JOduMonT** [GetPublii/Publii#748]
![Peek 2020-06-14 11-19](https://user-images.githubusercontent.com/5204724/84584663-3db31b00-ae31-11ea-960c-e7f20bf3c067.gif)

### How to reproduce

1. Add new post with the WYSIWIG editor
2. start writing your post
3. than try to add save it and/or to add a title to being able to save it ;)

**Comment by internettips** [comment]
Tested successfully using:

- Publii v.0.36.0 (build 13213) beta.

- Apple macOS Catlina v10.15.5.

- Latest versions of Publii Simple theme and other Publii themes.

So could not reproduce your issue.

Perhaps go to: https://getpublii.com/forum/ and post there with details of your OS, etc.

**Comment by JOduMonT** [comment]
so it is with: v.0.36.0 (build 13213) beta with the TechNews on Debian Testing

**Comment by dziudek** [comment]
@JOduMonT - unfortunately I cannot reproduce this issue on Ubuntu. It can be a distribution-specific issue.

**Comment by JOduMonT** [comment]
great, I'll deal with my unstable Debian ;)
thank for your testing

**Comment by JOduMonT** [comment]
just to mention with v.0.36.1 (build 13320) beta or update from Debian this issue disapeared.
