### ISSUE TITLE
Unable to Sync to Github

### ISSUE THREAD

**Issue by LebCit** [GetPublii/Publii#749]
Hello,

First of all thanks a lot for your hard work with this middle solution between the static and dynamic worlds.

I'm testing Publii and have only 11 articles.
I've tried to Sync to Netlify and everything works as expected.
But when I try to sync to GitHub, the number of files (104) stops at 16 and tells me that an error occured during connecting to the server.
![SyncError](https://user-images.githubusercontent.com/10379495/84590330-3f371000-ae3e-11ea-8e04-8bde7a0bcc20.png)

As a quick suggestion, would it be possible to use an SSG as [Eleventy](https://www.11ty.dev/docs/) that works with multiple template languages ?

Thanks in advance and have a nice codding day/night 😊

**Comment by dziudek** [comment]
Hi,

It seems to be an issue with your internet connection or with Github API. Please try try to sync your website again.

**Comment by dziudek** [comment]
I am closing this issue due inactivity.
