### ISSUE TITLE
Anchor links don't work in the mobile menu

### ISSUE THREAD

**Issue by gpsblues** [GetPublii/Publii#751]
Anchor links like "#contacts" or "http//:www.mysite.com/#contacts" only work properly in the desktop-style menu.
The same links in the mobile-style menu don't work.
This makes it impossible to create sites with one-page menus or menus with links to the page footer.

**Comment by internettips** [comment]
Could not reproduce your issue.

Tested successfully using:

- Publii v.0.36.0 (build 13213) beta.

- Apple macOS Catlina v10.15.5.

- Latest versions of Publii Editorial theme and other Publii themes.

Perhaps go to: https://getpublii.com/forum/ and post there with more details of your OS, etc.

**Comment by gpsblues** [comment]
Hi,
see this test site:
https://www.mywebpassion.it/siti/simple/

Footer is external relative link "#footer"
Middle post is external absolute link "https://www.mywebpassion.it/siti/simple/post.html#middle"

- Publii v.0.36.0 (build 13213) beta.
- Win 10 Home 10.0.18362 build 18362
- Simple v.2.2.2.0 (and other themes)
- Device Android 10.0.0.195

**Comment by dziudek** [comment]
Hi,

You must to provide the full link with anchor if you want to make it working on the whole website.

So instead `#contact` please use `https://mydomain.com/#contact`

**Comment by gpsblues** [comment]
Hi,
"Middle post" link is a absolute URL "https://www.mywebpassion.it/siti/simple/post.html#middle", but works only in desktop device (no mobile menu).

I don't think it's a theme issue. I can't make a list, but I have found the error in several themes.

**Comment by dziudek** [comment]
@bobmitro - it seems that the smooth scrolling mechanism does not handle properly link with anchors on the websites where the anchor leads on mobile devices.

When user clicks menu item: https://www.mywebpassion.it/siti/simple/post.html "Middle Post" then on mobile devices the page is not scrolling properly.

**Comment by dziudek** [comment]
The fix will be available in v.0.36.1 release in simple v.2.2.3.0
