### ISSUE TITLE
Missing FTPs server type upload

### ISSUE THREAD

**Issue by aitoraroza** [GetPublii/Publii#752]
Hello there,

In past months I couldn't find the right conf or make Publii (v35) upload changes to a FTPS server, always throwing a "check permissions, can't write" error, after sucessfully connecting to server (watching logs in both sides)

Now at v36 update, the option of using FPT over SSL/TLS is gone, having only SSH or plain FTP as options for private servers.

Is there any scheduled plan to bring back a working upload system for FTPS?

Thanks in advance for your time, and keep up the good work. Publii is by far the best tool I've ever tried in these years for blogging. Sorry for bothering with this minor issue!

**Comment by dziudek** [comment]
Hi @aitoraroza - you're right :) We have lost it after server settings screen redesign. I have added a fix for the upcoming v.0.36.1 release which restores the FTPS option under FTP screen (there will be an additional checkbox "FTPS").
