### ISSUE TITLE
S3: Cannot set empty relative URL

### ISSUE THREAD

**Issue by jchown** [GetPublii/Publii#754]
We want to host using relative URLs without a prefix, but on the S3 settings you cannot set this.

If you tick "Use relative URLs" and clear the URL text box it silently uses "./" instead.

**Comment by jchown** [comment]
If you set it to the empty string directly in site.config.json then sync fails with a "make sure your domainn name is set" message.

**Comment by dziudek** [comment]
I am closing as duplicate of this issue: https://github.com/GetPublii/Publii/issues/709
