### ISSUE TITLE
Shared Sites Folder

### ISSUE THREAD

**Issue by jchown** [GetPublii/Publii#755]
We would like to have a shared folder (e.g. on Dropbox) for sharing sites between content creators and designers/engineers.

In the most recent version of Publii (I'm using 0.36.0) when you change your sites folder it offers to "clean" the destination directory, which is almost certainly not what we want.

Could it offer to just change it and not move/clean the destination?

**Comment by jchown** [comment]
A related issue/solution would be to offer the choice of directory at install time.

**Comment by dziudek** [comment]
We will implement this as I described it here: https://github.com/GetPublii/Publii/issues/714

I will close this issue as duplicate to avoid two places for the same topic :)
