### ISSUE TITLE
Unable to save my Server preference

### ISSUE THREAD

**Issue by JOduMonT** [GetPublii/Publii#756]
OS: Debian
Desktop: KDE
Publii: v.0.36.0 (build 13213) beta

When I download getpublii and create a new site than configure, netlify and/or github, ... almost all of them (I didn't try s3), but Manual work

I'm able to test and I receive the green flag saying everything is fine
but I'm unable to save the configuration (which is lost when I go to another menu)

### my workaround

and for now I force netlify  by configuring it directly in site.config.json

        "protocol": "netlify",

than put my id and token

**Comment by dziudek** [comment]
Do you have these packages on your OS: https://github.com/atom/node-keytar#on-linux ?

**Comment by JOduMonT** [comment]
probably not, but I cant really test since I reinstall another Os and don't use Publii at the moment.
