### ISSUE TITLE
Generate tag pages even if there are 0 posts to show

### ISSUE THREAD

**Issue by Huluti** [GetPublii/Publii#762]
I think that Publii should generate tag pages even if there are 0 posts to show to avoid 404 links in the menu.

You could write a message : "There are no posts yet. Please come back later.".

**Comment by dziudek** [comment]
Hi, this feature is available -> Site Settings -> SEO -> Tag page -> Display tags w/o posts

**Comment by Huluti** [comment]
@dziudek Oh sorry. Thank you very much for this info ;) And thank you for developing Publii ;)
