### ISSUE TITLE
Why control+A close the software ?

### ISSUE THREAD

**Issue by JOduMonT** [GetPublii/Publii#763]
How I could change this binding ?
it's very annoying, every time I want to select all I loose my work.

my keyboard is configured EN-US
my OS Debian

everywhere else CTRL+A = select all

**Comment by renanlecaro** [comment]
This come from a typo in the fix of a bug I reported

**Comment by renanlecaro** [comment]
@dziudek see the typo here : https://github.com/GetPublii/Publii/commit/f7097d2de26e0a780e1c08c61a330093759c3eaf

Sorry that I didn't look at my notifications earlier, this could have been avoided

**Comment by JOduMonT** [comment]
@renanlecaro thank men!, that was driving me insane

**Comment by dziudek** [comment]
@JOduMonT - we have replaced packages for linux so you can download the Publii again and it won't have this problem (I recommend to use "Alternative downloads" as on CDN there can be still old version).

We will officially release this fix on Publii v.0.36.2
