### ISSUE TITLE
Bold does not appear on Wysiwyg editor

### ISSUE THREAD

**Issue by anselmyst** [GetPublii/Publii#765]
Hi
on Publii v.0.36.1 (build 13320) beta
installed with a deb on linux
on Wysiwyg editor (not in block editor)

Bold does not appear on editing view, only on preview and when published.

**Comment by dziudek** [comment]
Hi,

Sorry but I am unable to reproduce this issue on my Ubuntu:

![Screenshot 2020-07-11 at 15 08 40](https://user-images.githubusercontent.com/22004/87224807-9b7f4800-c388-11ea-902c-b10058012a4c.png)

**Comment by dziudek** [comment]
I am closing this issue due inactivity. If somebody will be able to reproduce this problem - feel free to reopen this issue :)
