### ISSUE TITLE
Ok button in gallery is not reachable 

### ISSUE THREAD

**Issue by gpsblues** [GetPublii/Publii#766]
With more than 4 images, the Ok button in the gallery is not visible.
I solve the problem by rotating the screen 90 degrees.
![image](https://user-images.githubusercontent.com/16633630/85538955-a8284000-b615-11ea-9a2d-7614c2d5e587.png)

Publii v.0.36.1 (build 13320) beta
WYSIWYG Editor
SO Win10
Screen resolution 1920 x 1080

**Comment by strelok899** [comment]
same problem as i posted but i have 13" laptop with 1920X1080 and 150% scaling

changing th scaling to 125% solves the problem
