### ISSUE TITLE
Micropub Support

### ISSUE THREAD

**Issue by jalcine** [GetPublii/Publii#768]
[Micropub](https://www.w3.org/TR/micropub/)'s a W3C standard for publishing content to one's site from any client. I _really_ like Publii and am interested to know if it's possible to have Micropub support on the roadmap. I know Publii is optimized for static sites - Micropub can work with those as well!

I'd love to see and help with this, I really want this for my personal site.

**Comment by dziudek** [comment]
Hi,

I hear about it first time. Could you elaborate what potential benefits we can get by adding support for Micropub and how it can work with static websites?

**Comment by Spacesurfer** [comment]
> The Micropub specification began as a simplified version of the AtomPub and MetaWeblog APIs. Where AtomPub is an API to create items in an Atom feed, Micropub is an API to create items in a [Microformats2] feed.
>
>In addition to being used with a different vocabulary from AtomPub and MetaWeblog, Micropub simplifies and improves upon both APIs in a number of ways. Micropub uses OAuth 2.0 Bearer Tokens for authentication, rather than the previous insecure username/password authentication method. Micropub also uses traditional form posts as well as JSON posts, which is both simpler and more secure than an XMLRPC approach.

Because Publii generates pages locally rather than on a server, I don't see the use for Micropub. Its purpose, if I understand correctly, is to accept posts written from other editors. I guess if one is wanting to write posts for your Publii site in a separate local editor and then have Publii generate it. Does that sound right @jalcine ?

**Comment by jalcine** [comment]
Yeah, that is the objective of it. It could also serve as a way to backfill posts into a site (like if you wanted to idiomatically import your Wordpress RSS feed or a Twitter archive).

**Comment by dziudek** [comment]
At this moment we have no plans to implement such feature. I think it is a topic for a plugin, not for the core feature.
