### ISSUE TITLE
Exclude from output rewrite all `.*` files/folder like `.github`

### ISSUE THREAD

**Issue by geoffreycrofte** [GetPublii/Publii#770]
Hello there !

Thanks a lot  for the great tool.
I have a use case where we are using a github action to merge 2 branches on the same `gh-pages` branch.
My first branch is `develop` where we have a static website.
My second branch is `blog` where we have a Publii website.

To be able to use Github Actions, we need a `.github/workflows/yourAction.yml` file in each branch to activate the automation. But Publii doesn't offer the ability to exclude files from being deleted from the `output` folder, right?
I tried to create in the `input` folder by `.github` folder, hoping that it will be included into the `output` folder, but it didn't work.

Is it possible to imagine a "include files from output folder" option where we could select custom files to include?
Or by default to imagine that I can create whatever `.custom-file` starting by a `.` that would not be overwritten during the Github Sync?

At the end, I just need my `.github` folder to be on my `blog` branch, which I use as Publii workspace.

Thanks a lot for you help.

PS. I found some exclusion here but I'm not sure if it's related or not https://github.com/GetPublii/Publii/blob/master/app/back-end/modules/deploy/deployment.js#L124

**Comment by dziudek** [comment]
Hi,

I think that the easiest solution will be allow to copy to the output directory catalogs from the `input/root-files` catalog. I will try to implement it in the next release :)

**Comment by dziudek** [comment]
@bobmitro - please prepare a catalog icon: app/src/assets/svg/svg-map-file-extensions.svg - lines 7-9.

**Comment by geoffreycrofte** [comment]
> 
> 
> Hi,
> 
> I think that the easiest solution will be allow to copy to the output directory catalogs from the `input/root-files` catalog. I will try to implement it in the next release :)

Oh yes that's a good idea.
Thanks for working on it 😃

**Comment by AppOutletTeam** [comment]
Im using Version: 0.46.4 (build 17047) and the .github folder is still being removed

**Comment by dziudek** [comment]
@AppOutletTeam - please put .github catalog under Tools -> File Manager -> root-files
