### ISSUE TITLE
Change to site name overwrites server password

### ISSUE THREAD

**Issue by edkeohane** [GetPublii/Publii#771]
As a CMS user, when I change the site name (site settings / site name) and save the change, then as well as saving the site name and renaming the directory that contains all the files (!), it also overwrites the server FTP password with the new site name

**Comment by dziudek** [comment]
Yeah, I have discovered this problem some time ago. I will try to resolve it with applying on the new websites some unique UUID which will be used to recognize a website instead of it's name :)
