### ISSUE TITLE
[Contribution inside] Added graphcomment cloud comments

### ISSUE THREAD

**Issue by wuniversales** [GetPublii/Publii#772]
Apparently graphcomment is faster than disqus and collects less information about users, so I would like to add an option to choose which comment box to use.

https://graphcomment.com/en/

I suggest that plugins can be installed to publii.

Just as you can currently download themes, give the possibility to install plugins in themes, install "disqus" or "graphcomment" in themes.

Regards

I edit, I provide some code that can be used to add this function.

_As I see that they take time to implement, you can download the theme from here._
https://up-load.io/44qaaf1p3dhx

**Comment by nitaaikumar** [comment]
> Apparently graphcomment is faster than disqus and collects less information about users, so I would like to add an option to choose which comment box to use.
> 
> https://graphcomment.com/en/

I fully agree. I have been thinking of requesting this for a long time. GraphComment is the fastestloading and most feature-rich commenting system out there. Here are some of its features:

Crowd discussion, Quality discussions, Live discussions, Automatic registration, Community profiles, Theming, Notification center, Media embedding, Sliding sidebar panel, Discussion sharing, Text formatting, Badges and awards, Multilingual, Import old comments, Editorialize & Pin best discussions, Community relationship management, Top Widget (comments, articles), Counter widget, Smart moderation, Keyword alerts, Restricted right to comment, Analytics, Spam protection, Multi-moderators, SEO friendly, Structured data, User comments legacy, Data access and ownership, Direct links, and Enhance with comment. They are also planning to add new more features soon.

Over and above all up GraphComment gives us 1,000,000 data loads / month for the free plan WITHOUT ADS which would be more than sufficient for everyone, unlike Disqus which has annoying ads. Even GraphComment's Starter plan is cheaper at $7/month for 1,000,000 data loads. Whereas Disqus's gives a meager 50,000 page loads for more cost of $10/month. And GraphComment's Pro plan is $74/month for 5 million data loads. Whereas Discuss charges $99 for just 150k page loads.

So please do add GraphComment support to Publii. Thanks.

**Comment by wuniversales** [comment]
I'm testing, but it seems to work ;)

![imagen](https://user-images.githubusercontent.com/48658161/94941724-9b996a80-04d5-11eb-9015-115621dc5360.png)

![imagen](https://user-images.githubusercontent.com/48658161/94943681-5f1b3e00-04d8-11eb-87a0-936d4c2aa6b2.png)

**Comment by wuniversales** [comment]
I just updated the post with the tutorial on how to add graphcomment to any theme of the publii.

Let's enjoy it!!!

**Comment by wuniversales** [comment]
@dziudek 
See if you can add it to all the themes of the publii, I have tested it and it works.
Greetings

**Comment by eimimue** [comment]
any updates on accepting pr, @bobmitro?

**Comment by bobmitro** [comment]
Thank you for the contribution and the work you did.
However, we decided not to implement it directly in themes now as we are going to release it as a plugin. This year will bring plugin support and I think this kind of addons should be released as a theme extension (plugin).

**Comment by krzakx** [comment]
As plugin support for publii seems to be not released yet, could anyone give tutorial how to implement this GraphComment Cloud service into EasyBlog theme please?

**Comment by wuniversales** [comment]
> As plugin support for publii seems to be not released yet, could anyone give tutorial how to implement this GraphComment Cloud service into EasyBlog theme please?

I think it is better to wait for the plugins to publish, so I can implement the plugin for all themes.

**Comment by krzakx** [comment]
@wuniversales I would kindly ask for instructions please share to krzakx@gmail.com ,
waiting for instructions.

**Comment by benthroop** [comment]
Hi is there any progress on this? Is the plugin system going? I'd love to move to Graphcomment as well.

**Comment by candideu** [comment]
Hey everyone: in case you haven't heard, the GraphComments plugin is here: https://marketplace.getpublii.com/plugins/graphcomment/
