### ISSUE TITLE
gdprScriptBlocker not working in customHTML, {{gdprScriptBlocker}} helper is not processed

### ISSUE THREAD

**Issue by mickert** [GetPublii/Publii#773]
### When using the gdprScriptBlocker helper handlebar in customHTML it is not processed. So blocked scripts wont be enabled.
For example, the following HEAD customHTML 
`<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXX" type="{{ gdprScriptBlocker "analytics" }}"></script>`

is rendered as followed in the save & preview and synchronized to server website:
`<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXX" type="{{ gdprScriptBlocker "analytics" }}"></script>`

As a work around, change the type in the customHTML  to `type="gdpr-blocker/groupname"`, for the above example the resulting customHTML is: `<script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXX" type="gdpr-blocker/analytics">`.
This lets hthe gdpr plugin correctly enable the scripts.

edit:
of course if the handlebar is not processes the resulting script tag is invalid because the type tag is ended by the second double quote after gdprScriptBlocker.

edit:
As a work-around i have modified the outputted javascript in the [app/back-end/modules/render-html/helpers/gdpr.js](https://github.com/mickert/Publii/blob/babc723cc72d1e7ae3a1425b0289f079cf083aab/app/back-end/modules/render-html/helpers/gdpr.js) as to process the type="gdpr-blocker/groupname" AND type="{{ gdprScriptBlocker "groupname" }}" so the end-user can use the  gdprScriptBlocker handlebars in the customHTML.

**Comment by dziudek** [comment]
I see that I misunderstand your problem - I though that gdprScriptBlocker helper is not parsed at all, now I see that the problem is only in the Custom HTML, what is absolutely correct. 

The only solution which I see is use of the inline partials: https://handlebarsjs.com/guide/partials.html#inline-partials

But in fact it is a theme thing not a Publii issue.
