### ISSUE TITLE
Native comments system

### ISSUE THREAD

**Issue by macgyverkam** [GetPublii/Publii#774]
That would be great if Publii team should add internal commenting system. This would help us to easily manage comments from our admin panel instead of depending on third parties. Now discuss started showing ads in his comment box section and that was not good at all. I would highly recommend having self-hosted comment system or that would be great if team include this feature in their future upgrades.

Thank you!

**Comment by strelok899** [comment]
if you adding this feature please don't make it mandatory , so i could turn it off ad have fully static web site.
it could be great plug in maybe even one multi tenant server which will be used as comment server for serval publii sites.

i like publii because it generates fully static web site's and i don't want to loose this ability

**Comment by bobmitro** [comment]
Excellent idea, but... its a static world guys...

**Comment by mickert** [comment]
It's a static world. But that's no reason it can't be done. For some inspirationn:

- Joost van der Schee - GDPR compliant comments (comments stored on/in GitHub issue): 
https://jekyllcodex.org/blog/gdpr-compliant-comment/ ; https://jekyllcodex.org/without-plugin/comments/
- Shaun Persad - How you can build your own free, serverless comment box: 
https://www.freecodecamp.org/news/how-you-can-build-your-own-free-serverless-comment-box-dc9d4f366d12/
- Eduardo Bouças - Rethinking the commenting system for my Jekyll site : https://eduardoboucas.com/blog/2015/05/11/rethinking-the-commenting-system-for-my-jekyll-site.html 

But even without rolling a new comment system it would be nice to implement **ad-free alternatives** like Hyvor Talk - [https://talk.hyvor.com/](https://talk.hyvor.com/).

**Comment by bobmitro** [comment]
_I would highly recommend having self-hosted comment system or that would be great if team include this feature in their future upgrades._
It's not possible to include it in the Publii.

_But that's no reason it can't be done. For some inspiration:_
All of them are 3rd party services.

**Comment by mickert** [comment]
Ah, sorry. Kind missed the whole self hosted criterium.

**Comment by cristian-milea** [comment]
> That would be great if Publii team should add internal commenting system. This would help us to easily manage comments from our admin panel instead of depending on third parties. Now discuss started showing ads in his comment box section and that was not good at all. I would highly recommend having self-hosted comment system or that would be great if team include this feature in their future upgrades.
> 
> Thank you!

Disquss is free with ads. If you want no ads, you have to pay on your Disquss account and they will now show on your publii website.

**Comment by strelok899** [comment]
I think feasible solution would be having some publii self hosted service for Comments.
Which can be used by different static publii websites.

**Comment by atomGit** [comment]
see the [Self-hosted](https://darekkay.com/blog/static-site-comments/) section

i also think it would be excellent if a comment system was added to Publii

**Comment by internettips** [comment]
I imagine comments as a kind of add-an, rather than a core feature. Plus, development and maintenance cost can be expensive for Publii. Maybe useful as a plugin later perhaps. But once comments are live, from an SEO perspective, if we don't manage comments carefully, they can cause more SEO and ranking problems than the benefits they may provide.

**Comment by dziudek** [comment]
Hi, at this moment we have no plans to add a such feature to the Publii, as it needs an external 3rd party service (or self-hosted), what creates a many new issues and problems. Also we have no plans to create our own one as it is an additional service and needs a dynamic code which won't work on some static pages hostings like Github, Netlify, Gitlab etc.

For comments please consider existing solutions like the ones described here: https://www.getshifter.io/blog/static-site-comments
