### ISSUE TITLE
Last modified date/time missing from sitemap

### ISSUE THREAD

**Issue by edkeohane** [GetPublii/Publii#775]
The sitemap that Publii automatically generates is missing last modified dates. It contains only page url and number of images.

**Comment by internettips** [comment]
It's there on my Publii showcase site. Maybe you have a theme issue. Try going to [https://getpublii.com/forum/](url) for help.

**Comment by dziudek** [comment]
I also have `<lastmod>` on my sites. Could you check if all posts does not have that field? Did you modified any of your posts?

**Comment by edkeohane** [comment]
Ok. I’ve found out what causes it. I wanted to have pretty URLs, but this means that you have to have use a tags prefix, which appears as an extra, empty directory in the url of a tag page, which is an SEO no-no. So I edited the tags prefix on line 77 of the config json so that it was blank. This fixes the url issue, and everything looks as though it builds ok, but it breaks the last mod column in the site map. If you roll back the change to the config, then it works again.

**Comment by dziudek** [comment]
@edkeohane - I suppose that it will solve your problem with empty tags directory: https://github.com/GetPublii/Publii/issues/725 :) 

So I am closing this issue
