### ISSUE TITLE
Back to top button not working properly (not in Firefox)

### ISSUE THREAD

**Issue by gpsblues** [GetPublii/Publii#776]
Except for Firefox "Back to top button" often does not lead to the top of the page.

I have noticed this problem in various sites. It is also visible in the live themes preview of the marketplace.

The problem does not seem reproducible: sometimes it goes to the top, sometimes it stops earlier. This also happens with the page fully loaded.

Publii: v.0.36.1 (build 13320) beta
Browser tested: Chrome, Opera, Edge. In Firefox it seems to work well.

**Comment by bobmitro** [comment]
This repo is dedicated to the app only. For any other problems please use the forum.
