### ISSUE TITLE
Firebase hosting integration

### ISSUE THREAD

**Issue by arifullahjan** [GetPublii/Publii#777]
Would love to be able to deploy to firebase hosting directly from publii. :)

**Comment by CiriousJoker** [comment]
Setting up `firebase deploy` yourself isn't too difficult, but it still would be a nice feature to have :)

**Comment by dziudek** [comment]
Hi,

I have note this deployment method as a possible plugin in the future. As we want to release plugin support later this year, we won't add any new deployment methods to the Publii core - all new deployment methods will be developed as plugins.

**Comment by drnw** [comment]
I am eagerly awaiting the release of plugin support :-) In the meantime, I am able to hack a deploy to Firebase using the Google Cloud server connector built onto Publii. However, this is a curiosity not a viable solution.

**Comment by drnw** [comment]
Deploying to Firebase via Github is close to working. Unfortunately, Publii deletes all files in the branch it deploys to. So the Github action and firebase.json files which are required for the deploy to work automagically get removed.

**Comment by dziudek** [comment]
@drnw - if you want to use other files, please try to put them in File Manager -> root directory - it should help :)

**Comment by drnw** [comment]
Thanks @dziudek. Sync website from Publii to Firebase via Github works for me. This is a practical workaround until a more direct route from Publii to Firebase is available :-)

<img width="445" alt="image" src="https://user-images.githubusercontent.com/24733582/202900138-b8cc7c08-2ea5-46a0-a8ec-a44c7f8c2112.png">
