### ISSUE TITLE
Is the multilanguage more expertimental ?

### ISSUE THREAD

**Issue by BogusCurry** [GetPublii/Publii#786]
Hello ;D
I have found your CMS Publii and I very liked ;D Now I come from germany and I see that the language is in it, but when I set in german, so save the settings, but the interface is not in german. Is that a bug or is the function more expertimental ? 

Greeings

Bogus

**Comment by damalix92** [comment]
Hi Bogus,
I thought the same. I think you found that setting in the "site settings"... Then I think it is more your site's language and not the GUI's language. I'm not sure but I think it adds some information for the search engines to classify your site. You may also have the spellcheck option available to spellcheck your posts.
Dam's

**Comment by BogusCurry** [comment]
Hi Dams ;D
Ok, but in the roadmap stand that in the 0.36 comes multilanguage support and here can see the roadmap https://getpublii.com/roadmap/

Bye
Bogus

**Comment by pagelab** [comment]
> Ok, but in the roadmap stand that in the 0.36 comes multilanguage support and here can see the roadmap https://getpublii.com/roadmap/
 
They abandoned the idea of changing the interface language some time ago. See #628

**Comment by BogusCurry** [comment]
Hmm .. ok, but what is the big problem for the translation ? When comes the translation from the community, thats it or ? Wordpress can's, Joomla can's too and what is the problem ?
Make the transolation as pot file, that is the very easier way ;D And a translation in another language makes more user happy ;D Not all humans can speak englisch or is his mouther language.

I think Publii is very good CMS, but with multilanguage is more better ;D

Greetings
Bogus

**Comment by dziudek** [comment]
As it was mentioned in https://github.com/GetPublii/Publii/issues/628 - we have abandoned multilanguage for App UI concept, maybe it will come back in the future, but at this moment we have no plans for it.
