### ISSUE TITLE
Publii translation for UBUNTU

### ISSUE THREAD

**Issue by Adriner** [GetPublii/Publii#788]
Good evening everyone

I'm using Publii on UBUNTU

I translated the file simple.lang.json, which is located in the folder "/ home / adriner / Documents / Publii / themes / simple"

But it is not being treated when uploading the site.
I'm doing it right. . .

Another asks where I can put the google analytics code.

Thank you for now

(using https://translate.google.com/) sorry

**Comment by dziudek** [comment]
Hi,

Your issue is not directly related to the Publii app but to the theme development - feel free to post at our official forum: https://getpublii.com/forum/
