### ISSUE TITLE
iframe embeds either have extra space after embed or cutoff the embedded item

### ISSUE THREAD

**Issue by jessespillane** [GetPublii/Publii#789]
1) In block editor with simple theme (may affect other included themes as well, not sure) add a html block and insert an an iframe embed such as from bandcamp.
2) Depending on the height of the embedded item, you either end up with a lot of space after the iframe (for short embeds) or an embed that gets cutoff at the bottom (for tall embeds)

Example

![image](https://user-images.githubusercontent.com/891359/89104244-d56ec780-d3e5-11ea-8383-a5d880ffa798.png)

Edit: forgot to mention this is with 0.36.1 .

**Comment by dziudek** [comment]
It seems that this issue has been fixed in Publii v.0.39 or v.0.40 and the related theme updates. If it still appears - feel free to reopen this issue.
