### ISSUE TITLE
Rendering Process Failed: File Already Exists

### ISSUE THREAD

**Issue by littletinman** [GetPublii/Publii#795]
**OS**: Windows 10 64 Bit
**Version**: v.0.36.1 (build 13320) beta
**Server**: AWS S3

**Error**: 
Rendering process failed
An error occurred during rendering process:

EEXIST: file already exists, mkdir C:\Users\littl\Dropbox\ThePracticeZone\the-practice-zone\preview\assets

I just downloaded and started using Publii today. Got the executable from the homepage. I got everything setup in the AWS S3 console. But before even publishing there, every other time I hit "preview changes" or "sync" I get this error. It happens without fail every other time. I end up having to run the "sync" or "preview" twice.

**Comment by dziudek** [comment]
Hi,

To be honest I have no idea why you get this message, but I have made small modification in the renderer code - now it will check if the catalog exists and if not - it will be created, otherwise app will do nothing, so in such situations it won't throw errors.

**Comment by francesmothrock** [comment]
I get the same error frequently with this new version, 0.39.0. Fortunately it works when I press Preview a second time.

On Linux, Ubuntu Mate, 21.10

**Comment by xstefen** [comment]
Sorry to resurrect but I have the same issue on any type of generation.

OS: Windows 11 21H2
Publii Version: 0.40.2 (build 15735)

```
Rendering process failed
An error occurred during rendering process:
EEXIST: file already exists, mkdir 'X:\Projects\publii-sites\.previews'

Rendering process failed
An error occurred during rendering process:
EEXIST: file already exists, mkdir 'X:\Projects\publii-sites\xstefendev\output'
```

I've tried setting different dirs, keeping defaults, etc. Same result every time.
