### ISSUE TITLE
Deployed Website to S3 Content is loading to slow to show up in the brwoser

### ISSUE THREAD

**Issue by Nutaboy** [GetPublii/Publii#797]
I deployed an S3 website to followed your user guide but not if i want to access the site every thing is pretty messed up and i takes decades to load

**Comment by dziudek** [comment]
Hi,

It must be an issue with your S3 bucket (performance) and with your configuration (most probably wrong domain name provided).

**Comment by dziudek** [comment]
Am closing this issue due inactivity.
