### ISSUE TITLE
[Feature request] Custom build + deploy pipeline as a server option?

### ISSUE THREAD

**Issue by ciriousjoker** [GetPublii/Publii#804]
I have a custom theme with a css library that produces huge css files. I tree-shake these using purgecss and deploy to firebase.

It would be nice if there was the ability to add scripts like purgecss to the existing build pipeline. Also, custom servers (using a deploy script) would allow for the integration of arbitrary destinations, like Firebase as suggested here: #777 

Obviously, a full integration esp for firebase would be nice, but a versatile deploy script option would be really good as well and probably easier to implement.

**Comment by dziudek** [comment]
Such features like custom shell commands evaluated after rendering a website, will be developed as plugins, not Publii core features, so I am closing this issue.
