### ISSUE TITLE
Unale to sync site to Github pages enterprise version (Rate limiting is not enabled error)

### ISSUE THREAD

**Issue by manaf-aboalrous** [GetPublii/Publii#805]
I'm getting the following error message when trying to sync my site to Github Pages even though the connection is working just fine.

I believe this is due to having rate limiting not enabled by our Github enterprise admin, which explains the error when Publii tries to get the current rate limit of the user. Can you please handle this exception.

![image](https://user-images.githubusercontent.com/743474/91630095-b3199b00-e9df-11ea-80dc-674e88bc2f7f.png)

 ![image](https://user-images.githubusercontent.com/743474/91630109-cc224c00-e9df-11ea-9e30-bcea125f4a7f.png)

**Comment by manaf-aboalrous** [comment]
I believe this is due to having rate limit not enabled by our Github enterprise admin, which explains the error when Publii tries to get the current rate limit of the user. Can you please handle this exception.

**Comment by dziudek** [comment]
Hi, I will try to address this issue in v.0.37 planned for the beginning of the September.

**Comment by manaf-aboalrous** [comment]
Hi Tomasz, any updates on the release date for v.0.37? I can't use Publii without this fix.
