### ISSUE TITLE
Request add a text character countdown counter for meta titles and descriptions

### ISSUE THREAD

**Issue by internettips** [GetPublii/Publii#81]
So that as each text character gets entered, the character counter, counts down. When we get to zero, we know we've reached the limit.

The following limits should get read by search engines:

- Meta Titles = 70 characters.

- Meta description = 160 characters.

**Comment by dziudek** [comment]
Thank you for this request - we have it on our old lists and I think that the 0.28.3 release will be a good moment to implement it :)

**Comment by internettips** [comment]
Thank you Tomasz 👍

**Comment by fghhfg** [comment]
It can be a warning, but don't limit user input.

**Comment by internettips** [comment]
Yes, good point: that would be perfect.

**Comment by YoavRheims** [comment]
Update: 70 is not the recommended number. From now on, it should up to 60 characters or maximum 600 pixels.

Source: https://moz.com/learn/seo/title-tag

**Comment by internettips** [comment]
Yes, 50 - 60 is perhaps a better range guide. Though if titles are longer, Google and probably other SEs will scan more than 50 or 70 characters, or the full title, in order to better "understand" the nuances of a web page. Makes sense that  50 or 60 characters is perhaps more helpful for smaller mobile device screens - and of course saves money for SEs :-)

**Comment by YoavRheims** [comment]
It's not only for mobile but also desktop serps.
