### ISSUE TITLE
support for netlify custom headers

### ISSUE THREAD

**Issue by foolioo** [GetPublii/Publii#811]
netlify supports [custom headers](https://docs.netlify.com/routing/headers/) and that is missing from publii. i implemented a complementary scripts that creates `_headers`, and would like to integrate contribute by adding such functionality to publii directly.

which place in the code do you offer me to start looking at?
do you think it should be added?

**Comment by dziudek** [comment]
Such files can be managed via Tools -> File manager -> under root files. So additional functionality regarding this is unnecessary.
