### ISSUE TITLE
Unable to add a link to an Image in WYSIWYG editor

### ISSUE THREAD

**Issue by smellyspice** [GetPublii/Publii#812]
Attempting to add a link to an image in WYSIWYG editor removes image from post.

Steps to reproduce:

1. Add new post using WYSIWYG editor
1. Click Insert/Edit image button and add an img, with desired options and then click Save
1. Click Insert/Edit Link and attempt to add a link (I tested to a Post or External). Add options and click OK

Result: Instead of a link being attached to the image, the entire Image disappears from the page.

Note: I tested the same steps above using the block editor and I *was* able to add a link to an image. This seems to only be an issue with the WYSIWYG editor. 

Version: v.0.36.1 (build 13320) beta (Windows)

**Comment by bobmitro** [comment]
This has been fixed and will appear in an upcoming Publii release https://github.com/GetPublii/Publii/issues/782
<img width="953" alt="screenshot 2020-09-5 o 19 36 45" src="https://user-images.githubusercontent.com/1391007/92310480-2a869600-efaf-11ea-80be-36022e2e30ac.png">

**Comment by smellyspice** [comment]
@bobmitro  - OK, sorry for the dupe. I did search for the issue before logging it, but came up empty handed. :(
