### ISSUE TITLE
Cannot switch editors when editing an existing post

### ISSUE THREAD

**Issue by smellyspice** [GetPublii/Publii#813]
The documentation under [Editing a Post](https://getpublii.com/docs/adding-editing-and-deleting-posts.html#editingapost) says: 

> Note: When a post is opened for editing, Publii will automatically use the last-used editor, rather than the specific editor that was used to create the post.

I don't see it functioning this way. 

Steps to reproduce: 
1. Add a New post called WYSIWYG with the WYSIWYG editor and Save
1. Add a new post called Block with the Block editor and Save
1. Click to edit the Block post, note the Block editor comes up.
1. Click to edit the WYSIWYG post, the WYSIWYG editor opens, even though the Block editor was last used.

Using version: v.0.36.1 (build 13320) beta (on Windows 10)

I also see no way of selecting what editor to use when Editing a post. This would be a nice feature to have, along with the above mentioned 'last used' editor -- for instances when you want to edit a post using a different editor than what is normally used.

**Comment by bobmitro** [comment]
There is a mistake in the user docs; you can't mix editors, so if your post was created in a WYSIWYG editor, it will be edited in the same editor.

**Comment by smellyspice** [comment]
@bobmitro  - Great, thanks for the clarification.
