### ISSUE TITLE
slider in portfolio theme displays a maximum of 5 posts

### ISSUE THREAD

**Issue by novalore** [GetPublii/Publii#82]
See https://publii.ticksy.com/ticket/1596653/
There is a bug on Portfolio theme that was fixed by @bobmitro in the ticket.
The default for "featuredPostsNumber": should be -1 and there should be an option in theme settings to decide how many featured posts have to be displayed on the homepage.

**Comment by GetPublii** [comment]
Our fault. Please add to your config.json file the following code:

`        "featuredPostsNumber": -1,
`
