### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by basharovV** [GetPublii/Publii#829]
I'm wondering if it's possible to implement hot reloading for Handlebars theme development.

**Problem:**
Currently, when you make a change to a theme, you always need to go back to Publii and press "Preview Changes", which opens a new tab in the browser. 

**Solution:**
Would be great if there was some kind of worker that watched changes to that directory and reloaded the page on the same tab.  I understand that this functionality might actually be a custom JS script, (part of the theme itself) but perhaps it can also be a settings toggle within Publii.

**Comment by abroudin** [comment]
Do you have a way to do it right now? it's kind of annoying to dev themes with "preview changes" only

**Comment by basharovV** [comment]
I've already developed the theme I needed using the slow manual method for now...

But from what I can gather it would require the following: 
- having a script that watches changes to files in a directory on an interval (eg. every 1s)
- compare the `lastModifiedDate` and if changed copy over the theme assets over to the Publii `preview` and `output` directory.
- finally trigger a reload (I believe this requires a separate socket connection via Websockets or socket.io, so we need a server to emit the event and a client on the page to handle the reload event - that's how bundlers like [Parcel](https://github.com/parcel-bundler/parcel/blob/v2/packages/core/parcel-bundler/src/HMRServer.js) and [Webpack](https://github.com/webpack-contrib/webpack-hot-middleware/blob/master/process-update.js) do it).

**Comment by rjcpereira** [comment]
> Did you find a way to do it? it's kind of annoying to dev themes with "preview changes" only

if you want go give this a try, not ideal, but saves some time: [publii-base-template](https://github.com/rjcpereira/publii-base-template)

**Comment by dziudek** [comment]
We will consider such feature, but at this moment only for developer tools (work in progress). So it will be a separate project which will help people to faster and easier create themes (where a lot of refreshes are necessary). I am closing this task as it won't be related to the core Publii app.

**Comment by hertg** [comment]
Has there been some kind of community project that addresses this? The project linked by @rjcpereira is no longer available.
I really want to get into Publii and start using it for some sites and create my own themes, but this limitation is what hindered me from actually doing it, because developing a theme seems like quite a hassle without hot reload.

**Comment by norrbru** [comment]
Would also really appreciate this feature.
