### ISSUE TITLE
Where to file/fix Doc issues?

### ISSUE THREAD

**Issue by tedyoung** [GetPublii/Publii#83]
I found some (minor) problems on one of the doc pages (first paragraph in https://getpublii.com/docs/build-a-static-website-with-netlify.html has the header repeated in the paragraph itself). Are the docs hosted somewhere that can accept contribution/fixes?

**Comment by GetPublii** [comment]
Thank you for reporting this issue. Our docs are generated by Publii, there is no repo for that. 
Problem fixed.

**Comment by xurizaemon** [comment]
Can Publii interoperate with sites managed in Git?

Open sourcing your docs is a great way to allow new contributors to participate and be credited for their work.

**Comment by dziudek** [comment]
@xurizaemon - unfortunately there is no easy way to manage the docs through repository as all website content is stored in the SQLite database.

**Comment by xurizaemon** [comment]
Fair enough! Thanks
