### ISSUE TITLE
Cant open "Read more about supported features"

### ISSUE THREAD

**Issue by umtksa** [GetPublii/Publii#830]
![Screen Shot 2020-09-26 at 14 22 26](https://user-images.githubusercontent.com/12473742/94339608-c67e4d00-0003-11eb-9a02-90eba3fc68ce.png)
clicking "Read more about supported features" throws a 404 error inside publii
![Screen Shot 2020-09-26 at 14 22 39](https://user-images.githubusercontent.com/12473742/94339603-c54d2000-0003-11eb-8cc6-71982fe6b1a4.png)

**Comment by dziudek** [comment]
Problem solved, also in just released v.0.37.1 we have solved an issue with opening this link inside Publii instead of browser window.
