### ISSUE TITLE
Rendering process failed An error occurred during rendering process:  Invalid count value

### ISSUE THREAD

**Issue by paule96** [GetPublii/Publii#833]
I upgraded publi to v0.37.1 and I now can't preview my websites. 

They both use the theme `Simple(v.2.3.0.0)`

It always fails with the following error:

```bash
Rendering process failed
An error occurred during rendering process:

Invalid count value
```

I now try to downgrad to the version before...

**Comment by dziudek** [comment]
Hi,

Are you using relative URLs options on windows?
