### ISSUE TITLE
FTP / SFTP upload problem

### ISSUE THREAD

**Issue by fbattal** [GetPublii/Publii#843]
Hello,

I'm running Publii on my Hosting, It's plesk based and there is no connection limitations. This problem becomes with if I try to upload my changings 4-5 times, it says to me;

An Error Occured during connecting to server. Screenshot;

<img width="1440" alt="Screen Shot 2020-10-09 at 03 39 12" src="https://user-images.githubusercontent.com/68411296/95528567-1e905880-09e1-11eb-91c8-a5245e2c6344.png">

How may I fix that?

Regards,
Fatih

**Comment by internettips** [comment]
Your connection settings probably need tweaking. Please ask at: https://getpublii.com/forum/

**Comment by dziudek** [comment]
Yes, please consult such issues on the support forum first, if we will have a confirmation about some edge-cases then the issue can be created.
