### ISSUE TITLE
Is there a way to disable post pages or ignore files?

### ISSUE THREAD

**Issue by Christilut** [GetPublii/Publii#844]
I've made a super simple template (a changelog) that I just want to be one page, the `index.html`. It adds all posts to the index so this is all good but it also creates a separate HTML file for each tiny post. Uploading takes way longer than needed because of this, since it really only needs to upload 1 HTML file each time instead of 100+.
Any way to turn off creating the post pages? Or filter them so only index.html gets uploaded?

**Comment by bobmitro** [comment]
You can't turn off the creation of post pages, you can do it with tags, author pages but not posts. Publii is a blog-oriented CMS and this is why it requires posts.

**Comment by Christilut** [comment]
Okay, I guess I'm abusing it a little bit :) Just really like how Publii works so I'm using it with non-blog sites too.

**Comment by bobmitro** [comment]
:)
