### ISSUE TITLE
[Simple theme] short description with links display them as text, not links

### ISSUE THREAD

**Issue by arthurlogilab** [GetPublii/Publii#846]
Here is an example : https://arthur.pages.logilab.fr/blog/ 

I would expect the "Summary" / "Extract" to include the links. Showing URLs without being able to click on them  feels like a bug. 

Did I miss an option in the theme or in the application ?

**Comment by bobmitro** [comment]
All issues not related to the app please report on the forum. https://getpublii.com/forum/

**Comment by arthurlogilab** [comment]
Sorry for the wrong canal. Posted here : https://getpublii.com/forum/topic/simple-theme-short-description-with-links-display-them-as-text-not-links/
