### ISSUE TITLE
directionality plugin does not work as expected

### ISSUE THREAD

**Issue by sepisoad** [GetPublii/Publii#848]
I have added the "**directionality**" plugin to "**tinymce.script.js**" file and saved this file in my theme root directory:

```js
tinymce.init({
  selector: 'textarea',
  plugins: 'directionality',
  toolbar: 'ltr rtl'
});
```

I have also updated "**tinymce.override.json**" toolbars file as follows:

```json
{
  "toolbar1": "bold italic underline strikethrough link unlink blockquote alignleft aligncenter alignright bullist numlist image gallery media table toc ltr rtl",
  "toolbar2": "styleselect formatselect searchreplace hr readmore removeformat undo redo restoredraft sourcecode forecolor backcolor"
}
```

however the plugin does not seem to work and I do cannot see the **rtl** and **ltr** toolbar items in editor

**Comment by dziudek** [comment]
Hi,

Please try to experiment with tinymce.override.json inside the Publii app config directory - you will need to define toolbar and plugins fields in your JSON.
