### ISSUE TITLE
Option to disable navbar visiblity when scrolling up

### ISSUE THREAD

**Issue by cwmke** [GetPublii/Publii#851]
Currently there doesn't appear to be an option to disable this functionality. It would be nice to have an option for the navbar be stationary at the top of the page. The up arrow that appears allows quick access to the top of a page which negates the need for the floating navbar in my case. Also, as I have a transparent navbar, while scrolling up occasionally a person may try to click a link that is actually covered by the invisible bar; rendering it unclickable and confusing.

A toggle placed in `Theme > Navbar` labeled "Navbar visible while scrolling" is the desired functionality.

**Comment by bobmitro** [comment]
All problems not related to the application should be referred to the [forum](https://getpublii.com/forum/) 

PS: I think you can adjust it yourself as it is related to modifying the theme files.
