### ISSUE TITLE
Hang on Site Title Change->Preview

### ISSUE THREAD

**Issue by benthroop** [GetPublii/Publii#853]
Hey in the 0.37.2  build, I attempted to change the name of my site in Site Settings->Basic Settings->Site Name. Publii allowed me to do this, and to save the setting. However once I tried to Preview changes, it hung. 

There is something in rendering-errors.log that might be related:

`(node:3632) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of undefined
    at new Renderer (C:\Users\Frame\AppData\Local\Programs\Publii\resources\app.asar\back-end\modules\render-html\renderer.js:47:41)
    at process.<anonymous> (C:\Users\Frame\AppData\Local\Programs\Publii\resources\app.asar\back-end\workers\renderer\preview.js:13:24)
    at process.emit (events.js:210:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(node:3632) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3632) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by benthroop** [comment]
I was able to work around this by changing the "displayName" in site.config.json to what I wanted. Then Publii was able to build the site.

**Comment by dziudek** [comment]
Hi,

Unfortunately I am unable to reproduce this issue - I have tried to rename a newly created website and rename a website after a Publii restart - in both cases it is working fine and I am able to do a preview.

Are you able to reproduce this issue? If yes - can you provide an exact description how you did it?

**Comment by dziudek** [comment]
Closing due inactivity
