### ISSUE TITLE
Malformed files.publii.json not working anymore

### ISSUE THREAD

**Issue by cristian-milea** [GetPublii/Publii#854]
Hi. 

My SFTP deployment gets stuck after working for months. I am on 0.37.2

Looking at logs, saw that `files.publii.json` had syntax incorrect, although no errors were displayed during the deployment. Checked the file on server and it was indeed malformed probably due to an interrupted deploy.

Found #594 , but I don't think it's working anymore.

Thought that by deleting the file, I would force uploading the whole site again but deployment gets stuck at files 0 of 2547. Left it for about 20min.

In logs I now have a new error:
```
ERR (2): Error: Failed to get public_html/files.publii.json: No such file (Error: Failed to get public_html/files.publii.json: No such file
    at ReadStream.<anonymous> (/opt/Publii/resources/app.asar/node_modules/ssh2-sftp-client/src/index.js:214:25)
    at ReadStream.emit (events.js:210:5)
    at ReadStream.EventEmitter.emit (domain.js:476:20)
    at /opt/Publii/resources/app.asar/node_modules/ssh2-streams/lib/sftp.js:2789:12
```
![Screenshot from 2020-10-21 15-21-47](https://user-images.githubusercontent.com/4988454/96778414-499b8480-13b1-11eb-9353-1636be7b7435.png)

**Comment by cristian-milea** [comment]
I managed to bypass this issue by creating a manual deployment and then uploading it through Filezilla.
Still think it is a good idea to check that json functionality for regressions.

**Comment by dziudek** [comment]
@cristian-milea - I was able to reproduce your issue and I have fixed this case. The fix will be available in v.0.37.3
