### ISSUE TITLE
Not able to run even once

### ISSUE THREAD

**Issue by editingaddictz** [GetPublii/Publii#855]
Hello I tried to install Publii on my windows 7 home premium edition 64 bit, but it shows black white screen each time I open it.

I have tried to re-install it several times, but was unable to find out the problem
![Untitled](https://user-images.githubusercontent.com/73574025/97432189-94814300-1941-11eb-8226-616c26121c15.png)

**Comment by dziudek** [comment]
Unfortuntely I have no access to Win7 x64 so I am unable to check if it is only your problem or a common problem on this platform :( 

If anyone has an access to this Windows version - please let us know about Publii in this environment.

**Comment by pagelab** [comment]
Yes, it's not working properly on Windows 64 bit. #652 has accounts of other users about it. 

You can download an [official Windows 10 ISO image](https://www.microsoft.com/en-us/software-download/windows10ISO) (64/32 bit) from the Microsoft website and install it on Virtual Box for testing purposes.

**Comment by editingaddictz** [comment]
Actually my laptop is 10 years old it does not work better with windows 10 also I can't afford to buy a new one, so I thought there might be some solution for my problem

check out my github page which I got made from one of my friend, I would like to hear comments on that [https://editingaddictz.github.io/](url)

I was going to make this blog on publii but as it does not worked I asked my friend to code it for me

**Comment by dziudek** [comment]
@pagelab - I am testing Publii on Windows 10  64-bit and it is working fine for me. I suppose that it can be some problem with AV software.

**Comment by pagelab** [comment]
I've created another WIn10 64-bit instance and the latest version is working fine on this one.

These are both clean installs for testing purposes, there's no AV software installed. So, I'm not sure what have caused it on the other one.

**Comment by hiensarahly** [comment]
On my Windows 7 Ultimate 64-bit, I installed Microsoft Visual C++ 2015-2019 Redistributable packages (both x86 and x64 versions). It has worked for me. Not sure if it helps.

https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by dziudek** [comment]
I am closing this issue due inactivity. If there will be something new, worth mentioning - feel free to reopen :)
