### ISSUE TITLE
Cannot set Github Pages

### ISSUE THREAD

**Issue by mencargo** [GetPublii/Publii#857]
Trying to set a Github Pages repo, testing shows:
Error! Application was unable to connect to your server: Not Found

Using a custom domain, server: api.github.com
Token is fine (after a lot of saving and testing)

Publii 3.7.2 in Linux

**Comment by dziudek** [comment]
Hi,

Maybe you have provided wrong repository name or unexisting branch name. We have no similar reports of such issues at this moment so please review your settings and come back if you will see that it looks like a bug not a configuration issue. You can always consult configuration issues on the official forum: https://getpublii.com/forum

**Comment by mencargo** [comment]
I'm the owner, and you can verify it:
Website URL: https://escuelinea.com/
API server: api.github.com
Username: mencargo
Repository: web-escuelinea
Branch: master

https://github.com/mencargo/web-escuelinea

**Comment by dziudek** [comment]
@mencargo - I see what is a reason of your issue: https://www.zdnet.com/article/github-to-replace-master-with-main-starting-next-month/

Please change the branch name from `master` to `main` - it should help.

I will update the UI in the app to mention this changes.
