### ISSUE TITLE
Unable to create new website after update to 0.37

### ISSUE THREAD

**Issue by jasedu** [GetPublii/Publii#862]
After installing, I add a new website (name and author) and I get this error message. I am runnig publii on a  Windows 10 Home 64 bits.

![image](https://user-images.githubusercontent.com/36727228/99045016-f58b5680-2590-11eb-91d0-e680a1fce0a1.png)

**Comment by dziudek** [comment]
Hi, do you have any AV software installed?

**Comment by jasedu** [comment]
> Hi, do you have any AV software installed?

Yes, AVAST. Could that be an issue? I run the program as adminstrator

**Comment by dziudek** [comment]
As I suppose AVAST blocked your DB file - some AV software treat SQLite databases as a potential problem. The only solution is to somehow whitelist specific files. Usually during second try there is no issues with it. 

I will leave this issue to create a detection of such issues and show a proper message in this case.
