### ISSUE TITLE
Widgets in side-bar

### ISSUE THREAD

**Issue by joeldebruijn** [GetPublii/Publii#865]
I'm under the impression that at the moment the content of the side-bar is theme dependent.

Would be nice to have "Widgets", so end-users can customise the content in the side-bar, by dragging this on a template-canvas.

For example a widget with just a photo, a widget with a blogroll or other resources, or one with just a little text.

Maybe I missed something, failry new to Publii. ;)

**Comment by joeldebruijn** [comment]
Or could I, in the meantime, just insert some hardcoded info here, following an example about ads:
![image](https://user-images.githubusercontent.com/3906940/99686183-a3ac6a00-2a83-11eb-8a7e-50a3e2176869.png)

**Comment by dziudek** [comment]
Hi,

If such things will be possible, then only via plugins, not in Publii core. But it will also require some theme modifications so I suppose that due amount of work it won't happen in the near future.
