### ISSUE TITLE
Uncaught Exception: Error: ENOENT

### ISSUE THREAD

**Issue by searchboy-sudo** [GetPublii/Publii#869]
I am using MacOS 11.0.1 and when I install Publii and launch the application I get the following error 

Uncaught Exception:
Error: ENOENT: no such file or directory, scandir '/Users/derin/Documents/Publii/sites'
at Object.readdirSync (fs.js:854:3)
at Object.fs.readdirSync (electron/js2c/asar.js:621:39)
at App.loadSites (/Applications/Publii.app/Contents/Resources/app.asar/back-end/app.js:305:24)
at new App (/Applications/Publii.app/Contents/Resources/app.asar/back-end/app.js:70:14)
at App.<anonymous> (/Applications/Publii.app/Contents/Resources/app.asar/main.js:36:19)
at App.emit (events.js:215:7)
at App.EventEmitter.emit (domain.js:476:20)
at App.topLevelDomainCallback (domain.js:131:23)

Not sure if this helos you fix it, or if it's something I can do. But I figured I should say something.

**Comment by dziudek** [comment]
Hi,

Did you give Publii permissions to write files in the documents folder? You should get a system notification about it during first run.

**Comment by Christilut** [comment]
I'm having the same error after moving the Publii folder elsewhere. Now I can't start Publii at all anymore, so I can't change where it looks for the Publii folder either.

**Comment by dziudek** [comment]
@Christilut - you can manually edit the sites location folder in the Publii/config/app-config.json under key `"sitesLocation"`

**Comment by Christilut** [comment]
Thanks. I fixed it by moving the Publii back to the old location and change the config after being able to launch it.

But this would be good to catch automatically because I really couldn't use Publii at all in this state.

**Comment by dziudek** [comment]
@Christilut - I suppose that this fix will solve this issue: https://github.com/GetPublii/Publii/issues/905 - in your situation you will get a message about invalid catalog. But anyway - it requires a manual fix on the user side.

I am closing this issue as I realized that #905 provides a better feedback for user in such situation.

**Comment by searchboy-sudo** [comment]
> I am using MacOS 11.0.1 and when I install Publii and launch the application I get the following error
> 
> Uncaught Exception:
> Error: ENOENT: no such file or directory, scandir '/Users/derin/Documents/Publii/sites'
> at Object.readdirSync (fs.js:854:3)
> at Object.fs.readdirSync (electron/js2c/asar.js:621:39)
> at App.loadSites (/Applications/Publii.app/Contents/Resources/app.asar/back-end/app.js:305:24)
> at new App (/Applications/Publii.app/Contents/Resources/app.asar/back-end/app.js:70:14)
> at App. (/Applications/Publii.app/Contents/Resources/app.asar/main.js:36:19)
> at App.emit (events.js:215:7)
> at App.EventEmitter.emit (domain.js:476:20)
> at App.topLevelDomainCallback (domain.js:131:23)
> 
> Not sure if this helos you fix it, or if it's something I can do. But I figured I should say something.



> Hi,
> 
> Did you give Publii permissions to write files in the documents folder? You should get a system notification about it during first run.

Yes It already has permissions to write in the documents folder. I just checked. I havent been able to use Publii in months. I had to find another solution for my documentation project.
