### ISSUE TITLE
Site location on remote machine (NAS)

### ISSUE THREAD

**Issue by shantee** [GetPublii/Publii#872]
Hello 
I would like to set my "sites location" , "site Backup" and site preview"  folders in a remote machine , a NAS. So i could work from different computer easily.
I am on Linux (Mint). So I can access, browse and select these remote folders on Publii
the path looks like this : 

`/run/user/1000/gvfs/sftp:host=192.168.1.18,port=2828,user=admin/home/publii
`
But when I save I get this error :

**"an error occured during saving the app setting "**

Please help

**Comment by dziudek** [comment]
Hi,

Sorry but it looks like SFTP connection not the normal locally available filesystem - Publii won't treat it as a normal local location.

I suppose that the only solution would be mount the catalog from NAS as a normal catalog in your filesystem (if possible) and then try again without the SFTP config inside the path.

**Comment by shantee** [comment]
Hello 
Thank you for you response. Yes mounting the remote folder on my local system works indeed. 
I found a way with sshfs.
If someone is interested I made "nicely wrapped"  my solution in a shell script you can find here :
https://github.com/shantee/SSHFSauto

That would be great if Publii supported natively to store its "catalog" somewhere else like FTP server, SMB  etc.. 
Maybe a future feature ? :)

**Comment by dziudek** [comment]
I am closing this issue, as it seems to be a quite niche feature, which also have a working workaround solution :)
