### ISSUE TITLE
.cookie-popup class only in style.css

### ISSUE THREAD

**Issue by lwndwsk1** [GetPublii/Publii#876]
So i wanna change the color of the GDPR box from the "Simple Theme". Only location for this Colorcode is in the style.css. In main.css there is no option for it. If i copy the style.css in my ../input/themes/simple-override/assets/css Folder, i gets overwritten everytime i render the page and my changes are gone. Could you pls help me with this topic?

**Comment by internettips** [comment]
Sure. Go to the support forum at: https://getpublii.com/forum/ ask there and mention the colour you want.

**Comment by lwndwsk1** [comment]
So can I assume you don't know the answer? Why you are responding then? From a technical point of view, I would like to know why the colorcode is only available in the style.css, not in the main.css. As ive been told, style.css is the rendered outcome from main.css. So "mention the colour you want" is a little bit to easy. And this is the "Issues" Tab, so i think im absolutely correct here.

**Comment by internettips** [comment]
Your problem will be solved by changing a theme, not about Publii CMS 'issues' directly. 

If you go to https://getpublii.com/forum/ , you can get help more easily.

But here's your answer:

1. In Publii, go to Tools > Custom CSS.

2. Enter the code below and save:

.cookie-popup__save {
    background: #aa2480;
}

.cookie-popup--uses-badge {
    background: #aa2480;
}

3. When you test the preview version of your theme, you'll note the colour has changed. If you know the CSS colour value you want, just change the code above to your value.

Hope that helps.

**Comment by lwndwsk1** [comment]
Nice, thanks! +1
