### ISSUE TITLE
Register and Use Custom Vue components

### ISSUE THREAD

**Issue by baramofme** [GetPublii/Publii#880]
Developer can register Custom vue.js components.
Developer can use that component in theme making process.

Users also can register Custom vue.js components.
Users can use component inside article.

For now I checked Vue code can rendered inside article. #367.

And If I can use custom(or plugins like quasar, vuetify ... etc) components, I feel  more comfortable with Publii. 

Thanks regards

**Comment by h8h** [comment]
I also thought about this.

The question I ask myself is Publii more a blog CMS or a raw CMS.

If the latter than I would like to have columns, too. It should be possible to decide per page where the text goes, either to the header or to the sidebar or to the main content. But I think, this breaks the simplicity and the main concept of this tool.

**Comment by dziudek** [comment]
If you need to use some custom HTML/script structure I recommend block editor with it's HTML block. Of course it needs a properly prepared theme which loads external libraries needed to render these components.
