### ISSUE TITLE
Use Publii on tablet (android & IOS)

### ISSUE THREAD

**Issue by baramofme** [GetPublii/Publii#881]
Users can open and edit his(her) contents on tablet device.
Tablet device is
 - has wide screen (more than 8 inch)
 - so that use it as Document editor tool.
 - Android and IOS
 - Not 6'inch  hand-held device.

Thanks regards

**Comment by dziudek** [comment]
Hi,

At this moment we have no plans for mobile system applications, as it means a developing a totally new apps.
