### ISSUE TITLE
Gallery Figcaption Textarea

### ISSUE THREAD

**Issue by h8h** [GetPublii/Publii#882]
Hi,

First of all, thank you for this amazing desktop-based CMS <3

I have a feature request I want to submit.

Is it possible to make multiline figcaptions within the gallery? Technically spoken to make a textarea instead of an input field, see [Gallery](https://github.com/GetPublii/Publii/blob/master/app/src/components/post-editor/GalleryPopup.vue#L35)?

For example I have a teams section, every member has an image, a name and a role like this one [Our creative minds](https://www.bootdey.com/snippets/view/social-team).

Currently I can only put name and role in one line or I can inject HTML by writing  `<p>Name</p><p>Role</p>`, but this is a dirty hack and I have to do it again every time I opening the gallery.

Thank you

**Comment by dziudek** [comment]
Hi,

Adding a textarea is a bad idea as it will expand the UI. But I have allowed HTML inside the image captions so you will be able to use e.g. `<br>` tags inside your captions :)
