### ISSUE TITLE
custom s3 endpoint not working with minio

### ISSUE THREAD

**Issue by lorenzogirardi** [GetPublii/Publii#883]
Using the custom s3 provider i receive and error

step to reproduce

- create a minio container/server with endpoint minio.domain.tld
- switch publii to s3 custom endpoint
- add minio.domain.tld as endpoint

<img width="964" alt="Screenshot 2020-12-08 at 12 05 36" src="https://user-images.githubusercontent.com/16288002/101476515-2bccb380-394e-11eb-9aab-05cc66f6e2be.png">

www prefix will be added and it's shared an error related to aws s3 region

**Comment by lorenzogirardi** [comment]
update

changed the url parameter to be compliance with the s3 standard where the bucket name is before the domain
i was able to connect , however still persiste an error

[Tue, 08 Dec 2020 11:31:20 GMT] <- files.publii.json
[Tue, 08 Dec 2020 11:31:20 GMT] S3 ERROR: Unknown API request at //minio/blog/files.publii.json

**Comment by lorenzogirardi** [comment]
fixed on minio server adding this env

        - name: MINIO_DOMAIN
          value: minio.mydomain.lan

**Comment by johnchristopher** [comment]
I have the same error but the answers aren't detailed enough to get rid of it.

1. Could you provide an example of a remote minio server parameter compliant with the s3 standard ?

2. Could you elaborate on the minio server-side fix ?
