### ISSUE TITLE
[Windows10] Languages that require conversion causes duplication on Enter in block editor

### ISSUE THREAD

**Issue by Kolloom** [GetPublii/Publii#886]
![bug_2](https://user-images.githubusercontent.com/13244794/102038581-3becf480-3d8d-11eb-9f8e-d8e3373293aa.png)

OS: windows 10
Publii version: v.0.37.3 (build 13870) beta

Some langauge input methods requires user to hit enter to convert selected characters. The staged characters are indicated with a dark underline. 
In the block editor, when hitting enter to confirm characters, the entered characters are duplicated in the text field.

This behavior is only seen in the block editor. Entering characters in the title field causes no duplication.

**Comment by Kolloom** [comment]
Tested and reproducible with windows 10 built-in Traditional Chinese and Japanese IME.

**Comment by dziudek** [comment]
The problem is caused by lack of check if the keydown event contains flag isComposing set to true. I have fixed it in the block editor and in Publii for every enter key detections.

ref. https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/isComposing
