### ISSUE TITLE
Publii not creating sitemap.xml

### ISSUE THREAD

**Issue by mrlen76** [GetPublii/Publii#887]
I have created a site with Publii, and even though I have sitemap toggled on, it is not generating a sitemap.xml

Is there anything I can try/adjust to correct this?

**Comment by dziudek** [comment]
Hi,

Did you enabled indexing of your website under SEO settings? You should have disabled option "Noindex website" under `Site setings -> Advanced options -> SEO`

**Comment by Feriman22** [comment]
Hi @mrlen76 

Do you use "relative path" in Server Settings?
_Note: while using relative URLs, some features like Open Graph tags, sitemaps, RSS feeds, JSON feeds etc. will be disabled._

More information:
https://getpublii.com/docs/server-configuration.html

**Comment by dziudek** [comment]
Closing due inactivity
