### ISSUE TITLE
Include full HTML content of a post on the front page

### ISSUE THREAD

**Issue by niutech** [GetPublii/Publii#892]
I want to include a full HTML content of one of my posts (edited using the WYSIWYG editor) on the front page, so in `index.hbs` I put:
```
{{#getPost 1}}
{{text}}
{{/getPost}}
```
But when I preview my changes, I get escaped HTML entities instead of the raw HTML, i.e. `&lt;div&gt;` instead of `<div>`. How to insert the raw HTML content?

**Comment by dziudek** [comment]
Hi,

You can put raw content using the `{{{ text }}}` syntax :) 

https://handlebarsjs.com/guide/expressions.html#literal-segments

**Comment by niutech** [comment]
Dziękuję!

**Comment by masvil** [comment]
> You can put raw content using the `{{{ text }}}` syntax :)

Good to know, any chance to see that included in Publii documentation?
