### ISSUE TITLE
Publii Appimage not running on Debian 10

### ISSUE THREAD

**Issue by gcomi1977** [GetPublii/Publii#893]
hello,
I am on Debian 10 Buster,
if I launch the appimage here is the error:

$ ./Publii-0.37.3.AppImage 
The setuid sandbox is not running as root. Common causes:
  * An unprivileged process using ptrace on it, like a debugger.
  * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Rilevato trace/breakpoint

thanks in advice

**Comment by dziudek** [comment]
Hi,

Did you tried to use the *.deb package?

**Comment by dziudek** [comment]
It seems that your issue can be related to a fact that electron-builder do not add no-sandbox flag during creating appImage: https://github.com/electron-userland/electron-builder/issues/5371

**Comment by gcomi1977** [comment]
hi,
thank

> It seems that your issue can be related to a fact that electron-builder do not add no-sandbox flag during creating appImage: [electron-userland/electron-builder#5371](https://github.com/electron-userland/electron-builder/issues/5371)
> 
> More details: https://www.reddit.com/r/debian/comments/hkyeft/unable_to_run_appimage_applications_without/

hi! thank you very much the --no-sandbox solved the problem.
I found Publii by pure luck and I must say it's a fantastic tool, I'll reccomend it to everyone! I've been looking for something similar for years.I think it might be useful to publish it on flathub and the Debian repositories as well.

**Comment by dziudek** [comment]
Thank you for your warm words about Publii :) 

At this moment we have many important tasks to do, but I do hope that, when we finish the most important milestones, we will give more focus on preparing more packages and publish it on more repositories (it is also time consuming and makes the build process longer).
