### ISSUE TITLE
Missing helper lazyload

### ISSUE THREAD

**Issue by Swader** [GetPublii/Publii#896]
I'm getting this error after updating a site that's not been updated for a while:

```
Rendering process failed
An error (1002) occurred during parsing index.hbs file.

Missing helper: "lazyload"
```

How do I get around it?

**Comment by bobmitro** [comment]
Are you overwriting any file in the theme? Publii, from the 36.0 version (https://getpublii.com/blog/release-036.html) uses a native lazy loading, so now the helper is no more needed.

**Comment by Swader** [comment]
Works great with a newer Publii, thank you
