### ISSUE TITLE
UX Suggestion: Change Preview/Back button positions

### ISSUE THREAD

**Issue by matthillco** [GetPublii/Publii#897]
When creating/editing a post, the **Preview** button is top left, and the **Back to Posts** button is top right, next to Save. 

This is counter-intuitive, because when you're saving the post, you probably want to preview it as a next step, and having to search for that option on the opposite side of the screen is confusing. It's also customary for a "back" button to be on the left of the screen.

Swapping the position of these buttons would likely provide a better user experience.

**Comment by bobmitro** [comment]
This has been changed in the latest Publii versions.
