### ISSUE TITLE
Add custom styles in the editor.

### ISSUE THREAD

**Issue by shantee** [GetPublii/Publii#899]
Hello 
I would like to add some custom styles that I could use inside the editor.
Let me explain :
For exemple let's say I want some text to be inside of "speech bubbles" like in lots of  IM apps.
I would then just select my text and apply "style-name" which could be some CSS.

That would be neat if there was a dropdown menu with all my custom styles.
So I 'll just clikc and select for example "pink-bubble" "blue-bubble" etc.. :)  

Is there a way to do it already ?
Thanks

**Comment by bobmitro** [comment]
There is an option for that, all you need to do is define CSS styles (class) in the ** customElements ** section of the config.json file https://getpublii.com/dev/theme-configjson-file/
Your custom classes will be available in the **paragraph** drop-down menu in the WYSIWYG editor.
You can also consider adding CSS code to the CSS editor, thanks to this, after applying ** customElements ** classes, the changes will be visible immediately in the editor when writing/editing a post. https://getpublii.com/dev/post-editor-api/#customposteditorcssstyles

**Comment by shantee** [comment]
Thanks a lot ! It helped a lot and it is working.
That's awesome it is pretty easy.
