### ISSUE TITLE
Amazon S3 & CloudFront Configuration - posts return 'No such key' error

### ISSUE THREAD

**Issue by arsachdeva595** [GetPublii/Publii#900]
I launched a blog on S3 bucket with Publii. Everything was working fine before I setup cloudfront for HTTPs. 

After setting cloudfrount, now the issue is, individual posts, tag pages and any other pages doesn't open without adding 'index.html' at the end. 

I can do that in the site settings, but for user experience sake I want to use pretty URLs without index.html at the end for each of the post. 

(Secondly, there's no way I can find to make the Sitemap work when adding index.html at the end) 

I know this is possible by tweaking some settings in Cloudfront but so far I haven't been able to have any success with the issue. Can anyone who knows publii and S3 configuration help me out with this issue? 

I want pretty URLs for all posts (without .html at the end)

**Comment by dziudek** [comment]
Hi,

Maybe this will help: https://jarredkenny.com/cloudfront-pretty-urls/

**Comment by dziudek** [comment]
Closing due inactivity
