### ISSUE TITLE
Add a portable version for Windows

### ISSUE THREAD

**Issue by Bellisario** [GetPublii/Publii#909]
Actually, there isn't a Windows portable version, yet.

Please, add a portable version: I'd like to test the app features but without installing it.

**Comment by dziudek** [comment]
Hi,

Due lack of time for managing so many releases (mac OS, Windows, Linux 3 types of packages), we have currently no plans for preparing another variant of Publii.

**Comment by Bellisario** [comment]
Thank you for your answer @dziudek, but a portable version isn't a problem for Electron... you need only do these changes (and the compiler will compile the app automatically):
> from this:

https://github.com/GetPublii/Publii/blob/f5da3df3a92fd164577d14dede9eaec1969f9cad/package.json#L94-L96

> to this:
```
 "win": { 
   "icon": "build/installation/icon.ico", 
   "target": ["nsis", "portable"]
```

For me, can be very useful, also to only test the app, but this is only my idea. Thanks again for your time.

**Comment by dziudek** [comment]
It is not such easy as it looks, because Publii uses some paths for storing files and it also requires a separate flow in the portable app
