### ISSUE TITLE
[Feature requests] Support CNAME file or custom deployment option

### ISSUE THREAD

**Issue by kinototo** [GetPublii/Publii#911]
I use ```Manual deployment``` as the server settings, than git push the sites to my custom git server.

But I have to create ```CNAME``` file every time after sync my websites because ```Sync``` button will erase it.

Where I can set custom domain at ```Manual deployment``` option?

Maybe further, We can create a custom deployment option, write script like this

```
#!/bin/bash
cd $output_path
echo "mydomain.example.com" > CNAME
git add -A
git commit -m $(date)
git push
```
So that I can create CNAME file, push to git at one click!

**Comment by dziudek** [comment]
Hi,

Did you tried to create the CNAME file under Tools -> File manager?

**Comment by kinototo** [comment]
Oh, thank you a lot.
