### ISSUE TITLE
Feature request: Upload publii to Cloudflare Page

### ISSUE THREAD

**Issue by Viteok** [GetPublii/Publii#918]
Do you planning to use cloudflare Page ?

> https://developers.cloudflare.com/docs

**Comment by dziudek** [comment]
I have request for the beta access, but still no reply from them :( 

But yes - if it will be possible - we will add support for CloudFlare Pages :)

**Comment by dziudek** [comment]
As any additional configuration is required - we will just prepare an article which will describe how to use Cloudflare Pages with Publii (it requires Github repository which is supported by Publii).

**Comment by kmanadkat** [comment]
Hi @dziudek I used github pages and cloudflare deployment strategy described here https://getpublii.com/docs/configure-cloudflare-pages-with-publii.html

The site was deployed: https://krupeshanadkat.pages.dev/

But it has all hyperlinks mapped to github pages & not cloudlfare pages. How do I fix it ?

**Comment by dziudek** [comment]
@kmanadkat 

> But it has all hyperlinks mapped to github pages & not cloudlfare pages. How do I fix it ?

Sorry - I do not understand - your links looks correct and links to your subdomain in *.pages.dev

**Comment by kmanadkat** [comment]
Hi @dziudek thanks for very quick reply. Yes, I changed the website url at top to the domain I need, and it started working.

<img width="1114" alt="Screenshot 2022-06-18 at 9 09 06 AM" src="https://user-images.githubusercontent.com/25281055/174421469-30ff91ac-1546-4e55-b891-948c7f181e6b.png">
 
I also added custom domain now in cloudflare: https://krupeshanadkat.com/

Thanks for building/maintaining Publii, i just love it :)
