### ISSUE TITLE
An error occurred during connecting to the server:406- {"message"' "Branch cannot be merged"}

### ISSUE THREAD

**Issue by Carl19** [GetPublii/Publii#919]
An error occurred during connecting to the server:406- {"message"' "Branch cannot be merged"}
![image](https://user-images.githubusercontent.com/34640178/109089321-016be480-774c-11eb-9e21-7c29d0edf10e.png)
![image](https://user-images.githubusercontent.com/34640178/109089380-1779a500-774c-11eb-9ea6-07649b14c267.png)

**Comment by dziudek** [comment]
Hi,

Please check if your branch should not be set to "main" - Github changed their naming conventions and now old repositories uses "master" and new uses "main" as a name.

**Comment by Carl19** [comment]
hi，
I'm very sorry, I don't know English。
So can't express clearly。
I'm not making Github。
![image](https://user-images.githubusercontent.com/34640178/109239103-ac91a200-780f-11eb-9f03-0ba887e3b8d6.png)
I try to use Manual upload settings.Uploaded to the cloud。But the web page display is not normal.

**Comment by Carl19** [comment]
> 你好，
> 
> 请检查您的分支是否应该设置为“ main”-Github更改了其命名约定，现在旧存储库使用“ master”，新存储库使用“ main”作为名称。



> Hi,
> 
> Please check if your branch should not be set to "main" - Github changed their naming conventions and now old repositories uses "master" and new uses "main" as a name.

hi，
I'm very sorry, I don't know English。
So can't express clearly。
I'm not making Github。
![image](https://user-images.githubusercontent.com/34640178/109239514-946e5280-7810-11eb-8a93-312ebb6407a2.png)

I try to use Manual upload settings.Uploaded to the cloud。But the web page display is not normal.

**Comment by dziudek** [comment]
Please try to change "master" to "main" and then try again :)

**Comment by dziudek** [comment]
Hi,

I have found a reason of this issue - in v.0.38 Publii will not use branches as this functionality seems to be broken in GitLab API.
