### ISSUE TITLE
Seek for Android App MVP

### ISSUE THREAD

**Issue by AlexNetman** [GetPublii/Publii#92]
Pushing new posts from phone is huge helper.
Just like wordpress has https://github.com/wordpress-mobile/WordPress-Android
No configurations for Mimimum Valuable Product needed: only adding and editing of posts.

**Comment by dziudek** [comment]
Hi Alex,

Even creating MVP in this case is a quite big project to implement, as it requires core changes in Publii and I am not sure if code reuse will be possible in the mobile app. What can be equal to renderer rewrite for mobile platforms. We have some ideas for this kind of project, but it is a big task and it is not planned in the nearest future. I will leave this issue for the future references :)

**Comment by Maayur** [comment]
Any Updates or possibility of a Android App for publishing Posts

**Comment by dziudek** [comment]
(clearing the backlog)

At the predictable future we have no plans for the mobile apps.

**Comment by AlexandrShmakov** [comment]
Being able to send posts from smartphone to Publii's website would be very cool and useful for promoting your product.
