### ISSUE TITLE
Error in  Test Connection Gitlab

### ISSUE THREAD

**Issue by noelnuguid** [GetPublii/Publii#920]
I'm trying to Sync a site unfortunately the documentation shown on this page:

https://getpublii.com/docs/host-static-website-gitlab-pages.html

Shows a different screenshot. Following the directions, I keep getting a 

![image](https://user-images.githubusercontent.com/16016730/109156282-9d790880-77ab-11eb-9373-fc62bcf73593.png)

Here is the screenshot of what it looks like now

![image](https://user-images.githubusercontent.com/16016730/109156574-f6e13780-77ab-11eb-83a6-7a274681fc76.png)

Im using the following version:

![image](https://user-images.githubusercontent.com/16016730/109156666-124c4280-77ac-11eb-898c-6a4c3c6224ca.png)

on MacOS running on Big Sur.

**Comment by dziudek** [comment]
Hi,

Please check if changing "master" to "main" as a branch name helps in your case.

**Comment by noelnuguid** [comment]
Thanks for the input. I tried creating a `main` branch from my master branch and changed the rules in .gitlab-ci.yml. Afterwards i change the branch field in Publii to `main.` click on the test button yields the same error.

**Comment by xinaesthete** [comment]
I had the same problem (in Catalina). I didn't try changing branch name but I'm pretty sure the branch names were the same.

In my case, [I went on to try to use Netlify instead, but that also didn't work](https://forum.getpublii.com/topic/unable-to-connect-with-netlify-server/). As I commented there, I now tested the Netlify config in Windows as well and see a similar problem. Haven't tried GitLab again. I did also earlier try GitHub & had a similar problem, although I think I only tried it with a private repo that I didn't really expect to work. Might've experimented with public as well, I forget.

May be veering off-topic here but it seems moderately likely that these errors share a similar root-cause, that is somehow related particular sites.

I also noticed a couple of slight discrepencies between the screenshots in the Publii docs & the current interface, but nothing that makes it too difficult to follow.

**Comment by dziudek** [comment]
Hi again,

@noelnuguid @xinaesthete - please check if your repository name has proper letter size. In my case `publii-another-test` won't work, but `Publii-another-test` is working fine so that value is case sensitive :)

**Comment by xinaesthete** [comment]
Hi @dziudek,

Sounded promising but altering case doesn't seem to be helping I'm afraid. I also notice that anywhere I can see in the GitLab interface for URIs etc it appears all lower-case although I'm pretty sure the name I gave when I set up the project was capitalized.

**Comment by dziudek** [comment]
@noelnuguid - I have now fixed many different issues with Gitlab deployment method. Unfortunately I am unable to reproduce your issue. After my fixes the Gitlab deployment works flawless.

The last question which can come to my mind: are you using groups for your projects on Gitlab?

**Comment by noelnuguid** [comment]
Hello 

> @noelnuguid - I have now fixed many different issues with Gitlab deployment method. Unfortunately I am unable to reproduce your issue. After my fixes the Gitlab deployment works flawless.
> 
> The last question which can come to my mind: are you using groups for your projects on Gitlab?

Hello, apologies for the delay in response. To provide feedback, I've been trying to use different branches (ie main or master) and sometimes it works sometimes it doesnt. it seems that it able to commit to a generated branch but unable to merge to whatever i've set to be the publish branch.

And also I am not using groups as of the moment (I believe there is another issue related to groups)

**Comment by dziudek** [comment]
@noelnuguid - so I suppose that the nearest update will solve your issues. Currently as a temporary solution you can try to merge manually on Gitlab branches generated by Publii. It seems that something changes in the Gitlab API what prevents Publii from merging changes in branch to the main branch. New version of Publii (we want to release it around Monday) will sync pages to Gitlab without branches due this issue with API and for me it is working fine.

**Comment by noelnuguid** [comment]
Thanks for this! Appreciate the assistance.
