### ISSUE TITLE
Add support for WebP (macOS / Windows)

### ISSUE THREAD

**Issue by dziudek** [GetPublii/Publii#921]
Currently Publii do not create responsive thumbnails for the WebP images, but sharp supports this format.

On linux it won't work as jimp does not support WebP at this moment.

**Comment by noxidsoft** [comment]
It's been a few years. Is there any traction on jimp or sharp supporting webp image format for Linux yet? As the OS user base in the wild is growing for Linux based distributions, would this be something the Publii team might look into?

**Comment by dziudek** [comment]
@noxidsoft - it was solved ~2 years ago? :) https://github.com/GetPublii/Publii/commit/e781c71b781f1af9baf3cdd75ad313dcef3d2ad1
