### ISSUE TITLE
PR: [SOLUTION] How to run Publii in KDE, XFCE and other DE than Gnome

### ISSUE THREAD

**Issue by JOduMonT** [GetPublii/Publii#926]
To prevent messages like these:

- https://github.com/GetPublii/Publii/issues/925
- https://forum.getpublii.com/topic/netlify-not-working-with-xubuntu/
- https://forum.getpublii.com/topic/unable-to-save-my-server-setting-even-with-a-new-site/#post-3156
- and probably more less explicit

I would like to propose a change in the documentation and/or it could be mentioned in a GitHub Issue Template

to say something like: Linux require libsecret but also gnome-keyring which is not by default is you use XFCE, KDE or any other DE not base on GNOME.

### such as on Xubuntu and Kubuntu is work will after:
`sudo apt install -y libsecret-1-dev gnome-keyring`

but it is probably true for Manjaro and others Linux such as Mint and MXLinux, ...

**Comment by dziudek** [comment]
Hi,

The next release (v.0.38) will contain a message when such issue will be detected: https://github.com/GetPublii/Publii/issues/739

I will also add `gnome-keyring` as a dependency in  *.deb and *.rpm packages
