### ISSUE TITLE
In Simple Theme Layout term are confusing

### ISSUE THREAD

**Issue by JOduMonT** [GetPublii/Publii#927]
Maybe just me, but in the theme Simple, at least, but the Page width and Page confuse me
![2021-03-04_09-04](https://user-images.githubusercontent.com/5204724/109899651-c1b37880-7cc8-11eb-8eaf-f4ce1827d0a3.png)

I would rather see something which reflect the code
- page margin
- entry width

**Comment by bobmitro** [comment]
Fixed https://github.com/GetPublii/Publii/commit/a39ca8735f7c8c73bf8757597f436680121f3023
