### ISSUE TITLE
backup javascript error

### ISSUE THREAD

**Issue by 1MachineElf** [GetPublii/Publii#935]
This error popped up each time I tried to open the Backup tool on the first launch of Publii. Subsequent runs of Publii did not have the problem. FYI

![publii backup error](https://user-images.githubusercontent.com/59202332/110860870-51d65c80-828b-11eb-8f0a-243fe75be10b.png)

Occurred on v.0.37.3 (build 13870) beta

**Comment by dziudek** [comment]
Hi,

Thanks I have fixed it in the upcoming v.0.38 :)
