### ISSUE TITLE
amp-img width set as null leads to an error within google search console

### ISSUE THREAD

**Issue by shuhaid** [GetPublii/Publii#940]
AMP image width was being set as null for images copy pasted into the editor.
For ex. if you copy a gif from giphy and add into your content editor. The image has width and height set as "null"

Google search console does not like this and raises it as an AMP error in the search console.

To fix the error you would need delete the image from your content editor and add it manually using the image button.

**Comment by dziudek** [comment]
Hi,

I have checked this case and it won't work, because when you copy paste image is it loaded externaly as:

```html
<p><img src="https://media2.giphy.com/media/..." alt="title"></p>
```

In such case you must provide manually height and width tags.
