### ISSUE TITLE
Website synchronization cannot end the second time

### ISSUE THREAD

**Issue by didierfolly** [GetPublii/Publii#945]
When I click the button "Sync your website" once it works but when I click it a second time the process does not end.

Here an example:
![image](https://user-images.githubusercontent.com/13508431/113046575-865d7a00-91a0-11eb-852f-65daca895c29.png)

I got the error in the log "deployment-erros.log" file in C:\Users\Username\AppData\Roaming\Publii\Publii\logs :
'-------------------
(node:5388) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, rename 'C:\Users\Username\Documents\Publii\sites\MyWebsite\output\media' -> 'C:\Users\Username\Documents\Websites\MyWebsite\LocalVersion\media'
(node:5388) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5388) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
'-------------------

If I delete the folder 'C:\Users\Username\Documents\Websites\MyWebsite\LocalVersion\media' then I can sync all the files again but I have to do it each time I want to use the button "Sync your website".

I tried to run publii as admin but it does not change anything.

Thanks in advance for your help and thanks for your software that make my life easier.

**Comment by dziudek** [comment]
Hi,

I have analysed this issue and at this moment I have no idea what can be a reason. It looks like you have some connection between Publii sites and document/websites folder what can lead to unexpected issues.

If you can provide some more details about any non-standard configuration it can help to solve this problem.

**Comment by didierfolly** [comment]
Hi,
I only have this issue on my laptop but I don't have it on another computer. I tried to find out the source of the problem without any luck. It's maybe a problem of installation but I couldn't figure it out.
You can close this bug.
Thanks by the way for your help and for your app that is wonderful!
Best regards
Didier
