### ISSUE TITLE
Allow use bigger font size in the app

### ISSUE THREAD

**Issue by dziudek** [GetPublii/Publii#950]
ref: https://forum.getpublii.com/topic/bigger-font-size-inside-the-app/

**Comment by Pilvinen** [comment]
Just a reminder - this is still very much a problem. I can't see the small font in the app UI.

**Comment by atomGit** [comment]
ditto
pretty sure it can be changed in dev tools but i couldn't quickly find it

**Comment by atomGit** [comment]
actually i did find it - it appears font size for the entire UI can be changed using the html css selector - of course this doesn't stick across sessions

@bobmitro responded to this problem (which skirts the bug category IMO) [on the forum](https://forum.getpublii.com/topic/bigger-font-size-inside-the-app/#post-10692) with...

> Making font sizes customizable in the Publii interface in different sections is quite a challenge due to the different screen sizes and complexity of the user interface. Therefore, there are currently no plans to implement this feature.

given that Publii depends on electron/chromium, i'm not certain of what technical hurdles there may be, but i have to suspect that implementing such a feature may be less difficult than Bob thinks

Publii already has a dark/light theme option that affects the entire UI, so i assume it's possible to interact with chromium on the same level that would be required to change the value of the font-size property for the html selector ... or, like firefox, 
i'm sure chromium has a global 'zoom' feature

i'd be interested in hearing from the devs as to the technical details why incorporating such a very necessary feature may be far more difficult than i suspect it is

**Comment by Pilvinen** [comment]
There's literally a single setting in the dev options which changes the UI font size,  retains the intended UI and 100% fixed the issue - just fine:

![image](https://github.com/GetPublii/Publii/assets/4374351/4fe173c8-0023-4d41-be5b-4c89cace50b2)
62.5%... for real? I mean. Come on.

![image](https://github.com/GetPublii/Publii/assets/4374351/c26a76bf-d653-41b3-9542-27d7b50ba6ce)
Before (can't see anything).

![image](https://github.com/GetPublii/Publii/assets/4374351/c40d5ab9-4ba0-4b63-9311-8483a9da4e99)
After setting to font-size to 100% (wow, it's readable and the UI space is actually used for something besides empty space between elements!)

Couple of menus need their width set to max/larger + small margins added and you're basically done (server, theme, and site settings).

It would be so simple - and so fast - to expose this setting through the settings menu. And if one wants to be super lazy about it and not make the aforementioned pages wider and add a small disclaimer to it "Warning, might affect your UI layout adversely" and that's 2 years of waiting wrapped up in 5 minutes.

Boom!

**Comment by atomGit** [comment]
@Pilvinen - yep, that's the selector i was referring to - thanks for the pix which i was too lazy to screen-cap :)

**Comment by atomGit** [comment]
looks like adding custom css to the app begins in the unpacked asar directory which, on linux, is located at `/opt/Publii/resources/app.asar.unpacked/` in my case

see: [Customize Electron Desktop Apps with JavaScript & CSS - QloudX](https://www.qloudx.com/customize-electron-desktop-apps-with-javascript-css/)

but i don't know how to implement the css in publii's case - regardless, the problem of the UI font size appears to be simple to solve, just a matter of figuring it out

**Comment by atomGit** [comment]
came up empty after some hacking around....

* installed publii-bin package (AUR) (the maintainer just now fixed a bug + is pulling the latest publii build)
* renamed `app.asar.unpacked`
* `asar e app.asar app.asar.unpacked`
* set new font-size value for html selector in `/opt/publii/resources/app.asar.unpacked/src/scss/global.scss`

according to what i read publii should use the `app.asar.unpacked` but, alas, it don't

fail

anyone else???

**Comment by atomGit** [comment]
found a (slightly hacky) solution - **largely untested** and not totally pretty - works on linux and i suspect that "other" OS as well - **be sure to back up your publii data!**

this requires publii with the external electron dep (publii-bin in the AUR - may not be relevant for other OSs ???) 

launch electron with `--force-device-scale-factor=N.N` where 'N.N' is a floating point number (1 = default / 1:1 scale):

`<path to electron> --force-device-scale-factor=[N.N] <path to publii app.asar file>`

example...

`/usr/lib/electron26/electron --force-device-scale-factor=1.3 '/opt/publii/resources/app.asar'`

**Comment by derpyherp** [comment]
Adding the parameter to the  Publii shortcut in Windows works too. Thanks.

**Comment by dziudek** [comment]
Hi,

I have added support for native zoom level API, instead of working with CSS, because it would lead to many issues e.g. with editor.

It will be included in the upcoming Publii v.0.44:
![screen](https://github.com/GetPublii/Publii/assets/22004/957ba608-12de-4106-bc23-7e7835920bde)
