### ISSUE TITLE
Connection error with Gitlab server - Application was unable to connect with yout server : selected repository does not exist

### ISSUE THREAD

**Issue by v20100v** [GetPublii/Publii#953]
Hello,

### Error message

I can't connect to my Gitlab server (on premise), without this connection error :

_Error ! Application cas unable to connect with your server : Selected repository does not exist_
![2021-04-07_181415](https://user-images.githubusercontent.com/7567933/113900084-c1c5fd00-97cd-11eb-9d32-9fed3f60578d.png)

### Context

My configuration looks like this :

- **Website url** : https://myusername.gitlab-pages.myCustomDomain.com/testjekyll
- **Server** : https://gitlab.myCustomDomain.com
- **Repository** : testjekyll
- **Branch** : master
- **Token** : a valid token with all scopes generated in Gitlab web interface

I use a private Gitlab server not exposed on web, it is reachable only in network entreprise or by VPN. I don't want to use the public Gitlab server (https://gitlab.com/).

- The url of this private Gitlab server looks like : https://gitlab.myCustomDomain.com
- The url of git repository looks like : https://gitlab.myCustomDomain.com/myusername/testjekyll
- And the Jekyll website is correctly generated by Gitlab CI/CD and it is available at this url : https://myusername.gitlab-pages.myCustomDomain.com/testjekyll
![image](https://user-images.githubusercontent.com/7567933/113900883-94c61a00-97ce-11eb-9803-292ade1ea778.png)

I'm wondering if there isn't a problem for Publii to deals with Gitlab groups ?

Could you help me ?
Thx

**Comment by dziudek** [comment]
Hi,

At this moment GitLab groups are not supported :(

**Comment by v20100v** [comment]
OK thanks for your answer.

**Comment by dziudek** [comment]
I am closing this issue, because we have another issue which is connected with lack of the support for Gitlab groups feature: https://github.com/GetPublii/Publii/issues/697
