### ISSUE TITLE
Connection error with github

### ISSUE THREAD

**Issue by Jairgo** [GetPublii/Publii#954]
Hello everyone!

I have been using publii for a very short time, I had already been working and making deployments to my github repository without problems, but today that I have tried to upload some changes I get the following error:
![image](https://user-images.githubusercontent.com/36084661/114283532-d09bf200-9a0f-11eb-9b49-2438710ebf83.png)

### **Enviroment:**
**Website URL:** https://myUserName.github.io/MyRepository
**branch:** blog
**token:** a valid token generated in Github web interface
My repository and branch exist and I have checked that they are written correctly.

### **Test Connection:**
I did the connection test and it comes out correct.
![image](https://user-images.githubusercontent.com/36084661/114283560-f923ec00-9a0f-11eb-9c2e-21bda8ad0d36.png)

I wonder why it is failing now, if it hadn't had problems before.
Could you help me?
Thank you!

**Comment by dziudek** [comment]
Hi,

First of all please check the Tools -> Log viewer -> select "deployment-process.log" and "deployment-errors.log" - it should contain some more details about your issue

**Comment by Jairgo** [comment]
Hi.

Sure, but all are the "CREATE BLOB" messages. I don't see anything useful. ☹️

**Comment by dziudek** [comment]
Hi again,

I have tried to reproduce your issue, but for me Publii works with Github perfectly. I have even tried to remove some files on Github to check if it is not a reason of the issue, but always the sync process was working fine. So at this moment I have no idea what can be a reason of your issue.

**Comment by dziudek** [comment]
Closing this issue due inactivity
