### ISSUE TITLE
Update jQuery in next release

### ISSUE THREAD

**Issue by Feriman22** [GetPublii/Publii#955]
Hi,

please update the jQuery in the next release. Publii is using v3.4.1, meanwhile the v3.6.0 has been released:
[https://blog.jquery.com/2021/03/02/jquery-3-6-0-released/](https://blog.jquery.com/2021/03/02/jquery-3-6-0-released/)

The v3.4.1 is vulnerable:
[https://snyk.io/test/npm/jquery/3.4.1](https://snyk.io/test/npm/jquery/3.4.1)

Until then how can I update it manually in Publii? I use Windows client.

Thank you!
Feriman

**Comment by dziudek** [comment]
Hi @Feriman22 ,

The latest release of Publii uses jQuery 3.5.1 so I suppose that you are using some older version of the app.

Anyway - it is a very bad practice to inform authors of the software about vulnerabilities or even suspect of a vulnerability on a public place such this issues section or public forum.

For the future cases - use more private way of communication with us like:

- private topic on our forum (https://forum.getpublii.com)
- direct e-mail e.g. you can write to my public Github e-mail or to tomasz[at]dziuda[dot]com

Thanks in advance :)
