### ISSUE TITLE
Is it possible to implement a function like hexo-generator-searchdb

### ISSUE THREAD

**Issue by Cineray** [GetPublii/Publii#957]
Hi,
Publii is a great CMS and I love it!
However Google search is not convenient enough.
Hexo has a build-in search engine which has fast responce. 

https://github.com/theme-next/hexo-generator-searchdb

I was wonder that if is possible Publii to have this, Is so importent for tech blog.
Thank you for your work!

**Comment by bobmitro** [comment]
> However Google search is not convenient enough.

You can now use our new [Static Search](https://marketplace.getpublii.com/plugins/static-search/) plugin based on FlexSearch.
