### ISSUE TITLE
Output method in manual upload is too dangerous

### ISSUE THREAD

**Issue by hydescarf** [GetPublii/Publii#961]
In the `output directory` of `Manual Upload/Deployment` in the `Server` tab, the warning is too ineffective.

I didn't read the warning written below the output directory before I press the sync button, and the result was a wipe of my whole desktop stuff, luckily enough I took a backup just right a day before this happened. While this is my responsibility, it's also an UX fault, as the warning was in light tone color (gray instead of red), and the font size was very small.

Hopefully the development team can consider 3 of these suggestions to prevent from that happening:
1. Make a pop up button warning user that they will wipe the "output folder" when they try to sync (if the method was a manual upload)
2. Deleted items should go into the Recycle Bin, not destroying them immediately. I had to use a recovery software to retrieve the deleted items but to no avail as it was too limited.
3. Compare before and after in that directory, and delete those that are no longer part of the project, but not those that didn't exist in the directory previously **_and_** in the project. This will further prevent accidents like what I have experienced.
I was just trying out the app, while not sure how the app works, I believe no one would manually edit the contents of output folder when they already have an app that does that for them. With this, a comparison check should make sense, and it will be the user's responsibility if they add/remove anything in the output folder.

Having 1st and 2nd are already sufficient enough, having 3rd will provide extra defense, but I can see it requires a little more work.
To further extend how 3rd should work, it can be either:
- record the contents on each sync, providing a list for "before and after" comparison
- record only the items deleted through the app, and delete those said items during sync (must be also the same with size, date, and possible metadata)
- or maybe something else the development team has in their mind

**Comment by hydescarf** [comment]
I just thought of a 4th suggestion, which should be the easiest one to solve.
Automatically make a new folder in the selected directory, where the name of the new folder can be edited in the other input field.
This does not require 1st, 2nd, 3rd to be considered into it. If there's an existing folder, warn the user about it (include the wipe warning, if 3rd is not included). With this, the app can simply just erase the content inside it without the need of checking (having it is an extra defense, however)

This was what I was expecting in the first place, which it gave an entirely different result to me. x(

**Comment by dziudek** [comment]
Hi @hydescarf,

FYI - I have decided to output in the selected catalog new directory with name `[SITENAME]-files` what should solve described issues :) 

This feature will be included in Publii v.0.39
