### ISSUE TITLE
Request to add WYSIWYG editor button to create HTML bookmark anchors 

### ISSUE THREAD

**Issue by internettips** [GetPublii/Publii#97]
Creating and managing linking is superb. Though as far as I can see, there's just one omission: adding a link to somewhere else on a web page, rather than to another internal or external web page.

Although of course, we can manually put in the bookmark anchor links, a button option solution on the editor would be great.

**Comment by dziudek** [comment]
Hi,

Good idea - I will add it to the 0.29.3 release :)

**Comment by candideu** [comment]
Hi, how can I get this to work?
