### ISSUE TITLE
Site preview on Windows doesn't work

### ISSUE THREAD

**Issue by KatDries** [GetPublii/Publii#975]
Hello, 
I'm running Publii v.0.38.2 (build 14204) on Windows 10 Pro 64-bits. 
The "Preview your changes" feature doesn't work. When i try to use it, i see this message: 
![Publii_preview](https://user-images.githubusercontent.com/74900456/118121091-34d81a00-b3f1-11eb-9df1-215bfa70e066.PNG)
but then it runs like this forever, the pogress bar never moving forward and the preview never opens...
Does anyone have any idea why this feature doesn't work? 

Thanks a lot for your help! 
Kat

**Comment by dziudek** [comment]
Hi,

Please check the Tools -> Log Viewer and check files for potential error reasons

**Comment by dziudek** [comment]
closing due inactivity
