### ISSUE TITLE
Add support for external featured image

### ISSUE THREAD

**Issue by devsdocs** [GetPublii/Publii#976]
The reason behind this is to lower the server load. Add option to load featured image from external URLs

**Comment by jezlister** [comment]
I would also like this option. When building Amazon Affiliate sites, Amazon expects you to link to their images and not upload them to your own site. They can delete your account for such behavior so this is an important feature to have for anyone building an affiliate site who wants to follow the guidance

**Comment by aymengn** [comment]
This will make publii much better platform for blogging I highly sport this because I'm using WordPress locally because of it.

**Comment by dziudek** [comment]
At this moment we have no plans for such feature. If you have such specific needs, it can be implemented using post config (adding a field to store URL for external image) and then handle it in your theme.
