### ISSUE TITLE
New feature request: menus > create new nav menu > link to multiple tag pages

### ISSUE THREAD

**Issue by internettips** [GetPublii/Publii#98]
Request new feature option, when creating nav menu links, to link to more than one tag page. And be able to configure which tag page gets listed first / top of page.

**Comment by dziudek** [comment]
Hi,

If you need this kind of page, you can create a hidden post which will use a custom template based on the `@website.contentStructure` global variable: https://getpublii.com/dev/create-post-list-from-specific-tags/

At this moment we have no plans to built in this kind of functionality to Publii, but I will leave this issue - if more and more users will request it, we will add it to our ToDo list :)

**Comment by bobmitro** [comment]
The Tags page, which contains all published tags, was added in Publii v. 0.37. You can find more about it here: https://getpublii.com/blog/publii-37-release.html
