### ISSUE TITLE
[Bug] 404 errors are not displayed correctly on the IPFS network

### ISSUE THREAD

**Issue by wuniversales** [GetPublii/Publii#982]
On the IPFS network, it is necessary to use "ipfs-404.html" to display the "404.html" error.
There are 3 possible solutions for this:

1- Generate a file "ipfs-404.html" that redirects to the current file "404.html".
(I think this option is the most suitable)

2- Give the possibility to rename the current file "404.html" by "ipfs-404.html".
(Maybe this solution is the cleanest)

3- Generate the 2 files "ipfs-404.html" and "404.html".
(This option is the dirtiest)

Greetings

**Comment by dziudek** [comment]
Hi,

You can easily use solution number 2. as you can specify the 404 error page filename by using option "Site settings -> Advanced Options -> URLs -> Error page" :)
