### ISSUE TITLE
Make vertical and horizontal images consume roughly the same screen area in galleries

### ISSUE THREAD

**Issue by mork1976** [GetPublii/Publii#983]
Currently vertical images are assigned much more screen space than horizontal ones which is often not the intent of the author. 
One way to solve this would be to fit all images inside their bounding square.

**Comment by bobmitro** [comment]
The gallery is styled by theme, so you can easily adapt it to your needs; here you will find all CSS classes generated by the gallery https://getpublii.com/dev/default-publii-classes-for-using-with-css/#gallery

**Comment by bobmitro** [comment]
Closed due to inactivity for a long time.
