### ISSUE TITLE
Duplicate in other project

### ISSUE THREAD

**Issue by jeckyl** [GetPublii/Publii#986]
Hi,

When managing several projects with Publii, it would be interesting to allow the duplication of Post between projects, very practical when managing multiple languages on several projects.

**Comment by dziudek** [comment]
At this moment we have no plans for such functionality. In basic terms it looks quite cool and easy to implement (just copy the post and their assets), but after deeper analyse - it can cause a lot of additional issues (e.g. non-working internal links, non-compatible post options between themes etc.)
