### ISSUE TITLE
Not able to set Category/Post-Name Slug in URL

### ISSUE THREAD

**Issue by azadshaikh** [GetPublii/Publii#993]
Hi,

I am migrating wordpress website to Publii. But not able to set proper URL for post. 

Wordpress Permalink is:

www.example.com/category-name/post-name

In Publii this is converted into 

www.example.com/post-name

I am new to Publii. I tried to find a solution but no success. Please help. 

In case there is no option to do this what is the next best solution? I don't want so many 404 errors in search console.

Thanks!

**Comment by internettips** [comment]
To get support help, I suggest go to: https://forum.getpublii.com/ and ask there.

**Comment by dziudek** [comment]
Publii has non-editable permalink structure at this moment, so the only solution for migrated websites is using redirects from old urls to the new ones.
