### ISSUE TITLE
Syncing to git doesn't merge

### ISSUE THREAD

**Issue by strelok899** [GetPublii/Publii#997]
When I press sync to github publii remove from. File tree all existing files which is not publii at all.

Behavior now: publii remove all the repo files and replace them with only its files. 

Expected behavior is : publii will replace all changes, add new files. Not remove non publii files which the repository have

**Comment by dziudek** [comment]
Hi,

If you want to store some additional files you can always use file manager to store them. Trying to merge Publii files with other files on a repository can lead to unexpected issues - Publii should be the only source of files for your github pages repository. At this moment we have no plans to change this behaviour.
